### ISSUE TITLE
Support in Angular 6

### ISSUE THREAD

**Issue by markgrichanik** [valor-software/ng2-charts#1001]
is it supported in Angular 6?

**Comment by jonathanspence** [comment]
I would really like to know, does it?

**Comment by Gullfaxi171** [comment]
Yes it does, I just made it work, without any particular operation

**Comment by Epicnessism** [comment]
Asking the real questions. I wish this was by default on all angular libraries.

**Comment by angelmartinez-wz** [comment]
Yes it does, I have just created a new project with Angular 6 version, there is my package.json dependencies.

```
"dependencies": {
    "@angular/animations": "^6.0.2",
    "@angular/common": "^6.0.2",
    "@angular/compiler": "^6.0.2",
    "@angular/core": "^6.0.2",
    "@angular/forms": "^6.0.2",
    "@angular/http": "^6.0.2",
    "@angular/platform-browser": "^6.0.2",
    "@angular/platform-browser-dynamic": "^6.0.2",
    "@angular/router": "^6.0.2",
    "core-js": "^2.5.4",
    "ng2-charts": "^1.6.0",
    "rxjs": "^6.0.0",
    "zone.js": "^0.8.26"
  }
```

Just verify the documentation to implements library correctly.

**Comment by angelmartinez-wz** [comment]
@chovy Chart.js is under MIT License, there is no restriction in commercial use, you can use it installing the package or via CDN.

**Comment by chovy** [comment]
That wasn't what i was asking.

**Comment by Sturgelose** [comment]
@Gullfaxi171 The error is thrown because the ng2-charts require a stable package. Note that the installed version of Angular is 7.0.0-rc.0. It should work with 7.0.0 (stable channel)

**Comment by 93Alliance** [comment]
please this chart https://github.com/93Alliance/ng-chartjs

**Comment by woodi3** [comment]
For Angular 7.1, this worked for me, add the path to chartjs node_module script to the scripts array in the angular.json and import the ChartsModule normally.

` 
"assets": [
              "src/favicon.ico",
              "src/assets"
            ],
            "styles": [
              "src/styles.css",
              "node_modules/bootstrap/dist/css/bootstrap.min.css"
            ],
            "scripts": [
              "node_modules/chart.js/dist/Chart.min.js"
            ]
`

**Comment by paviad** [comment]
This project is now fully updated for Angular 7 with some new enhancements such as type safety.
