### ISSUE TITLE
When clicking on an element inside a table, mark (change border, background) a specific bar inside bar chart

### ISSUE THREAD

**Issue by GoodPotato** [valor-software/ng2-charts#1004]
Hi!

I am trying to figure it out how to make it so that I can click on some table row in a table (the table rows have same data as data displayed in graph) and it executes the same event in the bar chart as if I would hover over a particular bar (show tooltip of data, change background and border color - to make it stand out). I can't find any documentation that would be bit more detailed.

If anyone has any clues, please share them. :)

**Comment by paviad** [comment]
I don't think this feature is in scope of this library.
