### ISSUE TITLE
ng2-charts reset all registered plugins once it is loaded

### ISSUE THREAD

**Issue by wazani** [valor-software/ng2-charts#1006]
Hello there!
I hope you are doing well!

I have to use a plugin for ChartJS in my application, and in order to do that I added that 3rd party plugin script in '.angular-cli.json', under 'scripts' section and immediately after 'Chart.js' script

`"scripts": [
        "../node_modules/chart.js/dist/Chart.bundle.min.js",
        "../node_modules/chart.piecelabel.js/build/Chart.PieceLabel.min.js"
      ]`

Now, I expect once my angular App lunch, this 3rd party plugin will be registered successfully under chart.js.
Unfortunately, Once ng2-charts module is being loaded, it reset and clears all registered plugins.
I think this happened because of the following line:
https://github.com/valor-software/ng2-charts/blob/602742b71d61d19bb56b23f71094ff189315355b/src/charts/charts.ts#L14
 it looks here you re-initialize the global Chart variable with a new instance.

Am I right, or I am missing something ?
Could you please Advice ?

One further comment,  In your installation instructions, you mentioned that it is mandatory to include the Chart.js library before we can start using the ng2-charts module. Which is totally fine and make sense.
then why you need to import Chart.js in  chart.ts file that I pointed to it before, isn't it enough to just use something like:
`declare var Chart: any;`

Your help is appreciated!
Thank you in advance!!

**Comment by DSKevk** [comment]
Hi @wazani,

I'm not sure about the problem your encounter, but that's what I do when I add ng2-chart to my Angular application.

First, run: 
```
npm install chartjs ng2-charts chart.piecelabel.js --save
```

After you installed all the needed packages just add this to your module: 

```typescript
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import { ChartsModule } from 'ng2-charts';

@NgModule({
  imports: [
    CommonModule,
    ChartsModule,
  ],
  declarations: []
})
export class YourModule { }
````

Now, you can add this HTML in your chart component:

```html
<canvas baseChart [datasets]="chartData" [labels]="chartLabels" [options]="chartOptions" [colors]="chartColors" [chartType]="chartType"></canvas>
```

I don't add the scripts in the _angular-cli.json_, it works well and there is no plugin clearing on my differents projects.

Hope it helps!

**Comment by 93Alliance** [comment]
please this chart https://github.com/93Alliance/ng-chartjs

**Comment by paviad** [comment]
Refer to https://github.com/valor-software/ng2-charts/issues/1058#issuecomment-469021112 for example on how to load plugins without changing `angular.json` (previously `.angular-cli.json`)
