### ISSUE TITLE
Can't change font-family

### ISSUE THREAD

**Issue by DSKevk** [valor-software/ng2-charts#1007]
Hi guys,

I'm actually trying to change the font-family of a chart by another font imported as `@font-face { ... }` in my _styles.scss_ file.

```javscript
title: {
  display: true,
  text: 'My Chart Title',
  fontColor: 'white,
  fontFamily: '{My Imported Font Name}'
}
```

Nothing happened, it seems it doesn't detect the font. I tried with '_Comic Sans MS_' or '_Verdana_' and it works. Is there any method to use imported fonts?

Thank you in advance for your help!

**Comment by DSKevk** [comment]
@chovy directly in my chart options object.

**Comment by paviad** [comment]
Can you test on pure chart.js (no angular) and see if the problem is there?

**Comment by paviad** [comment]
It works now, see this stackblitz example (shows use of the `Arvo` font face from google)

https://stackblitz.com/edit/ng2-charts-fontfamily
