### ISSUE TITLE
No display using <mat-tab-group> Angular 6

### ISSUE THREAD

**Issue by kevincaradant** [valor-software/ng2-charts#1009]
Hi

Sorry, but I can't use your plunker to reproduce the issue for the moment.
To reproduce this issue, you need to create a `<mat-tab-group>` with X `<mat-tab>`
Only the first tab loaded can display a chart, every other tabs<mat-tab> are stilling empty. 
No canvas are drawed except the first ...
it's happening on IE11 and on FF and some versions of Chrome. 
It's working on mine (v 63)
Any idea why ? 

Thank you in advance

**Comment by kevincaradant** [comment]
Ok my bad, the example given in the doc doesn't work as expected with all browsers.
I had to define a size on the div and not only the canvas.

**Comment by bumuthu** [comment]
I also had to face no chart showing in the angular tab.. I used  div and following style it was solved. 
<div style="display: block">
<canvas> </canvas>
</div>
