### ISSUE TITLE
Bar chart sticks to y axis 

### ISSUE THREAD

**Issue by manhar-developer** [valor-software/ng2-charts#1011]
**Reproduction of the problem**

Bar chart is merged into the y axes of the graph while ploting the graph. How to have space between the bar and the y axis. Refer Snapshot 
![capture](https://user-images.githubusercontent.com/32042376/43503272-4456d318-957c-11e8-89db-831b77c9efa7.JPG)

**Comment by DSKevk** [comment]
Hi @manhar-developer can you show us some code of your chart data and your chart options, even the HTML would be usefull ?

**Comment by manhar-developer** [comment]
Hi @DSKevk 
Refer https://stackblitz.com/edit/ng2-chart-example-nhy163 , which represents the Line Graph Chart. When  there only sinle data , label starts from y axis there should be spme space between horizontal line (y axes) and the plotted graph

**Comment by DSKevk** [comment]
Hey @manhar-developer I created an updated version of this Stackblitz and It's working well, check this  [updated example](https://stackblitz.com/edit/ng2-chart-example-22wq6w).

If you want to use the provided code, you just have to create dynamically your chart data and your labels in the component and update your chart options in the file _bar-chart.options.ts_.

Eventually check if you have some global CSS that can conflict with the chart canvas.

Hope it helps,
Kevk.
