### ISSUE TITLE
Change label color

### ISSUE THREAD

**Issue by suparnavg** [valor-software/ng2-charts#1012]
Is it possible to change the color of labels (axis labels, legend labels?). Seems to be a default grey.

charts.js does provide an option inside the [labels object](http://www.chartjs.org/docs/latest/axes/labelling.html) and the [legend object](http://www.chartjs.org/docs/latest/configuration/legend.html#legend-label-configuration) - would be fantastic if these options was exposed in the ng2-charts library.

**Comment by DSKevk** [comment]
Hi @suparnavg,

There are some options to update the labels color. Check my code below; it provides you an example of a chart options object.

```javascript
 {
    responsive: true,
    title: {
      display: true,
      text: 'Your chart title',
      fontColor: 'black',  // chart title color (can be hexadecimal too)
    },
    scales: {
      xAxes: [{
        stacked: true,
        ticks: {
          fontColor: 'black',  // x axe labels (can be hexadecimal too)
        },
        gridLines: {
          color: '#5f5e5e'  // grid line color (can be removed or changed)
        }
      }],
      yAxes: [{
        id: 'yAxis1',
        stacked: true,
        ticks: {
          fontColor: 'black',  // y axes numbers color (can be hexadecimal too)
          min: 0,
          beginAtZero: true,

        },
        gridLines: {
          color: '#5f5e5e'  // grid line color (can be removed or changed)
        },
        scaleLabel: {
          display: true,
          labelString: 'nombre de DI',
          fontColor: 'black',  // y axe label color (can be hexadecimal too)
        }
      }]
    },
    legend: {
      display: true,
      labels: {
        fontColor: 'black', // legend color (can be hexadecimal too)
      },
    }
 }
```

Hope it helps,
Kevk.

**Comment by 93Alliance** [comment]
please this chart https://github.com/93Alliance/ng-chartjs

**Comment by paviad** [comment]
@DSKevk answer should close this.

**Comment by iryanjan18** [comment]
Is this also the same when changing the color values inside the chart? Like the pie chart slices have numbers inside it in dark color. I wanted to change it to light font color.

**Comment by ishwarThakare** [comment]
In pieChartOptions write, 

 public pieChartOptions: ChartOptions = {
    plugins: {
      datalabels: {
        color: '#3c3c3c'
      },
    }
  }
