### ISSUE TITLE
Disable Chart Click Event when Legend is Clicked

### ISSUE THREAD

**Issue by manhar-developer** [valor-software/ng2-charts#1013]
I have written a function on chart click that has a REST API call. Its working fine on bar or outside chart using active length property. 
Only issue is that when legend is selected /unselected , chart click function is called . 

Expected Behaviour : 
When Legend is selected/unselected or clicked , chart click function should not be called only the default behavior to display hide chart of the corresponding legend should work. 

Refer [https://stackblitz.com/edit/ng2-chart-example-ib8qvz?file=app/app.component.ts](url)

![graph](https://user-images.githubusercontent.com/32042376/43757765-8a3221c0-9a37-11e8-938e-99e0162cadb8.jpg)

**Comment by Joklogh** [comment]
Hi @manhar-developer 
You can achieve this behaviour by checking if event contains selected elements in `active` array.
If `active` is empty then you know that legend was clicked or space inside graph.
See improved example : https://stackblitz.com/edit/ng2-chart-example-63gvdz
Let me know if this resolves your issue.

**Comment by manhar-developer** [comment]
Hi @Joklogh 
Thanks for the response. 
Actually I am already using active length property when bar is checked (e.active length > 0). I redraw the chart and to go back to previous state reset if I click outside the bar i.e. chart click event when active length =0, chart is reset. However when legend is selected that reset function where (active length = 0) is called and chart is reset again. 

What is want is on legend selection , chart click event should be prevented or any other property just like active length which prevents click and works only when clicked outside bars.

**Comment by aishwaryardandi** [comment]
Hi @manhar-developer have you figured out a solution for this? I have a similar requirement and can't find anything that works!

**Comment by manhar-developer** [comment]
Hi @aishwaryardandi 
When Legend is clicked event.active.length is 0. So we can check based on these condition

**Comment by paviad** [comment]
Is this in our scope? Does chart.js allow you to test whether an empty area was clicked or the legend?

**Comment by paviad** [comment]
This is a chart.js issue https://github.com/chartjs/Chart.js/issues/6044
