### ISSUE TITLE
Multi-theme text color change just like mat-card title <Improvement>

### ISSUE THREAD

**Issue by bmangesh25** [valor-software/ng2-charts#1017]
Hello Team,

You are doing a wonderful development, I have a Angular project which support multi-theme just like "https://material.angular.io/components/card/examples"

Do you have any plan to support multi-theme text for chart labels.

For e.g:
1) **Mat card with white background text must be black**
2) **Mat card with black background text must be white**

**Comment by paviad** [comment]
Check out the updated demo, it includes dynamic themes, but I am still unsure on how to modify the chart.js inline styles.

**Comment by bmangesh25** [comment]
Thanks for your prompt reply. 

Below is the screen shoot which will help us to understand the scenario.

Mat card with white background text must be black -- **As expected**

![capture2](https://user-images.githubusercontent.com/32618630/53925031-7b5cbc00-40a4-11e9-93bf-91ade1bbb633.PNG)


Mat card with black background text must be white -- **need to work on below area**

![capture1](https://user-images.githubusercontent.com/32618630/53925088-b232d200-40a4-11e9-83bd-2a03f68dfe16.PNG)

**Comment by paviad** [comment]
Please see commit c079629 with updated [demo app](https://valor-software.com/ng2-charts), I started working on this and it seems ok, but I would like to get some code review going.

**Comment by bmangesh25** [comment]
> 
> 
> Please see commit [c079629](https://github.com/valor-software/ng2-charts/commit/c07962948f0d3bdb666bcd76e989a79fc93a9b65) with updated [demo app](https://valor-software.com/ng2-charts), I started working on this and it seems ok, but I would like to get some code review going.

Just awesome...  Update us when dark theme go live

**Comment by paviad** [comment]
Check this one out (from the demo app)

![Angular 2 Charts Demo - Edited](https://user-images.githubusercontent.com/1235688/54072777-3c875b80-4288-11e9-9ac4-6de09cb869ae.gif)

**Comment by paviad** [comment]
Check it out now, I added a plugins override section in the `ThemeService` call:
```typescript
...
plugins: {
  datalabels: {
    color: 'white',
  }
}
...
```

![Angular 2 Charts Demo - Edited (1)](https://user-images.githubusercontent.com/1235688/54073054-5d9d7b80-428b-11e9-807c-58bf74a3a608.gif)

**Comment by bmangesh25** [comment]
> 
> 
> Check it out now, I added a plugins override section in the `ThemeService` call:
> 
> ```ts
> ...
> plugins: {
>   datalabels: {
>     color: 'white',
>   }
> }
> ...
> ```
> 
> ![Angular 2 Charts Demo - Edited (1)](https://user-images.githubusercontent.com/1235688/54073054-5d9d7b80-428b-11e9-807c-58bf74a3a608.gif)

**It looks perfect. Thanks for taking feature into consideration.**  

I just have doubts:
1) do we need to write "ChartOptions" in every component, where we are using charts?
2) Based on angular  "mat-light-theme()" or "mat-dark-theme()" selection, can we auto detect and convert the text color.
3) Also can we set default responsive=true, If user don't require they can false the condition.

**Comment by paviad** [comment]
1. You don't have to use type annotations, but they are for your own safety :)
2. No you can't, but since you wrote your themes, you can incorporate that into the override json.
3. Yes you can manipulate the default options by accessing the underlying `Chart.defaults.global` object - see [chart.js documentation](https://www.chartjs.org/docs/latest/configuration/)
