### ISSUE TITLE
Is there any property to display negative values with different color (red) in bar chart

### ISSUE THREAD

**Issue by manhar-developer** [valor-software/ng2-charts#1019]
Refer the Stackblitz URL (https://ng2-chart-example-38nyxw.stackblitz.io) . Is it possible through ng2-chart or chart.js property to display negative value in the graph in red color. 
![capture](https://user-images.githubusercontent.com/32042376/44942389-460da380-adcd-11e8-9095-0310965d6f5e.JPG)

**Comment by Joklogh** [comment]
Hi @manhar-developer 
Stackblitz that you provide cannot be modified. Can you provide url with full access to code?

**Comment by manhar-developer** [comment]
Hi @Joklogh ,
Please refer [https://stackblitz.com/edit/ng2-chart-example-4tdgcj](url) which editable.

**Comment by Joklogh** [comment]
Hi @manhar-developer 
I managed to work out solution.
Here it is in action : https://stackblitz.com/edit/ng2-chart-example-qamgsg
Basically I am assigning color in `ngOnInit` hook based on the value in `lineChartData`. If it is negative, then red color is pushed into array of colors. However I you must both to dataset array and to bind to color input of directive which is strange, I was expecting to passed it only once not twice.
Let me know if this solution is fine to your needs.

**Comment by manhar-developer** [comment]
Thanks for suggesting the approach . I managed to check in the function where data is being fetched using the approach suggested :)

**Comment by am-awais** [comment]
How to give second color to the positive value bars?
