### ISSUE TITLE
What is wrong with webpack?

### ISSUE THREAD

**Issue by GTamara** [valor-software/ng2-charts#102]
I have cloned ng2-chart  repo and installed it using npm install.
When I try to run webpack command I get the following messages:

t@tpk:~/work/testCharts2/ng2-charts$ webpack
clean-webpack-plugin: /home/t/work/testCharts2/ng2-charts/build has been removed.
Hash: 5b357c276e0719c954a6
Version: webpack 1.12.14
Time: 2740ms
                 Asset       Size  Chunks             Chunk Names
           angular2.js     3.2 MB       0  [emitted]  angular2
    angular2-charts.js  236 bytes       1  [emitted]  angular2-charts
       angular2.js.map    3.41 MB       0  [emitted]  angular2
angular2-charts.js.map   95 bytes       1  [emitted]  angular2-charts
   [0] ./demo/index.ts 0 bytes [built] [failed]
   [0] multi angular2-charts 28 bytes {1} [built] [1 error]
   [0] multi angular2 64 bytes {0} [built]
 [164] ./ng2-charts.ts 0 bytes [built] [failed]
    + 163 hidden modules

ERROR in ./ng2-charts.ts
Module parse failed: /home/t/work/testCharts2/ng2-charts/ng2-charts.ts Line 1: Unexpected token
You may need an appropriate loader to handle this file type.
| export * from  './components/charts/charts';
| 
 @ multi angular2-charts

ERROR in ./demo/index.ts
Module parse failed: /home/t/work/testCharts2/ng2-charts/demo/index.ts Line 1: Unexpected token
You may need an appropriate loader to handle this file type.
| import {bootstrap} from 'angular2/bootstrap';
| import {Component} from 'angular2/core';
| import {NgClass} from 'angular2/common';

How can I fix the problem?
Thanks in advance.

**Comment by valorkin** [comment]
Ts loader failed to parse typescript file

**Comment by GTamara** [comment]
Thank you for your answer. How can I fix the problem?

**Comment by valorkin** [comment]
Compare webpack config with config in ng2-bootstrap

**Comment by GTamara** [comment]
Thank you for your answer. 
I have just loaded ng2-charts from github, I did not make any changes in the project.
Why it does not work by "plug and play" principle?
Please let me know where can I find ng2-bootstrap config?
How should I change one?

Thanks in advance.

**Comment by valorkin** [comment]
https://github.com/valor-software/ng2-bootstrap?files=1

**Comment by GTamara** [comment]
webpack within ng2-bootstrap works well.
webpack.config.js files in ng2-bootstrap and ng2-charts are quite different.
What part of webpack config should I pay attention?

**Comment by nsuhanshetty** [comment]
Do let us know the fix.. As I am facing the same issue, Thanks.

**Comment by valorkin** [comment]
fixed
