### ISSUE TITLE
Display Previous range comaprison in Line Chart

### ISSUE THREAD

**Issue by manhar-developer** [valor-software/ng2-charts#1020]
As per the snapshot , want to design a usecase using Line Chart. 
Displaying the current date range in x axis and plotting the graph. Also compairing the graph with last year or (any custome date range) with the dotted lines. 
![untitled](https://user-images.githubusercontent.com/32042376/45022568-33f06700-b052-11e8-968b-10cd4fdd24f6.jpg)

If we plot bot data range like year 2018 and 2017 it will come on different scale range. Need to plot both year graph in same date range as mentioned in the snapshot. 

Refer [URL ](https://stackblitz.com/edit/ng2-chart-example-g2hsrv)for the current year plot

**Comment by paviad** [comment]
You could process your data and adjust the year value of one of the datasets. This is a general programming question, please try asking in stackoverflow.com
