### ISSUE TITLE
How to create histogram / heat map chart like the snapshot in ng2-charts

### ISSUE THREAD

**Issue by manhar-developer** [valor-software/ng2-charts#1022]
How to create histogram / heat map chart like the snapshot in ng2-charts
![capture](https://user-images.githubusercontent.com/32042376/45213048-1c181d80-b2b4-11e8-8385-0186def207f7.JPG)

Requirement is to plot days of week on x axis (Sun, Mon, Tues) and time in hour on y axis (1-12 or 24). All the values will be shown in the color range lighter to darker

**Comment by paviad** [comment]
This is out of scope for this package, and in `chart.js` there is currently there is no support for heat map. But there are clever workarounds, see this: https://github.com/chartjs/Chart.js/issues/4627#issuecomment-400911590
