### ISSUE TITLE
How to add pattern fill to Pie chart or Bar chart

### ISSUE THREAD

**Issue by sanjay1684** [valor-software/ng2-charts#1025]
I want to add Pattern fill to my Pie chart and Bar chart as below examples.

![pie chart with pattern fill](https://user-images.githubusercontent.com/27825867/45898696-5cb98000-bdf8-11e8-9439-b80024355552.jpg)
![bar chart with pattern fill](https://user-images.githubusercontent.com/27825867/45898697-5cb98000-bdf8-11e8-90a9-f902c715b80c.png)

**Comment by miller45** [comment]
ng2-charts is wrapper for chart.js refer to https://www.chartjs.org/ to see if its possible and with what parameters...

**Comment by mariusl-a** [comment]
Check if this works for you;
http://www.chartjs.org/docs/latest/general/colors.html?h=pattern 👍

**Comment by miller45** [comment]
the used library patternomaly in the above link has no typescript "support", but I added typescript typings file in a pullrequest. You can support it by voting there: https://github.com/ashiguruma/patternomaly/pull/23

**Comment by paviad** [comment]
@mariusl-a comment seems to close this issue.
