### ISSUE TITLE
Someone still maintaining this repository  (actively)?

### ISSUE THREAD

**Issue by miller45** [valor-software/ng2-charts#1028]
Thanks for the hard work in past, but how about the future....

The last commit to master on Jan 17, 2017, last commit to development branch May 30, 2017
The CI build stops before actually starting a build.
The http://plnkr.co/edit/Ka4NXG3pZ1mXnaN95HX5?p=preview
does not work because the unpkg server does not have the old depdencies any more.

We are using the component, are happy with it, but need a small a bug fixed...and yes i can do the fix by myself...but i don´t know if its worth the effort (because this repository might be abandoned.

I don´t want to complain but i just want to know if have to switch to another component (which will be much work on our code basis)...or do a "dirty" fork and make an own npm package of it...

**Comment by micobarac** [comment]
33 pull requests waiting :(

**Comment by DSKevk** [comment]
Maybe someone has to fork it. Few people will contribute to maintain it.

**Comment by nkholski** [comment]
I hope someone decides to fork it. We'll eventually reach a point where this will break with future versions of Angular, even though it seems to work well with Angular 7. First thing would be to go through the PR:s and perhaps just start over with a blank list of issues. I'd star a project like that in a minute and try to contribute.

**Comment by 93Alliance** [comment]
> I hope someone decides to fork it. We'll eventually reach a point where this will break with future versions of Angular, even though it seems to work well with Angular 7. First thing would be to go through the PR:s and perhaps just start over with a blank list of issues. I'd star a project like that in a minute and try to contribute.

https://github.com/93Alliance/ng-chartjs https://github.com/93Alliance/ng-chartjs

**Comment by 93Alliance** [comment]
Please try this project https://github.com/93Alliance/ng-chartjs

**Comment by DSKevk** [comment]
> I hope someone decides to fork it. We'll eventually reach a point where this will break with future versions of Angular, even though it seems to work well with Angular 7. First thing would be to go through the PR:s and perhaps just start over with a blank list of issues. I'd star a project like that in a minute and try to contribute.

I wanted to, but at the moment I don't have enough time to work on it...

**Comment by nkholski** [comment]
@93Alliance Great! Being lazy here but is there differences in the implementation compared to this repository or do I need to adapt my code?

**Comment by 93Alliance** [comment]
Great! Being lazy here but is there differences in the implementation
compared to this repository or do I need to adapt my code?

Niklas Berg <notifications@github.com> 于2018年11月14日周三 下午4:11写道：

**Comment by miller45** [comment]
@nkholski  At first glance the interface looks similar but you have to change the name of directive at least.
Before it was `baseChart` and now it is `ngChartjs` but should have just click on their link..because their README.md is more detailed than this library...

**Comment by 93Alliance** [comment]
> @nkholski At first glance the interface looks similar but you have to change the name of directive at least.
> Before it was `baseChart` and now it is `ngChartjs` but should just click on their link..because their README.md is more detailed than this library...

I will add more detailed use documents later, and my project is in use, I will keep updating

**Comment by cecilef** [comment]
You can check this one out: https://github.com/donothingloop/ng2-charts-x
Some bugs have been fixed, seems maintained more recently as well

**Comment by paviad** [comment]
I have taken the code from this repository and created a new package, made fresh with the latest Angular tools (Angular CLI 7.3.4 at the time of this posting). The package is called `ng2-charts7` and it may be found on github at https://github.com/paviad/ng2-charts7

It is also published on npmjs.com at https://www.npmjs.com/package/ng2-charts7
