### ISSUE TITLE
npm install throws error

### ISSUE THREAD

**Issue by jgenchik** [valor-software/ng2-charts#103]
I downloaded the latest version of ng2-charts from git (`npm install -S valor-software/ng2-charts`). Then I went to the node_modules/ng2-charts directory and attempted to run `npm install`. That created the following error:
```
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\...\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.3.1
npm ERR! npm  v3.7.3

npm ERR! Cannot read property 'target' of null
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\....t\node_modules\ng2-charts\npm-debug.log
```

The reason I was running the install is because the Git repository does not have a .js file, only .ts. My plan was to run `npm install` and then `tsc ng2-charts.ts`
Any suggestions?
Also, when are you planning to release the code without @View to NPM repository?

Thanks for your help.

**Comment by valorkin** [comment]
now serving .js and .d.ts files
