### ISSUE TITLE
Line chart point overrides/distorts when legend is false.

### ISSUE THREAD

**Issue by manhar-developer** [valor-software/ng2-charts#1032]
**Reproduction of the problem**
Line chart point overrides/distorts when legend is false. 
As per the attached snapshot, points in the line chart are not completely visible and are distorted from top and bottom. 
In case of right and left, maxRotation property has been applied and margin is available in right and left. 

Expected Result : 
Point should be completly visible

Actual Results: 
Points are distorted/cut from top and bottom 

![capture](https://user-images.githubusercontent.com/32042376/47277960-cb9a1c80-d5e2-11e8-909f-d2fafffb8c04.JPG)

Refer Code Pen URL - https://codepen.io/manhar-developer/pen/YJjZdd

**Comment by paviad** [comment]
Obsoleted by #1033
