### ISSUE TITLE
Line chart point overrides/distorts when legend is false. 

### ISSUE THREAD

**Issue by manhar-developer** [valor-software/ng2-charts#1033]
**Reproduction of the problem**

Line chart point overrides/distorts when legend is false. 
![capture](https://user-images.githubusercontent.com/32042376/47278007-1caa1080-d5e3-11e8-8d11-8749c51c566e.JPG)

As per the attached snapshot, points in the line chart are not completely visible and are distorted from top and bottom. 
In case of right and left, maxRotation property has been applied and margin is available in right and left. 

Expected Result : 
Point should be completly visible

Actual Results: 
Points are distorted/cut from top and bottom 

Refer Code Pen URL - https://codepen.io/manhar-developer/pen/YJjZdd

===========================================
ng2-charts is a port & modification of Chart.js component for Angular 2. Sometimes the issue is related with Chart.js instead of ng2-charts.
To confirm, if the issue shows in a pure Chart.js project, it is a issue of Chart.js.
Pure Chart.js starting template: https://jsfiddle.net/Hongbo_Miao/mvct2uwo/3/

If the issue does not show in a pure Chart.js project, and shows in a ng2-charts project, please try to provide a minimal demo of the problem.
ng2-charts starting template: http://plnkr.co/edit/Ka4NXG3pZ1mXnaN95HX5?p=preview

**Comment by paviad** [comment]
I don't see how this is a problem, the dot really should be clipped, and also I don't see any distortion.
