### ISSUE TITLE
Unable to plot stacked bar graph across x-axis

### ISSUE THREAD

**Issue by sprakashg** [valor-software/ng2-charts#1035]
Hi Team,
I using this plugin for building stacked vertical bar graph using angular 5.
Here is the data structure I'm passing for [datasets] in HTML
```typescript
[
   {label: "Approved", data: [2], stack: 0},
   {label: "Accepted", data: [3], stack: 1},
   {label: "Open", data: [5], stack: 1},
   {label: "Open", data: [6], stack: 1},
   {label: "In Progress", data: [2], stack: 2},
   {label: "Open", data: [29], stack: 2}
]
```
and for [labels] in HTML, we are passing this
`["P", "R", "B"]`
Graph is stacked well and shown but it's showing only for the first index of labels array , instead of getting divided by three index of label array.  Any help or suggestion would be great

**Comment by sprakashg** [comment]
![screenshot 63](https://user-images.githubusercontent.com/6829701/48544338-6091ec00-e8e9-11e8-9294-18ed8e7d5399.png)

**Comment by sprakashg** [comment]
If you see above graph, all the graph's are plotted on the first index of the labels array i.e., P. It has to cascade across other two as well. Not sure where I'm getting this wrong

**Comment by paviad** [comment]
Sounds like you should have 3 labels, and 4 data sets. The labels should be: [`P`, `R`, `B`] and the data sets should be labeled: `Approved`, `Accepted`, `Open` and `In Progress`.

```typescript
public barChartData: ChartDataSets[] = [
  { data: [1, 2, 3], label: 'Approved' },
  { data: [1, 2, 3], label: 'Accepted' },
  { data: [1, 2, 3], label: 'Open' },
  { data: [1, 2, 3], label: 'In Progress' },
];
public barChartLabels: string[] = ['P', 'R', 'B'];
```
