### ISSUE TITLE
Console error: Unable to load chart.js

### ISSUE THREAD

**Issue by willysoria-idtnet** [valor-software/ng2-charts#1041]
**Reproduction of the problem**
Install ng2-charts over angular 7 following the official steps document.
After install you will notice the angular.json file has the following scrips:

```
"scripts": [
              "node_modules/hammerjs/hammer.min.js",
              "node_modules/chart.js/src/chart.js"
            ],
```

This causes the following console error:
`Unable to load chart.js`

After a lot of time reading I found a fix for this, I manually changed the angular.json file to use this:

`"node_modules/chart.js/dist/Chart.bundle.min.js"`

Is there a way to avoid doing this manually? Thank you for your time.

**Comment by miller45** [comment]
@willysoria-idtnet the documentation (Readme.md) says: `node_modules/chart.js/src/chart.js` but you have deleted the 't' (char.js whithout a t'). But anyway this didn´t work for me...i had to change it to `node_modules/chart.js/dist/chart.js`  (dist instead of src).

**Comment by willysoria-idtnet** [comment]
> @willysoria-idtnet the documentation (Readme.md) says: `node_modules/chart.js/src/chart.js` but you have deleted the 't' (char.js whithout a t'). But anyway this didn´t work for me...i had to change it to `node_modules/chart.js/dist/chart.js` (dist instead of src).

Yeah, you are totally right, fixed the typo in the main question, thank you!

**Comment by miller45** [comment]
>Is there a way to avoid doing this manually? Thank you for your time
the "node_modules/chart.js/src/chart.js" is necessary because chart.js does not "support" typescript.
And chart.js is not provided by ng2-charts developers. (but is the foundation of ng2-charts)

**Comment by willysoria-idtnet** [comment]
Got it thanks, but when I install unsing npm there is added this "node_modules/chart.js/src/chart.js" library, and this gives console errores, but if you change manually to use dist folder instead the error disapear, so I was wondering if ther can change the default src folder to use dist instead.
