### ISSUE TITLE
Labels are not loading by dynamically for Bar chart

### ISSUE THREAD

**Issue by shans-1983** [valor-software/ng2-charts#1045]
**Reproduction of the problem**

The labels are not loaded by dynamically. If changing the filter using the from date and to date with month in the x-axis not changing as per the filter.

If the issue does not show in a pure Chart.js project, and shows in a ng2-charts project, please try to provide a minimal demo of the problem.
ng2-charts starting template: http://plnkr.co/edit/Ka4NXG3pZ1mXnaN95HX5?p=preview

**Comment by louisdoe** [comment]
I have the same issue. Any ideas ?

**Comment by paviad** [comment]
Closed by ef5d2f4
