### ISSUE TITLE
How to use it with Ionic in a service

### ISSUE THREAD

**Issue by mathildebuenerd** [valor-software/ng2-charts#1049]
I am making an app using Ionic 4 I can't achieve to make ng2-charts work inside a service. I don't really get how to import it correctly, I don't have any error but nothing appears on the page.

I have two services: one called `TextAnalysisService`, that is doing some text analyses on a user input, and another one called `DatavisualisationService`, in which I want to use ng2-charts.

I use these two services into a page called `writing`.

I have installed both ng2-charts and charts.js

```json
"dependencies": {
  "chart.js": "^2.7.3",
  "ng2-charts": "^1.6.0",
}
```

Then I imported it in `app.module.ts`: 

```js
import { ChartsModule } from "ng2-charts";
imports: [
   ChartsModule
],
```

In my service `datavisualisation.service.ts` I added the example code:

```ts
import {Injectable} from "@angular/core";

@Injectable()
export class DatavisualisationService {

  constructor() {
  }

  public barChartOptions:any = {
    scaleShowVerticalLines: false,
    responsive: true
  };

  public barChartType:string = 'bar';
  public barChartLegend:boolean = true;

  public barChartData:any[] = [
    {data: [65, 59, 80, 81, 56, 55, 40], label: 'Series A'},
    {data: [28, 48, 40, 19, 86, 27, 90], label: 'Series B'}
  ];

  showBarChart() {
    let data = [
      Math.round(Math.random() * 100),
      59,
      80,
      (Math.random() * 100),
      56,
      (Math.random() * 100),
      40];
    let clone = JSON.parse(JSON.stringify(this.barChartData));
    clone[0].data = data;
    this.barChartData = clone;
  }
}
```

In my other service `textAnalysis.service.ts`, I created a simple function to show the graph:

```ts
showGraph() {
    this.datavis.showBarChart();
}
```

I launch that function in my page main ts file `writing.ts`, in `ionViewDidLoad()`. In my template `writing.html` I added this:

```html
<ion-card>
    <ion-card-header>Statistiques</ion-card-header>
    <ion-card-content>
      <canvas #realtimeStats
              baseChart
              [datasets]="barChartData"
              [labels]="barChartLabels"
              [options]="barChartOptions"
              [legend]="barChartLegend"
              [chartType]="barChartType"
              (chartHover)="chartHovered($event)"
              (chartClick)="chartClicked($event)"></canvas>
    </ion-card-content>
  </ion-card>
```

And I also imported it at the end of the body in my `index.html`, before the main.js. The file is located in that folder, though I am not sure that it's actually accessible after I build the app. I have tried to include the path `"src/assets/libraries"` in the includes in tsconfig.json.

`<script src="assets/libraries/charts/Chart.bundle.min.js"></script>`

I don't really get how to import it correctly. And how can I draw a different graph depend on the id of the canvas?

**Comment by 93Alliance** [comment]
Please use https://github.com/93Alliance/ng-chartjs

**Comment by MumblesNZ** [comment]
Hey, all those class params (barChartData, barChartLabels etc) on datavisualisation.service.ts have to be available to writing.html via declaring them on writing.ts. I would move all the params to writing.ts and then using datavisualisation.services.ts to update the data on writing.ts.  I am suprised you arn't getting an error saying can't find those parameters. Have you tried running it via ionic serve and looking for errors in the development console?

**Comment by paviad** [comment]
`ng2-charts` is now at version `2.2.0`. If you still have this problem with the current version, please reopen and share any new information if any.
