### ISSUE TITLE
change tooltip border-color width display border

### ISSUE THREAD

**Issue by orphen92** [valor-software/ng2-charts#1051]
Hi i need to custom my Tooltip for add same color for chart and border-color

i have a problème for get the chart color and use it to the border color of my tooltip.

How can i do that please?

**Comment by paviad** [comment]
Can you please provide more details? What is the current result, and what is the desired result, please include a stackblitz/codepen/... example, or at least some pictures.

**Comment by paviad** [comment]
It is possible by configuring tooltip options in the chart options object:

```typescript
{
  tooltips: {
    borderWidth: 10,
    borderColor: 'green',
  }
};
```


Please check out this stackblitz https://stackblitz.com/edit/ng2-charts-tooltip-border

![image](https://user-images.githubusercontent.com/1235688/54297689-03b8f080-45c0-11e9-892f-7094064b9789.png)

**Comment by kanchanDevi** [comment]
How to remove all sides border except left ?
