### ISSUE TITLE
The chart does not show up after a couple page reloads.

### ISSUE THREAD

**Issue by kevintenyroy** [valor-software/ng2-charts#1054]
The chart shows up, but after reloading the page a couple of times, it doesn't show up anymore and there is no error either. If I reload the page while keeping the developer mode open on chrome, it always shows up, but not if I reload it normally. After making any kind of change in the HTML,, it works again and then it repeats everything as before.

EDIT: I just tested it after putting another chart outside the mat-card. It's still the same for the chart inside mat-card, but the one outside the card always shows up. Is this a problem with mat-card?

                <h2>Class Track:</h2>
                <h4>Required:</h4>

                <ng-container *ngFor="let reqSkill of reqSkills">
                    <mat-card>
                        <mat-card-content>
                            <div class="card-flex-container">
                                <div class="leftPart">
                                    <div>
                                        <img [src]="reqSkill.classData.classImg" [alt]="reqSkill.skill.classID">
                                    </div>
                                    <div class="flex-div">
                                        <h4>{{reqSkill.classData.className}}</h4>
                                        <h6><b>Field: </b>{{reqSkill.classData.classField}}</h6>
                                        <h6><b>Category: </b>{{reqSkill.classData.classCategory}}</h6>
                                        <h6><b>Level: </b>{{reqSkill.classData.classLevel}}</h6>
                                    </div>
                                </div>
                                <div class="rightPart">
                                    <div *ngIf="radarChartData" style="display: block;">
                                        <canvas baseChart
                                            [datasets]="radarChartData"
                                            [labels]="radarChartLabels"
                                            [chartType]="radarChartType"></canvas>
                                    </div>
                                </div>
                            </div>
                        </mat-card-content>
                        <mat-card-actions align="end">
                            <button mat-raised-button color="primary" routerLink="/">Edit</button>
                        </mat-card-actions>
                    </mat-card>
                </ng-container>

**Comment by kevintenyroy** [comment]
I got the issue!! It seems that ng2-charts doesn't work properly inside flex.

**Comment by paviad** [comment]
Can you provide a stackblitz showing how the chart behaves badly in flex?

**Comment by paviad** [comment]
Looks like putting a chart in flex is working fine. See this stackblitz https://stackblitz.com/edit/ng2-charts-flex

![image](https://user-images.githubusercontent.com/1235688/54298446-6fe82400-45c1-11e9-9d8d-93a471e7fc41.png)
