### ISSUE TITLE
(sorry solved) how to manage the callback on the option parameter?

### ISSUE THREAD

**Issue by radici** [valor-software/ng2-charts#1055]
how to manage the callback on the option parameter?
for example:
this.pieChartOptions = {
            showLines: true,
                legend: {
                position: 'bottom',
                    fontSize: 10
            },
            title: {
                display: false,
                    text: 'Report'
            },
            tooltips: {
                callbacks: {
                    label: function (tooltipItem: any, data: any) {
                        var label = data.datasets[tooltipItem.datasetIndex].label || '';
                        if (label) {
                            label += ': ';
                        }
                        var dataset = data.datasets[tooltipItem.datasetIndex];
                        var total = dataset.data.reduce(function (previousValue: any, currentValue: any, currentIndex: any, array: any) {
                            return previousValue + currentValue;
                        });
                        var currentValue = dataset.data[tooltipItem.index];
                        var precentage = Math.floor(((currentValue / total) * 100) + 0.5);
                        return label + ' ' + precentage + "%";
                    }
                }
            }
        };

**Comment by paviad** [comment]
Closing by original poster request.
