### ISSUE TITLE
the pieClicked event does not return data of the segment clicked

### ISSUE THREAD

**Issue by radici** [valor-software/ng2-charts#1056]
for example the following code does not return in any array or item the data clicked on the pie chart segment.
pieClicked(event: any) {
        console.log(event.active[0]._model);
        console.log(event.active[0]._chart);

        let activePoints = event.active;
        if (activePoints.length > 0) {
            let value = activePoints[0]._model.value;
            let label = activePoints[0]._model.label;

            console.log(value + ' | ' + label);
        } 
    }

**Comment by paviad** [comment]
You should look at `activePoints[0]._datasetIndex` and `activePoints[0]._index` to determine which data point was clicked.
