### ISSUE TITLE
Upgraded library for Angular version 7 at paviad/ng2-charts7

### ISSUE THREAD

**Issue by paviad** [valor-software/ng2-charts#1062]
I have updated this library to conform to Angular 7, it may be found at `paviad/ng2-charts7`

https://github.com/paviad/ng2-charts7

It is also published on `npmjs.org` at:

https://www.npmjs.com/package/ng2-charts7

Please feel free to contribute.

Aviad.

**Comment by 93Alliance** [comment]
Please try ng-chartjs. https://github.com/93Alliance/ng-chartjs

**Comment by paviad** [comment]
It looks like i did what you did, but wasn't aware that you did it first...
How can we merge our projects together?

**Comment by paviad** [comment]
I'll gladly scrap my project for maintainer/contributor access to yours, if
you'll allow it

**Comment by 93Alliance** [comment]
I suggest you give up your project and I will allow you to contribute to it.

**Comment by paviad** [comment]
Alright - will do.

**Comment by 93Alliance** [comment]
https://github.com/93Alliance/ng-chartjs/invitations

**Comment by 93Alliance** [comment]
What's your E-mail address?

**Comment by paviad** [comment]
paviad2@gmail.com - i guess you already figured it out

Before I make my first commit, I have a question, why did you add
`package-lock.json` to the .gitignore file? It should be included in the
index

**Comment by paviad** [comment]
This repo has been upgraded to Angular 7, and is now again being actively maintained (by the original developers as well as by me). So I will continue my efforts here and resign from all others.
