### ISSUE TITLE
Biding Time In Y axis of Bubble Charts

### ISSUE THREAD

**Issue by felixchristo** [valor-software/ng2-charts#1069]
I am trying to show data according to the time in Y-axis and values in X-axis. My Data is like `x:[10,35,60] `and` y:["7.00 AM"]` and r will the same value of x. Basically I want to show multiple data for one date but the sample dataset given is different from my dataset. Can you help me out? and one more thing, I want to hide `r` from tooltip.

![untitled-1](https://user-images.githubusercontent.com/32506507/54015711-86981080-41a6-11e9-8824-c61d570d768c.jpg)

**Comment by paviad** [comment]
I assume [this SO answer](https://stackoverflow.com/a/55262848/235648) resolves it :)
