### ISSUE TITLE
NGRX - Dataset change defaulting colors to black and white

### ISSUE THREAD

**Issue by JoshMentzer** [valor-software/ng2-charts#1071]
Hey all - hoping someone else has come across this and can point me in the correct direction.
I have a line chart which is getting data and labels, colors, etc - from NGRX state.  I have the ng2-chart inside my own component which has Input()'s for datasets, colors, labels, all that.
The chart renders originally just fine - the correct colors, data - everything.  Then there is user interaction, action fires adding another series of data to the chart in the state.
The ng2-chart is updating to reflect and show the new data, but all the colors are defaulting to black and white.  Did a console log of the baseChart directive and the colors object still had the correct values from state.  
Any thoughts from anyone?

**Comment by paviad** [comment]
This is definitely something we'd like to look into, can you provide a stackblitz that reproduces this issue?

**Comment by JoshMentzer** [comment]
@paviad Sure - I mocked one up, to keep it a bit lighter I was able to reproduce the behavior just using a BehaviorSubject instead of doing up the whole Ngrx thing.
https://stackblitz.com/edit/angular-hb3hwk

Just a chart w/ colors - click the update data it runs through and creates a new object and sends it to the .next() - the chart is correct, just all styling to black and white.

**Comment by paviad** [comment]
Fixed (and hopefully didn't break anything) - the problem was that when the number of datasets changed, the colors object wasn't reapplied. Now it is always reapplied.

**Comment by gaeldemarseille** [comment]
This doesn't work when colors aren't set (so it uses the default ones)
I kinda need this because I don't how many datasets I'm adding and default colors are fine.

here's Josh's stackblitz forked to use 2.0.2 and not setting colors https://stackblitz.com/edit/angular-le1jzp

**Comment by paviad** [comment]
Fixed and published, please update your package to version 2.0.3

**Comment by JoshMentzer** [comment]
Working great, thank you @paviad
