### ISSUE TITLE
Update scales dynamically

### ISSUE THREAD

**Issue by MumblesNZ** [valor-software/ng2-charts#1073]
Good to see this library being updated again.

Library doesn't support updating of scales & data dynamically as any call for updating data blocks the refresh call.  If scales are updated independently of data it redraws the graph, but if data is updated as well then the data blocks the refresh call and the graph isn't updated. 

Could we update the base-chart.directive's change detection to listen for any option changes and if options have changed redraw / refresh the whole graph? 

Happy to do a pull request, just would like to know if this behavior is on purpose?

**Comment by paviad** [comment]
It's not on purpose, the change detection in this library is a mess. It is in dire need of improvement. You are more than welcome to create a PR for this.
