### ISSUE TITLE
Repeat colors  after colors length

### ISSUE THREAD

**Issue by UsmanRehmat** [valor-software/ng2-charts#1074]
I am giving [colors]=[{backgroundColor:123322 },... ]. but If my bar chart have series greater than colors lenght . then it's not giving any color to next bars. I want to repeat my colors again.
How can I achieve this functionality.

**Comment by MumblesNZ** [comment]
Can you check the bar chart series length and manually repeat the color array on your side as necessary to fill in the missing colors?

**Comment by paviad** [comment]
I don't think this should be a feature of this library. If at all, extra colors should be random and different than pre-set colors.
