### ISSUE TITLE
Is label scrolling possible?

### ISSUE THREAD

**Issue by maerni** [valor-software/ng2-charts#1076]
For example we have a line chart with labels of 180 days. Now we want to show only the latest 30 days but then it should be possible to scroll to the right to see older days just to the 180 days.

Is something linke that possible?

Thanks very much.

**Comment by paviad** [comment]
There's no built in feature for this, there might be a `chart.js` plugin that does it (try looking [here](https://www.chartjs.org/docs/latest/notes/extensions.html)). Or you can implement it yourself by hooking into the `chartClick` and `chartHover` events and implement your own dragging mechanism.

**Comment by maerni** [comment]
> There's no built in feature for this, there might be a `chart.js` plugin that does it (try looking [here](https://www.chartjs.org/docs/latest/notes/extensions.html)). Or you can implement it yourself by hooking into the `chartClick` and `chartHover` events and implement your own dragging mechanism.

Ok thanks very much. I will look at these plugins of chart.js.
