### ISSUE TITLE
In ng2-chart, setTimeOut function is not working on firefox using angular 7

### ISSUE THREAD

**Issue by NikitaPooja** [valor-software/ng2-charts#1095]
I am using setTimeOut function for ng2-chart. when Reload the app ng2-chart data not show thats way I am using setTimeout function. In crome browser,setTimeout function worked and ng2-chart data show but in firefox browser, setTimeout not worked or ng2-chart data not show.

**Comment by paviad** [comment]
Can you provide a stackblitz repro which works on chrome but fails on firefox?

**Comment by santam85** [comment]
Can't reproduce.
