### ISSUE TITLE
Error :- e is undefined in firefox using ng2-chart 

### ISSUE THREAD

**Issue by NikitaPooja** [valor-software/ng2-charts#1096]
ERROR TypeError: "e is undefined"
    chartDataChange http://bebo.theironnetwork.org/8.8a3ca98d27ca0948d32f.js:1
    ngOnInit http://bebo.theironnetwork.org/8.8a3ca98d27ca0948d32f.js:1
    invokeTask http://bebo.theironnetwork.org/polyfills.5894f199c513e3d2127b.js:1
    onInvokeTask http://bebo.theironnetwork.org/main.cc57e5dba8b386cad86c.js:1
    invokeTask http://bebo.theironnetwork.org/polyfills.5894f199c513e3d2127b.js:1
    runTask http://bebo.theironnetwork.org/polyfills.5894f199c513e3d2127b.js:1
    invokeTask http://bebo.theironnetwork.org/polyfills.5894f199c513e3d2127b.js:1
    invoke http://bebo.theironnetwork.org/polyfills.5894f199c513e3d2127b.js:1
    0 http://bebo.theironnetwork.org/polyfills.5894f199c513e3d2127b.js:1
main.cc57e5dba8b386cad86c.js:1:695389

**Comment by paviad** [comment]
Please provide a stackblitz repro, the demo app does work without a hitch on firefox as well as on chrome.

**Comment by santam85** [comment]
Can't reproduce.
