### ISSUE TITLE
scales property from ChartOptions interface should be scale

### ISSUE THREAD

**Issue by marianazangrossi** [valor-software/ng2-charts#1098]
I was trying to change the `ticks` property to build a Radar Chart, and it was not working until I changed `scales` by `scale`

Before: 
```
radarChartOptions: ChartOptions = {
    scales: {
      ticks: {
        beginAtZero: true,
        min: 0,
        max: 100,
        stepSize: 25,
        display: false
      }
    }
  };

```

After:
```
radarChartOptions: ChartOptions = {
    scale: {
      ticks: {
        beginAtZero: true,
        min: 0,
        max: 100,
        stepSize: 25,
        display: false
      }
    }
  };

```

**Comment by paviad** [comment]
I thank you so much for this observation, I honestly had no idea! This is so confusing... By the way this is from `chart.js` not from our wrapper of course.

**Comment by marianazangrossi** [comment]
Oh, sorry! I didn't realize that! I'll open an issue where the `index.d.ts` from `chart.js` is. Thank you!
