### ISSUE TITLE
The library is not working with Angular2 2.0.0-beta version

### ISSUE THREAD

**Issue by mappmechanic** [valor-software/ng2-charts#11]
I think you have loaded core components from 'angular2/angular2', which does not even exists right now.

**Comment by valorkin** [comment]
much simpler, this lib is for ng2 0.46.0, but I am updating it to beta right now

**Comment by magnayn** [comment]
I've done a chunk of upgrading locally, seems to nearly work..

**Comment by magnayn** [comment]
This mostly works if it's of any help
https://github.com/magnayn/ng2-charts

(There's an oddity around the table on the line chart demo that I don't understand, rest seems fine)

**Comment by valorkin** [comment]
Great job! @magnayn 
I am merging https://github.com/valor-software/ng2-charts/pull/12
but I would love to see some changes I see in your version like Input\Output

I have changed a bit npm publishing, etc...
