### ISSUE TITLE
Why did i get this Error (ParseError) ?!

### ISSUE THREAD

**Issue by YazCan** [valor-software/ng2-charts#110]
**When i serve my project locally i got this error ? **

node_modules/ng2-charts/ng2-charts.ts:1
export * from  './components/charts/charts';
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module'

**Comment by aicokleinovink** [comment]
I'm getting the same error since I'm using `angular 2.0.0-beta.13`

**Comment by davyzhang** [comment]
add extension '.ts' to browserify options fixed this problem

```  browserifyOptions: {
    cache: {},
    packageCache: {},
    debug: true,
    extensions:['.js','.ts'],
  },

```

looks like ng2-charts used typscript

**Comment by valorkin** [comment]
Now serving .js and .d.ts
