### ISSUE TITLE
Angular 4?

### ISSUE THREAD

**Issue by SteeledSlagle13** [valor-software/ng2-charts#1100]
Will this still work with Angular 4?

**Comment by adrogon** [comment]
It still works with Angular 8.
`ng2` is only the vestige of a time when `ng` meant "AngularJS". It does not mean it only works with Angular2, but anything Angular Typescript.

**Comment by danieldanielecki** [comment]
It still works with Angular 8, this issue should've been closed.

**Comment by SteeledSlagle13** [comment]
whoops XD
