### ISSUE TITLE
Chart is not defined when build prerender

### ISSUE THREAD

**Issue by tuanuvt001** [valor-software/ng2-charts#1103]
```
> node prerender.js

ReferenceError: Chart is not defined
    at eval (webpack:///./node_modules/ng2-charts/fesm5/ng2-charts.js?:1057:15)
```

**Comment by P0wersl4ve** [comment]
I already replied to your comment in #991 , I recommend trying downgrading to the mentioned versions which are currently working on my project with angular 7 / Universal =) also closing this issue, please.

"ng2-charts": "^1.6.0",
"chart.js": "^2.7.3"
