### ISSUE TITLE
Improve Bundle Size by correctly importing lodash.js

### ISSUE THREAD

**Issue by Starofall** [valor-software/ng2-charts#1105]
When using ng2-charts I currently get the complete lodash.js also imported into my build.

Lodash itself is 70k and it would be easy to get rid of most of this dependency.

I looked through the code and just found a single usage of lodash:

```
https://github.com/valor-software/ng2-charts/blob/development/projects/ng2-charts/src/lib/base-chart.directive.ts
443      options = _.cloneDeep(options);
```

If you would just change the code like this:
```
- 18 import * as _ from 'lodash';
+ 18 import {cloneDeep} from 'lodash';

- 443      options = _.cloneDeep(options);
+ 443      options = cloneDeep(options);
```

With this change the tree-shaking could get rid of most of the 70k lodash dependency, as discussed in this article:  https://www.blazemeter.com/blog/the-correct-way-to-import-lodash-libraries-a-benchmark

**Comment by beyondsanity** [comment]
I'm sorry to reopen this, but the library is still bringing in all lodash.
The correct way of importing cloneDeep for tree shacking should be:

`import cloneDeep deom 'lodash/cloneDeep';`
