### ISSUE TITLE
Internationalization (i18n)

### ISSUE THREAD

**Issue by Gimly** [valor-software/ng2-charts#1107]
I'd like to know if there is something simple that can be done to add internationalization to the graphs, for example, to translate the labels of the data. 

In most of my cases, the labels are static and I'd like to be able to translate them using Angular's i18n method.

Thanks.

**Comment by alberto-martinbelloso** [comment]
Any update on this? I'm facing the same issue

**Comment by santam85** [comment]
This should be possible starting in Angular 11 by combining [$localize](https://angular.io/api/localize) and the standard configuration options.
