### ISSUE TITLE
How to compile with lodash-es instead of lodash

### ISSUE THREAD

**Issue by cantacell** [valor-software/ng2-charts#1120]
Hi,
I cloned the repository and tried to compile with lodash-es instead of lodash  with npm command: "build:lib". It builds succesfully and i pushed it into my repository. When I want to use my repository I have these errors:  
"warning: templates not found in C:\Users\Frank\AppData\Local\Temp\pacote-git-template-tmp\git-clone-d869375e
npm ERR! Host key verification failed.
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! fatal: clone of 'git@github.com:chartjs/chartjs-chart-financial.git' into submodule path 'C:/Users/Frank/AppData/Roaming/npm-cache/_cacache/tmp/git-clone-c51e0978/chartjs-cha
rt-financial' failed"

If I try to run build:prop on my ng2-charts repository  I wille have:
ERROR in ./src/app/financial-chart/financial-chart.component.ts
Module not found: Error: Can't resolve 'dist/chartjs-chart-financial/chartjs-chart-financial' in 'C:\Users\Frank\WebstormProjects\ng2-charts\ng2-charts\src\app\financial-chart'
ERROR in ./dist/ng2-charts/fesm5/ng2-charts.js
Module not found: Error: Can't resolve 'lodash-es' in 'C:\Users\Frank\WebstormProjects\ng2-charts\ng2-charts\dist\ng2-charts\fesm5'

**Comment by adrogon** [comment]
This PR probably answers your question: https://github.com/valor-software/ng2-charts/pull/1123
