### ISSUE TITLE
Importing csv file data to postgresql table in omnidb where many tables are linked with each other by one of the column in windows

### ISSUE THREAD

**Issue by JanhviK** [valor-software/ng2-charts#1121]
I am using this command to import csv file data to postgresql in omnidb :

COPY owner."order"(id,type,name) 
FROM 'C:\Users\Desktop\omnidb_exported.csv' DELIMITER ';' CSV HEADER;
Getting this error, although it exists:

could not open file "C:\Users\Desktop\omnidb_exported.csv" for reading: No such file or directory

I have also provided everyone security permissions to read on csv file and its folder. Still the problem exists.

The csv file has delimiter ";" with header information. This owner schema has 3 tables, which are connected by "id" column.

How to import the csv file data correctly? What is the problem with this commands?

**Comment by santam85** [comment]
Not an issue. Refer to the the [Chart.js documentation](https://www.chartjs.org/docs/latest/) to learn how to configure charts.
