### ISSUE TITLE
Can you call resetZoom()?

### ISSUE THREAD

**Issue by NickBellamy** [valor-software/ng2-charts#1141]
In the [chart.js zoom plugin](https://github.com/chartjs/chartjs-plugin-zoom) there is a method `resetZoom()` - is this method accessible from ng2-charts, and if so, how do you call it?

**Comment by NickBellamy** [comment]
I managed to achieve this by getting the chart instance via `ViewChild()`, and then calling `resetZoom()` on it:

```
export class MyClass {
  @ViewChild(BaseChartDirective, { static: false }) chart: BaseChartDirective;

  private myResetZoom(): void {
    this.chart.chart.resetZoom();
  }
```

TypeScript won't like it as the `resetZoom()` method isn't exposed (See #1128), so you may have to suppress the error, but it will work.

**Comment by filippoboiani** [comment]
how did you suppress the error @NickBellamy ?

**Comment by sp3rk** [comment]
`this.chart.chart.['resetZoom']()`
throws ERROR 'error TS1003: Identifier expected.'

**Comment by biocrista96** [comment]
i still cannot get the resetZoom()

if i do this.chart.resetZoom() i get an error "Property 'resetZoom' does not exist on type 'BaseChartDirective'"

and if i made this.chart.chart.resetZoom() its  "Property 'resetZoom' does not exist on type 'Chart'"

and if  this.chart.chart.['resetZoom']()  throws ERROR 'error TS1003: Identifier expected.'

im using the pluggin of chart.js zoom in ng2charts, and ots works well, but i can access to them :(
