### ISSUE TITLE
Needs System.js entry [with solution]

### ISSUE THREAD

**Issue by airburst** [valor-software/ng2-charts#116]
Hi,

Nice work on the library, thanks.

Most users will come to this from the Angular2 docs, which use System.js rather than webpack.  Your directives don't install without a change in System.js config (for me at least).  I got the classic error where my index.html file is imported instead of charts.js.

See below:

        System.config({
            packages: {        
                app: {
                    format: 'register'
                },
                'ng2-charts': {
                    main: 'charts.js'         
                }  
            },
            map: {
                'ng2-charts': 'node_modules/ng2-charts/components/charts'
            }  
        });     
        System.import('app/boot')
            .then(null, console.error.bind(console));

**Comment by marcopolo25** [comment]
@airburst - ate these the changes you need to make for the charts to work? I've been fighting with this issue for a couple of days now.

**Comment by airburst** [comment]
@marcopolo25  -yes; I added that to my system.config script in index.html and the charts work fine.  Whenever you see a console error with an unrecognised "<" it generally means that system.js is trying to import a script (from an import statement) but can't resolve it to the necessary ts or js file and so pulls in your index html instead.

**Comment by yusijs** [comment]
@airburst Do you have a full example of this in action? I'm trying to get it working, but it's breaking all the time:
angular2-polyfills.js:267 Uncaught EXCEPTION: Error during evaluation of "mousemove"
ORIGINAL EXCEPTION: TypeError: Cannot read property 'getPointsAtEvent' of undefined
ORIGINAL STACKTRACE:
TypeError: Cannot read property 'getPointsAtEvent' of undefined
    at BaseChart.hover (http://localhost:3000/node_modules/ng2-charts/components/charts/charts.js:174:45)
    at AbstractChangeDetector.ChangeDetector_BaseChart_0.handleEventInternal (viewFactory_BaseChart:37:24)
    at AbstractChangeDetector.handleEvent (http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:9568:25)
    at AppView.triggerEventHandlers (http://localhost:3000/node_modules/angular2/bundles/angular2.dev.js:10246:34)

And the chart looks like this in the dom:
![image](https://cloud.githubusercontent.com/assets/11261560/14466973/62537964-00d9-11e6-951c-c098ab542c32.png)

Now, I know I'm missing something, but I've added your lines to my systemjs, and the .js is getting imported (as you can see above). I'm using the line-example outlined @ http://valor-software.com/ng2-charts/

Any clue?

**Comment by valorkin** [comment]
check bundles folder
