### ISSUE TITLE
Schematic does not work

### ISSUE THREAD

**Issue by danwellman** [valor-software/ng2-charts#1160]
**Reproduction of the problem**

1. Add 2 modules to the root of your app
2. Run `ng generate ng2-charts-schematics:[chart-type] [component-name]` as directed by ng2-charts documentation
3. Experience the error: "More than one module matches. Use skip-import option to skip importing the component into the closest module."
4. Update command to `ng generate ng2-charts-schematics:[chart-type] [component-name] --skip-import`
5. Experience the exact same error message as before, as if you had not added the `--skip-import` flag
6. Try specifying the correct module using the `--module` flag, e.g. `ng generate ng2-charts-schematics:[chart-type] [component-name] --module app.module`
7. Experience the error: "Index 6251 outside of range [0, 287]."
8. Cry

**Environment**
Angular 7.2.15
ng2-charts 2.3.0
Angular-cli 7.2.15
Mac OSX

**Comment by matheeshaYapa** [comment]
That is not an issue with the schematic.
Please try this.
`ng generate ng2-charts-schematics:[chart-type] [component-name] --module=app.module.ts`

**Comment by danwellman** [comment]
Excellent, that works, thanks.

Is `--skip-import` not working a problem with this schematic?
