### ISSUE TITLE
Can someone let me know how to label each point in scatter plot.

### ISSUE THREAD

**Issue by amitmoondra** [valor-software/ng2-charts#1176]
**Reproduction of the problem**

ng2-charts is a port & modification of Chart.js component for Angular 2. Sometimes the issue is related with Chart.js instead of ng2-charts.
To confirm, if the issue shows in a pure Chart.js project, it is a issue of Chart.js.
Pure Chart.js starting template: https://jsfiddle.net/Hongbo_Miao/mvct2uwo/3/

If the issue does not show in a pure Chart.js project, and shows in a ng2-charts project, please try to provide a minimal demo of the problem.
ng2-charts starting template: http://plnkr.co/edit/Ka4NXG3pZ1mXnaN95HX5?p=preview

**Comment by anand171** [comment]
So Simple pass label in scatterChartData and fetch it in tooltip by index in scatterChartOptions like...

Passing label in scatterChartData:

    for (let i = 0; i < this.data.length; i++) {
     let temp ={
      x:this.data[i].x_coordinates,
      y:this.data[i].y_coordinates,
      label:this.data[i].Category
     }
     this.scatterChartData[0].data.push(temp);
    }



Now fetch the label in tooltip:

  

    public scatterChartOptions: ChartOptions = {
      responsive: true,
      tooltips: {
          callbacks: {
            label: (item, data) => 
            {
              return this.scatterChartData[0].data[item.index].label + ' (X: '+ item.xLabel + ', Y: ' + item.yLabel +')'
            }
          }
        }
      };

It solved my problem
