### ISSUE TITLE
How do I get CanvasRenderingContext2D drawing context from BaseChartDirective?

### ISSUE THREAD

**Issue by micobarac** [valor-software/ng2-charts#1180]
If I do it like this:

```typescript
  @ViewChild('chartRef', { static: true })
  chartRef: BaseChartDirective;
```

There is a 

```typescript
this.chartRef.ctx
```
property, but it is a type of a `string`?

If I do it like this:

```typescript
  @ViewChild('chartRef', { static: true })
  chartRef: ElementRef;
```
I can get the context property by accessing

```typescript
this.chartRef.nativeElement.getContext('2d')
```

**Comment by micobarac** [comment]
I found a property:

```typescript
this.chartRef.chart.ctx
```

**Comment by micobarac** [comment]
But, now I have a problem:

```typescript
this.chartRef.chart
```

is undefined :(.

**Comment by santam85** [comment]
All chart properties are exposed in the directive instance, as in your example. If it's undefined it means it failed to render a chart.
