### ISSUE TITLE
ng2-charts - on component navigation error occurs - "Cannot read property 'onDestroy' of undefined"

### ISSUE THREAD

**Issue by pbravichandhar** [valor-software/ng2-charts#1184]
![image](https://user-images.githubusercontent.com/39514623/69941026-9eb87880-1509-11ea-9b79-4666a59a6dc9.png)

angular 7+ 
ng2-charts ^2.2.3

I am using minimum 3 charts in each routes.

When I try to navigate from one component to another I am getting this ERROR(screenshot)

Any fixes

**Comment by pbravichandhar** [comment]
I have found  the solution on my own!

whenever route navigates I use

Foe single chart:-

`
 @ViewChild(BaseChartDirective) chart: BaseChartDirective;

if (this.chart) {
          this.chart.ngOnDestroy();
        }`

for multiple chart in same component:-

`@ViewChildren(BaseChartDirective) charts: QueryList<BaseChartDirective>;

        const charts = _.get(this.charts, '_results');
        _.forEach(charts, (value) => {
          if (value) {
            value.ngOnDestroy();
          }
        });`


I have destroy it manually .

It works like a charm.!

**Comment by mehs2690** [comment]
HI
Where is this code snippet placed?
