### ISSUE TITLE
How to hide line values in a bar and line chart

### ISSUE THREAD

**Issue by GuilhermeHumberto** [valor-software/ng2-charts#1191]
I would like to hide the line values and leave only the bar values in the graph.

### Component
```typescript
import { ChartOptions, ChartType, ChartDataSets } from 'chart.js';
import * as pluginDataLabels from 'chartjs-plugin-datalabels';
import { Label } from 'ng2-charts';
```

```typescript
  public barChartOptions: ChartOptions = {
    responsive: true,
    maintainAspectRatio: false,
    scales: { 
      yAxes: [{ ticks: { fontSize: 0 }}],
      xAxes: [{ ticks: { fontSize: 25 }}] 
    },
    plugins: {
      datalabels: {
        color: 'white',
        font: {          
          size: 18
        }        
      }
    }
  };

  public barChartLabels: Label[] = ['Dez', 'Jan', "Fev", "Mar", "Abr", "Mai", "Jun", "Jul", "Ago", "Set", "Out", "Nov", "Dez"];
  public barChartType: ChartType = 'bar';
  public barChartLegend = true;
  public barChartPlugins = [pluginDataLabels];

  public barChartData: ChartDataSets[] = [    
    {
      label: "Espectativa",
      backgroundColor: "white",
      borderColor: "gray",
      data: [40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100],
      fill: false,            
      type: 'line',
      showLine: true,
      stack: "1"
    },
    {
      label: "Meta do Mês",
      backgroundColor: ['green', 'green', 'green','green', 'red', 'green','green', 'red', 'green','red', 'red', 'red','red'],
      data: [65, 59, 80, 81, 56, 80, 75, 59, 80, 81, 56, 59, 70],
      stack: "2"
    }
  ];
```

### HTML
```html
  <canvas baseChart
    [datasets]="barChartData"
    [labels]="barChartLabels"
    [options]="barChartOptions"
    [plugins]="barChartPlugins"
    [legend]="barChartLegend"
    [chartType]="barChartType">
  </canvas>
```

### PrintScreen
![Screenshot 2019-12-16_09-42-34-291](https://user-images.githubusercontent.com/25077663/70907843-aa676d00-1fe8-11ea-8f0c-6c8a9ce1518e.png)

**Comment by steeefyyy** [comment]
> I would like to hide the line values and leave only the bar values in the graph.
> 
> ### Component
> ```ts
> import { ChartOptions, ChartType, ChartDataSets } from 'chart.js';
> import * as pluginDataLabels from 'chartjs-plugin-datalabels';
> import { Label } from 'ng2-charts';
> ```
> 
> ```ts
>   public barChartOptions: ChartOptions = {
>     responsive: true,
>     maintainAspectRatio: false,
>     scales: { 
>       yAxes: [{ ticks: { fontSize: 0 }}],
>       xAxes: [{ ticks: { fontSize: 25 }}] 
>     },
>     plugins: {
>       datalabels: {
>         color: 'white',
>         font: {          
>           size: 18
>         }        
>       }
>     }
>   };
> 
>   public barChartLabels: Label[] = ['Dez', 'Jan', "Fev", "Mar", "Abr", "Mai", "Jun", "Jul", "Ago", "Set", "Out", "Nov", "Dez"];
>   public barChartType: ChartType = 'bar';
>   public barChartLegend = true;
>   public barChartPlugins = [pluginDataLabels];
> 
>   public barChartData: ChartDataSets[] = [    
>     {
>       label: "Espectativa",
>       backgroundColor: "white",
>       borderColor: "gray",
>       data: [40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100],
>       fill: false,            
>       type: 'line',
>       showLine: true,
>       stack: "1"
>     },
>     {
>       label: "Meta do Mês",
>       backgroundColor: ['green', 'green', 'green','green', 'red', 'green','green', 'red', 'green','red', 'red', 'red','red'],
>       data: [65, 59, 80, 81, 56, 80, 75, 59, 80, 81, 56, 59, 70],
>       stack: "2"
>     }
>   ];
> ```
> 
> ### HTML
> ```
>   <canvas baseChart
>     [datasets]="barChartData"
>     [labels]="barChartLabels"
>     [options]="barChartOptions"
>     [plugins]="barChartPlugins"
>     [legend]="barChartLegend"
>     [chartType]="barChartType">
>   </canvas>
> ```
> 
> ### PrintScreen
> ![Screenshot 2019-12-16_09-42-34-291](https://user-images.githubusercontent.com/25077663/70907843-aa676d00-1fe8-11ea-8f0c-6c8a9ce1518e.png)

Did you had answer on this???? Its happening to me - not sure why.

**Comment by steeefyyy** [comment]
I am having similar issue with all my charts and not really sure what the problem could be: 

![11](https://user-images.githubusercontent.com/3502498/85209756-bd158280-b33a-11ea-85d6-19c513312697.jpg)
![22](https://user-images.githubusercontent.com/3502498/85209758-be46af80-b33a-11ea-96d2-3c8970530a6a.jpg)

Could it be version problem????

my package.json
`{
  "name": "XXXX",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~9.1.11",
    "@angular/cdk": "^9.2.4",
    "@angular/common": "~9.1.11",
    "@angular/compiler": "~9.1.11",
    "@angular/core": "~9.1.11",
    "@angular/forms": "~9.1.11",
    "@angular/material": "^9.2.4",
    "@angular/material-moment-adapter": "^9.2.4",
    "@angular/platform-browser": "~9.1.11",
    "@angular/platform-browser-dynamic": "~9.1.11",
    "@angular/router": "~9.1.11",
    "@types/chart.js": "^2.9.22",
    "bootstrap": "^4.5.0",
    "chart.js": "^2.9.3",
    "chartjs-plugin-datalabels": "^0.7.0",
    "font-awesome": "^4.7.0",
    "jwt-decode": "^2.2.0",
    "moment": "^2.26.0",
    "ng-multiselect-dropdown": "^0.2.10",
    "ng2-charts": "^2.3.1",
    "rxjs": "~6.5.4",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "3": "^2.1.0",
    "-": "0.0.1",
    "@angular-devkit/build-angular": "^0.901.9",
    "@angular/cli": "~9.1.9",
    "@angular/compiler-cli": "~9.1.11",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.11.1",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "jquery": "^3.5.1",
    "karma": "~5.0.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-jasmine": "~3.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "popper.js": "^1.16.1",
    "protractor": "~5.4.3",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~3.8.3"
  }
}
`

**Comment by mayeg** [comment]
Do you fix this issue?

**Comment by arsenlol** [comment]
I have the same issue on cartesian line chart, and because of object values in dataset chart looks like a mess.
I have dug deep into charts.js issues, but it seems like this does not reproduce with pure charts.js itself.
![image](https://user-images.githubusercontent.com/8538255/94247985-89905880-ff26-11ea-915b-54a2a7859999.png)
ChartOptions are
`{
  responsive: true,
  scales: {
    xAxes: [{
      type: 'time',
      time: {
        parser: 'MM/DD/YYYY',
      }
    }],
    yAxes: []
  }
};`
Dataset item looks like this:
`{
        label: string,
        data: { t: string, y: number },
        fill: false,
      }`

**Comment by arsenlol** [comment]
My bad, chart.js itself appears to have this bug. After I removed ng2-charts, same issue preserved. Will look for another library.

**Comment by arsenlol** [comment]
Consider this https://stackoverflow.com/questions/51268325/chartjs-hide-data-point-labels

**Comment by santam85** [comment]
This library defers all the functionality to Chart.js. Refer to the the [Chart.js documentation](https://www.chartjs.org/docs/latest/) to learn how to configure charts. For this, try the data decimation feature.
