### ISSUE TITLE
Color class is missing lineTension property

### ISSUE THREAD

**Issue by atheros** [valor-software/ng2-charts#1192]
**Reproduction of the problem**

The Color interface is missing lineTension property used to make straight lines or adjust their curves (see https://www.chartjs.org/docs/latest/charts/line.html)

Forcing this property works as expected but without casting the object to any, it produces compiler error/warning.

**Comment by filipiz** [comment]
Line tension is not color related.
Use dataset instead.

**Comment by santam85** [comment]
Types are now inherited from Chart.js
