### ISSUE TITLE
Type 'number[]' is not assignable to type 'number | ChartPoint'

### ISSUE THREAD

**Issue by webmajstr** [valor-software/ng2-charts#1194]
Hi,

according to Bar chart documentation of ChartJS, I am creating chart where I define starting and ending point of each bar as following:

```
this.chartData = [
      { data: [[0,3], [3,6], [5,17], [0,20]], label: 'Crude oil prices' },
    ];
```

Code works as expected, but I get TS errors, that data types are incompatible.

```
ERROR in src/app/components/bar-chart/bar-chart.component.ts(47,16): error TS2322: Type 'number[]' is not assignable to type 'number | ChartPoint'.
      Type 'number[]' is not assignable to type 'number'.
```

**Comment by dagdashboard** [comment]
I am also facing a similar issue.

I am having the following code inside the bubbleChartOptions: ChartOptions. 
I am getting the following error. Request support
         Type '(context: any) => number' is not assignable to type 'number'.
elements:
{
point:
{
radius: function(context) {
var index = context.dataIndex;
var data = context.dataset.data[index];
var size = context.chart.width;
var base = Math.abs(data.value) / 30;
var value = Math.round((size /5) * base);
return value;
},
}
},

**Comment by santam85** [comment]
Since v3, we reverted to Chart.js original types, please upgrade to fix this.
