### ISSUE TITLE
Load charts.js from CDN

### ISSUE THREAD

**Issue by gmparker2000** [valor-software/ng2-charts#1195]
I'm trying to reduce my application's bundle size.  Just wondering why I have to bundle chart.js? Can I not bundle ng2-charts and load chart.js by using a script tag in my applications index.html?  When I try this I get an error from ng2-charts saying that chart.js is missing.

**Comment by Syldel** [comment]
Hello, i try to do the same thing. Have you found a solution ? Thank you.

**Comment by santam85** [comment]
We want to support treeshaking for both ng2-charts and Chart.js. For this reason, pre-built version of the lib served by a CDN will not be supported.
