### ISSUE TITLE
Need support of borderAlign in Doughnut Chart. On hover border effect will comes outside the chart only.

### ISSUE THREAD

**Issue by aminsmartsenese** [valor-software/ng2-charts#1201]

**Comment by aminsmartsenese** [comment]
![Group 3206](https://user-images.githubusercontent.com/16609973/73152865-82931b00-40f7-11ea-9ae0-a7e59c74c102.png)

**Comment by santam85** [comment]
This library defers all the functionality to Chart.js. Refer to the the [Chart.js documentation](https://www.chartjs.org/docs/latest/) to learn how to configure charts.
