### ISSUE TITLE
Question : Is there a way to create a stacked radar chart?

### ISSUE THREAD

**Issue by Robiig** [valor-software/ng2-charts#1202]
I was wondering if there's an option or a workaround to create a stacked radar chart with ng2-charts?

Something like this :
![qFQdE](https://user-images.githubusercontent.com/11925424/73202788-171f6c80-413c-11ea-945c-40f679033948.png)

**Comment by danmana** [comment]
Chart.js does not have support for stacked radar charts, so ng2-charts doesn't have it either

See official docs: https://www.chartjs.org/docs/master/charts/radar/

You would have to extend the [Radar controller](https://github.com/chartjs/Chart.js/blob/2.9/src/controllers/controller.radar.js) and add some of the logic from [stacked bar charts](https://github.com/chartjs/Chart.js/blob/2.9/src/controllers/controller.bar.js#L233)

**Comment by santam85** [comment]
This library defers all the functionality to Chart.js. Refer to the the [Chart.js documentation](https://www.chartjs.org/docs/latest/) to learn how to configure charts.
