### ISSUE TITLE
Angular 9 and IE support

### ISSUE THREAD

**Issue by hailtothethief** [valor-software/ng2-charts#1207]
It looks like bar chart doesn't work properly in Angular 9 and Internet Explorer. Background color is not rendered correctly. 
Is there any chance Angular 9 support will be available any time soon?
  
![Screenshot from 2020-02-25 10-47-25](https://user-images.githubusercontent.com/17404815/75240470-49180300-57bc-11ea-94ce-e91026db89a2.png)

**Comment by arttu76** [comment]
Motivated by this issue I just tested my app's ng2-charts' bar charts and the bar chart background color worked just fine when tested with Internet Explorer 11 (running in virtualBox).

**Comment by ChrisProlls** [comment]
And what about Angular 9 ?

**Comment by arttu76** [comment]
(in case  that questions was directed at me) my tests were run on Angular 9.

**Comment by jpike88** [comment]
works fine for me on angular 9. @hailtothethief you sure it's not a conflicting dependency?

**Comment by hailtothethief** [comment]
> works fine for me on angular 9. @hailtothethief you sure it's not a conflicting dependency?

Yes, it turned out it was a conflicting dependency issue. Thanks all.
