### ISSUE TITLE
Add Two Colours in bar

### ISSUE THREAD

**Issue by elavanya** [valor-software/ng2-charts#1213]
need to add two color in each bar, one is #F8F8F8 from bottom to top full bar, and another one is actual data count #0084E7
Like this https://prnt.sc/ritp45

**Comment by filipiz** [comment]
You need a stacked bar chart 
See a @paviad example here: https://stackblitz.com/edit/ng2-charts-bar-stacked-example

**Comment by santam85** [comment]
Not an issue. Refer to the the [Chart.js documentation](https://www.chartjs.org/docs/latest/) to learn how to configure charts.
