### ISSUE TITLE
Set bar background color with specific condition

### ISSUE THREAD

**Issue by henleywc** [valor-software/ng2-charts#1216]
Hi guys, just wondering is it possible to set the bar background color if any bar value is more than or 
less than certain amount? let's say there are 3 bars in one chart. thanks

**Comment by Kr0san89** [comment]
@henleywc you can easily do it on your own. by mapping all values to a color and input them into the binding
`
<canvas baseChart 
            [datasets]="chartData"
            [colors]="colors"
            [chartType]="barChartType">
    </canvas>
`

`
colors = values.map(v => {
return {
      backgroundColor: /*your func on value for color -> returning a color string*/
    }
})
`
