### ISSUE TITLE
cannot find module moment

### ISSUE THREAD

**Issue by Abhinav-Mingwal** [valor-software/ng2-charts#1220]
ERROR in node_modules/@types/chart.js/index.d.ts(32,24): error TS2307: Cannot find module 'moment'.
i've tried npm install --save moment as well doesn't help
"ng2-charts": "^2.3.0",

**Comment by AlexMilutinovic** [comment]
I've the same problem. Anyone experiencing the same issue? Maybe some solution?

**Comment by rrpuente** [comment]
Same problem here

**Comment by vdumont54** [comment]
I've got the same issue, but after installing a certain version of moment, the problem was solved.
`npm i -S moment@2.24.0`
