### ISSUE TITLE
error TS2322: Type '{ responsive: true; scales: { xAxes: {}[]; - ChartOptions TypeScript

### ISSUE THREAD

**Issue by danieldanielecki** [valor-software/ng2-charts#1221]
The `ChartOptions` type causes `error TS2322: Type '{ responsive: true; scales: { xAxes: {}[];...` in compilation when working with TypeScript.

```
public lineChartOptions: ChartOptions & { annotation: any } = {
   ...
}
```
Only changing this to `any` keeps the code to compile
```
public lineChartOptions: any & { annotation: any } = {
   ...
}
```
Edit: `@types/chartjs` isn't helpeful as well.

**Comment by bhaveshv89** [comment]
I am also facing this issue

**Comment by bhaveshv89** [comment]
@danieldanielecki I found the issue, ChartOptions was not imported correctly.

It should be import { ChartDataSets, ChartOptions } from 'chart.js';
