### ISSUE TITLE
Remove peer dependency

### ISSUE THREAD

**Issue by jpike88** [valor-software/ng2-charts#1224]
@paviad I know you're looking for a new repo owner, but would be nice if you could update the peer dependency warning, this lib works fine on angular 9.

**Comment by sapher** [comment]
I agree, no issue with angular 9

**Comment by paviad** [comment]
I feel you, but I seriously have no time to deal with this - do you want to prepare a PR I can merge?

**Comment by pedroCX486** [comment]
@paviad I made it:

https://github.com/valor-software/ng2-charts/pull/1225

**Comment by hamza124** [comment]
can i use this for angular  version 7 ? plz some one help me.

**Comment by jpike88** [comment]
Yes

**Comment by hamza124** [comment]
> Yes

Thx @jpike88

**Comment by paviad** [comment]
Closed by ff54527b
