### ISSUE TITLE
Angular 9 and npm install warning

### ISSUE THREAD

**Issue by kosaa** [valor-software/ng2-charts#1226]
While using angular 9 npm install produces following warning:
`npm WARN ng2-charts@2.3.0 requires a peer of @angular/common@^7.2.0 || ^8.0.0 but none is installed. You must install peer dependencies yourself.`

Current ng-charts version: ^2.3.0

Do you have in plans update this dependency?

**Comment by pedroCX486** [comment]
This was fixed by me in #1225.

**Comment by kosaa** [comment]
done, thanks
