### ISSUE TITLE
Property 'legend' does not exist

### ISSUE THREAD

**Issue by MortimerCat** [valor-software/ng2-charts#1228]
I am updating from Angular8 to Angular9.  My older version of ng2-charts (1.5) did not like the upgrade, so I also updated ng2-charts to the current latest (2.3.2).

But I am left with one compile error  _**TS2339: Property 'legend' does not exist on type 'Chart'**_.

[code]
import { BaseChartDirective } from 'ng2-charts';

@ViewChild('feedbackChart') feedbackChart: BaseChartDirective;

this.legendData = this.feedbackChart.chart.legend.legendItems;      ** Error Line**
[/code]

To be honest, this is someone else's code and I have not experienced ng2-charts until now. There are old issues on this page that has the same syntax, so I am guessing something broke with V2.    Please can someone suggest an alternative syntax.

**Comment by cyraid** [comment]
I don't see a legendItems on ChartLegendOptions, but I do see "labels". So perhaps this.feedbackChart.chart.legend.labels?

**Comment by santam85** [comment]
It also depends on the version of Chart.js you are using, as types are inherited from there in more recent versions. Check https://www.chartjs.org/docs/latest/configuration/legend.html
