### ISSUE TITLE
Its imposible to add rounded corners through ng2-charts for bar chart

### ISSUE THREAD

**Issue by timucincicek** [valor-software/ng2-charts#1231]
to have a border on the edge of bar,we need to implement that kinda .js method. 

Chart.elements.Rectangle.prototype.draw = function() 
{}

If a callback did exist,would be awesome.What is wanted to be achieved below

![image](https://user-images.githubusercontent.com/39439504/83929588-9b45c880-a79c-11ea-9df4-f25435c0d2f7.png)

**Comment by vipuljdev** [comment]
I'm having same issue. Trying for few hours now, not finding any solution. Let me know if anyone found anything

**Comment by TurtleTower** [comment]
Please, I need that too!

**Comment by danmana** [comment]
Here is a great [stackoverflow answer](https://stackoverflow.com/a/43281198/281252) that covers how to draw rounded bars in detail.

The code there is for simple bar chart, not stacked, but was pretty easy to adapt - see https://codepen.io/danmana/pen/yLOGjPV?editors=1010

![image](https://user-images.githubusercontent.com/498419/93980814-cbcf6380-fd87-11ea-867d-71ba27324b92.png)

**Comment by IanIsFluent** [comment]
Thanks, but how do I package the JS code from Angular so that it actually affects the chart in the browser?

**Comment by danmana** [comment]
I hope this is not too late for you.

First of all, if you switched already to chart.js 3.0 beta, it has rounded corners built in - see [sample](https://www.chartjs.org/samples/next/charts/bar/border-radius.html) and [docs](https://www.chartjs.org/docs/next/charts/bar#borderradius)

For 2.9 I adapted [the stackoverflow](https://stackoverflow.com/a/43281198/281252) solution from above to ng2-charts:

https://stackblitz.com/edit/ng2-charts-bar-template-zdhqtt?file=src%2Fapp%2Fapp.component.ts

Important points:
* use `public barChartType: ChartType = "roundedBar" as ChartType;`
* datasets must set the stack `{ data: [65, 59, 80], stack: "a", label: "Series A" }`
* you must define colors - see issue https://github.com/valor-software/ng2-charts/issues/876

**Comment by dmontidev** [comment]
var options = {
    cornerRadius: 20,
};
use this option
I solve this problem with **cornerRadius** property

**Comment by santam85** [comment]
https://www.chartjs.org/docs/latest/charts/bar.html#borderradius
