### ISSUE TITLE
Update peerDependencies to angular 10

### ISSUE THREAD

**Issue by inpercima** [valor-software/ng2-charts#1236]
While using angular 10, yarn install produces following warning:
`warning " > ng2-charts@2.3.2" has incorrect peer dependency "@angular/common@^7.2.0 || ^8.0.0 || ^9.0.0".`

Current ng-charts version: 2.3.2

Do you have plans to update this dependency to version 10?

Thanks a lot.

**Comment by andrejm7** [comment]
pm WARN ng2-charts@2.3.2 requires a peer of @angular/common@^7.2.0 || ^8.0.0 || ^9.0.0 but none is installed. You must install peer dependencies yourself.     
npm WARN ng2-charts@2.3.2 requires a peer of @angular/core@^7.2.0 || ^8.0.0 || ^9.0.0 but none is installed. You must install peer dependencies yourself.

**Comment by joekaiser** [comment]
As far as I can tell, this package works perfect on ng10. if you run the upgrade with `--force` it will ignore the error and go through.

**Comment by inpercima** [comment]
@joekaiser You are right, the update will work as workaround. For a stable build, it would be good if the dependencies match each other. So next to ^7.2.0 || ^8.0.0 || ^9.0.0 the version 10 should be added.

**Comment by EugeneLeclerc** [comment]
This was resolved by https://github.com/valor-software/ng2-charts/commit/a9b15013dd3403af1c902822bf5e4b06b8e453a2.

**Comment by StoyanStAtanasov** [comment]
Please close to show as resolved from the start.

Why is this still open?
I was searching for a fix for ng10 update and saw this as open issue and was disappointed. But reading to the end it looks that is is resolved.

**Comment by EugeneLeclerc** [comment]
The maintainer is not really active on this project, so @inpercima needs to close it himself.

**Comment by inpercima** [comment]
Sorry, I will close the issue. I wasn't getting some info about the release.
