### ISSUE TITLE
Not Compatible with Angular 9 Ivy

### ISSUE THREAD

**Issue by bornagainraj7** [valor-software/ng2-charts#1239]
After adding the ChartsModule to app.module.ts and executing ng serve you get error as:

ERROR in node_modules/ng2-charts/lib/charts.module.d.ts:1:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.
    
    This likely means that the library (ng2-charts) which declares ChartsModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also, consider checking with the library's authors to see if the library is expected to be compatible with Ivy.
    
    1 export declare class ChartsModule {

![Screenshot (56)](https://user-images.githubusercontent.com/43012371/87313107-0ffbe780-c53f-11ea-974a-162c45eb8ace.png)

Please refer the screenshot for clearity

**Comment by bornagainraj7** [comment]
I've Installed the Latest one available to the current date.

**Comment by bornagainraj7** [comment]
I don't know why but when I do ng build  --prod I don't see any errors

**Comment by khertgeverola** [comment]
@bornagainraj7  I've encountered that error also. I just restart the server then the error is gone

**Comment by paviad** [comment]
Please check now, @santam85 has authored a major change updating the library for Angular 10.

**Comment by Danebrouwer97** [comment]
@paviad I've just updated to Angular 10 and `ng2-charts v2.4.0` and I've run into the following issue:
```
WARNING in C:\Users\...\node_modules\ng2-charts\__ivy_ngcc__\fesm2015\ng2-charts.js depends on 'chart.js'. 
CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
```
Should I post this as a new issue? Just seemed related to your comment.

**Comment by paviad** [comment]
I believe that is a new issue. Angular 10 projects issue that warning on many libraries. I am not proficient enough to understand what this warning is really about.

**Comment by santam85** [comment]
It is due to some of the dependencies of ng2-charts (including Chart.js) using non ES imports. It will be hopefully addressed when Chart.js is updated to 3.0.0, worst case scenario now is that your bundle size is slightly bigger.

**Comment by paviad** [comment]
I don't think it has any actual effect apart from letting you know about
the optimization and bundle size.

**Comment by LEJames12142** [comment]
> After adding the ChartsModule to app.module.ts and executing ng serve you get error as:
> 
> ERROR in node_modules/ng2-charts/lib/charts.module.d.ts:1:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.
> 
> ```
> This likely means that the library (ng2-charts) which declares ChartsModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also, consider checking with the library's authors to see if the library is expected to be compatible with Ivy.
> 
> 1 export declare class ChartsModule {
> ```
> 
> ![Screenshot (56)](https://user-images.githubusercontent.com/43012371/87313107-0ffbe780-c53f-11ea-974a-162c45eb8ace.png)
> 
> Please refer the screenshot for clearity

@bornagainraj7 did you find any solution for this ng-chart2 issue?

**Comment by MattBrou** [comment]
Same issue here with angular 12 and ng2-charts@3.0.0-rc.4

**Comment by santam85** [comment]
Are you restarting your `ng serve` after installation? The ngcc needs to get the change to pre-process your new dependency. Can you create a git repo where you reproduce the issue?

**Comment by santam85** [comment]
@MattBrou I can't reproduce this issue, have you tried deleting your package-lock and node_modules folder to make sure you have a clean install?
