### ISSUE TITLE
can't resetZoom()

### ISSUE THREAD

**Issue by biocrista96** [valor-software/ng2-charts#1247]
i can't access to te resetZoom() of the plugin  charjs-zoom-plugin, any idea how can i resetZoom to the normal?

**Comment by danmana** [comment]
Hi @biocrista96 

First you have to obtain a reference to the original `chart` object, then you can call `resetZoom` on it.

To do this:

In your template
```html
 <canvas
    baseChart
    #myChart="base-chart"
...
```
In your component:
```ts
  @ViewChild("myChart")
  myChart: BaseChartDirective;

  onButtonClick() { 
    this.myChart.chart.resetZoom();
  }
```

Here is a working example: https://stackblitz.com/edit/angular-ivy-q8jcls?file=src%2Fapp%2Fapp.component.ts

**Comment by docaohuynh** [comment]
Works with angular 19
[zoom with angular 19](https://github.com/valor-software/ng2-charts/issues/1175#issuecomment-2749819366)
