### ISSUE TITLE
Bar chart columns fail to render above a certain width

### ISSUE THREAD

**Issue by bbarn3y** [valor-software/ng2-charts#1249]
I have a bar chart where I want to render hundreds of columns. It works well at the beginning, however columns fail to show up above a certain index.

My chart isn't complex, I only used a few necessary configurations, however the dataset is fairly large.

Stackblitz example: https://stackblitz.com/edit/angular-wrvgme

In the example the first 183 column are correctly rendered, the 184th is only partly and above that the columns are not visible, but they are "there" since the tooltip on mouseover actually works.

Full disclosure, I posted this issue before on StackOverflow, but no solution was posted as of yet: https://stackoverflow.com/questions/63299071/ng2-charts-chart-js-bar-chart-columns-fail-to-render-above-a-certain-width

**Comment by EugeneLeclerc** [comment]
[It works well for me](https://i.imgur.com/v5pXTku.png), both on Firefox 80 and Chrome 84.

**Comment by bbarn3y** [comment]
Very weird, Chrome 85.0.4183.83:
<img src="https://user-images.githubusercontent.com/8375284/91385953-3eedc480-e832-11ea-93ac-4efe418b82fc.png" width="400">
On Firefox 79.0 it's even weirder for me:
<img src="https://user-images.githubusercontent.com/8375284/91386639-c1c34f00-e833-11ea-86fe-371781712b68.png" width="600">

After that invisible line the grid lines are darker and the tooltips get stuck, just like winning Solitaire :)

**Comment by bbarn3y** [comment]
Tested on mobile as well:
<img src="https://user-images.githubusercontent.com/8375284/91387085-b7558500-e834-11ea-9a58-ca443dc9e272.png" width="250">

**Comment by EugeneLeclerc** [comment]
Well I have absolutly no idea how can this happen. Good luck !

**Comment by martinpagesaal** [comment]
I'm having same issue in horizontalBar version

https://stackblitz.com/edit/ng2-charts-bar-template-m67v1t

Any ideas?

**Comment by EugeneLeclerc** [comment]
HorizontalBar works well for me too... There must be some kind of common denominator between both of you.

**Comment by martinpagesaal** [comment]
@EugeneLeclerc  it works ok for small amount of bars it's starts failing with 100 or 200+. Do you have a working example of horizontalBar with that amount of bars?

**Comment by EugeneLeclerc** [comment]
Yes, your exemple (https://stackblitz.com/edit/ng2-charts-bar-template-m67v1t) works ok for me, even beyond 200 bars : 
![image](https://user-images.githubusercontent.com/44815069/91858543-9d1f0b00-ec69-11ea-8976-a106248cabcc.png)


Same thing for vertical bars (https://stackblitz.com/edit/angular-wrvgme) : 
![image](https://user-images.githubusercontent.com/44815069/91858611-bc1d9d00-ec69-11ea-9868-1c914daf03f5.png)

The question is : why is it working for me and not for you ? And I have no idea of the answer.

**Comment by martinpagesaal** [comment]
🤔 @EugeneLeclerc oh... fun 

Chrome? what version?

**Comment by EugeneLeclerc** [comment]
I tested with both `Chrome Version 84.0.4147.135 (Official Build) (64 bits)` and `Firefox 80.0 (64-bit)`. I seriously know nothing about JS and front-end in general so I dont know if it can change anything, but I have 16 Go of RAM and I'm using the latest Windows 10 Enterprise Edition.

**Comment by bbarn3y** [comment]
Huh, both @martinpagesaal's and my example work fine for me now.
Firefox version 80.0, Chrome version 85.0.4183.83.

I'm testing on the exact same machine. The issue occured previously with Firefox version 79 and Chrome version 85.0.4183.83, so my Firefox version changed since then, but my Chrome version did not. I can't think of anything else that changed since then.

**Comment by EugeneLeclerc** [comment]
Could it be an issue with https://stackblitz.com/ itself ?

**Comment by bbarn3y** [comment]
Nope, I have a production website that I can't link here, but I'm experiencing the exact same things there.

**Comment by martinpagesaal** [comment]
Yeah, same here. Stackblitz is just a small example, I have a issue in prod as well

**Comment by danmana** [comment]
It could be a memory issue due to the large canvas size.

The HTML canvas has some memory constraints that are not immediately obvious, and that can cause all sorts of problems, from weird clipping to blurry rendering and crashes.

The canvas in the stackblitz demo has 10650 x 937 pixels when viewed fullscreen (on my PC it works correctly).
While this is well within limits for Chrome (16,384 x 16,384), it might be too large on devices with low memory.

There is a library to test the max supported area: https://github.com/jhildenbiddle/canvas-size
Can you run it on your device and see what it says?

**Comment by bbarn3y** [comment]
Thanks for the assessment, tested with the provided size (10650 x 937), got the following results:
![image](https://user-images.githubusercontent.com/8375284/94126260-af9af780-fe57-11ea-8d12-a3b698f7abde.png)

However, since one of the latest Chrome updates, my original stackblitz example started working for me perfectly. Tested on Firefox too and the issues disappeared for me there as well.
Asked my client directly, he said that for him the issue was fixed on Chrome, but still pops up on Firefox (the codebase did not change at all).

I'm not sure what caused the issue (or what's causing it still on certain machines), but the issue is likely not with ng2-charts, but somewhere deeper, so I'll close this issue.
