### ISSUE TITLE
Demo site does not load resources (valor-software.com/ng2-charts/)

### ISSUE THREAD

**Issue by danmana** [valor-software/ng2-charts#1253]
**Reproduction of the problem**

Open: https://valor-software.com/ng2-charts/

Result:
Blank page opens.

Open dev console:
`Not allowed to load local resource: file:///C:/Program%20Files/Git/ng2-charts/styles.f0c1e18b59e133136247.css`

![image](https://user-images.githubusercontent.com/498419/91400681-bdedf780-e848-11ea-8074-0dcbdbb73dea.png)

It looks like the build set a local absolute path for the js/css files (C:/Program Files/Git/ng2-charts)

**Comment by lascapi** [comment]
A work around :  https://web.archive.org/web/20200730194506if_/https://valor-software.com/ng2-charts/#/LineChart

**Comment by paviad** [comment]
Fixed by 02962268
