### ISSUE TITLE
"Border" between data in stacked bar chart with same backgroundcolor

### ISSUE THREAD

**Issue by fridagoransson** [valor-software/ng2-charts#1254]
I'm creating a stacked bar chart and som of the data have the same backgroundColor. When using ng2-charts there is a tiny "border" between the different data. 
https://stackblitz.com/edit/ng2-charts-bar-stacked-example-yaf1ma?file=src%2Fapp%2Fapp.component.ts

Example from chart.js. I think you can see the tiny borders in the beginning when it's animating but then they disappear: https://jsfiddle.net/ey15jdmp/

Is there something I can do to fix this?

**Comment by santam85** [comment]
Not an issue. Refer to the the [Chart.js documentation](https://www.chartjs.org/docs/latest/) to learn how to configure charts.
