### ISSUE TITLE
Module not found error

### ISSUE THREAD

**Issue by ziqbalbh** [valor-software/ng2-charts#1257]
When we do a clean npm install and then build angular project we are getting this error.

ERROR in ./src/app/app.module.ngfactory.js
Module not found: Error: Can't resolve '@valor-software/ng2-charts'

can anyone help.

**Comment by paviad** [comment]
Use `ng2-charts` not `@valor-software/ng2-charts` - the latter was published by mistake

**Comment by Andhu7** [comment]
I am having same issue,cant resolve @valor-software/ng2-charts 
Am using ng2-charts only

**Comment by paviad** [comment]
@valor-software/ng2-charts has been published by mistake, it has already
been unpublished.

**Comment by Andhu7** [comment]
I tried reinstalling the plugin but am getting the same error.
My angular version is 8 and my ng2-chart version is 2.4.1
Shall I downgrade it to 2.3.3?

**Comment by liberona91** [comment]
Same error here.

@paviad How do I specifiy only ng2-charts and not @valor-software/ng2-charts? It seems that npm installs that valor-software by itself

**Comment by paviad** [comment]
Running `npm i ng2-charts` should work, you can also do `npm view
ng2-charts` to see its stats

**Comment by debugger200** [comment]
Same problem with the above command. I downgraded to a stable version 2.3.3, it works. However still no solution for the version - 2.4.1. @paviad

**Comment by paviad** [comment]
Try to create a new directory, run `npm init` press enter on all the questions, then run `npm i -S ng2-charts` - does that work?

**Comment by liberona91** [comment]
Hi paviad,

We downgraded to 2.3.3 and compiled OK. We will try `npm i -S ng2-charts` later to see if it works.

Thanks a lot!

**Comment by amitusc** [comment]
HI @paviad,

We downgraded to 2.3.3 in our package.json but we are still seeing the same issue. Could you please advise.

Thanks

**Comment by paviad** [comment]
Sounds like it sometimes works and sometimes it doesn't, try deleting your
`node_modules` directory and running `npm i` again.

**Comment by yglodt** [comment]
> Sounds like it sometimes works and sometimes it doesn't, try deleting your `node_modules` directory and running `npm i` again.

Tried this and still got the error when using 2.4.1

**Comment by paviad** [comment]
Can you provide a minimal reproduction example?

**Comment by paviad** [comment]
Try deleting `package-lock.json` too

**Comment by paviad** [comment]
@ziqbalbh please close if resolved.

**Comment by paviad** [comment]
See this https://github.com/valor-software/ng2-charts/issues/1260#issuecomment-692174405

**Comment by Esom** [comment]
> Hi paviad,
> 
> We downgraded to 2.3.3 and compiled OK. We will try `npm i -S ng2-charts` later to see if it works.
> 
> Thanks a lot!

had to downgrade to 2.3.3 as well to resolve this issue

**Comment by paviad** [comment]
@Esom did you see https://github.com/valor-software/ng2-charts/issues/1260#issuecomment-692174405 ?
