### ISSUE TITLE
Error: getInternalNameOfClass() called on a non-ES5 class

### ISSUE THREAD

**Issue by upadhyaya8095** [valor-software/ng2-charts#1264]
Error on worker 7: Error: getInternalNameOfClass() called on a non-ES5 class: expected ThemeService to have an inner class declaration ​at Esm5ReflectionHost.getInternalNameOfClass.
I am currently using v2.3.0 and chart.js 2.9.3. Recently I have not done any changes to my code but still my builds are failing in the pipeline.

tsconfig
"target": "es5",    
// "target": "es2015", -> no luck
"module": "esnext",
"lib": [
      "es2018",
      "dom"
    ]

I tried adding ThemeService to my ~~imports~~ **providers** in my module where I have imported my Chartmodule. But still It did not work.
So I wanted to know, is there something which I am missing!

**Comment by paviad** [comment]
`ThemeService` should go in the `providers` section, not in the `imports` section, and then only for angular <=8

**Comment by upadhyaya8095** [comment]
Sorry It was a typo, I have actually added it to providers only

**Comment by paviad** [comment]
Can you tell me how to reproduce this? What angular version, what is the content of `package.json`?

**Comment by upadhyaya8095** [comment]
```
{
  "name": "ng2chart-test",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~9.1.4",
    "@angular/common": "~9.1.4",
    "@angular/compiler": "~9.1.4",
    "@angular/core": "~9.1.4",
    "@angular/forms": "~9.1.4",
    "@angular/platform-browser": "~9.1.4",
    "@angular/platform-browser-dynamic": "~9.1.4",
    "@angular/router": "~9.1.4",
    "chart.js": "^2.9.3",
    "ng2-charts": "^2.3.0",
    "rxjs": "~6.5.5",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.901.4",
    "@angular/cli": "~9.1.4",
    "@angular/compiler-cli": "^9.1.4",
    "@angular/language-service": "~9.1.4",
    "@types/bootstrap": "^4.3.1",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.11.1",
    "codelyzer": "^5.1.2",
    "jasmine-core": "^2.5.2",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "^5.0.2",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage": "^1.1.2",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-spec-reporter": "0.0.32",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.8.3"
  }
}
```
Issue observed in two different  angular versions - 9.1.4 and 8.1.2
I am not able to reproduce this in my local system. But this issue is coming up in my Jenkins pipeline. It was working fine till August last week.  Have not done any changes to my pipeline. (Linux env)

**Comment by paviad** [comment]
Can you clear the cache of the pipeline?

**Comment by upadhyaya8095** [comment]
I will try to clear it out but for v2.3.0, I don't see any update. I am trying to understand what is the root cause of it.

**Comment by pungiish** [comment]
Having the same problem here. Works on my local windows machine, but not on the server.

**Comment by upadhyaya8095** [comment]
I tried clearing the cache in my server, Thanks @paviad . looks like the issue is resolved for me now.
