### ISSUE TITLE
ng2-charts doesn't work with newly created angular 10 project 

### ISSUE THREAD

**Issue by KhaledMansour92** [valor-software/ng2-charts#1268]
**Reproduction of the problem**
- create a new angular project using **Angular CLI: 10.1.2** by running `ng new testChart` 
- run  `npm install ng2-charts --save` 
- run `npm install chart.js --save`
- add **ChartsModule** to **imports** in **app.module.ts** and save 
- run `ng serve` 
------------------------------------------------------------------------------------------
**Expected behavior** 
- the project runs 

**Actual behavior** 
- exception is thrown as shown below 
```
ERROR in node_modules/ng2-charts/lib/charts.module.d.ts:1:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.
This likely means that the library (ng2-charts/lib/charts.module) which declares ChartsModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.
1 - export declare class ChartsModule {
                          ~~~~~~~~~~~
```
----------------------------------------------------
[a related equation in stackoverflow ](https://stackoverflow.com/questions/63959229/ng2-chart-not-working-with-newly-created-angular-10-project)

**Comment by paviad** [comment]
I just followed all of your prescribed steps, and it worked for me without issue...

**Comment by KhaledMansour92** [comment]
i just trid it and it did the same 
<img width="1318" alt="Screen Shot 2020-09-19 at 09 36 08" src="https://user-images.githubusercontent.com/44553734/93660821-93fcaf00-fa5b-11ea-8bb1-15df00596a39.png">

also when I checked node
<img width="364" alt="Screen Shot 2020-09-19 at 09 38 14" src="https://user-images.githubusercontent.com/44553734/93660859-da520e00-fa5b-11ea-9e7a-a533a4fccd3c.png">

also here's my package.json 

```
{
  "name": "test-chart2",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~10.1.0-next.7",
    "@angular/common": "~10.1.0-next.7",
    "@angular/compiler": "~10.1.0-next.7",
    "@angular/core": "~10.1.0-next.7",
    "@angular/forms": "~10.1.0-next.7",
    "@angular/platform-browser": "~10.1.0-next.7",
    "@angular/platform-browser-dynamic": "~10.1.0-next.7",
    "@angular/router": "~10.1.0-next.7",
    "chart.js": "^2.9.3",
    "ng2-charts": "^2.4.1",
    "rxjs": "~6.6.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1001.0-next.6",
    "@angular/cli": "~10.1.0-next.6",
    "@angular/compiler-cli": "~10.1.0-next.7",
    "@types/node": "^12.11.1",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.0.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~3.9.5"
  }
}

```

**Comment by paviad** [comment]
Something is off with your setup, why do you have `~10.1.0-next.7` versions in there?

Mine looks like this:

```json
{
  "name": "ch",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~10.1.2",
    "@angular/common": "~10.1.2",
    "@angular/compiler": "~10.1.2",
    "@angular/core": "~10.1.2",
    "@angular/forms": "~10.1.2",
    "@angular/platform-browser": "~10.1.2",
    "@angular/platform-browser-dynamic": "~10.1.2",
    "@angular/router": "~10.1.2",
    "chart.js": "^2.9.3",
    "ng2-charts": "^2.4.1",
    "rxjs": "~6.6.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1001.2",
    "@angular/cli": "~10.1.2",
    "@angular/compiler-cli": "~10.1.2",
    "@types/node": "^12.11.1",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.0.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~4.0.2"
  }
}
```

**Comment by KhaledMansour92** [comment]
I just tried copying and pasting that part of **package.json** 
deleted the node_modules 
ran `sudo npm install` 
nothing happened, the same problem keeps happening 

I uploaded the project [here](https://github.com/KhaledMansour92/testCharts

idk if this could help but here's some info about ng version 

<img width="579" alt="Screen Shot 2020-09-19 at 14 01 17" src="https://user-images.githubusercontent.com/44553734/93665632-a0473300-fa80-11ea-8564-4136bd6ae3d0.png">

**Comment by paviad** [comment]
This is mine:

![image](https://user-images.githubusercontent.com/1235688/93668820-d93ed200-fa97-11ea-994c-8d287bdb5083.png)

**Comment by paviad** [comment]
Can you try it in a docker container?

**Comment by KhaledMansour92** [comment]
I tried something similar 
I cloned the project from [GitHub](https://github.com/KhaledMansour92/testCharts) to [StackBlitz](https://stackblitz.com/edit/github-lcyggo) and this what happiness 

<img width="535" alt="Screen Shot 2020-09-19 at 20 17 37" src="https://user-images.githubusercontent.com/44553734/93676743-37c67900-fab5-11ea-87dc-6e1b52580d80.png">

also, I tried creating a new project on and add ng2-charts to the project in the same way as before with the same result

**Comment by paviad** [comment]
When creating directly on stackblitz... again, no problems - what could be the difference? Locale maybe?

![image](https://user-images.githubusercontent.com/1235688/93684762-1a46de80-fab8-11ea-873e-d8a53cea6fc5.png)

**Comment by paviad** [comment]
Found your problem by looking at your `app.module.ts`

This is wrong:
`import { ChartsModule } from 'ng2-charts/lib/charts.module';`

It should be this:
`import { ChartsModule } from 'ng2-charts';`

**Comment by KhaledMansour92** [comment]
thanks a lot, you are a life savior, and sorry for wasting your time on such a trifle error
