### ISSUE TITLE
ng2-chart doughnut breaks on mouse hover

### ISSUE THREAD

**Issue by nijakanthan** [valor-software/ng2-charts#1271]
<img width="467" alt="Screenshot 2020-09-30 at 00 30 50" src="https://user-images.githubusercontent.com/8392195/94603911-8bef0b80-02b4-11eb-8d7d-3c0f1fd0e67b.png">

Help me fix this issue

**Comment by santam85** [comment]
cannot reproduce on v2 nor v3
