### ISSUE TITLE
Lodash Tree Shaking not working

### ISSUE THREAD

**Issue by Jamforce** [valor-software/ng2-charts#1272]
```
"@angular/cli": "~8.3.8",
"ng2-charts": "^2.4.2",
```

As title suggest, lodash treeshaking is not working right, the difference is **huge** :

` import { cloneDeep } from 'lodash-es';`

![no_treeshaking](https://user-images.githubusercontent.com/9673970/94684736-c0041400-0328-11eb-905a-a16cba4844c2.PNG)

` import cloneDeep from 'lodash-es/cloneDeep ';`

![treeshaking](https://user-images.githubusercontent.com/9673970/94684752-c4c8c800-0328-11eb-9b03-0a2cb0035b0f.PNG)

**Comment by santam85** [comment]
Are you sure you tested this with treeshaking enabled? Even without the change you suggest I see a different result (on v2.3.4):
![Screenshot 2021-07-07 at 14 51 19](https://user-images.githubusercontent.com/2706307/124762294-09763500-df33-11eb-85b8-3eb800ee0df3.png)
