### ISSUE TITLE
Angular 8 + ng2-chart not working in IE

### ISSUE THREAD

**Issue by drchaks83** [valor-software/ng2-charts#1278]
Steps followed as same as https://www.npmjs.com/package/ng2-charts

But once added to app.module the application is not alunching.

**Comment by drchaks83** [comment]
![error](https://user-images.githubusercontent.com/5450339/97277697-d1283e00-185e-11eb-8212-84ccecdfc25f.PNG)
This is the error I get once added into app.module.ts

**Comment by valorkin** [comment]
Hello, this should help https://dev.to/coly010/angular-how-to-support-ie11-4924
