### ISSUE TITLE
Chart.js is giving me a console error in Angular 8 environment

### ISSUE THREAD

**Issue by assmabenmussa** [valor-software/ng2-charts#1279]
hi, I am trying to use this library for an Angular 8 project, the line chart to be precise. The lineChartOptions property returns the following console error:
`Type '{ responsive: true; }' is not assignable to type 'ChartOptions & { annotation: any; }'.
  Property 'annotation' is missing in type '{ responsive: true; }' but required in type '{ annotation: any; }'.ts(2322)`

in console:
`ERROR in src/app/library/js-chart/js-chart.component.ts(16,10): error TS2322: Type '{ responsive: true; }' is not assignable to type 'ChartOptions & { annotation: any; }'.
      Property 'annotation' is missing in type '{ responsive: true; }' but required in type '{ annotation: any; }'.`

and here are the versions of angular libraries that I'm working with:
![image](https://user-images.githubusercontent.com/40716424/97865072-4b027080-1d12-11eb-98b0-39a6a394ed8f.png)

I've done some googling on the issue and I realized that most developers faced a problem getting the library to work with Angular 8, so if there is a workaround to the issue, that would be very helpful 🙏

**Comment by DespotMagic** [comment]
It is not related to Angular. I'm sure this is just a problem with type definition.
I'm sure you have such a description somewhere `'ChartOptions & {annotation: any;}'`. perhaps from examples. 

Try to replace `"annotation: any"` with `"annotation ?: any"`. Or, if not using the annotation plugin, replace `"'ChartOptions & {annotation: any;}'"` with `"ChartOptions"`.

**Comment by wablerahul** [comment]
Thank you....
My problem is solved....
