### ISSUE TITLE
Build warning with Angular 10

### ISSUE THREAD

**Issue by ThomasDevens** [valor-software/ng2-charts#1282]
Getting this warning when building after upgrading to Angular 10:
```
WARNING in C:\Users\td941211\Documents\Git\repos\Dashboard\ID_Client\node_modules\ng2-charts\fesm2015\ng2-charts.js depends on 'chart.js'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
```

Using Angular 10.2.3 and ng2-charts 2.4.2

**Comment by MikeG96** [comment]
Hello, you must add this to `angular.json` file, after the scripts attribute

```
"allowedCommonJsDependencies": [
  "chart.js",
]
```

**Comment by ThomasDevens** [comment]
This is what I've been using to fix the issue on my end, but it seems like something that should be added to this package

**Comment by pete0959** [comment]
This is still an issue and I get this warning despite adding the recommended 'allowedCommonJsDependencies.
Using Angular 11.0.9 / ng2-charts 2.4.2 / chart.js 2.9.4

**Comment by samherrmann** [comment]
Silencing the warning in the console does not solve the problem. From what I can see in the [Chart.js docs](https://www.chartjs.org/docs/latest/getting-started/integration.html#bundlers-webpack-rollup-etc) is that v3 is now tree-shakable.   Looks like [ng2-charts merged support for chart.js v3 yesterday](https://github.com/valor-software/ng2-charts/pull/1276). So perhaps all that's missing now to fix the build warning is for ng2-charts to cut a release.

**Comment by santam85** [comment]
No warning should be present on ng2-charts v3.x
