### ISSUE TITLE
Group chart labels together? (Nested)

### ISSUE THREAD

**Issue by coolvijaymca** [valor-software/ng2-charts#1284]
**Reproduction of the problem**
I've got a chart to display data month wise, but I also show it to the category wise. Here is an image of what I'm trying to do:

![x](https://user-images.githubusercontent.com/27564614/101075887-9bb6f480-3570-11eb-96f0-de6dd4ff093b.png)

I'm not sure how to do this or if it's even possible. I'm currently using ng2-charts (which is based off of Chart.js).

**Comment by danmana** [comment]
Chart.js does not support this out of the box (so ng2-charts doesn't either), but it looks like there is a plugin that might help: https://github.com/datavisyn/chartjs-scale-hierarchical

See discussion and other options https://github.com/chartjs/Chart.js/issues/4946

**Comment by coolvijaymca** [comment]
Thank You let me have a look and will post here if that worked out form me

**Comment by santam85** [comment]
Please open this ticket against Chart.js
