### ISSUE TITLE
Build errors out on Angular 11

### ISSUE THREAD

**Issue by fsalerno-sdc** [valor-software/ng2-charts#1286]
**Reproduction of the problem**
1. Installed the library in my Angular 11 project (`yarn add ng2-charts chart.js`)
2. Imported the library in app.module
3. Made a component to host an example chart (example from a tutorial on the internet which claimed compatibility with Angular 11, slightly modified, excuse the inconsistent quotes):
```
import { Component, OnInit } from '@angular/core';
import { ChartDataSets } from "chart.js";
import { Color, Label } from "ng2-charts";

@Component({
  selector: 'app-line-chart',
  template: `
    <div class="chart-wrapper">
      <canvas baseChart 
          [datasets]="lineChartData" 
          [labels]="lineChartLabels" 
          [options]="lineChartOptions"
          [colors]="lineChartColors" 
          [legend]="lineChartLegend" 
          [chartType]="lineChartType" 
          [plugins]="lineChartPlugins">
      </canvas>
    </div>
  `,
  styles: [],
})
export class LineChartComponent implements OnInit {
  public lineChartData: ChartDataSets[] = [
    { data: [85, 72, 78, 75, 77, 75], label: 'Crude oil prices' },
  ];

  public lineChartLabels: Label[] = ['January', 'February', 'March', 'April', 'May', 'June'];

  public lineChartOptions = {
    responsive: true,
  };

  public lineChartColors: Color[] = [
    {
      borderColor: "black",
      backgroundColor: 'rgba(255,255,0,0.28)',
    },
  ];

  public lineChartLegend = true;
  public lineChartPlugins = [];
  public lineChartType = "line" as const;

  constructor() {}

  ngOnInit(): void {}
}
```
4. `ng serve` errors out with the following message:
```
Error: node_modules/ng2-charts/lib/charts.module.d.ts:1:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.

    This likely means that the library (ng2-charts) which declares ChartsModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

    1 export declare class ChartsModule {
                           ~~~~~~~~~~~~
```

I suppose it's possible that I've done something wrong on my part (if so please help me make the library work), but given how new Angular 11 is, by bet is on some incompatibility (despite the recent merge I've seen to make the library compatible).

Notably a chart *is* drawn despite the errors but the error is still undesirable.

(Off-topic and this is probably due to chart.js itself rather than this library, but I only found a way to style the chart's height and width using css and it seems using `!important` is a necessity because of how seemingly arbitrary attributes are aggressively added to the canvas element. I found that rather annoying.)

**Comment by danmana** [comment]
How are you importing ChartsModule?
```import { ChartsModule } from 'ng2-charts';```

I've seen this kind of message before with another lib due to some problems caused by ngcc  (when my npm install froze) ...  
Try and see if clearing the npm cache, deleting node_modules and re-installing helps
```
npm clear cache -force
rm -rf node_modules
npm install
```

**Comment by fsalerno-sdc** [comment]
Without having done anything specific to the code, the error isn't there anymore today. It probably was an issue with some cache but it seems to have resolved itself. I'll reopen if it should resurface. Thank you for your time.
