### ISSUE TITLE
Line-Chart - Non-numeric yAxis support?

### ISSUE THREAD

**Issue by camriera** [valor-software/ng2-charts#1287]
Is it possible to customize the yAxis with non numeric string values? 

I see there is a labels input binding, but its documented as only being there for the xAxis... I was hoping there might be a workaround to support this sort of case that chart.js provides. 

https://www.chartjs.org/samples/latest/scales/non-numeric-y.html

**Comment by santam85** [comment]
This library supports all and only the features provided in Chart.js. If you cannot achieve what you need with pure Chart.js, then it won't be possible with ng2-charts either.
