### ISSUE TITLE
How to Customize font for a specific label in yAxes or xAxes

### ISSUE THREAD

**Issue by martinpagesaal** [valor-software/ng2-charts#1293]
I'm trying to get italic font on yAxes but only for ONE particular value (blank), in case the yAxes value is empty string I replace it with "blank" and in that particular case I would like to have an italic font.

this are my options. 

```
public barChartOptions: ChartOptions = {
    legend: { ... },
    tooltips:: { ... },
    layout: : { ... },
    plugins: : { ... },
    scales: {
      gridLines: : { ... },
      xAxes: [ { ... }  ],
      yAxes: [
        {
          gridLines: { display: false },
          display: true,
          barThickness: 25,
          ticks: {
            callback: (value: string) => {
              return value === '' ? 'blank' : value.length > 10 ? `${value.substr(0, 7)}...` : value;
            }
          }
        } as ChartYAxe
      ]
    }
  };
```

If I use `fontStyle: 'italic'` all my yAxis will change; is there a way?

**Comment by santam85** [comment]
You should try with scriptable options. See: https://www.chartjs.org/docs/latest/general/options.html#scriptable-options
