### ISSUE TITLE
Dump lodash-es, use lodash instead

### ISSUE THREAD

**Issue by jpike88** [valor-software/ng2-charts#1294]
```lodash-es``` is causing a weird error on recent typescript versions, related to a maximum cell stack exceeded... and it's not necessary anyway.

- Solution one: Migrate to standard 'lodash' library, removes weird resolution issues, keeps the lodash functionality 
- Solution two: Remove it altogether, replace with native or 3rd party implementations as only a couple of functions are being used and it's not performance sensitive

Either way would solve the issue. In meantime I'm going to fork and go with options 1 (move to ```lodash```). Thoughts?

**Comment by jpike88** [comment]
I'm just confirming that this following switch worked on my fork and solved my build issues:

```
    - "lodash-es": "^4.17.15",
    + "lodash": "^4.17.20",
```

**Comment by jpike88** [comment]
@santam85 are you able to review this pls?

**Comment by paviad** [comment]
As far as I understand `lodash-es` is better than lodash since it is tree-shakable

**Comment by santam85** [comment]
@jpike88 I can try removing it altogether, but would like to understand the errors you are running into better. Which TS version are you using? can you reproduce the issue for us in a demo project?

**Comment by jpike88** [comment]
The fuse-box bundler has issues with it for reasons I'm not 100% about yet.

By glancing at your code, you're just using the merge function from lodash. Is this correct? And don't you build an output that contains that function tree-shaken anyway?

Should lodash be in devDependencies?

**Comment by santam85** [comment]
I am using 2 lodash functions at runtime: https://github.com/valor-software/ng2-charts/blob/ec5f4a7c09a501eb01c11181fde84486a1109caa/projects/ng2-charts/src/lib/base-chart.directive.ts#L18
lodash is brought in anyway as a transitive dependency: https://github.com/valor-software/ng2-charts/blob/development/package-lock.json#L9638
The umd and esm2015 build outputs do not include the lodash-es functions.
There is no fundamental difference in using lodash-es instead of lodash except for deep imports: perhaps fuse-box doesn't support those?

**Comment by jpike88** [comment]
It may be because fuse-box doesn't know how to handle es module libraries, or it may be an issue specific to lodash-es. I can debug later this week but I got 120+ packages in my clients package.json and this lib is the only one breaking in this way :( @nchanged comments?

**Comment by changhuixu** [comment]
Got the following message, using v3.0.0-rc.3

```
Warning: Entry point 'ng2-charts' contains deep imports into './angular/node_modules/lodash-es/assign', './angular/node_modules/lodash-es/merge'. 
This is probably not a problem, but may cause the compilation of entry points to be out of order.
```

Why do you use lodash (assign, merge) instead of [Object.assign](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign)? 
https://stackoverflow.com/questions/37123425/object-assign-vs-lodash-assign

**Comment by santam85** [comment]
> Got the following message, using v3.0.0-rc.3
> 
> ```
> Warning: Entry point 'ng2-charts' contains deep imports into './angular/node_modules/lodash-es/assign', './angular/node_modules/lodash-es/merge'. 
> This is probably not a problem, but may cause the compilation of entry points to be out of order.
> ```
> 
> Why do you use lodash (assign, merge) instead of [Object.assign](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign)?
> https://stackoverflow.com/questions/37123425/object-assign-vs-lodash-assign

Exactly for the reason stated at the link you shared: polyfilling incompatible browsers (IE11). Given the market-share nowadays, I guess I could remove it...

**Comment by paviad** [comment]
Regarding the deep import, I think the point of es modules is that you can import from the top level module, and still benefit from tree shaking.

**Comment by BlindDespair** [comment]
Considering that IE is no longer supported by Microsoft, I would suggest to drop support for it too and get rid of lodash altogether.

**Comment by santam85** [comment]
@BlindDespair would you be open to create a PR implementing that?
