### ISSUE TITLE
Plugin annotation is not working 

### ISSUE THREAD

**Issue by pranavgupta93** [valor-software/ng2-charts#1295]
**Reproduction of the problem**

Hi 
I am trying to add "chartjs-plugin-annotation": "^0.5.7" but not working after I've updated my chartjs libraries and updated plugins array as per new syntax
"chart.js": "^2.9.4",
"ng2-charts": "^2.4.2"

It was working earlier with below versions
"ng2-charts": "^1.6.0",
"chart.js": "^2.7.0"

Attaching stackblitz link : https://stackblitz.com/edit/angular-5krys8?file=src%2Fapp%2Fapp.component.ts

Any help will be appreciated. TIA.

**Comment by sijmenvos** [comment]
Hi @pranavgupta93 

Make sure you add the plugin to the chart as well:
```javascript
public barChartPlugins = [pluginAnnotation];
```
And in the HTML:
```html
[plugins]="barChartPlugins"
```

And use the correct settings notation in the options object:
```javascript
{
    annotation: {
      annotations: [
        {
          type: "line",
          mode: "horizontal",
          scaleID: "y-axis-0",
          value: 60,
          borderColor: "red",
          borderWidth: 2
        }
      ]
    }
}
```

Working Stackblitz: https://stackblitz.com/edit/angular-juufpv

**Comment by JoaquimDmt** [comment]
tried everything but I still have the same issue than @pranavgupta93 and using the exacts same versions as him

**Comment by melaniesigrid** [comment]
I'm having the same issue. Hopefully it can be fixed!
