### ISSUE TITLE
Rendering issue with charts with several rows or columns

### ISSUE THREAD

**Issue by martinpagesaal** [valor-software/ng2-charts#1298]
This is the original issue where I posted things that still is happening to me.
https://github.com/valor-software/ng2-charts/issues/1249

This are 2 example that are not working on my notebook display but are working in my secondary one horizontal one vertical.

https://stackblitz.com/edit/angular-wrvgme
https://stackblitz.com/edit/ng2-charts-bar-template-m67v1t

On my Macbook Pro 16'' (Scaled or not scaled display)

![image](https://user-images.githubusercontent.com/3630631/110881180-afd06780-82be-11eb-921c-c19ca78cee36.png)
![image](https://user-images.githubusercontent.com/3630631/110881195-b5c64880-82be-11eb-9757-f7e1ca56c963.png)

On my Dell UP2716D (no scaled)

 
![image](https://user-images.githubusercontent.com/3630631/110881286-ddb5ac00-82be-11eb-964b-2ce149d7c98f.png)
![image](https://user-images.githubusercontent.com/3630631/110881301-e4dcba00-82be-11eb-96f1-8d918ef4b164.png)

After some bar it breaks, not sure why.

**Comment by santam85** [comment]
You should raise this issue with the Chart.js team directly, `ng2-charts` does nothing to alter the rendering process of the underlying library.
