### ISSUE TITLE
Unable to create new Chart object

### ISSUE THREAD

**Issue by cfoxy17** [valor-software/ng2-charts#1302]
I am attempting to create a new chart in Angular 11.2.7 (latest version) with Chart.js version 3.0.2 (latest version) and ng2-charts 2.4.2 (latest version) but cannot create a new chart object. This was not a problem in 2.9.4, but I need 3.0.2 because it has the "borderRadius". Needed my bar charts to have rounded edges.

           this.canvas = document.getElementById(ChartId);
	    this.ctx = this.canvas.getContext('2d');
	    this.myChart = new Chart(this.ctx, {
		.......
fails on "Chart" above

ERROR MESSAGE:
"chart.js/types/index.esm" has no construct signatures.

![image](https://user-images.githubusercontent.com/50955085/113943113-fd61c680-97cf-11eb-8893-88e41af13ac7.png)

**Comment by GitHubish** [comment]
I have the same issue

**Comment by vibonacci** [comment]
The current master branch of ng-charts2 is not compatible with the latest Chartjs major version 3. It only works with Chartjs 2.x.

There is a dev-3 branch ready though, awaiting an update from the maintainers on the status of it.

**Comment by Msimoneau** [comment]
@vibonacci Thank you  !

**Comment by santam85** [comment]
@cfoxy17 try `npm i ng2-charts@next`
