### ISSUE TITLE
Is plugin updated for Angular 9. 10 and 11 version?

### ISSUE THREAD

**Issue by ambujkhanna** [valor-software/ng2-charts#1304]
Hi,

Is this plugin updated to Angular latest versions? If yes then Is there any document available for same?

**Reproduction of the problem**

ng2-charts is a port & modification of Chart.js component for Angular 2. Sometimes the issue is related with Chart.js instead of ng2-charts.
To confirm, if the issue shows in a pure Chart.js project, it is a issue of Chart.js.
Pure Chart.js starting template: https://jsfiddle.net/Hongbo_Miao/mvct2uwo/3/

If the issue does not show in a pure Chart.js project, and shows in a ng2-charts project, please try to provide a minimal demo of the problem.
ng2-charts starting template: http://plnkr.co/edit/Ka4NXG3pZ1mXnaN95HX5?p=preview

**Comment by wocampodev** [comment]
Install chart.js in version two with `npm i --save chart.js@2.x.x`

**Comment by Sarah-JJ** [comment]
> 
> 
> Install chart.js in version two with `npm i --save chart.js@2.x.x`

This doesn't solve the issue

**Comment by santam85** [comment]
ng2-charts is compatible with Angular 7+
