### ISSUE TITLE
Gradient for each bar in bar-charts

### ISSUE THREAD

**Issue by fitimsijarinaa** [valor-software/ng2-charts#1305]
**Reproduction of the problem**
I want to add a gradient for each bar in a bar-charts. So far I found just https://codepen.io/MillerTime/pen/wGRYxW as a solution. In the solution the problem is, that the gradient is through the whole chart and the bar YELLOW is being displayed just with one color. 

I want that each bar has an own gradient. Is this possible?

![image](https://user-images.githubusercontent.com/34582738/115022576-da18d480-9ebd-11eb-9752-895f1b23515d.png)

**Comment by santam85** [comment]
This plugin is just a wrapper around Chart.js. Check their documentation on how to achieve this.
