### ISSUE TITLE
ng2-charts hovering over one Chart, should show horizontal and vertical line across all charts

### ISSUE THREAD

**Issue by MohitGogia** [valor-software/ng2-charts#1308]
Hi 

I need to show horizontal and vertical line on all the charts if I am hovering on one chart of the page. 
https://jsfiddle.net/vikas12118/k4oveLsb/
In above example it is showing only vertical line on hovering on first chart not on second chart. I have around 8-9 charts on the page and I am using ng2-charts.

Please help

**Comment by MohitGogia** [comment]
![exampleCloudWatch](https://user-images.githubusercontent.com/61184222/115826597-ca9f0b80-a428-11eb-924f-3446d05a68be.JPG)

**Comment by weirdyang** [comment]
The issue is with your code;
https://jsfiddle.net/synd6e1t/2/
