### ISSUE TITLE
AngularWebpackPlugin missing error 

### ISSUE THREAD

**Issue by Asscobara** [valor-software/ng2-charts#1310]
Using Angular 11, cause this error when trying to compile:

Error: [file name].ts
Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):
Error: The Angular Webpack loader requires the AngularWebpackPlugin.
    at Object.angularWebpackLoader 

Webpack 4.22

**Comment by santam85** [comment]
Lib builds successfully with Angular 11 and 12 now
