### ISSUE TITLE
Chart isn't updating with Response data (Chart.js: 3.2.1, ng2-charts: 3.0.0-beta.9)

### ISSUE THREAD

**Issue by nerkess** [valor-software/ng2-charts#1313]
I am using **Chart.js** of version **3.2.1** and **ng2-charts** of version **3.0.0-beta.9**. I was upgrading a project with this versions. I started with mock data and everything was ok: the charts were showing up as expected. 

Until I started testing with the real data, I get from the backend. The axes, labels, legends are not updating and charts are not showing up.

I reproduced the problem here:
https://stackblitz.com/edit/chart-js-321-ng2-charts-300-beta9-rest?file=src%2Fapp%2Fapp.component.ts

**Comment by santam85** [comment]
@nerkess would you be able to try this again with 3.0.0-rc.1?

**Comment by nerkess** [comment]
@santam85 Thank you for the reply! 
I installed 3.0.0-rc.1 in my Stackblitz project, but without success: 
https://stackblitz.com/edit/chart-js-321-ng2-charts-300-beta9-rest?file=package.json

**Comment by santam85** [comment]
You can temporarily work around the issue by calling `.render()` instead of `.refresh()`. I will have a look in the meantime.

**Comment by nerkess** [comment]
I was using chart.**update**()
With chart.**render**() the chart updates with versions 3.0.0-beta.9 and 3.0.0-rc.1

**Comment by santam85** [comment]
@nerkess released 3.0.0-rc.2 with a small fix for this. Tested it in your stackblitz and seems to work with .update() now (or even without it altogether, depending on the parameters used). You should get better performance with that.

**Comment by nerkess** [comment]
@santam85 yes, it's working without update too, that's pretty cool 👍  thank you for your contribution!
