### ISSUE TITLE
Request : Can there be a property added for 'font-color' similar to 'backgroundColor' in color.d.ts

### ISSUE THREAD

**Issue by anuragyg** [valor-software/ng2-charts#1314]
Feature request

 Can there be a property added for 'font-color' similar to 'backgroundColor' in color.d.ts ?
 
 So that it is possible to set font colors based on a specific condition, similar to how we set it for backgroundColor.
 Been struggling to implement this. 
 
![image](https://user-images.githubusercontent.com/33143502/118517251-ae0aa080-b754-11eb-815f-1f53f0563793.png)

**Comment by santam85** [comment]
v3.0.0 for this library inherits all the typing from Chart.js (https://www.chartjs.org/)
Moving forward that's the typings we are going to use for colors and configuration in general.
