### ISSUE TITLE
[options] on line ng2-chart

### ISSUE THREAD

**Issue by ppenan** [valor-software/ng2-charts#1318]
Hi, I am trying to use a line chart, and I need to use datalabes on any point on the line but I can't figure out how to use it. I am using "chart.js": "^2.9.4" and "ng2-charts": "^2.4.0", with this Options:

public lineChartOptions: ChartOptions & { annotation?: any } = {
    responsive: true,
    plugins: {
      datalabels: {
        display: true,
        formatter: Math.round,
        padding: 6
      }
    }
  };

but it doesn't work, I tried everything, Has anyone had the same problem? I am using Angular 12.

**Comment by santam85** [comment]
Are you passing the DataLabels plugin to the directive 'plugins' property? See https://valor-software.com/ng2-charts/#/BarChart
