### ISSUE TITLE
When do we support the Angular 12 project and chart.js 3.3.x ?

### ISSUE THREAD

**Issue by IngoManthey** [valor-software/ng2-charts#1319]

**Comment by Vitaly1025** [comment]
Same question. May be needs some help

**Comment by kaulex99** [comment]
https://github.com/valor-software/ng2-charts/releases/tag/v3.0.0-rc.2

Looks like it is done already

**Comment by TeamGenji** [comment]
./node_modules/ng2-charts/__ivy_ngcc__/fesm2015/ng2-charts.js:317:8-30 - Error: export 'pluginService' (imported as 'pluginService') was not found in 'chart.js' (possible exports: Animation, Animations, ArcElement, BarController, BarElement, BasePlatform, BasicPlatform, BubbleController, CategoryScale, Chart, DatasetController, Decimation, DomPlatform, DoughnutController, Element, Filler, Interaction, Legend, LineController, LineElement, LinearScale, LogarithmicScale, PieController, PointElement, PolarAreaController, RadarController, RadialLinearScale, Scale, ScatterController, Ticks, TimeScale, TimeSeriesScale, Title, Tooltip, _adapters, animator, controllers, defaults, elements, layouts, plugins, registerables, registry, scales)

./node_modules/ng2-charts/__ivy_ngcc__/fesm2015/ng2-charts.js:324:8-32 - Error: export 'pluginService' (imported as 'pluginService') was not found in 'chart.js' (possible exports: Animation, Animations, ArcElement, BarController, BarElement, BasePlatform, BasicPlatform, BubbleController, CategoryScale, Chart, DatasetController, Decimation, DomPlatform, DoughnutController, Element, Filler, Interaction, Legend, LineController, LineElement, LinearScale, LogarithmicScale, PieController, PointElement, PolarAreaController, RadarController, RadialLinearScale, Scale, ScatterController, Ticks, TimeScale, TimeSeriesScale, Title, Tooltip, _adapters, animator, controllers, defaults, elements, layouts, plugins, registerables, registry, scales)

Error: node_modules/ng2-charts/lib/base-chart.directive.d.ts:4:30 - error TS2724: '"chart.js"' has no exported member named 'ChartDataSets'. Did you mean 'ChartDataset'?

4 import { ChartConfiguration, ChartDataSets, ChartOptions, ChartPoint, ChartType, PluginServiceGlobalRegistration, PluginServiceRegistrationOptions } from 'chart.js';
                               ~~~~~~~~~~~~~


Error: node_modules/ng2-charts/lib/base-chart.directive.d.ts:4:59 - error TS2305: Module '"chart.js"' has no exported member 'ChartPoint'.

4 import { ChartConfiguration, ChartDataSets, ChartOptions, ChartPoint, ChartType, PluginServiceGlobalRegistration, PluginServiceRegistrationOptions } from 'chart.js';

I have multiple errors when adding it to Angular 12.

**Comment by swidziniak** [comment]
I'm getting the same errors as @TeamGenji in v3.0.0-rc.3.

**Comment by santam85** [comment]
Types have changed in v3, you'll need to update your code to match. I am working on updating documentation, but in the meantime you can refer to https://www.chartjs.org/docs/master/api/

**Comment by bkr32** [comment]
@swidziniak were you able to solve the `has no exported member 'Label'.` error?

**Comment by Siedlerchr** [comment]
I'm also currently struggling with the no exported member Label. 
I also tried to use the example with the charts plugin here https://github.com/valor-software/ng2-charts/blob/development/src/app/bar-chart/bar-chart.component.ts but that didn't really work either

**Comment by bkr32** [comment]
thanks for the tip @Siedlerchr

**Comment by santam85** [comment]
You should use Chart.js types starting from v3.0; label type is generally `TLabel[]`: https://github.com/chartjs/Chart.js/blob/master/types/index.esm.d.ts#L3409

**Comment by ryan0122** [comment]
I'm having trouble with gettin the datalabels to display.

Current setup: 

Angular CLI: 12.1.1
"chart.js": "^3.5.1",
"chartjs-plugin-datalabels": "^2.0.0",
"ng2-charts": "^3.0.0-rc.2"

The charts are working as expected except datalabels plugin. They do not render and none of my configuration options seem to have an effect.

Anyone have this issue?

**Comment by Sampath-Lokuge** [comment]
Still, doc types are not working? https://valor-software.com/ng2-charts/#/BarChart

**Comment by santam85** [comment]
The RC works perfectly with Chart.js v3, as demonstrated in the https://valor-software.com/ng2-charts/next/ docs (there's a few changes needed for v2 examples) Once again: you'll have to migrate types in your projects to Chart.js v3 official types.

**Comment by Siedlerchr** [comment]
Yep, can only agree. Been using chart.js v3 and ng-charts rc for a while now. Works fine.

**Comment by iamnaveenoff** [comment]
error TS2305: Module '"ng2-charts"' has no exported member 'MultiDataSet'.

3 import {Color, Label, MultiDataSet} from 'ng2-charts';

 Module '"ng2-charts"' has no exported member 'Label'.

3 import {Color, Label, MultiDataSet} from 'ng2-charts';
                 
  TS2305: Module '"ng2-charts"' has no exported member 'Color'.
3 import {Color, Label, MultiDataSet} from 'ng2-charts';
          

 Type '{ ticks: { beginAtZero: true; callback: (val: any) => any; }; }[]' is not assignable to type '_DeepPartialObject<{ type: "linear"; } & CartesianScaleOptions & { beginAtZero: boolean; suggestedMin?: number | undefined; suggestedMax?: number | undefined; ticks: { format: NumberFormatOptions; maxTicksLimit: number; precision: number; stepSize: number; count: number; }; }> | ... 5 more ... | undefined'.
  Type '{ ticks: { beginAtZero: true; callback: (val: any) => any; }; }[]' is not assignable to type '_DeepPartialObject<{ type: "radialLinear"; } & CoreScaleOptions & { animate: boolean; angleLines: { display: boolean; color: Scriptable<Color, ScriptableScaleContext>; lineWidth: Scriptable<...>; borderDash: Scriptable<...>; borderDashOffset: Scriptable<...>; }; ... 7 more ...; ticks: TickOptions & { ...; }; }>'.
    Types of property 'reverse' are incompatible.
      Type '() => { ticks: { beginAtZero: true; callback: (val: any) => any; }; }[]' is not assignable to type 'boolean | undefined'.

98             yAxes: [



after angular 16 update am facing this issue 

am using 
 "ng2-charts": "5.0.3",
  "chart.js": "3.0.0",
  
  is there any implementation doc

**Comment by santam85** [comment]
Follow the type migration guide on Chart.js: https://www.chartjs.org/docs/latest/migration/v3-migration.html
