### ISSUE TITLE
Stale data and labels due to merging

### ISSUE THREAD

**Issue by Ondrashx** [valor-software/ng2-charts#1320]
**Reproduction of the problem**
First of all thanks for making your work public.

There is one problem I run into
The merging of the config on ngChanges is not ok. New data and labels are merged. When input of baseChart directive of data and labels changes only those new data and labels should be used. Instead they are merged together. The merging happens here:

![image](https://user-images.githubusercontent.com/1877530/121731308-0ed98e80-caf1-11eb-85b3-0917da3a44f2.png)

What I have done in my client code to overcome this issue, is that I clear the data and labels before assigning to inputs of baseChartDirective new data, but it is just hack. 

![image](https://user-images.githubusercontent.com/1877530/121731549-6677fa00-caf1-11eb-8433-5bf8dd488b8e.png)

I think the merging should not be employed at all, but maybe there is some reason I do not see.

Anyway, just wanted to let you know.

**Comment by santam85** [comment]
@Ondrashx the reason it is done that way is to support Chart.js animations, which require the JS object ref to stay the same. The solution is definitely not perfect yet, I'll add some tests to check animations still work when not merging labels and datasets.

**Comment by Gimly** [comment]
@santam85 We're getting a very weird behavior where we have a time serie which data is bound to an Observable collection.

If we change the values of the the existing points everything seems to work correctly, but as soon as we reduce or add more points the graph behaves really weirdly, keeping the previous data points and messing up the time scale.

Is this related to this issue?

**Comment by Ondrashx** [comment]
@Gimly Yep, that seems exactly like the issue caused by merging. The fix is simple though ... you can tap into the stream of data and reset the datasets and labels, like I did in the client code.

**Comment by santam85** [comment]
@Ondrashx could you try the latest RC? I believe I got this fixed...
