### ISSUE TITLE
Angular 12, some changes in properties

### ISSUE THREAD

**Issue by Whisper40** [valor-software/ng2-charts#1325]
I was using ng2-charts with Angular 9,10,11.
But actually i'm migrating to Angular 12, which is causing some trouble to your tool.

I generate my chart like this : 

```
<div class="ml-auto" style="height: 84px; width: 100px">
            <canvas
              baseChart
              [datasets]="barChartData"
              [labels]="barChartLabels"
              [options]="barChartOptions"
              [colors]="barChartColors"
              [legend]="barChartLegend"
              [chartType]="barChartType">
            </canvas>
```

```
public barChartColors = [
        {
            backgroundColor: 'rgba(255, 255, 255, 0.5)',
            hoverBackgroundColor: 'rgba(255, 255, 255, 0.5)',
            hoverBorderWidth: 2,
            hoverBorderColor: 'rgba(255, 255, 255, 0.5)'
        }
    ];
    public barChartLegend = false;
    public barChartType = 'bar';
```

chartType seems to have migrated to just "type".
But i don't found the word that replace "colors"..

-> Can't bind to 'colors' since it isn't a known property of 'canvas'.

Versions : 
```
"ng2-charts": "^3.0.0-rc.4",
"chart.js": "^3.4.1"
```

**Comment by santam85** [comment]
Yes, upgrading the library to Chart.js v3, we made breaking changes to the APIs so that it matches more closely the one from the upstream lib. I am still updating docs, but you can find more information in Chart.js v3 docs: https://www.chartjs.org/docs/latest/general/options.html
You'll have to use Dataset and Chart level options if you want to override chart colors

**Comment by micobarac** [comment]
So, how do I bind colors array now, since it isn't available as a chart property any more? The solution is unclear.

**Comment by santam85** [comment]
By setting, for instance, the `backgroundColor` of each dataset, as per the Chart.js documentation suggests. This allows more flexibility. There is no `colors` input anymore.
