### ISSUE TITLE
Do you support chart.js 3+ version?

### ISSUE THREAD

**Issue by ranmax123** [valor-software/ng2-charts#1326]
I'm trying to use latest advancements in chart.js 3+ version, but how do I use it with ng-2?

**Comment by GitHubish** [comment]
I have the same question. If not, is there a technical reason? Thanks

**Comment by GitHubish** [comment]
@ranmax123 I just saw that there was a release for version 3 which is currently in the Release Candidate stage. 

[https://github.com/valor-software/ng2-charts/releases/tag/v3.0.0-rc.4](https://github.com/valor-software/ng2-charts/releases/tag/v3.0.0-rc.4)

**Comment by santam85** [comment]
Use v3.0.0+ of ng2-charts, currently in RC

**Comment by ranmax123** [comment]
What is the release date?

**Comment by santam85** [comment]
The RC was released 8 days ago: https://www.npmjs.com/package/ng2-charts/v/3.0.0-rc.4, you can use it already and report any problems you might find.
There is no set release date, documentation needs to be updated, help is welcome.
