### ISSUE TITLE
When can we expect stable release of version 3.0.0

### ISSUE THREAD

**Issue by jarulraj666** [valor-software/ng2-charts#1328]
When can we expect stable release of version 3.0.0. Currently I can see 3.0.0-rc.4. When can we expect the stable release of this version

**Comment by piotrroda** [comment]
I'm also wondering about that. @santam85 Could you write something about stable release date?

**Comment by santam85** [comment]
I released rc.5 today, which addresses a problem with initialization of defaults when not providing custom configuration.
The library is stable enough, at the moment I am mostly working on documentation. I'd really love to get https://github.com/chartjs/chartjs-chart-financial/pull/95 merged before releasing the final version, but it seems the maintainer of that library is unresponsive at the moment.

**Comment by dostarora97** [comment]
I see that https://github.com/chartjs/chartjs-chart-financial/pull/95 is finally merged.
Thanks @santam85 for following on it and getting it merged.
Hope 3.0.0. would be released soon! 🤞

**Comment by santam85** [comment]
It was merged, but the package has not been released yet 😞

**Comment by jcn-ithaca** [comment]
Any rough ETA? thanks!

**Comment by Sampath-Lokuge** [comment]
Yes, V3 is very important with proper Types on the doc too. Now we have to face these kinds of issues. Since I work on Mobile apps this is very bad. i.e. larger bundle size and poor performances.

```
ng2-charts.js depends on 'chart.js'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
```

**Comment by santam85** [comment]
> Yes, V3 is very important with proper Types on the doc too. Now we have to face these kinds of issues. Since I work on Mobile apps this is very bad. i.e. larger bundle size and poor performances.
> 
> ```
> ng2-charts.js depends on 'chart.js'. CommonJS or AMD dependencies can cause optimization bailouts.
> For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
> ```

Have you tried the RC available under the `next` label?

**Comment by Sampath-Lokuge** [comment]
Hi @santam85 

Yes, I had to face an ample amount of Typing issues on it hence I have followed your official doc. So After that, I have moved in to `  "ng2-charts": "^2.2.3",`.  So update on your doc is supper important for V3. Thanks!

**Comment by santam85** [comment]
> Hi @santam85
> 
> Yes, I had to face an ample amount of Typing issues on it hence I have followed your official doc. So After that, I have moved in to ` "ng2-charts": "^2.2.3",`. So update on your doc is supper important for V3. Thanks!

Can you expand a bit more on which typing issues you are having? There are no types on ng-charts v3 except from the Chart.js ones. Major type changes happened between Chart.js v2 and Chart.js v3, see https://www.chartjs.org/docs/latest/getting-started/v3-migration.html

**Comment by dylanvdmerwe** [comment]
How are we looking with an update to latest chartjs version? 😄 
We are quite keen to update to latest chartjs but are blocked due to this dependency.

**Comment by tru-koto** [comment]
> > Any rough ETA? thanks!
> 
> I am focusing on getting [chartjs/chartjs-chart-financial#95](https://github.com/chartjs/chartjs-chart-financial/pull/95) pipelines in order and release it on npmjs.org While that's going on I would appreciate some help with the docs: I have new examples prepared, but we need to sort out pipelines to publish documentation pages.

@santam85 - What sort of help do you need with the documentation?

**Comment by santam85** [comment]
> > > Any rough ETA? thanks!
> > 
> > 
> > I am focusing on getting [chartjs/chartjs-chart-financial#95](https://github.com/chartjs/chartjs-chart-financial/pull/95) pipelines in order and release it on npmjs.org While that's going on I would appreciate some help with the docs: I have new examples prepared, but we need to sort out pipelines to publish documentation pages.
> 
> @santam85 - What sort of help do you need with the documentation?

There were some changes in the APIs of the libraries, and we are now using types from Chart.js directly. Examples, reference docs and links to Chart.js docs need updating.

**Comment by santam85** [comment]
Added an RC doc-site: https://valor-software.com/ng2-charts/next/

**Comment by santam85** [comment]
Released. Feedback on docs, samples and issues welcome.
