### ISSUE TITLE
NgChartsModule is already loaded. Use .forRoot() in the AppModule only

### ISSUE THREAD

**Issue by jansgescheit** [valor-software/ng2-charts#1333]
Since rc6 i have some trouble with the module.

I have two chart components in my `shared` module.
The `shared.module.ts` on `rc4` looks like this:

``` 
@NgModule({
    imports: [CommonModule, FormsModule, RouterModule, ChartsModule, TranslateModule],
    declarations: [
        FooChartComponent,
        BarChartComponent,
    ],
    exports: [
        FooChartComponent,
        BarChartComponent,
    ],
    providers: [],
})
export class SharedModule {}
 ```

for `rc6` i have to rename the `ChartsModule` to `NgChartsModule` ✅ 

But on runtime i got the error `NgChartsModule is already loaded. Use .forRoot() in the AppModule only` 
if i add `NgChartsModule` or `NgChartsModule.forRoot()` in the `AppModule` i got the same error. 
Next try was to add the module only in the `AppModule` but at this point i got errors from the `canvas` element with unknown attributes.

**Comment by santam85** [comment]
@jansgescheit could you create a minimal reproduction repo? This is probably caused by an overzealous check I am doing during module instantiation.

**Comment by sydneyhenrard** [comment]
I managed to reproduce the issue when you have an app routing module with lazy loading. The `NgChartsModule` is loaded by the `SharedModule`. The `SharedModule` is imported in `AppModule` and `FeatureModule`.

If you go to https://angular-hb3vmk.stackblitz.io/bug you will see the issue.

Stackblitz: https://stackblitz.com/edit/angular-hb3vmk

**Comment by santam85** [comment]
@sydneyhenrard thanks for reproducing, I see what you are trying to do now.
Unfortunately, because of the way Chart.js handles plugins and defaults, a singleton provider for configuration and the chart library is needed. For this reason, the pattern of sharing the NgChart

**Comment by Gefyaqiilah** [comment]
> @sydneyhenrard thanks for reproducing, I see what you are trying to do now.
> Unfortunately, because of the way Chart.js handles plugins and defaults, a singleton root provider for configuration and the chart library is needed to share defaults. For this reason, the pattern of re-exporting the `NgChartModule` within a `SharedModule` cannot work, and it's prevented by the library (the providers would be instantiated multiple times).
> 
> See https://angular.io/guide/module-types#shared-ngmodules for reference:
> 
> > Shared NgModules should not include providers, nor should any of its imported or re-exported NgModules include providers.
> 
> If you don't need the chart library in the whole app, a way to achieve lazy loading of the library is simply adding the `NgChartsModule` to every lazy-loaded feature module that needs it. If you need to override defaults, you can add a provider yourself to the lazy loaded module:
> 
> ```
> providers: [
>         { provide: NgChartsConfiguration, useValue: config }
>       ]
> ```
> 
> That way every feature module gets it's own defaults

huff this problem happen to me, maybe can i get some clear direction to solve this problem.

**Comment by santam85** [comment]
I edited the stackblitz above and fixed the double instance of the module, when using a shared module:
https://stackblitz.com/edit/angular-bsnzbd
Make sure your shared module is imported only on feature modules, and not in the app module too!

**Comment by santam85** [comment]
> > I edited the stackblitz above and fixed the double instance of the module, when using a shared module:
> > https://stackblitz.com/edit/angular-bsnzbd
> > Make sure your shared module is imported only on feature modules, and not in the app module too!
> 
> And if I import the shared module into another feature module? https://stackblitz.com/edit/angular-9kclra?file=src/app/app.component.ts

If you fix the unrelated error (declarations: [Feature2Component], in your Feature2Module is missing), then it just works.

**Comment by saulofr** [comment]
> I edited the stackblitz above and fixed the double instance of the module, when using a shared module:
> https://stackblitz.com/edit/angular-bsnzbd
> Make sure your shared module is imported only on feature modules, and not in the app module too!

Not working in sub-sub-modules https://stackblitz.com/edit/angular-9kclra?file=src/feature2/f23/f23.module.ts

**Comment by santam85** [comment]
There wouldn't be any advantage in splitting it out to a separate module then, since it could not be lazy-loaded but always included as part of the main bundle

**Comment by mythjuha** [comment]
Well in my case that module isn't lazy loaded indeed. It's simply put in a seperate module as a way to structure the program. For now i've worked my way around the error by actually including the component in the module where it's used (which is lazy loaded). But this might break reusability later on in the project. But I guess i'll come back here then if needed :).
