### ISSUE TITLE
How to left-align the entire chart in the canvas?

### ISSUE THREAD

**Issue by jake-mittleman** [valor-software/ng2-charts#1334]
![image](https://user-images.githubusercontent.com/76964262/128754481-db1f1283-39a9-484a-a9b7-e1b4d28d9c9f.png)

I have an issue where when the legend labels are too long the graph shrinks.

Here's a js fiddle with this issue https://jsfiddle.net/wt2az794/

Alternatively if I could left-align the graph in the canvas that'd be good. Basically I need these doughnut charts to be the same size with varying lengths of the legend labels.

Here's some code:
```
<div class="doughnut-chart">
  <canvas width="100%" baseChart
          [data]="doughnutChartData"
          [chartType]="doughnutChartType"
          [labels]="chartLabels"
          [colors]="barChartColors"
          [options]="chartOptions">
  </canvas>
</div>
```

```
.doughnut-chart {
  display: flex;
  justify-content: flex-start;
  width: 600px;
  height: 600px;
}
```

```
<doughnut-chart
      [chartLabels]="[
        'Female',
        'Male',
        'Non-Binary',
        'Not Disclosed']">
    </doughnut-chart>

  <!--ethnicity-->
    <doughnut-chart
      [chartLabels]="[
        'AMERICAN INDIAN OR ALASKAN NATIVE',
        'ASIAN (NOT HISPANIC OR LATINO)',
        'NATIVE HAWAIIAN OR OTHER PAC. ISLANDER',
        'HISPANIC OR LATINO',
        'WHITE (NOT HISPANIC OR LATINO)',
        'BLACK OR AFRICAN-AMERICAN',
        'TWO OR MORE RACES',
        'UNKNOWN',
        'NOT DISCLOSED']">
    </doughnut-chart>
```
    
```
.donut-box {
  display: flex;
  justify-content: space-between;
  flex-wrap: wrap;
  //width: 50%;
  //height: auto;
  margin: 0 500px 0 500px;
}
```

**Comment by santam85** [comment]
This is how the layout of the chart.js library works, it has nothing to do with this library.
Try playing with the `responsive` option and the position of the legend: 
https://www.chartjs.org/docs/latest/configuration/responsive.html#responsive-charts
https://www.chartjs.org/docs/latest/configuration/legend.html
