### ISSUE TITLE
Ticks with images

### ISSUE THREAD

**Issue by fitimsijarinaa** [valor-software/ng2-charts#1335]
**Reproduction of the problem**
Hi,

is it possible to have ticks with an image? 
![image](https://user-images.githubusercontent.com/34582738/129264947-6240f3f9-2994-43cf-8c30-029a948896b9.png)

In the ticks I may Include a dollar sign to the values:

```
         ticks: {
          callback: function (value, index, values) {

            return "$" + value;
          },
        },
```

Is it also possible to add the additional image to the tick?

**Comment by santam85** [comment]
No. Check https://www.chartjs.org/docs/latest/axes/#tick-configuration

**Comment by fitimsijarinaa** [comment]
@santam85 found a solution. Need to add a new plugin ChartConfiguration and in the function afterDraw. When I have more time I will make this case clear here somewhere so anybody will be able to implement this case.
