### ISSUE TITLE
Create proper documentation with updated examples

### ISSUE THREAD

**Issue by AdriannaAndrukowicz** [valor-software/ng2-charts#1341]
I really enjoy Charts, but there a lack of examples... It's hard to implement it in the Angular project. Already existing examples are outdated, new version of library is refusing to cooperate. Would be nice to have proper documentation with examples, everything at one place.

**Comment by Aml-Abbas** [comment]
The same for me, very hard to understand the documentation and to try change the style and element. No helpful examples out there.

**Comment by santam85** [comment]
Added an RC doc-site: https://valor-software.com/ng2-charts/next/

**Comment by santam85** [comment]
Updated examples and linked them in Readmes and doc site.
