### ISSUE TITLE
Create percent stcked bar chart

### ISSUE THREAD

**Issue by chetanapadmane1** [valor-software/ng2-charts#1344]
Hi Team,

We are trying to create a percentage stacked chart using ng2-charts. Need your help/support here.

Can we get to know what type of parameters need to add while setting the chart options.
Does ng2-charts support Percentage Stacked bar chart?

Thanks,
Chetana Padmane

**Comment by santam85** [comment]
@chetanapadmane1 ng2-charts supports all the chart styles and configurations that Chart.js does. Check their documentation on how to achieve stacked bar charts: https://www.chartjs.org/docs/latest/samples/bar/stacked.html
