### ISSUE TITLE
Angular 13 Support

### ISSUE THREAD

**Issue by adnanebrahimi** [valor-software/ng2-charts#1346]
After updating our project to Angular 13 the ng2-charts have errors while ` ng serve`

`./node_modules/ng2-charts/fesm2015/ng2-charts.js:317:8-30 - Error: export 'pluginService' (imported as 'pluginService') was not found in 'chart.js' (possible exports: Animation, Animations, ArcElement, BarController, BarElement, BasePlatform, BasicPlatform, BubbleController, CategoryScale, Chart, DatasetController, Decimation, DomPlatform, DoughnutController, Element, Filler, Interaction, Legend, LineController, LineElement, LinearScale, LogarithmicScale, PieController, PointElement, PolarAreaController, RadarController, RadialLinearScale, Scale, ScatterController, SubTitle, Ticks, TimeScale, TimeSeriesScale, Title, Tooltip, _adapters, _detectPlatform, animator, controllers, defaults, elements, layouts, plugins, registerables, registry, scales)`

**Comment by JeremieLapert** [comment]
@adnanebrahimi : the work is in progress -> [PR](https://github.com/valor-software/ng2-charts/pull/1345#)

**Comment by soori-reddy** [comment]
any ETA

**Comment by santam85** [comment]
Released v3.0.0 today. Not sure your error is a result of upgrading to Angular 13, but probably caused by updating Chart.js to v3. For Chart.js v3 compatibility, you'll have to upgrade to ng2-charts v3 too.
