### ISSUE TITLE
Having issue with generateLegend in BaseChartDirective

### ISSUE THREAD

**Issue by paragkulkarni** [valor-software/ng2-charts#1362]
We are using following module for the project - 
Project contains - 
             1. Angular13
             2. ng2-charts -  3.0.1
             3. chart.js - ^3.6.2
We are migrating  ng2-charts@1.4 to ng2-charts@3.x. We are facing issue in generateLegend using this as follows- 

import { BaseChartDirective } from 'ng2-charts';

BaseChartDirective .chart.generateLegend();

It doesn't find generateLegend.

is there any alternative or solution for the generateLegend()???

can you please someone help me for this.

How should I do it with this?

Thank you respected experts.

**Comment by santam85** [comment]
`generateLegend` has been removed in the parent library: see https://www.chartjs.org/docs/latest/getting-started/v3-migration.html
