### ISSUE TITLE
An unhandled exception occurred: NOT SUPPORTED: keyword "id", use "$id" for schema ID

### ISSUE THREAD

**Issue by f0-x** [valor-software/ng2-charts#1368]
Can't generate any kind of charts and trying out commands like

`>ng generate ng2-charts-schematics:radar productModel-sales-radar`

throws:

`An unhandled exception occurred: NOT SUPPORTED: keyword "id", use "$id" for schema ID
See "C:\Users\Adam\AppData\Local\Temp\ng-nTc7Wm\angular-errors.log" for further details.`

The log file is as follows:

`[error] Error: NOT SUPPORTED: keyword "id", use "$id" for schema ID
    at Object.code (D:\Code\vehicle-store\node_modules\ajv\dist\vocabularies\core\id.js:6:15)
    at keywordCode (D:\Code\vehicle-store\node_modules\ajv\dist\compile\validate\index.js:454:13)
    at D:\Code\vehicle-store\node_modules\ajv\dist\compile\validate\index.js:222:17
    at CodeGen.code (D:\Code\vehicle-store\node_modules\ajv\dist\compile\codegen\index.js:439:13)
    at CodeGen.block (D:\Code\vehicle-store\node_modules\ajv\dist\compile\codegen\index.js:568:18)
    at iterateKeywords (D:\Code\vehicle-store\node_modules\ajv\dist\compile\validate\index.js:219:9)
    at groupKeywords (D:\Code\vehicle-store\node_modules\ajv\dist\compile\validate\index.js:208:13)
    at D:\Code\vehicle-store\node_modules\ajv\dist\compile\validate\index.js:192:13
    at CodeGen.code (D:\Code\vehicle-store\node_modules\ajv\dist\compile\codegen\index.js:439:13)
    at CodeGen.block (D:\Code\vehicle-store\node_modules\ajv\dist\compile\codegen\index.js:568:18)`

**Comment by santam85** [comment]
Our schema ids already contain `$id` instead of `id`. Can you double-check that your version of angular-cli and all angular-related dependencies are on the same major?

**Comment by emaas** [comment]
@f0-x  is using ng2-charts-schematics. The latest (non-beta) version of this is 0.1.7. A version of 3 years old.
This version does have the issue with the $id.
@f0-x you can work around this by changing the schema in your node_modules folder (it's just for generating so shouldn't be that big of a deal).
According to the docs, there is also a way to generate modules with ng2-charts itself.

I'm replying because I was running into the exact same issue. New project on angular 13.

**Comment by f0-x** [comment]
> @f0-x is using ng2-charts-schematics. The latest (non-beta) version of this is 0.1.7. A version of 3 years old. This version does have the issue with the $id. @f0-x you can work around this by changing the schema in your node_modules folder (it's just for generating so shouldn't be that big of a deal). According to the docs, there is also a way to generate modules with ng2-charts itself.
> 
> I'm replying because I was running into the exact same issue. New project on angular 13.

Thanks for the response, @emaas . But I didn't get how to change the `schema` in my node_modules folder. Could you elaborate please ? :)

**Comment by santam85** [comment]
Sorry I did not read your issue closely and assumed you were trying to use the new schematics. Your command should work if you change it slightly:
`ng generate ng2-charts:radar productModel-sales-radar`
But the issue triggered me to find a bug with chart generation other than line. Pushing 3.0.7 with a fix for this.

**Comment by f0-x** [comment]
> Sorry I did not read your issue closely and assumed you were trying to use the new schematics. Your command should work if you change it slightly: `ng generate ng2-charts:radar productModel-sales-radar` But the issue triggered me to find a bug with chart generation other than line. Pushing 3.0.7 with a fix for this.

Running `ng generate ng2-charts:radar productModel-sales-radar` gave me

`An unhandled exception occurred: Collection "ng2-charts" cannot be resolved.
See "C:\Users\Adam\AppData\Local\Temp\ng-OLu5op\angular-errors.log" for further details.`

I re-installed ng2-charts and ran your command again and got

`ENOENT: no such file or directory, open 'D:\Code\car-sales\node_modules\ng2-charts\schematics\ng-generate\radar\files\__path__\__name@dasherize@if-flat__\__name@dasherize__.component.html.template'`

**Comment by emaas** [comment]
I'm trying to create a pull request with a fix for this. Few minutes out I hope.

**Comment by santam85** [comment]
Fixed in v3.0.8

**Comment by hill636** [comment]
Hello, I'm getting the same error as @f0-x in their original post (quoted below).  My project is built on Angular v14.0.x, ng2-charts v3.1.2, chart.js v3.8.0, ng2charts-schematics v0.1.7.  Dropping "-schematics" from the command as suggested by @santam85 produces a different error, which I can provide upon request.  
 
Kind Regards

> Can't generate any kind of charts and trying out commands like
> 
> `>ng generate ng2-charts-schematics:radar productModel-sales-radar`
> 
> throws:
> 
> `An unhandled exception occurred: NOT SUPPORTED: keyword "id", use "$id" for schema ID See "C:\Users\Adam\AppData\Local\Temp\ng-nTc7Wm\angular-errors.log" for further details.`
> 
> The log file is as follows:
> 
> `[error] Error: NOT SUPPORTED: keyword "id", use "$id" for schema ID at Object.code (D:\Code\vehicle-store\node_modules\ajv\dist\vocabularies\core\id.js:6:15) at keywordCode (D:\Code\vehicle-store\node_modules\ajv\dist\compile\validate\index.js:454:13) at D:\Code\vehicle-store\node_modules\ajv\dist\compile\validate\index.js:222:17 at CodeGen.code (D:\Code\vehicle-store\node_modules\ajv\dist\compile\codegen\index.js:439:13) at CodeGen.block (D:\Code\vehicle-store\node_modules\ajv\dist\compile\codegen\index.js:568:18) at iterateKeywords (D:\Code\vehicle-store\node_modules\ajv\dist\compile\validate\index.js:219:9) at groupKeywords (D:\Code\vehicle-store\node_modules\ajv\dist\compile\validate\index.js:208:13) at D:\Code\vehicle-store\node_modules\ajv\dist\compile\validate\index.js:192:13 at CodeGen.code (D:\Code\vehicle-store\node_modules\ajv\dist\compile\codegen\index.js:439:13) at CodeGen.block (D:\Code\vehicle-store\node_modules\ajv\dist\compile\codegen\index.js:568:18)`
