### ISSUE TITLE
Tooltip doesn't work as expected on safari

### ISSUE THREAD

**Issue by pasanaa** [valor-software/ng2-charts#1369]
**Reproduction of the problem**

ng2-charts is a port & modification of Chart.js component for Angular 2. Sometimes the issue is related with Chart.js instead of ng2-charts.
To confirm, if the issue shows in a pure Chart.js project, it is a issue of Chart.js.
Pure Chart.js starting template: https://jsfiddle.net/Hongbo_Miao/mvct2uwo/3/

If the issue does not show in a pure Chart.js project, and shows in a ng2-charts project, please try to provide a minimal demo of the problem.

chart.js version
3.7.0

ng2-charts version
3.0.6

ng2-charts starting template: http://plnkr.co/edit/Ka4NXG3pZ1mXnaN95HX5?p=preview
![Screen Shot 2022-01-10 at 12 03 45 PM](https://user-images.githubusercontent.com/37524591/148727839-80d3739e-ae4b-4efb-b92d-9f4c84af1f54.png)

**Comment by santam85** [comment]
I cannot load your plnkr nor reproduce your problem. Does it happen if you visit https://valor-software.com/ng2-charts/#LineChart for instance? Tooltips work fine there for me. 
Which version of Safari are you using?

**Comment by pasanaa** [comment]
Can't reproduce this. it's happening only inside the project

**Comment by pasanaa** [comment]
Can't reproduce this. it's happening only inside the project
