### ISSUE TITLE
package install failed for Angular 13 using command ng add ng2-charts@next --force

### ISSUE THREAD

**Issue by yzhan407** [valor-software/ng2-charts#1370]
I am using Angular 13 and here is my package.json:
"dependencies": {
        "@angular/animations": "~13.1.0",
        "@angular/cdk": "^13.1.1",
        "@angular/common": "~13.1.0",
        "@angular/compiler": "~13.1.0",
        "@angular/core": "~13.1.0",
        "@angular/forms": "~13.1.0",
        "@angular/material": "^13.1.1",
        "@angular/platform-browser": "~13.1.0",
        "@angular/platform-browser-dynamic": "~13.1.0",
        "@angular/router": "~13.1.0",
        "chart.js": "^3.7.0",
        "rxjs": "~7.4.0",
        "tslib": "^2.3.0",
        "zone.js": "~0.11.4"
      },
      "devDependencies": {
        "@angular-devkit/build-angular": "~13.1.2",
        "@angular/cli": "~13.1.2",
        "@angular/compiler-cli": "~13.1.0",
        "@types/jasmine": "~3.10.0",
        "@types/node": "^12.11.1",
        "jasmine-core": "~3.10.0",
        "karma": "~6.3.0",
        "karma-chrome-launcher": "~3.1.0",
        "karma-coverage": "~2.1.0",
        "karma-jasmine": "~4.0.0",
        "karma-jasmine-html-reporter": "~1.7.0",
        "prettier": "2.5.1",
        "typescript": "~4.5.2"
      }
I am using command ng2-charts@next --force or ng add ng2-charts@next --legacy-peer-deps or ng add ng2-charts@next , none of these commands works, and I receive errors in console like these:
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: angular-weather2@0.0.0
npm ERR! Found: rxjs@7.4.0
npm ERR! node_modules/rxjs
npm ERR!   rxjs@"~7.4.0" from the root project
npm ERR!   peer rxjs@"^6.5.3 || ^7.4.0" from @angular/common@13.1.1
npm ERR!   node_modules/@angular/common
npm ERR!     @angular/common@"~13.1.0" from the root project
npm ERR!     peer @angular/common@">=11.0.0" from ng2-charts@3.0.0-rc.7
npm ERR!     node_modules/ng2-charts
npm ERR!       ng2-charts@"3.0.0-rc.7" from the root project
npm ERR!   1 more (@angular/core)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer rxjs@"^6.3.3" from ng2-charts@3.0.0-rc.7
npm ERR! node_modules/ng2-charts
npm ERR!   ng2-charts@"3.0.0-rc.7" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!

**Comment by inpercima** [comment]
The version looks wrong. The **next** version in your case is **3.0.0-rc.7** but the current one is **3.0.6**, try this.

It seems there is an issue in the order of the next version.

**Comment by santam85** [comment]
Indeed, this has been fixed for the latest stable version, where peer dependencies are compatible with Angular 11-13
