### ISSUE TITLE
Can't bind to 'chartType' since it isn't a known property of 'canvas'

### ISSUE THREAD

**Issue by joootdooot** [valor-software/ng2-charts#1372]
Using the following minimal code in component html

```
<div>
  <div style="display: block">
    <canvas baseChart
              [datasets]="lineChartData"
              [labels]="lineChartLabels"
              [options]="lineChartOptions"
              [legend]="lineChartLegend"
              [chartType]="lineChartType"></canvas>
  </div>
</div>
```

I am following the guide from https://medium.com/codingthesmartway-com-blog/angular-chart-js-with-ng2-charts-e21c8262777f

**Comment by yzhan407** [comment]
It is named as [type]
I found this document useful and maybe you need to follow the data structure defined here: [chartjs document](https://www.chartjs.org/docs/latest/general/options.html)

**Comment by joootdooot** [comment]
the working example on https://stackblitz.com/edit/ng2-charts-line-template?file=src%2Fapp%2Fapp.component.html suggests otherwise, may I know why?

**Comment by joootdooot** [comment]
they completely changed the api in v3.0.0?

**Comment by santam85** [comment]
@joootdooot the template is outdated, I am trying to get access from the old maintainer to update all of them. The change in API was done with the release to the new v3 major, when we added compatibility with Chart.js v3

**Comment by patricknikolaus** [comment]
I'm also running into this issue. Following all the steps as required and changing "chartType" to "type" still results in a similar error.
