### ISSUE TITLE
ERROR Error: "logarithmic" is not a registered scale.

### ISSUE THREAD

**Issue by SAVpro** [valor-software/ng2-charts#1377]
When set for SCALE type = logarithmic I get an Error: "logarithmic" is not a registered scale.

`public chartOptions: ChartOptions<'line'> = {
    scales: {
      x: { },
      y: {
        type: 'logarithmic'
      }
    }
  };`

`  <canvas    baseChart    width="400"    height="400"    [data]="chartData"    [options]="chartOptions"    [type]="'line'"  ></canvas>`

`chartData = {
      labels: ["Alpha", "Beta", "Cat", "Dog", "Elephant", "Giraffe", "Hippo"],
      datasets: [
        {
          label: "Male",
          data: [65, 59, 1, 5, 56, 55, 40],
          tension: 0.1,
          borderWidth: 1,
          borderColor: "rgba(104, 197, 100, 1)",
          backgroundColor: "rgba(104, 197, 100, 1)",
          fill: false
        },
        {
          label: "Female",
          data: [33, 87, 1, 5, 71, 90, 32],
          tension: 0.1,
          borderWidth: 1,
          borderColor: "rgba(239, 138, 12, 1)",
          backgroundColor: "rgba(239, 138, 12, 1)",
          fill: false
        }
      ]
    };`
demo 
https://codesandbox.io/s/ng2-charts-tooltip-color-issue2-forked-1zuui?file=/src/app/app.component.ts

**Comment by kemo89** [comment]
I found this on stackoverflow: https://stackoverflow.com/questions/67727603/error-category-is-not-a-registered-scale 

So you have to register the LogarithmicScale. For me the code looks like:
`
import { Chart, LogarithmicScale } from 'chart.js';

// ...

ngOnInit(): void {
  Chart.register(LogarithmicScale);
}
  ngOnDestroy(): void {
    Chart.unregister(LogarithmicScale);
  }
`

**Comment by santam85** [comment]
This should be fixed since v3.0.11, please have a try with the latest v3 or v4 (depending on your Angular version)
