### ISSUE TITLE
Unable to import Color and Label from ng2-charts v.3.0.8 Angular v12

### ISSUE THREAD

**Issue by siva-krishna-m** [valor-software/ng2-charts#1386]
![ng2-charts](https://user-images.githubusercontent.com/73309496/156324826-2808e041-5fc5-4ce8-9569-3f237b90f0db.PNG)

**Comment by daniboi112** [comment]
same issue here using:

![image](https://user-images.githubusercontent.com/3529594/156901019-e7aa7b33-5ecd-4371-930b-1a075564256b.png)

--- package.json ----
"dependencies": {
"@angular/animations": "~13.2.0",
"@angular/cdk": "^13.2.5",
"@angular/common": "~13.2.0",
"@angular/compiler": "~13.2.0",
"@angular/core": "~13.2.0",
"@angular/forms": "~13.2.0",
"@angular/material": "^13.2.5",
"@angular/platform-browser": "~13.2.0",
"@angular/platform-browser-dynamic": "~13.2.0",
"@angular/router": "~13.2.0",
"chart.js": "^3.7.1",
"ng2-charts": "^3.0.8",
"rxjs": "~7.5.0",
"tslib": "^2.3.0",
"zone.js": "~0.11.4"
},
"devDependencies": {
"@angular-devkit/build-angular": "~13.2.3",
"@angular-eslint/builder": "13.0.0-alpha.1",
"@angular-eslint/eslint-plugin": "13.0.0-alpha.1",
"@angular-eslint/eslint-plugin-template": "13.0.0-alpha.1",
"@angular-eslint/schematics": "13.0.0-alpha.1",
"@angular-eslint/template-parser": "13.0.0-alpha.1",
"@angular/cli": "~13.2.3",
"@angular/compiler-cli": "~13.2.0",
"@types/jasmine": "~3.10.0",
"@types/node": "^12.11.1",
"@typescript-eslint/eslint-plugin": "5.3.0",
"@typescript-eslint/parser": "5.3.0",
"eslint": "^8.2.0",
"jasmine-core": "~4.0.0",
"karma": "~6.3.0",
"karma-chrome-launcher": "~3.1.0",
"karma-coverage": "~2.1.0",
"karma-jasmine": "~4.0.0",
"karma-jasmine-html-reporter": "~1.7.0",
"ng2-charts-schematics": "^0.1.7",
"typescript": "~4.5.2"
}
--------------------------------------------------------------

Angular CLI: 13.2.5
Node: 16.14.0
Package Manager: npm 8.3.1
OS: darwin x64

Angular: 13.2.5
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1302.5
@angular-devkit/build-angular   13.2.5
@angular-devkit/core            13.2.5
@angular-devkit/schematics      13.2.5
@schematics/angular             13.2.5
rxjs                            7.5.4
typescript                      4.5.5


![image](https://user-images.githubusercontent.com/3529594/156901066-1524148d-2255-4ac4-baa9-e737906f1a5a.png)

**Comment by Franchise-x** [comment]
Was able to solve this by:

import {  BaseChartDirective } from 'ng2-charts';

Call parameter of Class -

public barChartLabels: BaseChartDirective["labels"] = ['2006', '2007', '2008', '2009', '2010', '2011', '2012'];

**Comment by santam85** [comment]
These types do not exist anymore in v3. Did you find any examples or documentation referring to them?

**Comment by daniboi112** [comment]
@Franchise-x, that did not help much on my side as Color is still not found

![image](https://user-images.githubusercontent.com/3529594/156926128-f7b2e7af-b1c8-487f-977d-387aaa45fdb9.png)

charts created by: **ng generate ng2-charts:{chart-type} {chart-name}** are missing amongst others these references below; (_then something funny happens, for a moment they are not referenced then again they are found it's inconsistent._)

Label
Color
RadialChartOptions
ChartDataSetsRadar
SingleDataSet
ChartDataSets

@santam85, i referenced/compared with charts at the below urls
https://stackblitz.com/edit/ng2-charts-line-template
https://stackblitz.com/edit/ng2-charts-radar-template
https://stackblitz.com/edit/ng2-charts-bar-template
and
https://valor-software.com/ng2-charts/

urls obtained here -> https://github.com/valor-software/ng2-charts#readme

and please provide updated references for v3

or should i downgrade to versions as per examples in stackblitz.com?

**Comment by daniboi112** [comment]
thank you that v3 template link helped, now charts are displaying, looking forward to the fully updated docs...cheers

**Comment by mohdabraralikhan** [comment]
> The types are inherited from Chart.js v3, that had some breaking changes. Labels are just a `string[]`, while Color is defined at https://www.chartjs.org/docs/latest/api/#color
> 
> See the new examples (which I will update soon in the docs): https://stackblitz.com/edit/ng2-charts-line-template-v3

Page not found

**Comment by samiulllah** [comment]
> > The types are inherited from Chart.js v3, that had some breaking changes. Labels are just a `string[]`, while Color is defined at https://www.chartjs.org/docs/latest/api/#color
> > See the new examples (which I will update soon in the docs): https://stackblitz.com/edit/ng2-charts-line-template-v3
> 
> Page not found

have you found work around?

**Comment by mohdabraralikhan** [comment]
Nope.

**Comment by NuthanaPriyaM** [comment]
> @Franchise-x, that did not help much on my side as Color is still not found
> 
> ![image](https://user-images.githubusercontent.com/3529594/156926128-f7b2e7af-b1c8-487f-977d-387aaa45fdb9.png)
> 
> charts created by: **ng generate ng2-charts:{chart-type} {chart-name}** are missing amongst others these references below; (_then something funny happens, for a moment they are not referenced then again they are found it's inconsistent._)
> 
> Label Color RadialChartOptions ChartDataSetsRadar SingleDataSet ChartDataSets
> 
> @santam85, i referenced/compared with charts at the below urls https://stackblitz.com/edit/ng2-charts-line-template https://stackblitz.com/edit/ng2-charts-radar-template https://stackblitz.com/edit/ng2-charts-bar-template and https://valor-software.com/ng2-charts/
> 
> urls obtained here -> https://github.com/valor-software/ng2-charts#readme
> 
> and please provide updated references for v3
> 
> or should i downgrade to versions as per examples in stackblitz.com?

I have Angular 18 project, chart.js version is 4.4.6 and ng2-charts version is 6.0.1 . I'm getting these errors:
Module '"ng2-charts"' has no exported member 'Label'.
Module '"ng2-charts"' has no exported member 'SingleDataSet'.

How do I solve them? Please respond.

thank you.
