### ISSUE TITLE
bar graph tooltip is not showing for smaller values.

### ISSUE THREAD

**Issue by js08** [valor-software/ng2-charts#1391]
Hi,

In bar graph tooltip is not showing for smaller values. For example, if one bar graph has a value of 8000 and another has a value of 40, then the tooltip is not showing up. Providing fiddle and code changes below.

https://stackblitz.com/edit/ng2-charts-bar-template-tbehxn

public barChartData: ChartDataSets[] = [
    { data: [40, 80, 80, 81, 56, 55, 40], label: 'Series A' },
    { data: [8000, 48, 40, 19, 86, 27, 90], label: 'Series B' },
  ];

**Comment by santam85** [comment]
Looks like that when the value rounds down to 0, the bar simply doesn't get drawn. You might argue this is right or wrong, but it's definitely a discussion you should have on the [Chart.js](https://github.com/chartjs/Chart.js) repo, we are just the messenger!
