### ISSUE TITLE
How to set the cutout values for Doughnut charts

### ISSUE THREAD

**Issue by emlimlf** [valor-software/ng2-charts#1393]
Where can I find examples on changing the cutout values for doughnut charts? In the charts.js documentation [here](https://www.chartjs.org/docs/latest/charts/doughnut.html#styling), it says the cutout config does "The portion of the chart that is cut out of the middle. If string and ending with '%', percentage of the chart radius. number is considered to be pixels" but I am unable to set this value in the "ChartConfiguration['options']" property. Please help.

**Comment by santam85** [comment]
Not really a bug nor a question for `ng2-charts`, but:
```
  doughnutChartOptions: ChartConfiguration<'doughnut'>['options'] = {
    cutout: '50%', // percentage of chart to cut out of the middle
    //cutout: 100, // pixels
  };
  ```

**Comment by disalvoluke** [comment]
@santam85 I am getting this error `Type 'keyof ChartTypeRegistry' is not assignable to type '"doughnut"'.` when I try to do this. Any idea why? I am using the most recent versions of chart.js and ng2-charts.
chart.js@4.0.1
ng2-charts@4.1.1

**Comment by disalvoluke** [comment]
I was able to work around this by doing:
`import { Chart } from 'chart.js'`  
`Chart.overrides.pie.cutout = '50%'`
While doing everything else the same as you would to create a pie chart.
