### ISSUE TITLE
Plugin registration

### ISSUE THREAD

**Issue by hmsuchier** [valor-software/ng2-charts#1395]
Hello, 
 What is the correct way to register a module in order to be able to configure it later in a configuration object ?
I get a comprehensible error when trying to do as following: 

```
Chart.register({
  id: "myPluginName,
  ....
})

```
And then 
```
// options for specific charts
myChartOptions:  ChartConfiguration['options'] = {
  ... 
  plugins: {
      myPluginName: false,   <---------------- compiler gives me an error here, which I can understand...
      ...
  }
}
```
I guess I need a way to extends ChartConfiguration['options'] definition but can't understand how to do it...
Any help appreciated...

**Comment by santam85** [comment]
Is this a custom plugin you are writing? Most Chart.js plugins extend the options type with extra fields (see https://github.com/chartjs/chartjs-plugin-datalabels/blob/master/types/index.d.ts#L13)
