### ISSUE TITLE
canvas can't bind to [colors] property in Angular 12

### ISSUE THREAD

**Issue by Quickdiv311** [valor-software/ng2-charts#1400]
I am facing error- "canvas can't bind to [colors] property", when I upgraded to Angular 12 from version 10.
So, I removed this property from canvas in v12.

Here is the code which I removed from version 12:

HTML - `[colors]="chartColors"`
ts -  ` this.chartColors = [{ borderColor: 'white' }];`

Here are the images which I got from:

Version 10
![canvasChart1](https://user-images.githubusercontent.com/76987517/163389282-7171a89a-ade2-4c77-8ef2-1a9f379d694e.PNG)

Version 12
![canvasChart2](https://user-images.githubusercontent.com/76987517/163389302-fcdc7d11-1c2b-4325-ae16-478efaff0916.PNG)

So, here in version 12 we require that chart line color(red) to be same as that of version 10 (white)

**Comment by santam85** [comment]
Check Chart.js documentation on which dataset property to use for the required chart type:
https://www.chartjs.org/docs/latest/charts/line.html#line-styling
