### ISSUE TITLE
Horizontal Bar Chart

### ISSUE THREAD

**Issue by Prettivy** [valor-software/ng2-charts#1407]
I am trying to do an horizontal bar chart.
I tried adding indexAxis: 'y' in the ChartConfiguration but only the last label is showing with its data. Othesr labels and datas are not showing.
I am using ng2-Chart : "^3.0.9", chart.js : "^3.6.0", angular13.2.3~
How do we show all of them?

**Comment by Prettivy** [comment]
Oh sorry! I added a scale and it did something. It is showing normaly with  indexAxis: 'y'.

**Comment by Allusgod** [comment]
Hii,can you please share the configuration. I'm stuck in same problem
