### ISSUE TITLE
Problems to display the chart in lazy loading material tab

### ISSUE THREAD

**Issue by NESTicle** [valor-software/ng2-charts#1408]
Im trying to display a graph in my angular project, but when I add a graph in a lazy load tab it doesn't load, it takes the size of the canvas but nothing is displayed, my code looks like this

```html
<mat-tab-group color="primary" backgroundColor="primary" dynamicHeight class="mt-2">
    <mat-tab>
        <ng-template mat-tab-label>
            <mat-icon>directions_car</mat-icon> Element
        </ng-template>

        <section>
            <app-report-example></app-report-example>
        </section>
    </mat-tab>

    <mat-tab>
        <ng-template mat-tab-label>
            <mat-icon>approval</mat-icon> Element 2
        </ng-template>

        <ng-template matTabContent>
            <app-report-example></app-report-example>
        </ng-template>
    </mat-tab>
</mat-tab-group>
```

the first tab loads well, but the second with lazy load does not load anything, anyone has the same issue as me?

thanks in advance

**Comment by santam85** [comment]
Chart.js used to have issues when trying to render onto an invisible canvas, or one without a fixed calculated size. With lazy-loaded tabs this can happen expecially if you have animations active.
Can you share the versions used, and perhaps try adding some fixed sizes to your canvas? The demo/docs app of ng2-charts also uses lazy tabs.
