### ISSUE TITLE
Polar Area rescaling

### ISSUE THREAD

**Issue by Prettivy** [valor-software/ng2-charts#1409]
I would like to know if it is possible to have the scale of a polar chart to rescal when we cross out one data from the legend like it did before.
I have currently the 3.0.9 version and 3.6.0 for chart.JS.

**Comment by santam85** [comment]
That functionality was not supported by this library, but from one of the dependants (Chart.js). Please check how to achieve that behaviour on https://www.chartjs.org/docs/latest/
