### ISSUE TITLE
Error on npm i.. What am I missing.

### ISSUE THREAD

**Issue by nsuhanshetty** [valor-software/ng2-charts#141]
> ng2-charts@1.0.2 flow.clean C:\Users\suhan.shetty\Documents\angular2\ng2-chart
s
> del bundles coverage demo-build typings "components/**/*.+(js|d.ts|js.map)" di
st "ng2-bootstrap.+(js|d.ts|js.map)"
Could Not Find ..\angular2\ng2-charts\bundles The filename, directory name, or volume label syntax is incorrect.

Kindly do let me know if I am missing something..
npm - 3.8.3
node - 5.10.1

**Comment by valorkin** [comment]
You are using windows,
I am not testing shell scripts on Windows
