### ISSUE TITLE
StackBlitz examples are out of date

### ISSUE THREAD

**Issue by toastertom** [valor-software/ng2-charts#1410]
Your examples on StackBlitz are still using 2.4.2

**Comment by Jadamae77** [comment]
+1. This was very confusing to me as I was trying to implement charts in my app.

**Comment by thopah** [comment]
+1. yes, it's really confusing now. all the examples are out of date. Please update asap.

**Comment by santam85** [comment]
I am trying to get a hold of the owner to update them, I don't have access to it. @paviad if you are reading us please help!

**Comment by paviad** [comment]
I couldn't find a way to share edit permissions on Stackblitz itself, so I
connected all the sample to new repositories and invited you as
collaborator.

Here are the links:

https://github.com/paviad/ng2-charts-line-template
https://github.com/paviad/ng2-charts-pie-template
https://github.com/paviad/ng2-charts-bar-template
https://github.com/paviad/ng2-charts-doughnut-template
https://github.com/paviad/ng2-charts-radar-template
https://github.com/paviad/ng2-charts-polar-area-template
https://github.com/paviad/ng2-charts-bubble-template
https://github.com/paviad/ng2-charts-scatter-template

Aviad

**Comment by santam85** [comment]
example links have been updated in readme, docs and npm.

**Comment by Jadamae77** [comment]
Thank you!

**Comment by santam85** [comment]
@paviad thanks for doing that, but turns out that pattern doesn't work very well, still requires you to manually update the stackblitz after changes are pushed. You can delete your stackblitz projects and repos if you like, I moved all examples elsewhere, and will add them to the ng2-charts org soon.

**Comment by paviad** [comment]
Done.
