### ISSUE TITLE
Cannot set point colors

### ISSUE THREAD

**Issue by dudewad** [valor-software/ng2-charts#1413]
The plunk playground setup provided by this repo does not currently work. I'm not sure how to fix it.

However, my problem is that the chart is not accepting color styles for points (I'm creating a line chart). I'm able to style lines no problem - thickness, tension, etc. Also, interestingly enough, I am able to style point attributes like radius and border size. However, color does not work. Here is the relevant part of the config I'm using:
```
{
   ...other data
  options: {
    elements: {
      line: {
          borderColor: '#12CE4E',   <-- works
          borderWidth: 1.25,   <-- works
          tension: 0,   <-- works
        },
        point: {
          backgroundColor: '#EB4747',   <-- *DOES NOT WORK*
          borderColor: '#000000',   <-- *DOES NOT WORK*
          radius: 0,   <-- works
          borderWidth: 0,   <-- works
          hoverRadius: 6,   <-- works
          hoverBorderWidth: 2,   <-- works
        },
    }
  }
}
```
Am I doing something wrong? I've spent _hours_ pouring over both the ng2-charts and the chartjs documentation. I'm certain that according to the chartjs docs I'm doing things correctly, esp because I'm seeing everything but the colors of the points change - including the colors of the line itself!

Any assistance would be helpful. Thanks.

**Comment by orbitr-dudewad** [comment]
Despite having tried it already, I added these styles to the data set object and it fixed it.
I do think you have a bug here, though, where "base" styles are overriding what should be user configurable items.

**Comment by dudewad** [comment]
I fixed it by adding these items to the dataset object. This still seems like a bug since a generic random set of colors is overriding an explicit configuration.

**Comment by santam85** [comment]
The library overrides some line and point specific settings on the datasets in order to generate default colors: see https://github.com/valor-software/ng2-charts/blob/master/projects/ng2-charts/src/lib/get-colors.ts

Can you create a reproduction plunkr so that I can investigate this more for you?
