### ISSUE TITLE
How to left-align the entire chart in the canvas, Currently We can align the legend but not the chart

### ISSUE THREAD

**Issue by vikasgunjeti** [valor-software/ng2-charts#1414]
How to left-align the entire chart in the canvas, Currently We can align the legend but not the chart.

Please find the below attached screenshot.

![image](https://user-images.githubusercontent.com/60781391/174469620-44747c69-126c-45d1-a79c-fc86a3f5487d.png)

If anyone solved the issue, Please let us know the solution.

**Comment by santam85** [comment]
You can find the answer to that in the Chart.js [documentation](https://www.chartjs.org/). Chart drawing logic is not implemented in this project.
