### ISSUE TITLE
Bar Chart skipNull

### ISSUE THREAD

**Issue by kinjalgamit** [valor-software/ng2-charts#1416]
Hello my angular version is 14.0.0.
"ng2-charts": "3.0.11"
"chart.js": "3.8.0",
"chartjs-plugin-datalabels": "2.0.0"

I am using bar chart.  And consider we have 2 datasets .
My question is I want to pass null or undefined value into dataset. 
And when its value is undefined. I need to remove space from bar chart.

As right now If we have 0 value then black space appear into chart.
We use this example direct right now.
https://valor-software.com/ng2-charts/#LineChart

Kindly assist.

Regards,
     Kinjal Gamit

**Comment by kinjalgamit** [comment]
Hello,
    Sorry I am not able to get you properly.
My question is that I am using @ng2-charts in my angular project to display the BAR chart. and how I can configure skip null in its config. Does it supported or not for @ng2-charts. kindly suggest.
Thanks,
    Kinjal Gamit

**Comment by santam85** [comment]
It supports every configuration that is supported in Chart.js.

**Comment by kinjalgamit** [comment]
then how to achieve skip null functionality?

**Comment by kinjalgamit** [comment]
Hi,
    I follow this url.
https://www.chartjs.org/docs/latest/charts/bar.html#general
 inside list there is one property for skipnull. 
I am not able to configure into ng2-charts. So, My question is where I can configure it's value in bar chart of ng2-charts.
Thanks,
    Kinjal Gamit

**Comment by santam85** [comment]
It's a dataset level property, so it really depends if you want to enable it for all datasets (using the `[options]` input for instance), or a single one (then using the `[data]` input).
In the first case, your options needs to have a `datasets.bar.skipNull` property, in the second case your data needs to have a `datasets[index].skipNull` property.

**Comment by kzimny** [comment]
Unfortunatelly the property `skipNull` doesn't exist in your library:
![image](https://github.com/valor-software/ng2-charts/assets/12007674/ccdd37a8-8406-4bb9-8155-0daaf6a0230e)

![image](https://github.com/valor-software/ng2-charts/assets/12007674/c3c6bba4-f704-4cc9-b373-27f62fae6cb7)

**Comment by kzimny** [comment]
Perfect. Many thanks.
