### ISSUE TITLE
Breaking Change v3.1.0

### ISSUE THREAD

**Issue by ScottSpittle** [valor-software/ng2-charts#1418]
An update was published a few hours ago, 3.1.0 with Angular 14 upgrade, which has introduced a breaking change as my build fails.

My package.json is configured as such "ng2-charts": "^3.0.8" so I would not expect 3.1.0 to be a breaking change, I would have expected 4.0.0 to become a breaking change at which point my build would not have installed this new version and continued to function 

:)

> [2022-06-29T14:50:50.495Z] ./node_modules/ng2-charts/fesm2015/ng2-charts.mjs - Error: Module build failed (from ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js):

> [2022-06-29T14:50:50.495Z] TypeError: Cannot create property 'message' on string '/build/node_modules/ng2-charts/fesm2015/ng2-charts.mjs: This application depends upon a library published using Angular version 14.0.3, which requires Angular version 14.0.0 or newer to work correctly.

**Comment by colinBranca** [comment]
I have the same issue
Do you have a workaround or do we just need to stay on 3.0.x while our app is on Angular 13 ?

**Comment by ScottSpittle** [comment]
> I have the same issue Do you have a workaround or do we just need to stay on 3.0.x while our app is on Angular 13 ?

I just updated my package.json to install the previous version

`"ng2-charts": "3.0.8"`

**Comment by santam85** [comment]
The breaking change was not intended, odd that this is the case as the library does not have any explicit dependency on any lib from Angular 14 (as you can see from it's package.json). I did not realize Angular 14 would add this at build time. You get that error by just running ng-serve on Angular 13?

**Comment by ScottSpittle** [comment]
> The breaking change was not intended, odd that this is the case as the library does not have any explicit dependency on any lib from Angular 14 (as you can see from it's package.json). I did not realize Angular 14 would add this at build time. You get that error by just running ng-serve on Angular 13?

I haven't tested with ng serve as I already had 3.0.8, I've only noticed it at build time in our build pipeline.
