### ISSUE TITLE
Error while using ng2-charts with Angular 13

### ISSUE THREAD

**Issue by uraswi** [valor-software/ng2-charts#1419]
**Reproduction of the problem**
**package.json**

"@angular-devkit/build-angular": "~13.3.2",
"@angular/animations": "^13.3.2",
"@angular/cdk": "^12.1.1",
"@angular/common": "^13.3.2",
"@angular/compiler": "^13.3.2",
"@angular/compiler-cli": "^13.3.2",
"@angular/core": "^13.3.2",

**"chart.js": "^3.6.0",
"ng2-charts": "^3.0.0",**

I have tried different types of ng2-charts version from 3.0.0 to latest. Still facing same issue pls.

"ng2-charts": "^3.0.0" is updated to Angular 13. But, why the below code checking for minVersion to ng 14?

<img width="898" alt="Screenshot 2022-06-30 at 10 16 39 PM" src="https://user-images.githubusercontent.com/96533590/176733061-7cc3ed46-6c28-4b8c-af46-29a6a09ec75f.png">

**Comment by santam85** [comment]
Not sure I get the issue: the ng2-charts peer dependency is:
```
 "@angular/common": ">=11.0.0",
 "@angular/core": ">=11.0.0",
```

**Comment by santam85** [comment]
Releasing v3.1.2 with a fix for this.
