### ISSUE TITLE
Chart.min.js file not found angular 14

### ISSUE THREAD

**Issue by dittuxdev** [valor-software/ng2-charts#1420]
im facing problems, after execute an **npm install ng2-charts --save**  im getting the following message:

```
Generating browser application bundles (phase: setup)...An unhandled exception occurred: Script file node_modules/chart.js/dist/Chart.min.js does not exist.
See "/tmp/ng-xknQwS/angular-errors.log" for further details.
```
![image](https://user-images.githubusercontent.com/54783343/176755100-4190c0f2-a084-401e-8bfe-4c842ecfd20a.png)

**Comment by santam85** [comment]
With the info you provided it's impossible to debug this, but I think it might be caused by a wrong import in your project, there's no mention of ng2-charts in your error log. Can you provide a minimal reproduction example on stackblitz/github?
