### ISSUE TITLE
Fixed vertical position for the tooltip

### ISSUE THREAD

**Issue by directcuteo** [valor-software/ng2-charts#1455]
Hi. I am using ng2-charts on a `line-chart` with 2 lines.

Is there any way to display the tooltip on the vertical middle of the chart and follow the cursor on the horizontal direction?
Currently tooltip is shown near each line which seems very weird for me, I am expecting the tooltip to stay in a rather fixed position since it's displaying both values already.
![image](https://user-images.githubusercontent.com/37619567/179964469-5d74648b-82b2-4df4-962b-a62d0efde0ea.png)
![image](https://user-images.githubusercontent.com/37619567/179964536-d0da095c-ba39-43ee-bf3d-286331789174.png)

The images represent the same graph with same settings.

Thank you!

**Comment by santam85** [comment]
Check Chart.js documentation on how to achieve that, this library doesn't take care of the rendering!
https://www.chartjs.org/docs/latest/
