### ISSUE TITLE
ng2-charts drawn partially for big chart in Firefox

### ISSUE THREAD

**Issue by Andranik-89** [valor-software/ng2-charts#1469]
Hi guys. I prepared a stackblitz example for you. You can see only 60% (16384px or 2^14px) of the ng2-chart is drawn in Firefox, but 100% in Chrome - https://stackblitz.com/edit/github-nlvlrr-mwudnj?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html,tsconfig.json&preset=node.

Maybe there is some quick workaround to this? Have been trying to solve this bug since the last week...

**Comment by Andranik-89** [comment]
![image](https://user-images.githubusercontent.com/20794092/183511963-e69a4798-063a-4658-a8a8-b8a4d882fd0a.png)

**Comment by Andranik-89** [comment]
Chrome:
![image](https://user-images.githubusercontent.com/20794092/183512405-26f50220-2ef7-499f-8f15-02128db5ea67.png)

**Comment by Andranik-89** [comment]
I also prepared this small jsfiddle eg - you can see ordinary canvas draws up to 32000px in Firefox normally - https://jsfiddle.net/1urw9q84/. 34000px for example will give you an error

**Comment by santam85** [comment]
Can you reproduce the same with Chart.js? If so, it's a bug for that library. There is absolutely no rendering logic in this one.
