### ISSUE TITLE
Add 'bottom' value for tooltip position

### ISSUE THREAD

**Issue by c-masson** [valor-software/ng2-charts#1471]
The latest version of Chart.js (`3.9.1` as of today) implements a new position `bottom` for the tooltip, which makes it stick to the x axis.

As seen in [documentation](https://www.chartjs.org/docs/latest/samples/tooltip/position.html):
<img width="357" alt="image" src="https://user-images.githubusercontent.com/49158497/183858255-c1386744-f159-49fc-8a6f-05940eccde91.png">

---

The current version of `ng2-charts` (`4.0.0` as of today) only implements `'nearerest'` and `'average'` attributes.  
Could you add this new attribute ?

**Comment by santam85** [comment]
We inherit all types from Chart.js, are you sure you can't just update to the new minor and use the new value?
