### ISSUE TITLE
Can't bind to 'colors' since it isn't a known property of 'canvas'.

### ISSUE THREAD

**Issue by Kissema** [valor-software/ng2-charts#1491]
Error: src/app/my-line-chart/my-line-chart.component.html:5:3 - error NG8002: Can't bind to 'colors' since it isn't a known property of 'canvas'.

5   [colors]="lineChartColors"

I'm using "ng2-charts": "^4.0.0" and @angular v 14.2.2

**Comment by santam85** [comment]
`colors` is not a directive input anymore starting in v3. You need to define colors in the dataset settings or by overriding defaults following [Chart.js documentation](https://www.chartjs.org/).
