### ISSUE TITLE
Cannot find name 'Cannot find name 'ChartDataSetsLine''

### ISSUE THREAD

**Issue by Kissema** [valor-software/ng2-charts#1492]
It's no possible to use ng2-chart types:
`
Cannot find name 'ChartDataSetsLine'
Cannot find name 'Label'
Cannot find name 'ChartOptions'
Cannot find name 'Color'
Cannot find name 'ChartType'
`
I'm using ng-chart v4 and @angular v14.2.2

**Comment by santam85** [comment]
What version of Chart.js are you using? You need v3+

**Comment by AndeYashwanth** [comment]
I am facing the same issue
"chart.js": "~3.9.1",
"ng2-charts": "~4.0.1",
"@angular/core": "^14.0.0",

**Comment by santam85** [comment]
I expect you get this when trying to migrate from Chart.js v2 and ng2-charts v2?
Those types don't exist anymore, you need to use the Chart.js types documented at https://www.chartjs.org/docs/latest/api/

**Comment by adover** [comment]
@santam85 - it looks like the schematics still have these incorrect references. I'll take a look at a solution and attempt a PR
