### ISSUE TITLE
Unable to import NgChartsModule into appmodule in stackblitz

### ISSUE THREAD

**Issue by AndeYashwanth** [valor-software/ng2-charts#1520]
```
Error in src/app/app.module.ts
The entrypoint for 'ng2-charts' could not successfully be resolved. The file '/turbo_modules/ng2-charts@4.0.1/src/public_api.ts' does not exist. Please log an issue with the package author or check for an updated version of the package.
```
![image](https://user-images.githubusercontent.com/34389995/198303814-5bb970fc-9961-4abc-ae57-5afa0b476708.png)

**Reproduction of the problem**
https://stackblitz.com/edit/angular-ivy-pnfadq?file=package.json,src%2Fapp%2Fapp.module.ts
To reproduce the issue in stackblitz

1. open stackblitz and create angular project from the given template.
2. Add chart.js and ng2-charts dependencies in package.json
3. Add NgChartsModule in imports of app.module.ts and let the stackblitz run
4. It is showing error mentioned above.

When I checked the given stackblitz demos of charts in readme page I dont see any such error. But if I download the same stackblitz as zip and import all the files in an empty stackblitz page, I get the same error.
One thing I observed is webcontainer.io vs stackblitz.io in the stackblitz preview URL's of the project.

**Comment by santam85** [comment]
Can't reproduce this one in a fresh stackblitz: https://stackblitz.com/edit/angular-ivy-hewpnv
Probably something wrong with that particular stackblitz, perhaps an issue with cached packages? Try a fresh one...

**Comment by Asheq096** [comment]
Were you able to resolve it? I am having the same issue.
