### ISSUE TITLE
Outdated version

### ISSUE THREAD

**Issue by malkeet-gwebs** [valor-software/ng2-charts#1540]
ng2-charts using outdated version of chart.js please update on urgent basis

**Comment by MarcoB1234** [comment]
I get the error below if I run `npm list chart.js` whilst having `ng2-charts` version 4.01 and `chart.js` version 4.01 installed on my node_modules folder (the fact that both versions are 4.0.1 makes you thinks they are supposed to work fine together)

![image](https://user-images.githubusercontent.com/26527963/203080727-8908535d-0742-46be-9e82-ae93af95ebcd.png)

**Comment by aplongh** [comment]
Are there any plans of supporting chartjs@4.0.1?

**Comment by dangreen** [comment]
@santam85 Hi. I'm Dan from Chart.js team. I want to help you, and I have a suggestion on how to upgrade to Chart.js v4.

Chart.js v4 becomes an ESM-only package, so the wrapper also should become ESM-only. You need to set `"type": "module"` in `package.json` - it can cause issues with configs/tools that you also have to solve.

**Comment by santam85** [comment]
Hey folks, hope to get around this soon. @dangreen thanks for the suggestion.

**Comment by santam85** [comment]
> @santam85 Hi. I'm Dan from Chart.js team. I want to help you, and I have a suggestion on how to upgrade to Chart.js v4.
> 
> Chart.js v4 becomes an ESM-only package, so the wrapper also should become ESM-only. You need to set `"type": "module"` in `package.json` - it can cause issues with configs/tools that you also have to solve.

@dangreen I did a first test with 4.0.1 and the library seems to work correctly in general, apart from some defaults resolution issues. Is there any breaking change on how that works in v4? Or any known issue? Seems to be limited to the doughnut/pie controllers...

**Comment by dangreen** [comment]
@santam85 The full list of changes is here: https://www.chartjs.org/docs/latest/migration/v4-migration.html

I think there are no more breaking changes important for the wrapper.

**Comment by santam85** [comment]
Then I think I'm running in either a bug or an undocumented change. Will try to reproduce it in an example.

**Comment by santam85** [comment]
@dangreen Unless I am missing something obvious, here's the issue that I'm facing. Nothing that blocks the release, but would like to understand if there's something fundamentally wrong with the way I do things in ng2-charts before ignoring the failing visual tests I have in place.

https://github.com/chartjs/Chart.js/issues/10927
