### ISSUE TITLE
smaller section in chart (with large data) flickers in color on hover

### ISSUE THREAD

**Issue by jain-isha02** [valor-software/ng2-charts#1543]
I am using Doughnut chart with Angular 14 . 
The issue only happens when charts has many sections . In that case when you hover on the chart , one smaller section starts flickering in color. Here's the demo of the issue.

https://stackblitz.com/edit/labs-ng2-charts-3-zxvj4y?file=src%2Fapp%2Fdoughnut%2Fdoughnut.component.ts,src%2Fapp%2Fdoughnut%2Fdoughnut.component.html,src%2Fapp%2Fdoughnut%2Fdoughnut.component.css,src%2Fapp%2Fapp.component.css

Pls check and share the resolution if any.

**Comment by santam85** [comment]
I can't see any issue with the example. If you want to disable hover animation to prevent the color from changing, or change the interaction method, check https://www.chartjs.org/docs/latest/configuration/interactions.html#modes

**Comment by jain-isha02** [comment]
ok. Got it. 

I have found some more issues only with the smallest sections of the chart, will share some more details in a bit

**Comment by jain-isha02** [comment]
@santam85 ,

My requirement is to highlight a section from outside of a chart. 
when I try to apply this on a broader section of chart , It works fine, But if I try it on a smaller section of chart it fails to show any difference.

Link to stalkblitz example : https://stackblitz.com/edit/labs-ng2-charts-3-zxvj4y?file=src%2Fapp%2Fdoughnut%2Fdoughnut.component.ts,src%2Fapp%2Fdoughnut%2Fdoughnut.component.html,src%2Fapp%2Fdoughnut%2Fdoughnut.component.css,src%2Fapp%2Fapp.component.css

If you hover on the span "hover on Broad section" you will see the portion moving out of the chart and the highlight in it with black 
but if you hover on the span "hover on Small section" there is no change.

Any specific reason why this behaves like this.

**Comment by santam85** [comment]
@jain-isha02 I actually see the change happening, the slice is just very small for that item, so it's less visible.

<img width="445" alt="Screenshot 2022-12-02 at 14 55 08" src="https://user-images.githubusercontent.com/2706307/205308746-8e592119-d967-4f93-9dd5-1fc08af30350.png">

The "issues" section of this library's github repo is reserved for just that: bugs and problems with the library. Please seek for guidance and support on Stackoverflow.

Moreover, this library is just a wrapper around the parent Chart.js one, you'll find better support if you broaden your search to their documentation, hosted [here](https://www.chartjs.org/).
