### ISSUE TITLE
Issue with time type on axis

### ISSUE THREAD

**Issue by 0pahh** [valor-software/ng2-charts#1547]
Hello, i'm currently trying to get type 'time' on my charts but i got this error : 

main.ts:11 ERROR Error: This method is not implemented: Check that a complete date adapter is provided.
    at abstract (chart.mjs:4151:9)
    at DateAdapter.formats (chart.mjs:4159:12)
    at TimeScale.init (chart.mjs:10406:42)
    at chart.mjs:5601:13
    at each (helpers.segment.mjs:60:12)
    at Chart.buildOrUpdateScales (chart.mjs:5579:9)
    at Chart._updateScales (chart.mjs:5726:10)
    at Chart.update (chart.mjs:5687:10)
    at new Chart (chart.mjs:5476:12)
    at ng2-charts.mjs:76:63

I can't figure out why i'm getting that error, even on the issues here.

Here's my axis config 
```
xAxis: {

          ticks: {

            autoSkip: true,

            maxTicksLimit: 30,

          },

          type: 'time',

          time: {

            unit: 'day',

            displayFormats: {

              day: 'MMM D', // This is the default

            },

          },

          grid: {

            display: false,

            color: 'white',

          },

          display: true,

          title: {

            display: true,

  

            text: this.graphData.titleX,

            font: {

              size: 13,

              weight: 'bold',

            },

            color: 'rgb(0, 152, 157)',

          },

        },
```

Thanks you

**Comment by santam85** [comment]
You need to register an adapter, as explained at https://www.chartjs.org/docs/latest/axes/cartesian/time.html
That's what we are dong in the financial chart example with the line
`import 'chartjs-adapter-date-fns';`
