### ISSUE TITLE
Not been processed correctly by ngcc, or is not compatible with Angular 15 Ivy

### ISSUE THREAD

**Issue by Kushagra-05** [valor-software/ng2-charts#1553]
I'm trying to import & export ChartsModule from ng-2 charts but encounter this error:

` 'ChartsModule' does not appear to be an NgModule, Component, Directive, or Pipe class.(-996003)
charts.d.ts(47, 28): This likely means that the library (ng2-charts/ng2-charts) which declares ChartsModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. `

Please suggest a solution.
Screenshot of error notification attached.
![Screenshot (397)](https://user-images.githubusercontent.com/98595254/205135381-2aaea5eb-bbdc-4a77-a9dc-921a99673a6d.png)

**Comment by santam85** [comment]
Which version of the library are you using? Only ng2-charts 3 and 4 are compatible with Ivy.

**Comment by Kushagra-05** [comment]
Yes, you're right, mine was a lower version;
Thanks for informing; Apologies for late reply.
