### ISSUE TITLE
Generic type 'ɵɵDirectiveDeclaration' requires between 6 and 8 type arguments

### ISSUE THREAD

**Issue by suhailkc** [valor-software/ng2-charts#1556]
Error: node_modules/ng2-charts/lib/base-chart.directive.d.ts:40:18 - error TS2707: Generic type 'ɵɵDirectiveDeclaration' requires between 6 and 8 type arguments.

40     static ɵdir: i0.ɵɵDirectiveDeclaration<BaseChartDirective<any, any, any>, "canvas[baseChart]", ["base-chart"], { "type": "type"; "legend": "legend"; "data": "data"; "options": "options"; "plugins": "plugins"; "labels": "labels"; "datasets": "datasets"; }, { "chartClick": "chartClick"; "chartHover": "chartHover"; }, never, never, false, never>;

`ng version`
Angular CLI: 14.2.10
Node: 14.21.1
Package Manager: npm 6.14.17 
OS: darwin x64

Angular: 14.2.12
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.10
@angular-devkit/build-angular   14.2.10
@angular-devkit/core            14.2.10
@angular-devkit/schematics      14.2.10
@angular/cli                    14.2.10
@schematics/angular             14.2.10
rxjs                            7.5.7
typescript                      4.7.4

**Comment by yanivamrami** [comment]
Hi @suhailkc, did you manage to solve the issue? I am having the same thing...

Thanks

**Comment by Klejin** [comment]
Hello @suhailkc , would it be possible to tell us how you manage to fix the error?
I'm having the same one and can't seem to fix it.
