### ISSUE TITLE
error TS2707: Generic type 'ɵɵDirectiveDeclaration'

### ISSUE THREAD

**Issue by wupaz** [valor-software/ng2-charts#1557]
Error: node_modules/ng2-charts/lib/base-chart.directive.d.ts:40:18 - error TS2707: Generic type 'ɵɵDirectiveDeclaration' requires between 6 and 8 type arguments. 

40     static ɵdir: i0.ɵɵDirectiveDeclaration<BaseChartDirective<any, any, any>, "canvas[baseChart]", ["base-chart"], { "type": "type"; "legend": "legend"; "data": "data"; "options": "options"; "plugins": "plugins"; "labels": "labels"; "datasets": "datasets"; }, { "chartClick": "chartClick"; "chartHover": "chartHover"; }, never, never, false, never>;

"ng2-charts": "^4.0.1",

Sorry, no repro for now

**Comment by ohois** [comment]
You're propably using Angular 14. Check your package-lock.json. You may have ng2-charts@4.1.0 installed. Downgrade to 4.0.2 which is the latest Angular 14 compatible version.

**Comment by Klejin** [comment]
Hello, I'm having the same problem on angular 14.0.5 I tried to downgrade to 4.0.2 and 3.1.2 and still gets the same error, is there any other way around ?

**Comment by familygw** [comment]
> Hello, I'm having the same problem on angular 14.0.5 I tried to downgrade to 4.0.2 and 3.1.2 and still gets the same error, is there any other way around ?

Try deleting node_modules folder and package-lock.json, then re-install all dependencies (npm i).

**Comment by Klejin** [comment]
> > Hello, I'm having the same problem on angular 14.0.5 I tried to downgrade to 4.0.2 and 3.1.2 and still gets the same error, is there any other way around ?
> 
> Try deleting node_modules folder and package-lock.json, then re-install all dependencies (npm i).

tried and still doesn't work only version that it works for me is 3.0.0-rc.7, so far tried 4.0.2, 4.0.0 , 3.1.2 which for me don't work

**Comment by familygw** [comment]
> > > Hello, I'm having the same problem on angular 14.0.5 I tried to downgrade to 4.0.2 and 3.1.2 and still gets the same error, is there any other way around ?
> > 
> > 
> > Try deleting node_modules folder and package-lock.json, then re-install all dependencies (npm i).
> 
> tried and still doesn't work only version that it works for me is 3.0.0-rc.7, so far tried 4.0.2, 4.0.0 , 3.1.2 which for me don't work

Good to know. I’ll check again, just in case.
Btw, I’m using Angular 14.2.x

**Comment by santam85** [comment]
Yes this is the case. I am patching the 4.1 line to make it compatible with Angular 14 again and bumping the major to 5 for the Angular 15 version.

**Comment by santam85** [comment]
Released 4.1.1 to address this.
