### ISSUE TITLE
How do I change the color of a radar chart and the labels?

### ISSUE THREAD

**Issue by nelo112** [valor-software/ng2-charts#157]
I would like to change the color of the radar chart "web" and labels. I found a view posts about how to do it with chart.js but I can't figure out how to do it with ng2-charts.

**Comment by jkyoutsey** [comment]
I've tried numerous things with a simple array of data like [10, 20, 70]:
`[colours]="['ff0000']"` results in TWO reds.
`[colours]="['ff0000', '00ffff']"` results in ALL red?!
`[colours]="['ff0000', '00ffff', '00ff00']"` results in all black?!

**Comment by jkyoutsey** [comment]
I've fixed this in my environment, but it's definitely a bug in the base code.
First, the right way to specify color is this: 
`[colours]="[ [204, 0, 0], [230, 230, 0], [0, 153, 51] ]"`
It's an Array<Array<number>>.  An array of RGB arrays.

Second, the base code is not calculating color from this.  So, if you want to use it you have to hack your `node_modules/ng2-charts/components/charts.js on line 217:
`var colour = i < this.colours.length ? this.getColour(this.colours[i]) : this.defaultsColours[i] || this.getColour(colourDesc);`

The alternate solution is to copy the BaseChart.getColor function from charts.js to your own component, call it, and provide the actual color object produced by that function to the colours attribute.  That is probably the production monkey patch you SHOULD do.  But take your pick.

**Comment by valorkin** [comment]
updated to rc.1 and colors issue should be fixed now
