### ISSUE TITLE
Doughnut legend will not display

### ISSUE THREAD

**Issue by rdppjr** [valor-software/ng2-charts#1576]
With the following data and code, I am unable to get the legend to display.   So far, I haven't been able to get a legend to display.

<div class="doughnutChart"
     *ngIf="doughnutChartData?.datasets?.length > 0">
    <canvas baseChart class="chart"
      [data]="doughnutChartData"
      [type]="doughnutChartType"
      [legend]="doughnutChartLegend">
    </canvas>
</div>

.doughnutChart {
  display: flex;
  margin: auto;
  height: 300px;
  width: 300px;
}

  @Input() doughnutChartData: ChartData<'doughnut'> = {
    datasets: [],
    labels: [],
  };
  public doughnutChartType: ChartType = 'doughnut';
  public doughnutChartLegend = true;

@Input parameter
{
    "labels": {
        "0": "Owned",
        "1": "Shared"
    },
    "datasets": [
        {
            "data": [
                44,
                15
            ]
        }
    ]
}

**Comment by santam85** [comment]
hard to debug without the html template, I expect you're not passing the legend input. As a workaround, try enabling it in the options directly.
