### ISSUE TITLE
Package "ng2-charts" was found but does not support schematics.

### ISSUE THREAD

**Issue by dcolakchile** [valor-software/ng2-charts#1584]
To reproduce run:

ng add ng2-charts

Response:

ℹ Using package manager: npm
✔ Found compatible package version: ng2-charts@0.0.0.
✔ Package information loaded.

The package ng2-charts@0.0.0 will be installed and executed.
Would you like to proceed? Yes
✔ Packages successfully installed.
Package "ng2-charts" was found but does not support schematics.

Problem:

Nothing works.

**Comment by HealthyPizza** [comment]
Same issue : Angular 14

**Comment by santam85** [comment]
can't reproduce, ng cli resolves latest version correctly for me (not 0.0.0). please check your npmrc, or delete package-lock files and node_modules before retrying

**Comment by kounelios13** [comment]
Can confirm the same happens in a branch new project in agular 16
