### ISSUE TITLE
TS2305: Module '"ng2-charts"' has no exported member 'Color'.

### ISSUE THREAD

**Issue by DmitriiCr** [valor-software/ng2-charts#1586]
Hello 
I installed  package ng2-charts version 3.0.0-rc.2.

Now when I import Color and Label from ng2-charts I'm getting this error.

TS2305: Module '"ng2-charts"' has no exported member 'Color'.
TS2305: Module '"ng2-charts"' has no exported member 'Label'.

How Can I fixed or is there any analogs for Color type that I can use for my charts

**Comment by H-Gomez** [comment]
Was there any solution for this? I currently see the same after upgrading an old Angular project and I'm guessing this type def is no longer available.

**Comment by himanshurajora** [comment]
Facing the same issue

**Comment by blerinaademii** [comment]
Facing the same issue

**Comment by himanshurajora** [comment]
Hi there, while bumping the version of ng2-charts in my project. I figured out that the `Label` type isn't needed anymore. Here's how I replaced my existing code.

I am currently at `5.0.1`

**Before**

```typescript
import { Label } from 'ng2-charts';
...

  @Input() chartData: {
    datasets: ChartDataSets[];
    labels: Label[];
    height?: number | null;
    width?: number | null;
  };
```
**After**

```typescript
  // the Label type is not needed any more
  @Input() chartData: ChartData<'doughnut'>; // whatever Chart Type you have
```

**Comment by santam85** [comment]
All types are now inherited directly from Chart.js: https://www.chartjs.org/docs/latest/api/ to avoid creating confusion and maintaining 2 sets of types. Check their migration documents from v2 to v3 to understand what types have changed, and find the corresponding ones in the typedoc.

**Comment by NuthanaPriyaM** [comment]
> All types are now inherited directly from Chart.js: https://www.chartjs.org/docs/latest/api/ to avoid creating confusion and maintaining 2 sets of types. Check their migration documents from v2 to v3 to understand what types have changed, and find the corresponding ones in the typedoc.

I have Angular 18 project, chart.js version is 4.4.6 and ng2-charts version is 6.0.1 . I'm getting these errors:
Module '"ng2-charts"' has no exported member 'Label'.
Module '"ng2-charts"' has no exported member 'SingleDataSet'.

How do I solve them? Please respond.

thank you.

**Comment by santam85** [comment]
@NuthanaPriyaM use `Chart.js` [types](https://www.chartjs.org/docs/latest/api/), not `ng2-charts` ones
