### ISSUE TITLE
Zoom and annotation plugins don't work together in v4

### ISSUE THREAD

**Issue by jkon** [valor-software/ng2-charts#1597]
I'm not sure if this is an issue with ng2-charts or with one of the plugins, but I can't seem to use both at the same time. Here is a stackblitz with a minimal reproduction: https://stackblitz.com/edit/ng2charts-gpi-p6oqxj?file=src/app/app.component.ts
in the app.component file, if you uncomment line 4, the import of the annotation plugin, you get a compiler error:

Error: node_modules/chart.js/dist/types/index.d.ts:2793:18 - error TS2428: All declarations of 'PluginOptionsByType' must have identical type parameters.

2793 export interface PluginOptionsByType<TType extends ChartType> {
                      ~~~~~~~~~~~~~~~~~~~


Error: node_modules/chart.js/dist/types/index.d.ts:2802:12 - error TS2314: Generic type 'PluginOptionsByType<TType, TType>' requires 2 type argument(s).

2802   plugins: PluginOptionsByType<TType>;
                ~~~~~~~~~~~~~~~~~~~~~~~~~~

My guess is that there is some mismatch of versions or something, but I can't track it down and I'm stumped. Any ideas on how to fix the compiler error would be appreciated, thanks

**Comment by AvniAnay** [comment]
Same issue with me when registering ChartDataLabels plugin.

**Comment by ssj300** [comment]
ditto

**Comment by tomsonawesome** [comment]
Same here, really annoying. Thinking about using a other chart library.

**Comment by DamboRam** [comment]
Same here
