### ISSUE TITLE
Import error Not Found

### ISSUE THREAD

**Issue by xXanth0s** [valor-software/ng2-charts#160]
Hello, 

i've tried it now with an old and a new project(quickstart from angular websit), but i still get problems with setting up the charts component.
For the installation i followed the instruction. For the code, i used one of the examples. 
The import i changed to 

`import {CHART_DIRECTIVES} from 'ng2-charts/ng2-charts';`

In the package file of my project, ng2-charts is available, but after starting npm, i get the error 

`[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (ng2-charts, line 0)`

`[Error] Error: invoke@http://localhost:3000/node_modules/angular2/bundles/angular2-polyfills.js:390:34
	runGuarded@http://localhost:3000/node_modules/angular2/bundles/angular2-polyfills.js:297:54
	http://localhost:3000/node_modules/angular2/bundles/angular2-polyfills.js:273:40
	Error loading http://localhost:3000/ng2-charts/ng2-charts as "ng2-charts/ng2-charts" from http://localhost:3000/app/charts.component.js 
	error
	invoke
	run
	(anonymous function)
	invokeTask
	runTask
	drainMicroTaskQueue
	invoke
	(anonymous function)
	invokeTask
	runTask
	invoke`

I've already changed the import in several ways, but still no success

**Comment by valorkin** [comment]
Please check ng2-bootstrap readme, there are an answer

**Comment by noor-siddique-m4** [comment]
Hi Valorkin,

I have not found any answer at ng2-bootstrap! Can you  please pin point what to do?

Regards,
Noor

**Comment by valorkin** [comment]
`Error loading http://localhost:3000/ng2-charts/ng2-charts`
from this is can assume you are using system.js and did not configured it

**Comment by valorkin** [comment]
Other words I need more info about your set up\config to help you

**Comment by noor-siddique-m4** [comment]
I have cloned repository from git@github.com:valor-software/angular2-quickstart.git and trying to use ng2-charts in that project. Here is the tsconfig.json file contents:

{
  "compilerOptions": {
    "target": "ES5",
    "module": "system",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false,
    "listFiles": true
  },
  "exclude": [
    "node_modules",
    "typings/browser.d.ts"
  ]
}

Thanks in advance.

**Comment by alfakappa** [comment]
No. Valor is pointing out this:

`

            System.config({

                // baseURL to node_modules
                baseURL: '/path/to/your/node_modules',
                defaultJSExtensions: true
            });
            // url to main.js (but without. js since you set defaultExtension to JS already above here ;-)
            System.import('/path/to/your/app/main')
                    .then(null, console.error.bind(console));
`
Hope this helps you out.

NB: System Config should be in sripttags in your <head>-tag after you load systemJS

**Comment by valorkin** [comment]
Thanks @alfakappa

**Comment by crossme** [comment]
**>-------- NG2BOOTSTRAP--------->**
Use these commands to add these dependencies to your package.json

1.npm install moment --save
2.npm install ng2-bootstrap --save
Modify your System.config.js to the following code :

var map = {
    'app':                        'app', // 'dist',
    '@angular':                   'node_modules/@angular',
     moment:              'node_modules/moment/moment.js',
    'ng2-bootstrap':              'node_modules/ng2-bootstrap',
  };

var packages = {
    'app':                        { main: 'main.js',    defaultExtension: 'js' },
    'ng2-bootstrap':          {defaultExtension: 'js' }
  };
Add Bootstrap to your index.html <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">

App.module.ts import { Ng2BootstrapModule } from 'ng2-bootstrap/ng2-bootstrap'; And, add Ng2BootstrapModule to imports of @NgModule.

Then, U are good to go for ng2Bootstrap.
