### ISSUE TITLE
[Question] - Any plans on upgrading to Chart.js 4.2.0 - for Line Segments feature

### ISSUE THREAD

**Issue by dinbtechit** [valor-software/ng2-charts#1602]
Looks like in `chartjs 4.2.0` they introduced line segments (The feature that I am looking for..). Just wondering if there are any plans on upgrading chartjs to 4.2.0 anytime soon?

https://www.chartjs.org/docs/latest/samples/line/segments.html

**Comment by santam85** [comment]
V5 of the lib is compatible with Chart.js 4
