### ISSUE TITLE
SyntaxError: Unexpected token <(…)

### ISSUE THREAD

**Issue by alexciesielski** [valor-software/ng2-charts#161]
Hello,

When including a component into my main-app, that has an ng2-charts import 
`import {CHART_DIRECTIVES} from 'ng2-charts/ng2-charts';` 
I get the following error: 
`angular2-polyfills.js:332 Error: SyntaxError: Unexpected token <(…)`

I installed using  the instructions here and then tried the Barchart example from the demos.

This is my index.html
`
<body>
	<main-app>
		<i class="center-fix main-spinner fa fa-spin fa-circle-o-notch fa-5x"></i>
	</main-app>
	
	
	
	<script src="/bower_components/jquery/dist/jquery.js"></script>
	<script src="/bower_components/Chart.js/dist/Chart.js"></script>
	<script src="/bower_components/bootswatch-dist/js/bootstrap.js"></script>
	

	<script src="node_modules/angular2/bundles/angular2-polyfills.js"></script>
	<script src="node_modules/systemjs/dist/system.js"></script>
	

	
	<script src="systemjs.conf.js"></script>
	

	<script>
		System.import('app/main.js')
            .then(null, console.error.bind(console));
	</script>
</body>
`

**Comment by alexciesielski** [comment]
Found the problem, had to add the `ng2-charts` to systemjs.conf.js
`
var SystemConfig = (function() {
    // List your node_modules packages here
    var packages = [
        'angular2',
        'rxjs',
        'ng2-charts'
    ];
`

**Comment by valorkin** [comment]
great!

**Comment by alexciesielski** [comment]
Would be nice to have that in the Readme, though, for all SystemJS users.

Cheers

**Comment by valorkin** [comment]
I am not using system.js a lot, but I will really appreciate PR with changes to readme
Thanks in advance :)
