### ISSUE TITLE
barChartType don't work anymore in version 4.1.1

### ISSUE THREAD

**Issue by PetruDragus** [valor-software/ng2-charts#1616]
Hello guys.

I upgraded an old project and seems that barChartType don't work anymore. Someone know how to pass the horizontalBar parameters to the 4.1 version?

Thanks

**Comment by fwatteau** [comment]
I've a similar problem when option responsive is set to true.

I fix it with 

` 
public barChartOptions: ChartConfiguration<'bar'>['options'] = {
    responsive: false,
  };
`
