### ISSUE TITLE
Dependency tree issue while installing version 4.0.1

### ISSUE THREAD

**Issue by piacentero** [valor-software/ng2-charts#1617]
While trying to install ng2-charts (version 4.0.1) with the command "npm i ng2-charts@4.0.1" the following error appears:

![ng2-charts401](https://user-images.githubusercontent.com/16261622/221831481-41c80604-edbd-490c-9e99-3e9e9529831e.png)

I am using angular@14.2.12 and chart.js@3.9.1

**Comment by hajty** [comment]
I have the similar problem. angular@14.2.12, chart.js@4.2.1 and ng2-charts@4.1.1.

**Comment by hajty** [comment]
Okay, I fixed my adding `"@angular/cdk": "^14.2.0"` to my dependencies in package.json.

**Comment by santam85** [comment]
missing peer dep in the library, was fixed in the latest 4.x minor and newer versions.
