### ISSUE TITLE
Error when adding tooltips in ChartOptions 

### ISSUE THREAD

**Issue by mavershang** [valor-software/ng2-charts#1630]
I got error when adding tooltips to ChartOptions

this works
```
  public scatterChartOptions: ChartOptions = {
    responsive: true,
   }
```

this doesnot work. It pops error "Type '{ responsive: true; tooltips: { borderWidth: number; borderColor: string; }; }' is not assignable to type '_DeepPartialObject<CoreChartOptions<keyof ChartTypeRegistry> & ElementChartOptions<keyof ChartTypeRegistry> & PluginChartOptions<...> & DatasetChartOptions<...> & ScaleChartOptions<...>>'.
  Object literal may only specify known properties, and 'tooltips' does not exist in type '_DeepPartialObject<CoreChartOptions<keyof ChartTypeRegistry> & ElementChartOptions<keyof ChartTypeRegistry> & PluginChartOptions<...> & DatasetChartOptions<...> & ScaleChartOptions<...>>'."
```
  public scatterChartOptions: ChartOptions = {
    responsive: true,
    tooltips: {
      callbacks: {
        label: (item, data) => 
        {
          console.log(item);
          return 'Label: ' + item.xLabel + ' ' + item.yLabel
        }
      }
    }
```

**Comment by godind** [comment]
I get a similar type issue with annotations also.

**Comment by santam85** [comment]
Typing in Chart.js is fairly complex, try using `ChartConfiguration<'line'>['options']`.
Replace `line` with whatever chart type you are using.
