### ISSUE TITLE
ng2-chart tutorial can't bind property

### ISSUE THREAD

**Issue by beppo-ivel** [valor-software/ng2-charts#1637]
Was following [this tutorial](https://valor-software.com/ng2-charts/#LineChart) useing Angular 15 and 
```
$ npm list | grep "ng2\|chart"
├── chart.js@4.2.1
├── chartjs-plugin-annotation@2.2.1
├── ng2-charts@4.1.1

```

Everything goes fine till I add the `<canvas>` to my lingraph.component.html, then I end up with:

```
error NG8002: Can't bind to 'data' since it isn't a known property of 'canvas'.

``` 
Found similar issue here: https://github.com/valor-software/ng2-charts/issues/1595

It works if I implement the graph in pure chart.js as described [here](https://techincent.com/how-to-add-chart-js-in-angular/#Implement_chart_with_pure_chartjs).

Below my setup for ng2-chart.js.

1) I imported NgChartsModule in app.modules.ts:

```
import { NgChartsModule } from 'ng2-charts';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    HttpClientModule,
    NgChartsModule
```

2) created a linegraph component, where I'm trying to create the graph:
```

import { Component, OnInit } from '@angular/core';
import { DataService }  from '../data.service';
import { Chart, ChartConfiguration, ChartEvent, ChartType, ChartDataset } from 'chart.js';
import { BaseChartDirective } from 'ng2-charts';

import { default as Annotation } from 'chartjs-plugin-annotation';


@Component({
  selector: 'app-linegraph',
  templateUrl: './linegraph.component.html',
  styleUrls: ['./linegraph.component.css']
})
export class LinegraphComponent implements OnInit {
 ...
``` 

3) my app-routing.modules.ts contains:
```
import { LinegraphComponent } from './linegraph/linegraph.component';


const routes: Routes = [
  { 
    path:"", component: LinegraphComponent
  }
];

```

**Comment by H-Gomez** [comment]
Where about to solve this? Having a similar issue in Angular 14 with `Can't bind to 'chartType' since it isn't a known property of 'canvas'.`

**Comment by santam85** [comment]
`data` and `datasets` will both work, they have different semantics. Try updating to the latest patches released for the library, your error means the chart directive cannot be resolved correctly, likely because the `NgChartsModule` module wasn't loaded properly in the child route module. Try moving the import of NgChartsModule to the module using it rather than the root module

**Comment by skygragon** [comment]
@santam85 I'm using inoic/angular in non-standalone mode，while it complains NgChartsModule doesn't exposed by ng2-charts?
