### ISSUE TITLE
Custom Ng2 charts backdrop for a graph.

### ISSUE THREAD

**Issue by Naru4337** [valor-software/ng2-charts#1651]
We were able to achieve this but not the next graph. 

![16843298049137048332455825922888](https://github.com/valor-software/ng2-charts/assets/77152511/01d10037-9dc9-414e-beda-417ef80dd4f7)

**Comment by Naru4337** [comment]
We are trying to color the backdrop of the graph with different colors by Y axis, now we need to shift the backdrop with respect to x axis values too. 

Has anyone implemented this so far in Angular NG2 charts.

**Comment by santam85** [comment]
Chart rendering is done by Chart.js (a different library). please check their docs for info on how to achieve this. https://www.chartjs.org/docs/latest/
