### ISSUE TITLE
Add support for Angular 16

### ISSUE THREAD

**Issue by dsubelman** [valor-software/ng2-charts#1652]
Now that Angular 16 has been released, are there any plans to release a new version that supports Angular 16?

**Comment by zackarychapple** [comment]
Hey there!  Will bump this internally and take a peek.

**Comment by Sampath-Lokuge** [comment]
@zackarychapple Please let us know once you'll do that. Thanks!

**Comment by madmacc** [comment]
Is this is what is causing the error "Module '"ng2-charts"' has no exported member 'SingleDataSet'"?
I can't seem to get this to work with Angular 16

**Comment by radunecsanu** [comment]
same here

**Comment by valorkin** [comment]
working on it

**Comment by valorkin** [comment]
finally, had to refactor it completely
I will everything once again later today and will release version 5
I will not close this issue - please try v5 when released and give here updates so I could fix fast, ok?

https://github.com/valor-software/ng2-charts/pull/1664

**Comment by valorkin** [comment]
5.0.1 is on npm, please check

**Comment by sydneyhenrard** [comment]
I migrated to Angular 16.1.6 and tried to upgrade from ng2-charts 4.1.1 to 5.0.1.  I got this error due to `ng2-charts-schematics` when running `npm install`.

```
npm WARN Could not resolve dependency:
npm WARN peer ng2-charts-schematics@"0.0.1" from ng2-charts@5.0.1
npm WARN node_modules/ng2-charts
npm WARN   ng2-charts@"^5.0.1" from the root project
```
package.json
```
"dependencies": {
    "@angular/animations": "^16.1.6",
    "@angular/cdk": "^16.1.5",
    "@angular/common": "^16.1.6",
    "@angular/compiler": "^16.1.6",
    "@angular/core": "^16.1.6",
    "@angular/forms": "^16.1.6",
    "@angular/material": "^16.1.5",
    "@angular/platform-browser": "^16.1.6",
    "@angular/platform-browser-dynamic": "^16.1.6",
    "@angular/router": "^16.1.6",
    "angular-oauth2-oidc": "^15.0.1",
    "chart.js": "^4.3.0",
    "chartjs-adapter-date-fns": "^3.0.0",
    "cross-env": "^7.0.3",
    "date-fns": "^2.30.0",
    "flag-icons": "^6.7.0",
    "ng2-charts": "^5.0.1",
    "ngx-auto-unsubscribe": "^3.0.1",
    "ngx-date-fns": "^10.0.1",
    "ngx-google-analytics": "^14.0.1",
    "rxjs": "~7.5.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.13.1"
  },
```

**Comment by Sampath-Lokuge** [comment]
@sydneyhenrard Please create a new issue for this hence this is a closed ticket.
