### ISSUE TITLE
cannot create horizontal bar chart

### ISSUE THREAD

**Issue by FrankZhang2046** [valor-software/ng2-charts#1654]
**Reproduction of the problem**

in prior version can create a horizontal bar chart with [chartType]="'horizontalBar'", in version 4.1.1, binding of chart type got changed to [type]=, and `horizontaBar` is not a viable option of the ChartTypeRegistry

so how do I create a horizontal bar chart? tried `indexAxis = 'y'`, it doesn't work because it only shows one label.

demo (fork of stackblitz bar chart demo): https://stackblitz.com/edit/github-nxkkeh?file=src%2Fapp%2Fapp.component.html

**Comment by JakeKeenan** [comment]
if you want a horizontal bar chart, under options for the chart you provide a different index axis
`options: {
    indexAxis: y
}`
