### ISSUE TITLE
2 Scales on Y-axis

### ISSUE THREAD

**Issue by rajendra-kumar-kandpal** [valor-software/ng2-charts#1658]
Hello There,

I am using ng2-charts: 4.1.1, I drawing a line chart, I am in a situation where i see 2 labels on y axis, please see below screen shot
![image](https://github.com/valor-software/ng2-charts/assets/36263243/78697de2-672b-4adb-a8b1-1f7b140bfbab)

I don't need the one that i have highlighted(one with decimal values), do you know how to get rid of it?
I have checked and tried out many thing, but haven't found anything helpful, hence reaching out here

can you please let me know about it??

Thanks!

**Comment by rajendra-kumar-kandpal** [comment]
hello can someone please help on this?

**Comment by martinzima** [comment]
I had this exact same problem a if I remember correctly, I solved it by removing an outdated Chart.js plugin.

**Comment by santam85** [comment]
check your config, you might have an outdated `yAxes` value. Check Chart.js docs for info.
