### ISSUE TITLE
Help pls

### ISSUE THREAD

**Issue by ZairDeLuque** [valor-software/ng2-charts#1682]
Try install ng2-charts but:

npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: myproyect@0.0.0
npm ERR! Found: @angular/platform-browser@16.1.6
npm ERR! node_modules/@angular/platform-browser
npm ERR!   @angular/platform-browser@"^16.1.6" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/platform-browser@"16.1.5" from ng2-charts@5.0.1
npm ERR! node_modules/ng2-charts
npm ERR!   ng2-charts@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!

Package.json:

"dependencies": {
    "@abacritt/angularx-social-login": "^1.2.5",
    "@angular/animations": "^16.1.6",
    "@angular/common": "^16.1.6",
    "@angular/compiler": "^16.1.6",
    "@angular/core": "^16.1.6",
    "@angular/forms": "^16.1.6",
    "@angular/platform-browser": "^16.1.6",
    "@angular/platform-browser-dynamic": "^16.1.6",
    "@angular/router": "^16.1.6",
    "@azure/msal-angular": "^2.5.9",
    "@azure/msal-browser": "^2.38.0",
    "@fortawesome/fontawesome-free": "^6.4.0",
    "bootstrap": "^5.3.0",
    "bootstrap-icons": "^1.10.5",
    "ng-recaptcha": "^11.0.0",
    "notiflix": "^3.2.6",
    "rxjs": "~7.8.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.13.1"
  },
  "devDependencies": {
    "@angular-builders/custom-webpack": "^10.0.1",
    "@angular-devkit/build-angular": "^16.1.5",
    "@angular/cli": "~16.1.5",
    "@angular/compiler-cli": "^16.1.6",
    "@types/electron": "^1.6.10",
    "@types/jasmine": "~4.3.0",
    "jasmine-core": "~4.5.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.0.0",
    "node-polyfill-webpack-plugin": "^2.0.1",
    "path-browserify": "^1.0.1",
    "typescript": "~4.9.4"
  }

**Comment by wjehring** [comment]
You can temporarily work round this until it's fixed by adding the following to your package.json:

```
"overrides": {
  "ng2-charts": {
     "@angular/platform-browser": "^16.1.6"
  }
}
```

You'll almost certainly need to add the override for the incorrect schematics version [here,](https://github.com/valor-software/ng2-charts/issues/1681#issuecomment-1653538043) too.
