### ISSUE TITLE
Not able to show the chart

### ISSUE THREAD

**Issue by EnricoPicci** [valor-software/ng2-charts#17]
I am trying to use your base-chart component but I am not able to get the chart shown on the browser.
If I inspect, I see that the dimension of the <canvas> is null. What I actually see is

<canvas width="0" height="0" style="width: 0px; height: 0px;"></canvas>

Could you help me in finding what I am doing wrong?

Thanks
Enrico

**Comment by valorkin** [comment]
push your sample app to some public repo or gist, and drop me a link, so I could take a look

**Comment by EnricoPicci** [comment]
The problem has been solved pointing at chart.min.js via CDN (<script data-require="chart.js@0.2.0" data-semver="0.2.0" src="//cdnjs.cloudflare.com/ajax/libs/Chart.js/0.2.0/Chart.js"></script>)

Previously I was pointing to a local copy of chart.min.js (just downloaded from GitHub and perfectly working outside angular2 components) but id did not work.
