### ISSUE TITLE
The legend posion do not work

### ISSUE THREAD

**Issue by PikeDr** [valor-software/ng2-charts#1705]
Hello, I am trying to create charts with Angular version 16 and the latest version of ng-charts2, and I can't get it to accept the 'position' value for the legend. Any ideas? Where can I place it?"

**Comment by santam85** [comment]
Types are inherited from chart.js, are you sure you are using the correct Chart v3+ option setup? Here's their docs: https://www.chartjs.org/docs/latest/api/interfaces/LegendOptions.html
Create a reproduction example

**Comment by santam85** [comment]
Closed due to lack of reproduction issue and inactivity.
