### ISSUE TITLE
ReferenceError: Chart is not defined in [lineChartOptions in LineChart@4:8]

### ISSUE THREAD

**Issue by alfakappa** [valor-software/ng2-charts#173]
Everything seems up to speed, added the CSS to get LineCharts to show up (first had the mouse over issue), a canvas is rendered, but now it is telling me this:

ReferenceError: Chart is not defined in [lineChartOptions in LineChart@4:8]

I used the demo and it does log "line demo" in the console, so it seems everything is rooted well.

Using angular2.0beta15 

Help would be appreciated

**Comment by sbert** [comment]
same with angular2.0beta16

ORIGINAL EXCEPTION: TypeError: this.chart is undefined

**Comment by alfakappa** [comment]
Issue Solved: 

First I did not referenced to my charts.min.js file. When I did, I used a 2.0 version. Loading chartsJS 1.0.2 made everything work fine. 

Sorry.. very lame issue, didn't RTFM actually :)

**Comment by valorkin** [comment]
released rc.1 ready version compatible with chart.js 2.1.3

**Comment by alfakappa** [comment]
I updated my app to angular2 beta 17,
updated chart js to 2.*
and updated ng-charts

but no I get this error:

ORIGINAL EXCEPTION: TypeError: t.controllers[o] is not a constructor

here is my component:

/*
 * Import Core/Angular Components
 */
import {Component, Input} from '@angular/core';
import {CORE_DIRECTIVES, FORM_DIRECTIVES, NgClass} from '@angular/common';

/*
 * Import Custom Components
 */
import {myNewsLetter} from './../../../objects/newsLetter';
import {CHART_DIRECTIVES} from 'ng2-charts/ng2-charts';

/*
 * Build Component
 */
@Component({
    selector: 'section.news-letter-doughnut-chart',
    template: `
        <base-chart *ngFor="let newsletter of newsletter" class="chart"
                [data]="[newsletter.bounced, newsletter.opened, newsletter.unsubscribed, calculateData(newsletter)]"
                [labels]="doughnutChartLabels"
                [legend]="doughnutChartLegend"
                [chartType]="doughnutChartType"
                (chartHover)="chartHovered($event)"
                (chartClick)="chartClicked($event)">
        </base-chart>
    `,
    directives: [CHART_DIRECTIVES, NgClass, CORE_DIRECTIVES, FORM_DIRECTIVES]
})

/*
 * Export Component
 */

export class NewsLetterDoughnutChart {
    //Make sure newsletter object is put into component
    @Input() newsletter: myNewsLetter;

    // events
    chartClicked(e:any) {
        //console.log(e);
    }
    chartHovered(e:any) {
        //console.log(e);
    }
    // Chart values
    doughnutChartLabels = ['Gebounced', 'Geopend', 'Uitschrijvingen', 'Ongeopend'];
    doughnutChartType = 'Doughnut';
    doughnutChartLegend:boolean = true;

    calculateData(newsletter) {
        return (newsletter.send - newsletter.bounced - newsletter.opened);
    }
}


Any ideas what is going wrong?


Astrid Karsten 
Consultant IT 

Mobiel +31 6 10 415 995
Werkdagen: maandag, dinsdag, donderdag, vrijdag 
 <https://nl.linkedin.com/in/nleknip> <https://nl.linkedin.com/in/astridkarsten> 
 <http://www.saxum.nl/?utm_source=signature&utm_medium=email&utm_campaign=saxum_signature>Jan Luijkenstraat 62, 1071 CS Amsterdam 
NB: deze email en eventuele bijlagen kunnen vertrouwelijke informatie bevatten en zijn uitsluitend bestemd voor degene aan wie de email is gericht. Het is een ieder aan wie deze email niet gericht is niet toegestaan de informatie te lezen, door te sturen of op welke manier dan ook te gebruiken. Voor wat betreft de aanbieding van kandidaten van Saxum aan derden geldt dat iedere aanbieding altijd onder voorbehoud is, tenzij schriftelijk anders overeengekomen.

**Comment by alfakappa** [comment]
and the complete error, just for sure


Astrid Karsten 
Consultant IT 

Mobiel +31 6 10 415 995
Werkdagen: maandag, dinsdag, donderdag, vrijdag 
 <https://nl.linkedin.com/in/nleknip> <https://nl.linkedin.com/in/astridkarsten> 
 <http://www.saxum.nl/?utm_source=signature&utm_medium=email&utm_campaign=saxum_signature>Jan Luijkenstraat 62, 1071 CS Amsterdam 
NB: deze email en eventuele bijlagen kunnen vertrouwelijke informatie bevatten en zijn uitsluitend bestemd voor degene aan wie de email is gericht. Het is een ieder aan wie deze email niet gericht is niet toegestaan de informatie te lezen, door te sturen of op welke manier dan ook te gebruiken. Voor wat betreft de aanbieding van kandidaten van Saxum aan derden geldt dat iedere aanbieding altijd onder voorbehoud is, tenzij schriftelijk anders overeengekomen.
