### ISSUE TITLE
"No such file or directory" when generating charts ng2-charts 5.0.3

### ISSUE THREAD

**Issue by Fweiberth** [valor-software/ng2-charts#1743]
When using ng2-charts 5.0.3 running ng generate ng2-charts:pie charts/*chartname* results in the following error:

ENOENT: no such file or directory

After downgradeing to 4.1.1 it works as intended.

Angular cdk ^16.2.4 Angular core ^16.0.1

**Comment by santam85** [comment]
Should be fixed in v5.0.4
