### ISSUE TITLE
[Req] Change peerDep for '^Angular-2.0.0-beta.15'

### ISSUE THREAD

**Issue by Luchillo** [valor-software/ng2-charts#175]
Currently the peerDeps force `Angular-2.0.0-beta.15` however the peerDeps should state the minimum version, unless it breaks if used with a recent version of Ng2 (unlikely) could you guys change the peerDeps to allow recent versions after beta.15? (Current Ng2 version is beta.17).

**Comment by crystoll** [comment]
Or even, RC.1 and release..

**Comment by Luchillo** [comment]
Nop, RC.1 now bundles the Angular 2 packages under `@angular/core`, `@angular/platform` and many others, to use the RC.1 version they will need to update the imports to use this ones instead, then the minimum version would be RC.0 up.

**Comment by valorkin** [comment]
updating lib to rc.1 and charts 2

**Comment by Luchillo** [comment]
Awesome, now i just need the other libs i'm using to update to the @angular namespace for the RC.1 of Ng2, will it work if i use both versions at same time? the @angular and the beta.17?

**Comment by crystoll** [comment]
Suberb!

**Comment by Luchillo** [comment]
For some reason if i try to get the `upgrade-rc1` branch through npm it doesn't shows the js files.

**Comment by valorkin** [comment]
And it should not contain generated .js files :)

**Comment by Luchillo** [comment]
@valorkin i mean, you have there an ng2-charts.ts but when i install like this it doesn't show that file:
```js
npm i -S git://github.com/valor-software/ng2-charts.git#upgrade-rc1
```

**Comment by Luchillo** [comment]
@valorkin i meant there's no `ts` files if i install like this:
```sh
npm i -S git://github.com/valor-software/ng2-charts.git#upgrade-rc1
```

**Comment by valorkin** [comment]
.npmignore hides .ts files, so keep calm and wait a bit :)

**Comment by Luchillo** [comment]
I'm sorry to say that if it is in the `.npmignore` i think it will never show, or you meant to wait a bit until the official release?

**Comment by valorkin** [comment]
to wait until I will publish it :)
