### ISSUE TITLE
Support of rxjs v7 in v2.x

### ISSUE THREAD

**Issue by duykhang53** [valor-software/ng2-charts#1753]
Angular v12 already support *rxjs@^7* as **peerDependencies**, my project need to run ```npm i --force``` every time to install packages.

For reference: https://www.npmjs.com/package/@angular/core/v/12.2.17?activeTab=code / package.json

Thanks!

**Comment by santam85** [comment]
Angular v12 is out of LTS, upgrade to a newer version of the framework.
