### ISSUE TITLE
chartClick interface eventEmitter interface is incorrect

### ISSUE THREAD

**Issue by Jackques** [valor-software/ng2-charts#1754]
**Reproduction of the problem**

The provided output method event param interface for the directive does not cover the actual data being returned when on clicked. The interface states:
`chartClick: EventEmitter<{
        event?: ChartEvent;
        active?: object[];
    }>`
https://github.com/valor-software/ng2-charts/blob/master/libs/ng2-charts/src/lib/base-chart.directive.ts line 56.

However when the data received when clicked is actually;
![image](https://github.com/valor-software/ng2-charts/assets/5686464/38af18dc-b2d0-4596-ac20-25b4092aa351)
where we are also receiving; 
`event.event.chart` (where the chart property is not part of the ChartEvent object)
and
`event.active[0].element.$context` (where the $context property is not part of the element interface)

**Comment by santam85** [comment]
The type and the event data both come from chart.js: https://www.chartjs.org/docs/latest/api/interfaces/ChartEvent.html
Please open a ticket with them to address this.
