### ISSUE TITLE
Can't create a Clustered Stacked Bar Chart as expected

### ISSUE THREAD

**Issue by LinusJose** [valor-software/ng2-charts#1764]
I am working on ng2-charts Clustered Stacked Bar where I want to achieve clustered stacks. Something similar to attached image, is it possible using Ng2-Charts in angular ?

![clusters10](https://github.com/valor-software/ng2-charts/assets/48787279/41040dcb-59d8-409e-ad75-e4ad35f74f15)

**Comment by santam85** [comment]
Check [Chart.js docs](https://www.chartjs.org/docs/latest/) to learn how to achieve this, this library does not directly implement any rendering functionality.
