### ISSUE TITLE
Module '"ng2-charts"' has no exported member 'provideCharts', 'withDefaultRegisterables'.

### ISSUE THREAD

**Issue by HenriqueCTMM** [valor-software/ng2-charts#1849]
I updated my Angular project to version 17, but when I refactored the code, I encountered this error:

>  Module 'ng2-charts' has no exported member 'provideCharts', 'withDefaultRegisterables'.

I read the new documentation, and the first step to configure is to add:
`"providers: [provideCharts(withDefaultRegisterables())]"` 
in the main.ts, but it leads to the error above. 
I tried reinstalling, deleting node_modules, installing with ng add ng2-charts or manually (with npm), and nothing worked.

### To reproduce the problem:
[ng2-charts  'provideCharts', 'withDefaultRegisterables' ERROR](https://stackblitz.com/edit/stackblitz-starters-4alxpm?file=src%2Fmain.ts)

**Comment by godind** [comment]
Same problem here

**Comment by godind** [comment]
just updated to v6 beta 1. Error gone but had to remove from main.ts:
`import { NgChartsModule } from 'ng2-charts';` 
in favour of:
` import { provideCharts, withDefaultRegisterables } from 'ng2-charts';`

and remove `NgChartsModule` from `providers: [
        importProvidersFrom(provideCharts(withDefaultRegisterables())`

**Comment by HenriqueCTMM** [comment]
> just updated to v6 beta 1. Error gone but had to remove from main.ts: `import { NgChartsModule } from 'ng2-charts';` in favour of: ` import { provideCharts, withDefaultRegisterables } from 'ng2-charts';`
> 
> and remove `NgChartsModule` from `providers: [ importProvidersFrom(provideCharts(withDefaultRegisterables())`

Thank you! It's working now, but it's not ideal. I can't use a beta version in production. I will wait for the new version or they fix it on v5.

**Comment by godind** [comment]
I guess a fix will be coming soon?

**Comment by santam85** [comment]
We made those breaking changes in v6 to encourage users to switch to module-less and to use the color generation plugin embedded in Chart.js directly. v6.0.0 is being released today. Will look into patching the issues for v5 as well soon.
