### ISSUE TITLE
Update library to work with angular2 rc version?

### ISSUE THREAD

**Issue by zeljko-bulatovic** [valor-software/ng2-charts#186]
Hello,

When we can expect update of the library to work with angular2 RC version? 

Since angular2 libraries are loaded from '@angular/...', i am receiving error:
- Error loading http://localhost:4200/angular2/core, angular2/common...

Thanks in advance.

**Comment by alexcastillo** [comment]
+1

**Comment by snarum** [comment]
rc1 is nice, but even beta17 would be appreciated.

**Comment by nnixaa** [comment]
+1

**Comment by jppellerin** [comment]
Obviously this would be great, but without underestimating the work required, is there a timeline for this?

Is the goal to do like ng2-bootstrap and also rename to components to correspond to angular2 naming conventions?

**Comment by enlightendev** [comment]
+1

**Comment by juhofriman** [comment]
+1

**Comment by valorkin** [comment]
updating lib to rc.1 and charts 2

**Comment by Luchillo** [comment]
@valorkin I guess the docs and readme are still pending to update?

**Comment by Luchillo** [comment]
@valorkin Oh i see, you are still working on it within a branch, btw how do you know which parts of @angular will you need? i see you use :
```js
  "peerDependencies": {
    "@angular/core": "^2.0.0-rc.1",
    "@angular/common": "^2.0.0-rc.1"
  },
  "devDependencies": {
    "@angular/common": "2.0.0-rc.1",
    "@angular/compiler": "2.0.0-rc.1",
    "@angular/core": "2.0.0-rc.1",
    "@angular/platform-browser": "2.0.0-rc.1",
    "@angular/platform-browser-dynamic": "2.0.0-rc.1"
  }
```
how do you know you need those 4 in dev and only `core` and `common` as peer deps in the dist?

**Comment by valorkin** [comment]
By import statement in directive (peer dependencies) and demo app imports (
dev dependencies )

**Comment by Luchillo** [comment]
I meant how do you know your directive needs core and common, where in the docs you find what each includes?

**Comment by robertBrem** [comment]
+1

**Comment by valorkin** [comment]
It is not in docs, it is in peer dependencies. So it will explicitly say to
you on install

**Comment by valorkin** [comment]
updated to rc.1 and chart.js 2
and published to npm
Re tweets are much appreciated :)
https://twitter.com/valorkin/status/732568221598027776
