### ISSUE TITLE
"bar" is not a registered controller

### ISSUE THREAD

**Issue by alaxed** [valor-software/ng2-charts#1863]
core.mjs:7473 ERROR Error: "bar" is not a registered controller.
    at Registry._get (chart.js:5050:19)
    at Registry.getController (chart.js:4994:21)
    at Chart.buildOrUpdateControllers (chart.js:5856:50)
    at Chart.update (chart.js:5893:37)
    at new Chart (chart.js:5663:18)
    at ng2-charts.mjs:109:59
    at _ZoneDelegate.invoke (zone.js:368:26)
    at _Zone.run (zone.js:130:43)
    at _NgZone.runOutsideAngular (core.mjs:15515:28)
    at _BaseChartDirective.render (ng2-charts.mjs:109:22)
    
    this is my code:
    
    import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { ChartConfiguration } from 'chart.js';
import { BaseChartDirective } from 'ng2-charts';
@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet, CommonModule,
    BaseChartDirective],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css'
})
export class AppComponent {
  title = 'column-chart';
  public barChartLegend = true;
  public barChartPlugins = [];

  public barChartData: ChartConfiguration<'bar'>['data'] = {
    labels: ['2006', '2007', '2008', '2009', '2010', '2011', '2012'],
    datasets: [
      { data: [65, 59, 80, 81, 56, 55, 40], label: 'Series A' },
      { data: [28, 48, 40, 19, 86, 27, 90], label: 'Series B' }
    ]
  };

  public barChartOptions: ChartConfiguration<'bar'>['options'] = {
    responsive: false,
  };

  constructor() {
  }
}

<canvas baseChart [data]="barChartData" [options]="barChartOptions" [plugins]="barChartPlugins"
  [legend]="barChartLegend" [type]="'bar'">
</canvas>

**Comment by docaohuynh** [comment]
I've got same error

**Comment by santam85** [comment]
You need to register the default components in standalone mode otherwise they will be treeshaken. Check the app code [example](https://github.com/valor-software/ng2-charts/blob/master/apps/ng2-charts-demo/src/app/app.config.ts), or add 

`provideCharts(withDefaultRegisterables())` to your app config.
