### ISSUE TITLE
V6 Annotation Typing issues

### ISSUE THREAD

**Issue by godind** [valor-software/ng2-charts#1865]
**Reproduction of the problem**
Using ng2-chart v6, Angular 17, chart.js 4.4.2

Template
```
  <canvas [id]="widgetProperties.uuid"
    baseChart class="chart"
    [data]="lineChartData"
    [options]="lineChartOptions"
    [type]="lineChartType"
  ></canvas>
```

Config
```
public lineChartOptions: ChartConfiguration['options'] = {
    plugins: {
      annotation: {
        annotations: {
          meanLine: {
            type: 'line',
            scaleID: 'y',
            value: 1,
            borderColor: 'green',
            drawTime: 'beforeDatasetsDraw',
            label: {
              display: true,
              content: "Minimum"
            }
          }
        }
      },
    }
  }
```
It won't compile. I've also tried to see if it would run anyway. 

Line of code with compiler error with @ts-ignore enabled
```
SyntaxError: /Users/godind/Documents/GitHub/Kip/src/app/widgets/widget-data-chart/widget-data-chart.component.ts: Support for the experimental syntax 'optionalChainingAssign' isn't currently enabled (190:13):

  188 |             });
  189 |             // @ts-ignore
> 190 |             this.chart.options.plugins.annotation.annotations["meanLine"].value = 10;
      |             ^
  191 |             this.chart?.update('none');
  192 |         });
  193 |     }

✖ Failed to compile.
```

Type script complaint
![image](https://github.com/valor-software/ng2-charts/assets/34038713/e449ebba-efe3-48d3-b468-6ff220c2bb30)

Not sure how to fix this or if it's a bug. Thanks for your Wonderfull work!

**Comment by godind** [comment]
It works fine in plain js.

**Comment by santam85** [comment]
The generic configuration does not have all plugin types merged in. Have you tried using `ChartConfiguration<'line'>['options']` ?

**Comment by godind** [comment]
I've not thought of `ChartConfiguration<'line'>['options'] ?
I assume you have import AnnotationPlugin from 'chartjs-plugin-annotation';`

First time with ng2-charts

Thank for the help!
