### ISSUE TITLE
Chart components registration errors

### ISSUE THREAD

**Issue by ilyakonrad** [valor-software/ng2-charts#1908]
Version 6 seems to require registering scales, controllers and elements manually like this
`Chart.register([CategoryScale, LinearScale, BarController, BarElement, LineController, LineElement, PointElement])`

otherwise it'll show one error at a time until you register all necessary things
![image](https://github.com/valor-software/ng2-charts/assets/25200186/eb74f497-f397-48b8-a8fb-880f1d9f9e08)

Here are the errors I've faced:
`ERROR Error: "category" is not a registered scale`
`ERROR Error: "linear" is not a registered scale`
`ERROR Error: "bar" is not a registered controller`
`ERROR Error: "bar" is not a registered element`
`ERROR Error: "line" is not a registered controller`
`ERROR Error: "line" is not a registered element`
`ERROR Error: "point" is not a registered element`

**Comment by anuj9196** [comment]
If you are not using standalone components, add this to the `app.module.ts` 
```
providers: [
 provideCharts(withDefaultRegisterables()),
 ...
]
```
