### ISSUE TITLE
Issue with ng-charts compatibility with the latest TypeScript version

### ISSUE THREAD

**Issue by AalaaHabib** [valor-software/ng2-charts#1913]
I would like to report an issue regarding the compatibility of ng-charts with the latest version of TypeScript. After updating to the latest TypeScript version (5.4.4), I have encountered problems while using ng-charts in my Angular application.

The specific issue I am facing is that ng-charts do not seem to work properly with TypeScript's latest version. I have followed the documentation and implemented the necessary configurations, but I am experiencing unexpected behavior and errors when using ng-charts components.
![ng-charts-issue](https://github.com/valor-software/ng2-charts/assets/30737217/0c911ba2-6094-4cfc-8f2e-c270669b08bd)

I have verified that the issue is related to TypeScript's latest version because when I downgrade TypeScript to an earlier version (e.g., 5.3.3), ng-charts functions as expected.

I would greatly appreciate it if the ng-charts team could investigate this compatibility issue and provide guidance or a fix to ensure that ng-charts works seamlessly with the latest TypeScript version. Please let me know if any further information or code examples are required to assist with troubleshooting and resolving this issue.

Thank you for your attention to this matter.

**Comment by markhus-aurelius** [comment]
Isn't it because you're using an unsupported typescript version in relation to your Angular version?

Like the error says?  **"The Angular Compiler requires Typescript >=5.2.0 and <5.4.0 but 5.4.4 was found instead?"**
