### ISSUE TITLE
Doesn't work 

### ISSUE THREAD

**Issue by lazywhite** [valor-software/ng2-charts#194]
I just can't configure this thing work with angular2-beta-17 and systemjs correctly , I already lost my faith

**Comment by jkeczan** [comment]
Never lose the faith lol. I have it working with systems and beta-17 right now. Mine is based off of this starter template:

[https://github.com/rogerpadilla/angular2-minimalist-starter](https://github.com/rogerpadilla/angular2-minimalist-starter)

To get it to load correct, I added this to the config file:

```
 js: [
        `${NM}/es6-shim/es6-shim.js`,
        `${NM}/systemjs/dist/system-register-only.src.js`,
        `${NM}/rxjs/bundles/Rx.js`,
        `${NM}/angular2/bundles/angular2-polyfills.js`,
        `${NM}/angular2/bundles/angular2.dev.js`,
        `${NM}/angular2/bundles/router.dev.js`,
        `${NM}/angular2/bundles/http.dev.js`,
        `${NM}/ng2-charts/bundles/ng2-charts.js`,
      ],
      copyOnly: [
        `${NM}/systemjs/dist/system-polyfills.src.js`,
        `${NM}/ng2-charts/bundles/ng2-charts.js`,
        `${NM}/ng2-charts/bundles/ng2-charts.js.map`,
        `${NM}/bootstrap/dist/css/bootstrap.css.map`
      ],
```

After that, I bootstrapped the CHARTS_DIRECTIVES in the client/boot.ts file and that was it.

**Comment by valorkin** [comment]
Thanks @jkeczan , updating lib to rc.1 and charts 2
