### ISSUE TITLE
Label property is missing for pie chart

### ISSUE THREAD

**Issue by faraz-ahmad-uft** [valor-software/ng2-charts#1943]
I want to display labels within the pie chart. How I can do that? I could not find any relevant tutorial for this.

![Screenshot 2024-05-08 at 4 10 26 PM](https://github.com/valor-software/ng2-charts/assets/110594522/17f32078-a68a-4c0e-b8d4-12f640561a53)

Following version are being used in the application.
"chart.js": "^4.4.2",
"ng2-charts": "^6.0.0",

**Comment by santam85** [comment]
The rendering of the chart is not done by this library, but by Chart.js. Their docs are found [here](https://www.chartjs.org/docs/latest/general/data-structures.html). I believe what you are looking for is the `labels` property for the options, or the dataset `label` property
