### ISSUE TITLE
Feature Request: Trend Lines

### ISSUE THREAD

**Issue by tehaaron** [valor-software/ng2-charts#20]
We are using ng2charts in our latest app and would really like an easy way to support trend lines on bar and line charts.

This is really the only reason we still have to send some clients data in another format rather than in our standard dashboard.

**Comment by valorkin** [comment]
hey, I see trends lines for line charts, but did not found for bar
http://valor-software.github.io/ng2-charts/

links to original doc will speed up their support in this module :)

**Comment by valorkin** [comment]
closing this, anyway such feature request should be in chart.js repo
