### ISSUE TITLE
Usage of chart crashes the whole page

### ISSUE THREAD

**Issue by lukazadel** [valor-software/ng2-charts#204]
dashboard:233 Error: Error: XHR error (404 Not Found) loading http://localhost:5555/dashboard/components/dashboard.component.js
	    at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:5555/node_modules/angular2/bundles/angular2-polyfills.js?1463398078789:830:30)
	    at ZoneDelegate.invokeTask (http://localhost:5555/node_modules/angular2/bundles/angular2-polyfills.js?1463398078789:423:38)
	    at Zone.runTask (http://localhost:5555/node_modules/angular2/bundles/angular2-polyfills.js?1463398078789:320:48)
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:5555/node_modules/angular2/bundles/angular2-polyfills.js?1463398078789:490:34)
	Error loading http://localhost:5555/dashboard/components/dashboard.component.js as "../../dashboard/components/dashboard.component" from 

This is the error thrown. chart installed with npm -i ng2-chart --save,

The code is same as used on the first example.

**Comment by Luchillo** [comment]
Did you installed chart.js an provided it to the app?

**Comment by valorkin** [comment]
XHR loading dashboard.js? Try to add Chart.js lib

**Comment by lukazadel** [comment]
Yep i did...

**Comment by lukazadel** [comment]
I did, but after your reply i guess i did it wrong. I'm using angular2-seed by mgechev. Any help on how to get the charts to work there would be greatly appriciated.

**Comment by valorkin** [comment]
I will update to rc.1 today and will get back to this question

**Comment by Luchillo** [comment]
Not much i can help, i have configured `ng2-charts` with `webpack` but `gulp`? may be simpler but idk how would it be done.

**Comment by valorkin** [comment]
oh, I am avoiding gulp lately, to much overhead for nothing I can not get with webpack

**Comment by valorkin** [comment]
updated to rc.1 and chart.js 2 BTW

**Comment by Luchillo** [comment]
Me too, trying to convert all projects in my company to webpack, the hardest one is the one where i used the ng2-charts because it uses both Ng1 and Ng2, the Ng1 code is legacy and is a MESS (Glad i used NgUpgrade to avoid touching that code and started re-creating the functionality with Ng2).
