### ISSUE TITLE
View doesnt exist anymore

### ISSUE THREAD

**Issue by Dzivo** [valor-software/ng2-charts#212]
Severity	Code	Description	Project	File	Line	Suppression State
Error	TS2305	Module '"/node_modules/angular2/core"' has no exported member 'View'.	TypeScript Virtual Projects\node_modules\ng2-charts\components\charts\charts.ts	2	Active

**Comment by valorkin** [comment]
oh, you are using something really outdated
please use latest ng2-charts
with ng2 rc.1 and chart.js2
