### ISSUE TITLE
Not a constuctor

### ISSUE THREAD

**Issue by Dzivo** [valor-software/ng2-charts#214]
TypeError: t.controllers[o.type] is not a constructor when trying to create 

    <base-chart *ngIf="!start"
                            class="chart"
                            [data]="doughnutChartData"
                            [labels]="doughnutChartLabels"
                            [legend]="true"
                            [chartType]="doughnutChartType"
                            (chartHover)="chartHovered($event)"
                            (chartClick)="chartClicked($event)"></base-chart>

**Comment by valorkin** [comment]
`doughnutChartType` what is value of this variable?
should be `doughnut`
BUT you are using not the latest version
please update

**Comment by valorkin** [comment]
I could guess that you are using old version of ng2-charts with latest chart.js
and ignoring peer  dependencies warning

**Comment by robotzaintlikeus** [comment]
I had the same issue. My `radarChartType `was `Radar` because an older version expected a capital letter, fixed it by re-naming it to `radar`.

**Comment by valorkin** [comment]
Yeap this is breaking change between chart.js 1 and 2
