### ISSUE TITLE
Documentation Typo (Colour) / Clarification

### ISSUE THREAD

**Issue by zprisk** [valor-software/ng2-charts#216]
Hello,

Just wanted to point out that the documentation is a little misleading with the usage of the word coloUr (with the U). Everything definitely uses "color".

Example 1:
<img width="919" alt="screen shot 2016-05-18 at 11 07 47 am" src="https://cloud.githubusercontent.com/assets/5308126/15366191/c474a2e6-1ce8-11e6-838e-34e9b5a45a3a.png">

Example 2:
<img width="698" alt="screen shot 2016-05-18 at 11 07 57 am" src="https://cloud.githubusercontent.com/assets/5308126/15366206/d7ad69ba-1ce8-11e6-82a4-47001876c0b6.png">

**Comment by valorkin** [comment]
can you PR typo fix?

**Comment by zprisk** [comment]
I have never actually done a PR before, but I believe I did it correctly. Let me know if I need to do something different.

**Comment by valorkin** [comment]
All cool thank you!
