### ISSUE TITLE
Tutorial is lacking

### ISSUE THREAD

**Issue by vaughansharman** [valor-software/ng2-charts#22]
I have been trying to set this up for a couple of days and still I am having no luck, I can't be the only one...

Is it possible to create a sample stand alone ng2 project along with a tutorial and put it on guthub? I know there is the demo folder but this does not really represent how a user might go about setting up a project from scratch and as a result makes it unclear as to why the project is not working...

**Comment by valorkin** [comment]
what about quick start? https://github.com/valor-software/ng2-charts#quick-start

and here some ng2 seeds: https://github.com/valor-software/ng2-bootstrap#starter-packages
or even simpler with ng2 quick start

**Comment by vaughansharman** [comment]
I have tried using the quick start links, perhaps the issue is because I am trying to use this with the ionic 2 framework, are you aware of anybody doing this successfully yet?

**Comment by valorkin** [comment]
oh, it is better to ask ionic guys or here:
https://gitter.im/valor-software/ng2-bootstrap
or here
https://gitter.im/angular/angular

**Comment by vaughansharman** [comment]
Thanks for your help, I will close this issue and chat on gitter

**Comment by valorkin** [comment]
keep me updated if some, I am thinking about tutorials anyway

**Comment by boyana86** [comment]
hey, valor wondering if you have any tutorial with ionic2... It would be appreciated alot!

**Comment by Luchillo** [comment]
I hope you don't really mean it, you know this was made for Ng2 so Ionic 2 isn't out of the question, i myself have implemented it in a production Ionic app, but since Ionic has been under so many changes and you have freedom in the bundle system, making a tutorial for it would go out of date very fast, and tackling each build system particularities is hard.

I think you're better asking in the Ionic forums for help, i did so since i'm using webpack instead of browserify and i can't change bundle systems now.

**Comment by boyana86** [comment]
ok let me revise my idea... I want to use a graphical js with ionic2 application but I couldn't find something stable (or let's say an applied example ) on internet so today I have countered with this ng2-charts.
As you have used, which one shall I use?

**Comment by Luchillo** [comment]
Ok let me tell you i tried with `D3`, found it hard to use and heavy, tried `C3` and it was a little bit easier to manage, but the size of bundle inflated a lot for a mobile app.

Next i was going to use Chart.js and i though it was pretty good, only a few charts (at least the most common ones) but was light and easy to use, then i got my hands on this repo and at start it had some issues but now i use it in 1 mobile app with Ionic 2 and 1 desktop app, it wraps Chart.js very good, integrates very good as an Ng2 component and the demo page explains most of the configs for all the charts, actually i think thats the docs and the actual docs are like supplementary lectures.

Anyway, the veredict, if you only need the common charts supported by `ng2-charts` (bar, line, radar, doughnut, polar, pie or a combination of those called `dynamic` chart) then use it, if it's any other chart not supported then you could try any other, D3 is OP or OK (Over Powered or Over Kill) unless you plan on making data visualization the main feature of the app.
