### ISSUE TITLE
Working with ng2-charts and angular2 2.0.0-beta.13

### ISSUE THREAD

**Issue by katsuragi545** [valor-software/ng2-charts#220]
I'm trying to incorporate ng2-charts to my Angular 2 app (I'm new to Angular 2 and ng2-charts). I'm currently using Angular2 version 2.0.0-beta.13. I've copied and pasted the line chart demo code straight from the demo website (I changed the ngFor lines to use '#' instead of 'let') into my project and nothing shows up but white lines. Is there a compatibility issue? Do I need to update/change anything (I've followed the installation instructions properly)?  My HTML produces this: 

![charts](https://cloud.githubusercontent.com/assets/19474503/15399609/3877841a-1d9d-11e6-84cd-8fce65a63273.png)

**Comment by katsuragi545** [comment]
Edit: Also, could someone clarify what exactly I need to do about the System.JS stuff during installation? The installation guide says "System.js bundles can be found in bundles directory of npm package or at npm cdn". What exactly am I supposed to do (sorry if this is a noob question but I just started learning Angular 2 a few days ago)?

**Comment by valorkin** [comment]
1. You will have to use angular2 rc.1
2. you don't have to use system.js (it is optional, you can use webpack or any other bundler)
