### ISSUE TITLE
Adding CHART_DIRECTIVES throws errors.

### ISSUE THREAD

**Issue by katsuragi545** [valor-software/ng2-charts#223]
Whenever I add CHART_DIRECTIVES to my list of directives in my @Component section I get several errors: 

`EXCEPTION: Error: Uncaught (in promise): No Directive annotation found on BaseChartComponent
browser_adapter.js:76

EXCEPTION: Error: Uncaught (in promise): No Directive annotation found on BaseChartComponentBrowserDomAdapter.logError @ browser_adapter.js:76
browser_adapter.js:76

STACKTRACE:BrowserDomAdapter.logError @ browser_adapter.js:76
browser_adapter.js:76

Error: Uncaught (in promise): No Directive annotation found on BaseChartComponent
    at resolvePromise (zone.js:538)
    at zone.js:515
    at ZoneDelegate.invoke (zone.js:323)
    at Object.NgZoneImpl.inner.inner.fork.onInvoke (ng_zone_impl.js:44)
    at ZoneDelegate.invoke (zone.js:322)
    at Zone.run (zone.js:216)
    at zone.js:571
    at ZoneDelegate.invokeTask (zone.js:356)
    at Object.NgZoneImpl.inner.inner.fork.onInvokeTask (ng_zone_impl.js:35)
    at ZoneDelegate.invokeTask (zone.js:355)BrowserDomAdapter.logError @ browser_adapter.js:76
zone.js:461

Unhandled Promise rejection: No Directive annotation found on BaseChartComponent ; Zone: angular ; Task: Promise.then ; Value: BaseExceptionconsoleError @ zone.js:461
zone.js:463Error: Uncaught (in promise): No Directive annotation found on BaseChartComponent(…)console

Error @ zone.js:463
core.service.ts:14CoreService:getVersion response: 0.1.0.0`

Does anyone know how to go about fixing this? This is my directives line:
`directives: [CHART_DIRECTIVES, NgClass, CORE_DIRECTIVES, FORM_DIRECTIVES]`

**Comment by valorkin** [comment]
your typescript configuration have to emit metadata
