### ISSUE TITLE
Bug is canvas size

### ISSUE THREAD

**Issue by snarum** [valor-software/ng2-charts#226]
I have made a small example illustrating how the ng2-charts v1.1 is creating wrong width/heigth on the canvas on a pie chart. In the example i use chart.js and ng2-chart side by side in similar divs, but the ng2-chart height is much smaller than the chart.js. Sadly I cant push my project to github due to firewall issues, but I'll attach the project files here.
![capture](https://cloud.githubusercontent.com/assets/5821202/15462287/fe593490-20c1-11e6-8c60-948ebac86fd1.PNG)

[testbench.zip](https://github.com/valor-software/ng2-charts/files/276910/testbench.zip)

**Comment by jhoralek** [comment]
Hi, I've got a similar issue with size of canvas. Here is a short video. http://screencast.com/t/Q6kToQIgxWY
It seems there is a bug around doughnut canvas resizing.

**Comment by jhoralek** [comment]
`options: {
       responsive: true,
}`
solved my issue.

**Comment by snarum** [comment]
I ended up writing my own typings for Chart.js for the methods that I needed.
