### ISSUE TITLE
(intermediate value)[this.chartType]

### ISSUE THREAD

**Issue by mohitook** [valor-software/ng2-charts#228]
Hello,

Could you help me? I have this issue when I am trying any of the charts... 
I didnt find any solution, so please help.

EXCEPTION: TypeError: (intermediate value)[this.chartType] is not a function in [pie in Home@32:24]

**Comment by mohitook** [comment]
My package.json:

Unfortunately I cant go higher with anguler versions...(for example rc1)

{
  "version": "1.0.0",
  "name": "ASP.NET",
  "private": true,
  "dependencies": {
    "angular2": "2.0.0-beta.15",
    "es6-promise": "^3.0.2",
    "es6-shim": "^0.35.0",
    "chart.js": "1.0.2",
    "ng2-charts": "1.0.0-beta.0",
    "reflect-metadata": "0.1.2",
    "rxjs": "5.0.0-beta.2",
    "systemjs": "0.19.6",
    "typings": "^1.0.4",
    "zone.js": "0.6.12"
  },
  "devDependencies": {
    "gulp": "^3.9.0"
  }
}

**Comment by alfakappa** [comment]
Could you update to "chart.js": "2.0.1",?

**Comment by valorkin** [comment]
and lower case chart types
