### ISSUE TITLE
Update problem with scatter chart

### ISSUE THREAD

**Issue by shenriksen4** [valor-software/ng2-charts#230]
I have a update problem with scatter chart:
data is initialized with some dummy xy-data => plot ok
data is changed first time  => plot updates ok
data is changed second time => Plot is not updated 
data is changed further => Plot is not updated

My dependencies:

dependencies": {
        "@angular/common": "2.0.0-rc.1",
        "ng2-charts": "^1.1.0",
        "chart.js": "^2.1.3",
        "chart.js-scatter": "^1.1.3"

**Comment by katsuragi545** [comment]
Out of curiousity - how did you create your ng2-chart with chart.js-scatter?

**Comment by BirgerK** [comment]
Any progress on this?

**Comment by softmodal** [comment]
For anyone else who finds this thread, by setting the borderColor to "transparent" in the colors directive I was able to make a line chart look like a scatter plot. I assume that a best-fit/trend line would need to be calculated outside of the library and provided as a second dataset.

**Comment by paviad** [comment]
This package now supports the `scatter` chart type. See this stackblitz https://stackblitz.com/edit/ng2-charts-scatter
