### ISSUE TITLE
Error TS2307: Cannot find module '@angular/core'.

### ISSUE THREAD

**Issue by cmyip** [valor-software/ng2-charts#231]
Changing line 1 of charts.d.ts from
`import { OnDestroy, OnInit, OnChanges, EventEmitter, ElementRef } from '@angular/core';`
to
`import { OnDestroy, OnInit, OnChanges, EventEmitter, ElementRef } from 'angular2/core';`

fixed this

**Comment by thorstenschaefer** [comment]
Are you using RC1? It should be @angular/core for the latest version afaik.

**Comment by cmyip** [comment]
yes, using latest version fixed this
