### ISSUE TITLE
Not plotting graph in browser

### ISSUE THREAD

**Issue by shreekantha** [valor-software/ng2-charts#232]
I have followed the steps , what was there in the ng2-charts docs.
I have used base-chart component, It's not giving me any error but  not showing any graph in the browser and even not adding canvas into base-chart div.
Please help me on this issue

**Comment by alfakappa** [comment]
Probably you need the css change as described here: https://github.com/valor-software/ng2-charts/issues/222#issuecomment-220463566

**Comment by shreekantha** [comment]
Thank you @alfakappa , problem resolved

**Comment by alfakappa** [comment]
YW
