### ISSUE TITLE
Chart.controllers[meta.type] is not a constructor

### ISSUE THREAD

**Issue by sam1019** [valor-software/ng2-charts#234]
I followed the instructions on the http://valor-software.com/ng2-charts/ and got this error.

**Comment by sam1019** [comment]
It turns out I typed "doughnut" as "Doughnut" with capital "D". :D :D :D :D :D

**Comment by nabilfreeman** [comment]
For anybody coming from Google who might have done what I did... If you are declaring the chart type directly in the HTML template I had to wrap it in double quotes.

```
<canvas baseChart class="chart"
				[datasets]="priceDataset"
				[chartType]='"line"'></canvas>
```

Note the `"line"` part. 😁
