### ISSUE TITLE
Angular2 Combo Charts Using chart.js

### ISSUE THREAD

**Issue by komalChandnani** [valor-software/ng2-charts#236]
Hello ,
How can we load a combo chart in angular2 using chart.js( Combination of bar and line chart)

**Comment by valorkin** [comment]
can you make a sample with chart.js 2 so I can work with something?
plunkr or codepen, thx

**Comment by shoudaos** [comment]
@valorkin 
Here it is.
http://plnkr.co/edit/TvY5tz?p=preview

**Comment by alyahmedaly** [comment]
any update on this

**Comment by valorkin** [comment]
busy with documentation at the moment

**Comment by invincible1388** [comment]
Any update or sample code snippet?

**Comment by mmiszy** [comment]
This would be so useful 👍

**Comment by zhaojunjie163** [comment]
Hi @valorkin are you working on this?

**Comment by dBer** [comment]
Any sample please??

**Comment by jas75** [comment]
Nothing ? Seems to be useful for many people !

**Comment by theunreal** [comment]
Looking for a support for this as well.

**Comment by prasanthtootcat** [comment]
Any updates?

**Comment by paviad** [comment]
This works out of the box, simply set the chart type to `line` on the relevant data set.

See this stackblitz for example: https://stackblitz.com/edit/angular-x36quh
