### ISSUE TITLE
Chart not rendering

### ISSUE THREAD

**Issue by jcford73** [valor-software/ng2-charts#246]
Trying with very simple, static test data:

    labels:Array<any> = ['1','2','3','4','5'];
    data:Array<number[]> = [[1,2,3,4,5]];
    chartType:string = 'line';
    options:any = {
        legendTemplate: "<div>Test</div>"
    };

    <base-chart class="chart chart-line"
                [data]="data"
                [labels]="labels"
                [options]="options"
                [legend]="true"
                [chartType]="chartType"
    ></base-chart>

The canvas element appears, but nothing is drawn and no error is reported to the console.

When I run an async process to retrieve real data for the chart and update the chart's bound properties I get this error:

"EXCEPTION: Error in app/features/dashboard/transcriptActivityChart.html:12:24↵ORIGINAL EXCEPTION: TypeError: this.chart.destroy is not a function↵ORIGINAL STACKTRACE:↵TypeError: this.chart.destroy is not a function↵    at BaseChartComponent.ngOnDestroy (http://localhost:8999/node_modules/ng2-charts/components/charts/charts.js:38:24)↵    at BaseChartComponent.refresh (http://localhost:8999/node_modules/ng2-charts/components/charts/charts.js:108:14)↵    at BaseChartComponent.ngOnChanges (http://localhost:8999/node_modules/ng2-charts/components/charts/charts.js:33:18)↵    at DebugAppView._View_TranscriptActivityChartComponent0.detectChangesInternal (TranscriptActivityChartComponent.template.js:200:59)↵    at DebugAppView.AppView.detectChanges (http://localhost:8999/node_modules/@angular/core/src/linker/view.js:200:14)↵    at DebugAppView.detectChanges (http://localhost:8999/node_modules/@angular/core/src/linker/view.js:289:44)↵    at DebugAppView.AppView.detectViewChildrenChanges (http://localhost:8999/node_modules/@angular/core/src/linker/view.js:220:34)↵    at DebugAppView._View_DashboardComponent0.detectChangesInternal (DashboardComponent.template.js:170:8)↵    at DebugAppView.AppView.detectChanges (http://localhost:8999/node_modules/@angular/core/src/linker/view.js:200:14)↵    at DebugAppView.detectChanges (http://localhost:8999/node_modules/@angular/core/src/linker/view.js:289:44)↵ERROR CONTEXT:↵[object Object]"

Any ideas?

**Comment by nikiben** [comment]
getting same error
