### ISSUE TITLE
Change point radius. 

### ISSUE THREAD

**Issue by katsuragi545** [valor-software/ng2-charts#250]
How do you go about changing the point radius of a point when you click or hover over it? I've found these values for the chart object that is returned when you click/hover on the chart. 

![matschartpointsettings](https://cloud.githubusercontent.com/assets/19474503/15867628/ffd12890-2c98-11e6-9284-42c9c3af8297.png)

I've tried setting the values for 'hitRadius' and 'radius'  for both the '_model' and '_view' parts but the chart point doesn't change at all. 

```
            e.active[0]._model.hitRadius = 5;
            e.active[0]._model.radius = 10;
            e.active[0]._view.hitRadius = 5;
            e.active[0]._view.radius = 10;
```

**Comment by Hongbo-Miao** [comment]
@aeacusvol is correct.
