### ISSUE TITLE
Responsive feature for a chart nested into a container

### ISSUE THREAD

**Issue by LPalmito** [valor-software/ng2-charts#253]
Hey!

I'm doing a dashboard with widgets, and one of these widgets is containing a chart. In order to display the dashboard properly:
- I'm using [angular2-grid](https://github.com/BTMorton/angular2-grid)
- the size of each widget depends on the size of the window (xs, sm, md, lg)
- but for a given window size, each widget's size is fixed

My issue is with the resizing of the chart when resizing the window:
- If I set the `responsive` feature to `true`, the chart is adapted to the width of the widget, but not to its height. Which results an unwanted behaviour when the window is too big: the width of the chart is adapted to the width of the widget, but the height of the chart is too big to fit the height of the widget.
- If I set the `responsive` feature to `false`, the chart is too small within the widget for certain sizes of screen.

The best solutions I've found so far are:
- Check the size of the window and change the height and width of the chart accordingly. But to do that I had to modify the source code, and that fix is then broken each time I pull a new version of ng2-charts.
- Check the size of the window and change the height and width style properties accordingly. But it results in a blurred chart, and I'm using jQuery, which is not really the best friend of Angular 2!

Ideally, I would like my chart to follow those 2 rules:
- The chart is fully contained into its widget container
- The chart's width is adapted to the widget's width, except if it makes it too big to respect the previous rule. In that case, the chart's width stops growing up/down when resizing and stays as it was before.

I would like to thank you for your work by the way, it helped me a lot in my project!

**Comment by Hongbo-Miao** [comment]
Hi @LPalmito Does this https://github.com/valor-software/ng2-charts/issues/319 help? And let me know.

**Comment by egervari** [comment]
I'm actually having the same problem, and I have included the basic css that is included. When responsive is false, I cannot set the height.

I'm also having a problem where the height properly fits the container when responsive is true, but then the height and width of the canvas is 0 when the component first loads

**Comment by egervari** [comment]
For what it's worth, the problem occurs when you put base-chart inside a flex container. In my case, there was justify-around being used, but getting rid of flex boxing solved the issue

**Comment by webgroup4business** [comment]
For the height issue, add maintainAspectRatio: false.

**Comment by paviad** [comment]
This package is updated for Angular 7. If this issue persists, please provide a stackblitz example.
