### ISSUE TITLE
Y Axis Tick Formatting

### ISSUE THREAD

**Issue by dylanidx20dichrisbr** [valor-software/ng2-charts#254]
Is there a way to format the Y axis tick mark lables?  I have numbers and would like to add a percent sign after the number.

**Comment by rahuja910** [comment]
+1

**Comment by Hongbo-Miao** [comment]
The working plnkr: 
http://plnkr.co/edit/hIsPY2LvB10i8qMZG4j3?p=preview

```ts
  private options = {
    scales: {
      yAxes: [{
        ticks: {
          beginAtZero: true,
          callback: function(label, index, labels) {
            return label/100+'%';
          }
        }
      }]
    }
  };
```

**Comment by jkoorts** [comment]
[Hongbo-Miao](https://github.com/Hongbo-Miao) 's solution does not work with latest version.

**Comment by Hongbo-Miao** [comment]
Hi @jkoorts maybe create a new issue ticket? 😃
(I didn't use this library any more)
