### ISSUE TITLE
Colors - Pie chart

### ISSUE THREAD

**Issue by Adwind** [valor-software/ng2-charts#263]
Sorry I am trying to put color like the Line chart example in a pie chart but i am unable it only takes the first color for all the pie part : 
![capture_5](https://cloud.githubusercontent.com/assets/9054739/16019925/9d125798-3179-11e6-90c1-d9fc163a8105.PNG)

Code html base-chart:  <base-chart class="chart"
           [data]="pieChartData"
           [labels]="pieChartLabels"
           [colors]="pieChartColor"
           [chartType]="pieChartType"
           (chartHover)="chartHovered($event)"></base-chart>

color array : pieChartColor:any = [
  { // blue
      backgroundColor: '#00285e'
    },
    { // purple
      backgroundColor: '#b4108b'
    },
    { // green
      backgroundColor: '#89ba17'
    }];

**Comment by Luchillo** [comment]
Check this comment about doughnut charts, it's almost the same input: https://github.com/valor-software/ng2-charts/issues/251#issuecomment-225581645

**Comment by Adwind** [comment]
Thank you

**Comment by Luchillo** [comment]
Then close the issue :) 👍
