### ISSUE TITLE
Bubble Chart possible?

### ISSUE THREAD

**Issue by RoxKilly** [valor-software/ng2-charts#270]
Chart.js [supports bubble charts](https://github.com/chartjs/Chart.js/blob/master/docs/08-Bubble-Chart.md), but your docs don't mention them. Is it possible to build a bubble chart with `ng2-charts`?  Any pointer to a working example would be great

note: cross-posted [on stackOverflow](http://stackoverflow.com/questions/37843632/how-to-make-chart-js-bubble-chart-with-ng2-chart)

**Comment by paviad** [comment]
This is definitely a desired feature - someone should take this :)

**Comment by paviad** [comment]
This package now supports bubble charts.

Closed by e72ac0c
