### ISSUE TITLE
Can't render chart

### ISSUE THREAD

**Issue by tuoitrexuquang** [valor-software/ng2-charts#275]
Dear all,
I tried implement the component but can't display chart in my browser
Only output: canvas style="width: 100%; height: 100%; and can't get anything to display in browse. i follow (http://valor-software.com/ng2-charts/#baseChart).
Please help me fix it. 
Thank you so much!

**Comment by Luchillo** [comment]
There's been an issue here about that, most likely is the lack of certain css property in the base chart:
```css
.chart {display: block; width: 100%;}
```

I don't remember which one does the trick, you can try each one by separate.

**Comment by Hongbo-Miao** [comment]
Duplicated with https://github.com/valor-software/ng2-charts/issues/229

**Comment by tuoitrexuquang** [comment]
Thank you so much, it's work fine now

**Comment by Hongbo-Miao** [comment]
You are welcome!
