### ISSUE TITLE
Unit test fails

### ISSUE THREAD

**Issue by omargon** [valor-software/ng2-charts#278]
Hi,

After successfully integrating the ng2-charts module I get the following 404 warning when I try to run my unit tests:

```
21 06 2016 15:44:55.759:WARN [web-server]: 404: /base/ng2-charts/ng2-charts.js
21 06 2016 15:44:55.760:WARN [web-server]: 404: /base/ng2-bootstrap.js
```

Am I missing any additional integration step(s)?

**Comment by paviad** [comment]
Closing - all tests pass now.
