### ISSUE TITLE
How can we change Chart.js attribute defaultFontColor	?

### ISSUE THREAD

**Issue by sandwichsudo** [valor-software/ng2-charts#283]
Hi, 
I am trying to change defaultFontColor as suggested here:http://www.chartjs.org/docs/#getting-started-colors
is that possible?
thanks

**Comment by sandwichsudo** [comment]
In particular, I'd like to change the options.ticks value in Charts.bundle.js (see line var optionTicks = me.options.ticks).

**Comment by alvarocasta** [comment]
same issue here. any idea? I haven't found any related info on the documentation.

**Comment by Shadowstep33** [comment]
Related info, though, these aren't working for me: http://www.chartjs.org/docs/latest/general/fonts.html

**Comment by mac10046** [comment]
is there any update in changing defaultFontColor using the config object or some ways ?

**Comment by paviad** [comment]
I believe this PR closes this https://github.com/valor-software/ng2-charts/pull/1068
