### ISSUE TITLE
UNMET PEER DEPENDENCY

### ISSUE THREAD

**Issue by funnytao** [valor-software/ng2-charts#285]
Hi,

I generated my project with Angular 2 CLI. Today I tried to install ng2-charts by npm but got these errors: 

+-- UNMET PEER DEPENDENCY @angular/common@2.0.0-rc.3
+-- UNMET PEER DEPENDENCY @angular/compiler@2.0.0-rc.3
+-- UNMET PEER DEPENDENCY @angular/core@2.0.0-rc.3
+-- UNMET PEER DEPENDENCY @angular/platform-browser@2.0.0-rc.3
+-- UNMET PEER DEPENDENCY @angular/platform-browser-dynamic@2.0.0-rc.3

I have updated npm and node but still can't solve it. Any thoughts please? Thank you so much.

Tao

**Comment by Luchillo** [comment]
Try `npm i` again, it should tell you which peer dependency isn't being met, paste the full npm output and please try and use code formatting, search it as  `markdown code format`.

**Comment by funnytao** [comment]
I fixed it with installing rc 2 version of these dependencies. Thank you.
