### ISSUE TITLE
Need ability to position legend

### ISSUE THREAD

**Issue by jkyoutsey** [valor-software/ng2-charts#294]
This is an enhancement request.
Charts.js shows that legend can be configured not only for on/off, but for position as well as other features.  It would be nice if [legend] was Object instead of boolean, allowing us to pass a config object that got passed to the core chart.

**Comment by brandonreid** [comment]
@jkyoutsey You can pass in those kinds of options in the `[options]`. 

Like..
```
public lineChartOptions:any = {
  animation: false,
  responsive: true,
  legend: {
    position: 'bottom'
  }
};
```

**Comment by mac10046** [comment]
its not working for me... I am not getting error but neither the legend position changes from top to left

**Comment by WouterVanherck** [comment]
Maybe [this issue thread](https://github.com/valor-software/ng2-charts/issues/519) can help you?

```
public barChartOptions:any = {
	legend: {position: 'bottom'}
}
```

Credit to @JanPeeters

**Comment by amirSohel007** [comment]
and how we can add legend title like total population this will be title
