### ISSUE TITLE
responsive: true and initial height calculation

### ISSUE THREAD

**Issue by philjones88** [valor-software/ng2-charts#299]
I have `<base-chart></base-chart>` inside a Bootstrap 3 page where they are inside a col-lg-6 columns with a fixed height of 350px.

However ng2-charts seems to default it somehow to 150px high and only resizes it to the full 350px when the page is resized.

I propose allowing fixed height to be set via adding a few lines like:

```
if (this.options && this.options.height) {
    this.cvs.height = this.options.height;
}

if (this.options && this.options.width) {
    this.cvs.width = this.options.width;
}
```

to:

https://github.com/valor-software/ng2-charts/blob/development/components/charts/charts.ts#L147

Maybe check if `maintainAspectRatio` is false too?

With those lines added I can pass in a height that overrides the default calculated one to my desired height.

**Comment by curlyfro** [comment]
+1

**Comment by erasethis** [comment]
+1

**Comment by Hongbo-Miao** [comment]
Does this https://github.com/valor-software/ng2-charts/issues/319 help? And let me know.

**Comment by philjones88** [comment]
Following a referenced issue I was able to fix this by:

```
<base-chart
   ....
   [style.height]="graph.height + 'px'"
   ....
   >
</base-chart>
```

And remove any height stuff from CSS like I had `height: auto !important;` inside a `.chart` rule. I left the `width: 100%` rule in though.

Also setting response to true and maintainAspectRatio to false
