### ISSUE TITLE
chart directives not found here as well

### ISSUE THREAD

**Issue by born2net** [valor-software/ng2-charts#31]
(12,9): error TS2305: Module '"C:/msweb/studioEnterprise/node_modules/ng2-charts/dist/index"' has no exported member 'CHART_DIRECTIVES'.

trying to include this project in http://ng2.javascriptninja.io
but can't seem to get it working with ng2 beta.1

using Webpack, but dont think matters...

regards

Sean

**Comment by born2net** [comment]
seems that npm version is outdated, can you please update?
reards

**Comment by born2net** [comment]
any news on npm? thx, Sean...

**Comment by ironmanwaring** [comment]
Were you able to resolve your issue?  I'm having the same one ATM, can't figure out what I'm doing wrong.

**Comment by mattjowens** [comment]
Same here. Any news?

**Comment by valorkin** [comment]
hi guys, seems I have found `good enough` methods to go with
please check this one https://github.com/valor-software/ng2-bootstrap#quick-start
feedback is appretiated
