### ISSUE TITLE
Charts dose not shows on main page

### ISSUE THREAD

**Issue by urielp** [valor-software/ng2-charts#323]
Hi,
i am facing issue presenting the basic line chart.
i used the example from the demo page and i am getting an empty table with no data or graphs:
![image](https://cloud.githubusercontent.com/assets/3310473/17077477/61a69270-50da-11e6-865c-de6854cf07f0.png)

i dont see any errors or missing imports.
what am i doing wrong ?

the only change ive made in the component code is this :
@Component({
    selector: 'line-chart-demo',
    templateUrl: 'app/line-chart-demo.html',
    directives: [CHART_DIRECTIVES, NgClass, CORE_DIRECTIVES, FORM_DIRECTIVES]
})
all the other is the same.

can you please advise?

**Comment by urielp** [comment]
Ok,
so i mange to present the data table
but still no luck with the graph
![image](https://cloud.githubusercontent.com/assets/3310473/17078077/50a32274-50f1-11e6-97f4-c456e4771b31.png)

any ideas?

**Comment by urielp** [comment]
i mange,
thanks anyway

**Comment by Rezguii** [comment]
Please urielp how can you resolve this behaviour

**Comment by Hongbo-Miao** [comment]
@Rezguii have u fixed the issue?

**Comment by urielp** [comment]
Hi,
sorry for the late response,
i have  changed the project back to angular 1  due to internal issues.
and once i switched it back i haven't faced the problem.
sorry that i could not assist

**Comment by Hongbo-Miao** [comment]
@urielp it is fine.

@Rezguii please track this issue https://github.com/valor-software/ng2-charts/issues/222 if you haven't solved it.

**Comment by Rezguii** [comment]
@Hongbo-Miao  thank you , it is ok
