### ISSUE TITLE
Access to the .toBase64Image() method

### ISSUE THREAD

**Issue by skamlet** [valor-software/ng2-charts#325]
Since ng2-charts is wrapping Chart.js, it would be great to have access to the chart.js' methods.
For example I need to be able to propose the chart as a downloadable image (`.toBase64Image()`) and I'm not sure it's currently achievable.

**Comment by paviad** [comment]
Sounds like a good feature, someone should pick this up :)

**Comment by paviad** [comment]
Done, you may now access `toBase60Image()` from the directive's API.

```typescript
@ViewChild(BaseChartDirective) chart: BaseChartDirective;
someFunc() {
  this.chart.toBase60Image();
  ...
```
