### ISSUE TITLE
Demo: Chart.js requires lowercase chart types

### ISSUE THREAD

**Issue by kyleledbetter** [valor-software/ng2-charts#331]
Great work btw!

I was getting this error:
```
t.controllers[o.type] is not a constructor chart.bundle
```

and it was a simple fix, change `Line` to lowercase `line`
here https://github.com/valor-software/ng2-charts/blob/master/demo/components/charts/line-chart-demo.ts#L60

**Comment by Hongbo-Miao** [comment]
@kyleledbetter thank you!
