### ISSUE TITLE
[SOLVED] Time Scale Chart - With auto-generated labels?

### ISSUE THREAD

**Issue by brandonreid** [valor-software/ng2-charts#333]
I'm trying to build a time series chart but in the real world, data doesn't line up on easy to extract labels like months (a data point may be mid month, or 2 in one month, etc).

Can the `[data]` input receive a date/value array and auto generate the x axis?

**Comment by brandonreid** [comment]
[SOLVED] Just pass the labels in as the date values in the data. Then in the chart options, [set the xAxis to a time type](http://www.chartjs.org/docs/#scales-time-scale). This will require you to modify the tooltip text and stuff, which can also be done in the options (this part untested yet).

**Comment by chrispickford** [comment]
Please can you explain better how you solved this? Maybe with some example code?

**Comment by sfeilmeier** [comment]
@chrispickford 
This is how we solved it (not the simplest example though... but it works)
options:
https://github.com/OpenEMS/openems/blob/develop/ui/src/app/edge/history/chart/soc/soc.component.ts#L80

labels
https://github.com/OpenEMS/openems/blob/develop/ui/src/app/edge/history/chart/shared.ts#L64

Screenshot:
https://github.com/OpenEMS/openems/blob/develop/doc/modules/ROOT/assets/images/ui-screenshots2.png

**Comment by anass130** [comment]
@sfeilmeier
hello my friend 
links don't work for me

**Comment by sfeilmeier** [comment]
@anass130: I updated my post with direct links to that historic state. Hope it helps.
