### ISSUE TITLE
No errors but Charts will not render...

### ISSUE THREAD

**Issue by born2net** [valor-software/ng2-charts#34]
So after several hours I was able to get all issues resolved and no errors.
But still no charts are rendered. For now I am forced to use ng-highcharts 
https://github.com/AngularShowcase/angular2-seed-ng2-highcharts

but if you ever find time and can take a look, would appreciate it:
Charting branch: https://github.com/born2net/studioEnterprise/tree/charting
and added to login panel:
https://github.com/born2net/studioEnterprise/blob/charting/src/comps/entry/LoginPanel.ts 
called MyChart
the project compiles via
git clone https://github.com/born2net/studioEnterprise.git (and switch to Charting branch after clone)
npm i
if you ever find time,
regards

Sean

**Comment by valorkin** [comment]
I will do my best

**Comment by born2net** [comment]
great tx
