### ISSUE TITLE
Chart canvas gets 0 width and 0 height

### ISSUE THREAD

**Issue by escarabin** [valor-software/ng2-charts#341]
Hi!

First of all, thank you very much for sharing this module.

However, I am facing an issue with it which is that I actually don't see any charts or any error log. Here is the HTML from the chart I created :
```
<base-chart
        class="chart"
        [datasets]="datasets"
        [labels]="labels"
        [options]="options"
        [chartType]="'line'">
</base-chart>
```

Here is the related TypeScript code (yep, taken from the demo) :
```
private datasets = [
        {
            label: "# of Votes",
            data: [12, 19, 3, 5, 2, 3]
        }
    ];

    private labels = ['Red', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange'];

    private options = {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero: true
                }
            }]
        }
    };
```

Here is the HTML result I get from the dev console : 
```
<base-chart class="chart" ng-reflect-datasets="[object Object]" ng-reflect-labels="Red,Blue,Yellow,Green,Purple,Orange" ng-reflect-options="[object Object]" ng-reflect-chart-type="line">
<iframe class="chartjs-hidden-iframe" style="width: 100%; display: block; border: 0px; height: 0px; margin: 0px; position: absolute; left: 0px; right: 0px; top: 0px; bottom: 0px;"></iframe>
<canvas style="width: 0px; height: 0px; display: block;" width="0" height="0"></canvas>
</base-chart>
```

Where did I go wrong here? Am I missing something?

Thank you very much in advance for your help

Cheers

**Comment by brandonreid** [comment]
@escarabin It's probably something to do with the container. Maybe your chart is in a component and you need to set it's selector as `display: block;`.

I set mine up to have a fixed height and responsive width by setting `maintainAspectRatio: false` in the options, then I set a height on `base-chart` in my styles.

**Comment by escarabin** [comment]
Indeed, thank you. I had to manually set a height for` base-chart` via CSS

**Comment by jmw5598** [comment]
I encountered this same issue.  The above solution didn't fix this for me.  I had a chart component where the template was simply just the `<canvas baseChart></canvas>`.  What fixed this was to simply wrap the canvas in a div `<div><canvas baseChart></canvas></div>`.  Just thought I'd add this as another possible solution.

**Comment by secretorange** [comment]
If the canvas tag is in a component you can use the following:

```
:host
{
    display: block;
}
```
