### ISSUE TITLE
Error : Chart.bundle.min.js:1 Uncaught SyntaxError: Unexpected token < 

### ISSUE THREAD

**Issue by Rahman-S-M** [valor-software/ng2-charts#346]
I'm working on angular2-meteor-typescript project. Getting this error in browser

Chart.bundle.min.js:1 Uncaught SyntaxError: Unexpected token <

**Comment by Hongbo-Miao** [comment]
@Rahman-S-M I am using Angular2-Meteor, it works well. Do you still have this issue?

**Comment by Hongbo-Miao** [comment]
close as not active
