### ISSUE TITLE
spanGaps support

### ISSUE THREAD

**Issue by gabrielruiu** [valor-software/ng2-charts#354]
I was playing around with a line chart, and came across an issue like #309 , which apparently should be solved by adding a ```spanGaps``` property to the dataset object:
```
 public data: any[] = [
    {data: [65, 59, null, 81, 56, 55, 40], label: 'My label', spanGaps: true},
  ];

```

I applied the property like in the example, but it doesn't seem to have effect.

So my question is:
Is there support for ```spanGaps``` in ```ng2-charts```? Or have I applied it incorrectly?

In the [documentation](http://valor-software.com/ng2-charts), in the Properties section under API, the ```datasets``` property description mentions only ```data``` and ```label``` as the supported values, but I'm not sure if they are indeed the only supported, or they are just given as an example, and the dataset configuration object is injected directly into Chart.js

**Comment by Hongbo-Miao** [comment]
It should work, check this plunkr:

http://plnkr.co/edit/1ncWQdLF4mC7yjPEY0Ks?p=preview
