### ISSUE TITLE
dynamic ng2-charts

### ISSUE THREAD

**Issue by ulou** [valor-software/ng2-charts#364]
Hello, 
is there any possibility to dynamically update chart (real time)? I trying to add new point and it not showing on the chart untill I resize window, is there any option to run redraw function manually?

https://plnkr.co/edit/fXQTIjONhzeMDYmAWTe1?p=preview

**Comment by Hongbo-Miao** [comment]
@ulou the link shows plunkr not found

**Comment by ulou** [comment]
Sorry, its looks like its somehow gone. Anyway I figure it out.

**Comment by Sfairet** [comment]
Hello,
I think, i have some problem. I just try update chart on run time with change dataset variable. 
http://plnkr.co/edit/gyCBnoQLehDgfcLntjuG?p=preview  - on click chart dataset changed, but chart not refreshed.
