### ISSUE TITLE
Refresh chart when binded dataset changes

### ISSUE THREAD

**Issue by Sfairet** [valor-software/ng2-charts#378]
Hello,
#364 
I think, i have some problem. I just try update chart on run time with change dataset variable. 
http://plnkr.co/edit/gyCBnoQLehDgfcLntjuG?p=preview - on click chart dataset changed, but chart not refreshed.

**Comment by Hongbo-Miao** [comment]
It is because Angular 2 change detection only runs when value or reference changes.
`datasets` is an array. Your way does not change the reference of the array.

So you can use `let data = this.datasets.slice();`.
The working demo:
http://plnkr.co/edit/m3fBiHpKuDgYG6GVdJQD?p=preview

**Comment by Sfairet** [comment]
@Hongbo-Miao sorry for false issue, i am new in Angular. Thank you for help.
But, on your example, chart refresh with blink. All points renders as new. On clear JS chart show animation for only changed data: https://plnkr.co/edit/QI3DyM6gKyY5kaYLrS9d?p=preview
If you can, please show,how i can get same effect?

**Comment by Hongbo-Miao** [comment]
@Sfairet no it is fine, we all new before.

For that, I saw DmitryEfimenko talked about that at that bottom in this [issue](https://github.com/valor-software/ng2-charts/issues/291).
Maybe related with https://github.com/chartjs/Chart.js/issues/1997?

**Comment by Sfairet** [comment]
@Hongbo-Miao yes, i read this. 
I dont try delete data, how in [1997](https://github.com/chartjs/Chart.js/issues/1997). I just try add point or change it. 
In this example on pure JS https://plnkr.co/edit/QI3DyM6gKyY5kaYLrS9d?p=preview chart don't redraw fully, it just animate adding data, as expected. On Angular chart redraw with blink. So, i don't think is issue for Chart.js...

**Comment by Hongbo-Miao** [comment]
@Sfairet I run out of ideas.

Would u mind creating an new issue, because that is a different issue. Thanks

**Comment by Sfairet** [comment]
@Hongbo-Miao ok, thank you!

**Comment by Hongbo-Miao** [comment]
You are welcome!

**Comment by Meiyananth** [comment]
How to update this data of the charts using angular 2? I will write the http service and i will subscribe it. after how to update the data set? any leads please
