### ISSUE TITLE
backgroundColor in datasets element has no effect

### ISSUE THREAD

**Issue by Sfairet** [valor-software/ng2-charts#382]
Property backgroundColor, borderColor, borderWidth in datasets element has no effect.

Pure JS: https://plnkr.co/edit/zJ3DSr9Oap6dkYqkG0LT?p=preview
ng-charts: http://plnkr.co/edit/fCdHHTKE7RAvHpBBxVZB?p=preview

Or exist another method to set colors?

**Comment by Hongbo-Miao** [comment]
Dup with https://github.com/valor-software/ng2-charts/issues/372

**Comment by Sfairet** [comment]
Thanks, it's works fine. 
I just read in http://valor-software.com/ng2-charts/ that "color" variable is "colour" (misprint?).

**Comment by Hongbo-Miao** [comment]
@Sfairet thanks
https://github.com/valor-software/ng2-charts/pull/383

**Comment by saxicek** [comment]
What is the point of having `colors` property anyway? I would prefer to configure it in chart.js directly - I had to go to ng-charts sources to see why my `backgroundColor` definition is not applied. And I set `gridLines` color in options so it would be more systematic approach to set it all as per chart.js spec.

My suggestion is to not overwrite `backgroundColor` if specified. Is it possible?

**Comment by alisalama** [comment]
You can do this by setting the [colors] attribute to an empty object, like so...

   lineChartColors: Array<any> = [{}];

then...

   [colors]="lineChartColors"

and then passing the colors in with the dataset as per the actual chartJS, like so...

      [{
            type: 'line',
            data: [0,1,2,3,4,5]
            label: this.name,
            borderColor: '#D65745',
            backgroundColor: '#D65745',
            pointBackgroundColor: '#D65745',
            pointBorderColor: '#fff',
            pointHoverBackgroundColor: '#fff',
            pointHoverBorderColor: '#D65745',
            radius: 0,
            fill: false
        }];
