### ISSUE TITLE
Is there any way to implement zooming & dragging features

### ISSUE THREAD

**Issue by achinigayanthika** [valor-software/ng2-charts#388]
Is there any way to implement zooming & dragging features ? I Googled lots unfortunately couldn't find a proper way to do it.

**Comment by paviad** [comment]
This is a *great* feature, someone should definitely pick this up!

**Comment by 1moere1** [comment]
any news on this?

**Comment by ndrake** [comment]
I've had some initial success using this plugin: https://github.com/chartjs/chartjs-plugin-zoom

**Comment by santam85** [comment]
Feature must be provided in the core Chart.js library or one of it's plugins. Closing this.
