### ISSUE TITLE
Doesnt seem to work with Angular2 AoT Compilation - Please add .metadata.json file with next release

### ISSUE THREAD

**Issue by naveedahmed1** [valor-software/ng2-charts#391]
Hi,

It seems that ng2-charts isn't compatible with Angular 2 Ahead of Time Compilation (AoT) in Angular 2 RC 6.

When I try to compile my project it throws below error:

`Error: Unexpected value 'CHART_DIRECTIVES' declared by the module 'AppModule'`

**Edit**

**Your might find below comments useful:**

https://github.com/angular/angular/issues/11262#issuecomment-244449696

https://github.com/angular/angular/issues/11262#issuecomment-244472000

https://github.com/angular/angular/issues/11262#issuecomment-244489405

Complete conversation (https://github.com/angular/angular/issues/11262)

Actually the Angular team suggest that library vendors should also ship **.metadata.json** files. These files are produced automatically by ngc.

**Comment by JBoothUA** [comment]
I have the .metadata.json but this still appears to be an issue?  can someone verify?

**Comment by paviad** [comment]
This package has been updated for Angular 7, with many bugs fixed and features added. I believe this issue is now resolved. If not, please provide a stackblitz/codepen/... example showing it.
