### ISSUE TITLE
Update peer dependency to RC 7

### ISSUE THREAD

**Issue by naveedahmed1** [valor-software/ng2-charts#401]
Since RC 7 is out, the peer dependency should to updated to avoid below warnings:

`ng2-charts@1.2.0 requires a peer of @angular/common@2.0.0-rc.6 but none was installed.`

**Comment by valorkin** [comment]
@naveedahmed1 nice reason for small PR :)

**Comment by beck24** [comment]
is there any way to force-install it in the meantime?  I'm still fairly newish to the npm world and I'm being blocked by:

```
npm ERR! peerinvalid The package @angular/common@2.0.0-rc.7 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer @angular/forms@0.2.0 wants @angular/common@^2.0.0-rc.4
npm ERR! peerinvalid Peer @angular/platform-browser@2.0.0-rc.7 wants @angular/common@^2.0.0-rc.7
npm ERR! peerinvalid Peer @angular/platform-browser-dynamic@2.0.0-rc.7 wants @angular/common@^2.0.0-rc.7
npm ERR! peerinvalid Peer @angular/router@2.0.0-rc.2 wants @angular/common@^2.0.0-rc
npm ERR! peerinvalid Peer ionic-angular@2.0.0-beta.9-201606271842 wants @angular/common@^2.0.0-rc.3
npm ERR! peerinvalid Peer ng2-charts@1.2.0 wants @angular/common@2.0.0-rc.6
```

**Comment by valorkin** [comment]
With npm 3 you can ignore peer dependencies errors, they actually optional

**Comment by beck24** [comment]
Well, I gave that a go and it didn't work.  They're don't appear to be optional

**Comment by sdornan** [comment]
Angular 2 final is out now.

**Comment by lhalver1** [comment]
Looking to use with Angular 2.0.0! Update would be super slick! I am getting blocked by

```
npm ERR! peerinvalid The package @angular/common@2.0.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer @angular/forms@2.0.0 wants @angular/common@^2.0.0
npm ERR! peerinvalid Peer @angular/platform-browser@2.0.0 wants @angular/common@^2.0.0
npm ERR! peerinvalid Peer @angular/platform-browser-dynamic@2.0.0 wants @angular/common@^2.0.0
npm ERR! peerinvalid Peer @angular/router@3.0.0 wants @angular/common@^2.0.0
npm ERR! peerinvalid Peer ng2-charts@1.2.0 wants @angular/common@2.0.0-rc.6
```

**Comment by jbgarr** [comment]
@lhalver1 I'm looking forward to the official update to ng2-charts too, but you should still be able to use the current version (v1.2.0) with Angular 2.0.0 (final release). I get the same errors you see when running npm install, but it still works.

**Comment by lhalver1** [comment]
@jbgarr Thanks dude! Sure enough that is right, get the error but it still works for me when running Angular 2.0 (final).

**Comment by willvincent** [comment]
It only 'still works' if you _already_ had everything installed from rc6.  However, if you are installing fresh (for example, a travis automated test/deploy scenario) it'll fail. So this isn't really a small annoyance, this is an urgent update that must happen before you can safely, reliably, migrate to the final angular 2.0.0 release.

**Comment by willvincent** [comment]
@valorkin / @natali-abyss -- Please prioritize updating peer dependency to the full angular 2.0.0 release. I cannot update my current codebase because this module causes build failure due to it's now outdated peer dependencies.

**Comment by valorkin** [comment]
Will be updated to final today

**Comment by willvincent** [comment]
@valorkin I didn't see an update happen yesterday.. have a new ETA when we can expect it? :)

**Comment by lhalver1** [comment]
@willvincent Looks like it got [updated](https://github.com/valor-software/ng2-charts/blob/development/package.json#L48)

**Comment by valorkin** [comment]
Yeap, it was :) I always writing to twitter about updates, tomorrow will be
filtering and closing issues. Now I am going to sleep :)
