### ISSUE TITLE
Pie chart not showing labels

### ISSUE THREAD

**Issue by alexlacasa86** [valor-software/ng2-charts#420]
I just updated to 1.3 and now my pie charts has _undefined_ (literally) labels.

I rolled back to 1.2 and they work perfectly.

**Comment by alexlacasa86** [comment]
It works now for 1.4.0 nicely. Thanks!

**Comment by nraboy** [comment]
Does something else need to be done to make this work?  When I define constant labels, they show up, but when I have dynamic labels created from API data, they show as undefined.

Any ideas?

**Comment by valorkin** [comment]
Refresh Chart, I didn't saw a method to redraw labels separately

**Comment by nraboy** [comment]
I applied the changes from here manually:

https://github.com/valor-software/ng2-charts/commit/7175c1edd8983d97022d3d36148cd112e5e5c54c

I noticed that those changes were not in the 1.4.0 version.  However once I added those changes it worked great.

My question now is, when will those changes appear in a versioned release?
