### ISSUE TITLE
Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by Hongbo-Miao** [valor-software/ng2-charts#424]
After updating from 1.2 to 1.3.

[This line of code](https://github.com/valor-software/ng2-charts/pull/416/files#diff-a9c21733d1dae126806a2430f417fd66R66) 
`this.chart.data.datasets = this.getDatasets();`
gives me error when I show chart:

> Cannot read property 'data' of undefined

Tring to reproduce the issue in plunker, got no luck so far...

**Comment by Hongbo-Miao** [comment]
Ok, I got some time to look into this.

The issue can be reproduced by adding a `setTimeout`.
```ts
setTimeout(() => {
  this.datasets = [{
    label: "# of Votes",
    data: [12, 19, 3, 5, 2, 3]
  }];
}, 100);
```
The issue is because of `[{ data: [] }];` in the beginning.

In 1.2, it works this way in a child component.
```ts
@Input() datasets: any[] = [{ data: [] }];
```
Then you can provide data later.

But 1.3, that way does not work any more. Since I am using ngrx/store, so I changed the way to give that default data in reducer:
```ts
const initialState = {
  datasets: [{ data: [] }]
};
```
At least, it works now, I will close now.

**Comment by blubberbo** [comment]
I just ran into this issue in my application as well, although I am not sure how to solve it in my case.

where exactly did you add the code above? To your code or the angular2 charts code?

thanks in advance

**Comment by Hongbo-Miao** [comment]
@blubberbo I am using ngrx/store, so I added it in the `initialState`, which makes sure `datasets` initial value is `[{ data: [] }]`.

**Comment by blubberbo** [comment]
ah, alright. I am not, I am passing a variable Widget to the ngFor the base-chart element is in. So basically, if I initialize the value `Widget.chart.data` to nothing, like this:

`Widget.chart.data = []`

before passing it onto the page, it should then work?

**Comment by Hongbo-Miao** [comment]
@blubberbo u need at least provide `[{ data: [] }]`, like this `Widget.chart.data = [{ data: [] }]`

**Comment by szykov** [comment]
+1 i run in the same issue.

I'm using rxjs observables with angular2 and even if i provide some default empty data fot chart.data i'm still facing errors.

code very basic:

```
this.myService.getMyData()
      .subscribe(value=> {
        this.ChartData = [
          { data: value.data1, label: 'data1' },
          { data: value.data2, label: 'data2' }
        ];
      });
```

Error: Cannot read property 'data' of undefined

**Comment by blubberbo** [comment]
@szykov great idea! молодец

**Comment by nniclas** [comment]
I'm also having this issue, although not with using initial data.
When updating the chart, data including label count, I'm using ViewChild / chart.ngOnChanges().
issue ref here: #692

This works when going from a set of series to higher count, but not the other way, it throws a data undefined error. 

specifically here:
```
BaseChartDirective.prototype.updateChartData = function (newDataValues) {
	        if (Array.isArray(newDataValues[0].data)) {
	            this.chart.data.datasets.forEach(function (dataset, i) {
	                dataset.data = newDataValues[i].data;
	                if (newDataValues[i].label) {
	                    dataset.label = newDataValues[i].label;
	                }
```
(current "datasets" array count differ from newDataValues)

Any ideas of a workaround to this?

**Comment by nponna** [comment]
@nniclas Im facing the same issue too. Let me know if you have found any workarounds.

**Comment by nponna** [comment]
@valorkin Are you guys planning to handle dynamic labels and dynamic sizes of datasets anytime in the future for ng2-charts?

**Comment by nniclas** [comment]
@nponna Unfortunately I don't have any solid workaround, although I did modify updateChartData() in ng2-charts.js 

from
```
	    BaseChartDirective.prototype.updateChartData = function (newDataValues) {
	        if (Array.isArray(newDataValues[0].data)) {
	            this.chart.data.datasets.forEach(function (dataset, i) {
	                dataset.data = newDataValues[i].data;
	                if (newDataValues[i].label) {
	                    dataset.label = newDataValues[i].label;
	                }
	            });
	        }
	        else {
	            this.chart.data.datasets[0].data = newDataValues;
	        }
	    };
```
to
```
	    BaseChartDirective.prototype.updateChartData = function (newDataValues) {
	        if (Array.isArray(newDataValues[0].data)) {
	            this.chart.data.datasets.forEach(function (dataset, i) {
	                if (newDataValues[i]) {  // skip if new array count is lower
	                    dataset.data = newDataValues[i].data;
	                    if (newDataValues[i].label) {
	                        dataset.label = newDataValues[i].label;
	                    }
	                }
	            });
	        }
	        else {
	            this.chart.data.datasets[0].data = newDataValues;
	        }
	    };
```
this seems to work without any errors and side effects, (so far..)

I have no experience in extending and modifying libraries, appreciate if anyone could guide me how to override this function?

**Comment by nniclas** [comment]
Ok so I solved this, I just added a file and referenced BaseChartDirective from ng2-charts, had to require ng2-charts..
```
 var ng2charts = require('ng2-charts');
    ng2charts.BaseChartDirective.prototype.updateChartData = function (newDataValues) 
    { // new code }
```
this fix works and builds with webpack

**Comment by nchandna** [comment]
i am facing the same issue "(current "datasets" array count differ from newDataValues)",changing in charts.js works for me but i dont want to change that.
can you provide the alternative way in detail @nniclas .
i am not getting your below mentioned solution(As i am new to charts.js) it is giving require not found and many issues :
 var ng2charts = require('ng2-charts');
    ng2charts.BaseChartDirective.prototype.updateChartData = function (newDataValues) 
    { // new code }

can you provide the way to override the existing code of updateChartData  in my solution or component itself.

**Comment by tinyweasel** [comment]
I'm having the same issue moving to a dataset with less values, overwriting updateChartData didn't work, destroying the chart instance doesn't work. Any plans for a fix?

**Comment by joe20123** [comment]
szykov's solution is great. use the following should work:
"<div *ngIf="chartData[0].data.length>0" ...

**Comment by lula** [comment]
Hello! I was having the same problem (I guess). Dataset is refreshed from `ngOnChanges` method. Dataset can be filtered and after reducing the number of data the error `Cannot read property 'data' of undefined` was thrown. 

I came to the @szykov solution `*ngif..` as well 

```
<div *ngIf="barChartData.length > 0">
  <canvas
    baseChart 
    [datasets]="barChartData" ...
```

However that wasn't enough for me. What I did as a workaround to properly refresh the chart is clear the barCharData and wait a tick to refresh dataset: 

```
ngOnChanges(changes) {
  this.barChartData = [];
  Promise.resolve(true).then(() => this.refresh());
}

refresh() {
  this.barChartData = ...
}
```

**Comment by hamzahalvanaa** [comment]
Hi, I have data like this

`dataCharts = [{"value":54,"ru":"R201","area":"HCC"},{"value":1,"ru":"R401","area":"HOC"},{"value":3,"ru":"R401","area":"LWSR"}];
`

`  getStatsMonthly() {
    this.authProvider.getDataChartMonthly().then(data => {
      this.dataCharts = data;
      this.datasetMonthly = [];
      let res = [];
      let dataValue: any = [];
      dataValue = [];

      res = Object.values(this.dataCharts.reduce((obj, curr) => {
      if (!obj[curr.ru]) obj[curr.ru] = {ru: curr.ru, area: [],value:[]};
        // push the current name into the current time entry
        obj[curr.ru]['area'].push(curr.area);
        obj[curr.ru]['value'].push(curr.value);
        return obj;
      }, {}));

      for (let a of res) {
        // Get label chart data
        this.labelMonthly.push(a.ru);
      }

      for (let a of res) {
        for (let r of a.area) {
          // Get data area
        }
        const reducer = (values, currentValue) => values + currentValue;
        // Get data value
        setTimeout(() => {
          this.datasetMonthly.push(a.value.reduce(reducer));
        }, 300);
      }
    });
  }
`

The error says ERROR TypeError: Cannot read property 'data' of undefined, could someone help this?

**Comment by mamedshahmaliyev** [comment]
just use: 
this.lineChartLabels = this.lineChartLabels.slice(0); 
this.lineChartData[0]['data'] = this.lineChartData[0]['data'].slice(0);;

**Comment by ikomangmahendra** [comment]
> +1 i run in the same issue.
> 
> I'm using rxjs observables with angular2 and even if i provide some default empty data fot chart.data i'm still facing errors.
> 
> code very basic:
> 
> ```
> this.myService.getMyData()
>       .subscribe(value=> {
>         this.ChartData = [
>           { data: value.data1, label: 'data1' },
>           { data: value.data2, label: 'data2' }
>         ];
>       });
> ```
> 
> Error: Cannot read property 'data' of undefined
> 
> UPDATE:
> okey i just solved it with technic of using *ngIf. I hide chart component till i get data and then show it.

Finally after struggling for a half day with this issue. Why ng2chart doesn't provide this example? Many thanks brotha!!!

**Comment by dennis-zhang-va** [comment]
> @blubberbo u need at least provide `[{ data: [] }]`, like this `Widget.chart.data = [{ data: [] }]`

thanks! but I have to say this is not good at all

**Comment by Sujoykar97** [comment]
> +1 i run in the same issue.
> 
> I'm using rxjs observables with angular2 and even if i provide some default empty data fot chart.data i'm still facing errors.
> 
> code very basic:
> 
> ```
> this.myService.getMyData()
>       .subscribe(value=> {
>         this.ChartData = [
>           { data: value.data1, label: 'data1' },
>           { data: value.data2, label: 'data2' }
>         ];
>       });
> ```
> 
> Error: Cannot read property 'data' of undefined
> 
> UPDATE:
> okey i just solved it with technic of using *ngIf. I hide chart component till i get data and then show it.

You could have also put the chart code inside the subscribe method itself. So that it could render the chart after gettting data. All of this in the chart component ts file.

**Comment by cmsImagine** [comment]
I was getting this issue when providing labels initially in the labels property then later assigning dataset with elements that also had a labels.

**Comment by james-chege** [comment]
This worked for me `[datasets]="[{ data: [] }] || chartData.datasets` It is like having an initial state before the actual data pops in.

**Comment by Mr-Tuntun** [comment]
> @blubberbo u need at least provide `[{ data: [] }]`, like this `Widget.chart.data = [{ data: [] }]`

Thanks. This works perfectly.
