### ISSUE TITLE
Stacked charts

### ISSUE THREAD

**Issue by Kaizeras** [valor-software/ng2-charts#433]
Is it possible to create a stacked bar chart?

**Comment by bialad** [comment]
I had this issue as well, but managed to figure it out. It's even in the README. :)

**Properties**

- ...
- options (?any) - chart options (as from Chart.js documentation)

So you can customize these charts according to the chart.js [documentation](http://www.chartjs.org/docs/#bar-chart-chart-options) by using the options binding. You get a stacked bar chart by putting this `scales` object in the `options` object that's bound to the view:

  ```
options = {
  scales: {
    xAxes: [{
      stacked: true
    }],
    yAxes: [{
      stacked: true
    }]
  }
};
```

**Comment by Kaizeras** [comment]
Thanks!

**Comment by Hongbo-Miao** [comment]
thanks @bialad for help!
