### ISSUE TITLE
Can't bind to 'charttype' since it isn't a known property of 'base-chart'. (Angular 2.0.1)

### ISSUE THREAD

**Issue by amartone** [valor-software/ng2-charts#436]
Hi,

I am using:
- Angular 2.0.1
- Chart.js 2.3.0
- ng2-charts 1.3.0

While testing out the line chart example here http://valor-software.com/ng2-charts/, I am running into the following issue:

![image](https://cloud.githubusercontent.com/assets/1809105/19017938/e09f4a2a-881d-11e6-9c9c-517197caa855.png)

I have already included the ChartsModule as follows:
```
import { ChartsModule } from 'ng2-charts/ng2-charts';

// In your App's module:
imports: [
   ChartsModule
]
```

And `chart.js` in my index.html:
`<script src="node_modules/chart.js/src/chart.js"></script>`

Any ideas? Thank you in advance!

**Comment by amartone** [comment]
This might be related 
https://github.com/angular/angular/issues/10618

**Comment by amartone** [comment]
Resolved: 

The issue happens when 'chartType' is all lowercase.
 
This HTML to Jade converter http://html2jade.org/ converted 'chartType' to 'charttype'.

**Comment by mchamo** [comment]
Sorry, I may be missing something, what was the fix here?

**Comment by amartone** [comment]
@mchamo the fix was making sure the properties were correctly capitalized.

 i.e. `chartType` and not `charttype`.

**Comment by mcheung610** [comment]
I have the same problem too. Given we already know the problems, can someone suggest a possible fix for this?
