### ISSUE TITLE
Height on canvas isn't working on 1.4.0

### ISSUE THREAD

**Issue by rafaelss95** [valor-software/ng2-charts#454]
Before (in 1.3.0) I was able to adjust the height of chart with the following code:

**CSS:**

```
.chart {
  display: block;
}

.bar-chart {
  height: 420px;
}
```

**TS:**

```
this.barChartOptions = {
  scaleShowVerticalLines: false,
  responsive: true,
  maintainAspectRatio: false
}; 
```

**HTML:**

```
<base-chart class="bar-chart"
  [chartType]="barChartType"
  [options]="barChartOptions"
  [legend]="barChartLegend"
  [labels]="barChartLabels"
  [datasets]="barChartData"></base-chart>
```
**Now**, I have the code below after update to _1.4.0_ and the chart isn't being adjusted.
```
<div class="chart">
  <canvas baseChart class="bar-chart"
    [chartType]="barChartType"
    [options]="barChartOptions"
    [legend]="barChartLegend"
    [labels]="barChartLabels"
    [datasets]="barChartData"></canvas>
</div>
```
How can I adjust the height in the new version?

**Comment by rafaelss95** [comment]
Does anyone have a solution for this? I would appreciate any help. Thanks.

**Comment by paulo-santos** [comment]
I have the same issue with 1.4.0.
I placed just a simple <canvas> without graph data and it uses de defined height.  

When I add the baseChart directive, the graph takes all the height of the window.
My css rules look like yours.

**Comment by paulo-santos** [comment]
I think that this is not an issue with ng2-charts but with Chart.js
I added `maintainAspectRatio: false` to the chart options and now I'm able to control the size as I want. Otherwise it would always draw the chart based on widht

**Comment by rafaelss95** [comment]
Yes, it works @paulo-santos . Thanks.
