### ISSUE TITLE
UglifyPlugin breaks ng2-charts

### ISSUE THREAD

**Issue by msegers** [valor-software/ng2-charts#462]
I can't really find out why, but i'll put this one out here simply, when I compile my webpack project for production (with UglifyPlugin of course) ng2-chart stops working, I get a: t.each is not a function wheras our components don't use any mention of each. (could be foreach might be wrong).

So to reproduce you just create a webpack project with uglify and try to use your ng2-charts!

**Comment by anthony-pinskey** [comment]
Hey there!

Are you sure it's ng2-charts specific or actually with Angular2? Do you still get errors if you uglify/mangle with the ng2-charts module not rendered in your project? I had an issue with uglify causing issues with my Angular2 project, but it turned out not to be specific to this module.

**Comment by msegers** [comment]
Hey iT compiles but throws th error only when I access a page which shows the chart.

**Comment by msegers** [comment]
Without uglyfy it works using that for now

**Comment by zbarbuto** [comment]
Sorry to grave-dig and old issue but FWIW I was having issues with uglify when using ng2-charts.

After chasing dependencies I found the actual issue to be in color-convert:

https://github.com/Qix-/color-convert/pull/49

After making this change uglify builds were working again.

**Comment by paviad** [comment]
This package is now updated for Angular 7. The demo app is built with the Angular CLI `--prod` flag which uses uglify. If this issue persists, please provide a codepen/stackblitz/... example showing the issue.
