### ISSUE TITLE
Tooltip outside visible region

### ISSUE THREAD

**Issue by blubberbo** [valor-software/ng2-charts#470]
Hi,

I am using the most recent version of the Chart.js libray and I am getting a behavior on certain bar charts where the tooltip extends outside of the visible area. On small bar charts and line charts, the tooltips on the edge are displayed correctly, but on the larger bar charts, the tooltip hangs over the edge (see screenshots below):

![image](https://cloud.githubusercontent.com/assets/17286750/19456156/0ae87596-9475-11e6-81ac-367f07c20eb2.png)
![image](https://cloud.githubusercontent.com/assets/17286750/19456179/1d5c2b28-9475-11e6-9106-5a8b53cd9a22.png)
![image](https://cloud.githubusercontent.com/assets/17286750/19456195/28d07ba8-9475-11e6-9fcc-63e76f040257.png)

Does anyone have any idea what might be causing this to point me in the right direction?

Thank you in advance!

**Comment by Hongbo-Miao** [comment]
it is an issue of Chart.js, fixed in https://github.com/chartjs/Chart.js/pull/3476
