### ISSUE TITLE
Typings for Typescript

### ISSUE THREAD

**Issue by gvillo** [valor-software/ng2-charts#473]
I want to ask you where I can find the typings to use this with Angular2 using Typescript? 

I couldn't find it here > https://github.com/DefinitelyTyped/DefinitelyTyped

Thanks!

**Comment by gvillo** [comment]
I found them > https://github.com/DefinitelyTyped/DefinitelyTyped/tree/types-2.0/chartjs

**Comment by Hongbo-Miao** [comment]
You don't need install any typing file separately using this package
