### ISSUE TITLE
How to change size of responsive chart?

### ISSUE THREAD

**Issue by georgeedwards** [valor-software/ng2-charts#476]
I want to set the height of my chart to be a percentage of it's containing div. How do I do this? 
It's such a simple question, but if I set the chart `responsive: false`, then I can stretch it but it is out of proportion, as the underlying height and width are already set. 
If I set it as `responsive: true` then the chart will spill out of the containing div and fill the screen. 
If I set the containing div's CSS to `contain: content`, then I can just see the top of the graph. 

What should I do?

**Comment by victorcarvalhosp** [comment]
Same question here... Some solution?

**Comment by sridharan31** [comment]
any solution ?

**Comment by gufi** [comment]
specificly for this and the line chart ( although a bit wonky ) was to set the height in css on the canvas, width is still a but uncontrolable. setting width will draw the plot far too large on the canvas using the width and height inputs were no help either

**Comment by norberteder** [comment]
Is there any solution for this issue?

**Comment by AlwaysAbhl001** [comment]
Any work around ?

**Comment by masiorama** [comment]
I'm facing this issue too.

**Comment by paviad** [comment]
Please see this stackblitz for a possible solution: https://stackblitz.com/edit/ng2-charts-dynamic-height
