### ISSUE TITLE
Doughnut Chart Click event returns label as "Label 0" always?

### ISSUE THREAD

**Issue by georgeedwards** [valor-software/ng2-charts#489]
**Reproduction of the problem**

If I click on a bar chart for example, the event triggered in a `onClick(e)` function, I can do `e.active[0]._model.label` and get the label of the clicked data point. However, on doughnut chartjs this always returns "Label 0".

To reproduce:
1.  Go to the project [site](http://valor-software.com/ng2-charts/)
2.  Navigate to the doughnut graph 
3.  Open Chrome (or other browser) dev tools and look at the console
4.  Click on a data point
5.  Expand the path and observe that the label reported dis not correct

**Comment by mjharper84** [comment]
I have this issue also

**Comment by JonatanPotrikus** [comment]
I have also the same problem, some solution ?

My issue is chart Pie.

**Comment by kowach** [comment]
I found the solution on [https://stackoverflow.com/questions/26257268/click-events-on-pie-charts-in-chart-js](url)

    public chartClicked(e: any): void {
      if (e.active.length > 0) {
        const chart = e.active[0]._chart;
        const activePoints = chart.getElementAtEvent(e.event);
        if ( activePoints.length > 0) {
          // get the internal index of slice in pie chart
          const clickedElementIndex = activePoints[0]._index;
          const label = chart.data.labels[clickedElementIndex];
          // get value by index
          const value = chart.data.datasets[0].data[clickedElementIndex];
          console.log(clickedElementIndex, label, value)
        }
      }
    }

And then use/remap `label` for your stuff.

**Comment by hamzahalvanaa** [comment]
@kowach how to use/remap label based on chart data?

**Comment by kowach** [comment]
@hamzahalvanaa you do something like this

    ...
    const clickedElementIndex = activePoints[0]._index;
    const label = chart.data.labels[clickedElementIndex];
    // get value by index
    const value = chart.data.datasets[0].data[clickedElementIndex];
    console.log(clickedElementIndex, label, value)
    ...
    // you have chart labels and other properties in this.myLabels
    for ( const m of this.myLabels] ) {
        if ( m.label === label ) {
            this.loadChartData( m.labelId );
        }
    }

I'm using it for data drill down.

**Comment by twenceb** [comment]
I tried chart click events for days in vain. Any help below?

<canvas id="chart1"  width="400" height="300"/>
                        <script>
                            var ctx = document.getElementById("chart1");
                            var chart1 = new Chart(ctx, {
                                type: 'bar',
                                data: {
                                    labels: [#{dashboardBean.yearsSalesByYear}],
                                    datasets: [{
                                            label: 'Yearly Sales',
                                            data: [#{dashboardBean.amountSalesByYear}],
                                            backgroundColor: 'lightsalmon',
                                            borderColor: 'lightsalmon',
                                            borderWidth: 1
                                        }]
                                },
                                options: {
                                    legend: {
                                        display: true
                                    },
                                    tooltips: {
                                        mode: 'label',
                                        label: 'mylabel',
                                        callbacks: {
                                            label: function (tooltipItem, data) {
                                                return tooltipItem.yLabel.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
                                            }}
                                    },
                                    scales: {
                                        yAxes: [{
                                                ticks: {
                                                    beginAtZero: true,
                                                    callback: function (value, index, values) {
                                                        if (parseInt(value) >= 1000) {
                                                            return value.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
                                                        } else {
                                                            return value;
                                                        }
                                                    }
                                                }
                                            }]
                                    }
                                }
                            });
                            ctx.addEventListener('click', function (evt) {
                                var activePoints = chart1.getElementsAtEvent(evt);
                                var activeDataSet = chart1.getDatasetAtEvent(evt);
                                alert("activePoints:" + activePoints.length);
                                if (activePoints.length > 0)
                                {
                                    var clickedDatasetIndex = activeDataSet[0]._datasetIndex;
                                    var clickedElementIndex = activePoints[0]._index;
                                    var value = chart1.data.datasets[clickedDatasetIndex].data[clickedElementIndex];
                                }
                            }, false);
                        </script>

**Comment by paviad** [comment]
@twenceb This is not Angular code... I refer you to https://github.com/chartjs/Chart.js/issues
