### ISSUE TITLE
this.lineChartLabels cannot be updated

### ISSUE THREAD

**Issue by wsjwong** [valor-software/ng2-charts#49]
In the line chart example, user could click randomize and change the data by `this.lineChartData = _lineChartData;`. This is working.

However, if I try to update the labels with the same way
`var _lineChartLabels = ['December', 'February', 'March', 'April', 'May', 'June', 'July'];
this.lineChartLabels = _lineChartLabels;`
This is not working.

Is labels supposed to be unchangeable or is this a bug? Thank you.

**Comment by tianjy15** [comment]
@wsjwong  I have the same issue  
could you tell me how do you resolved

**Comment by wsjwong** [comment]
Currently, I am using array push to update the data in it

`this.lineChartLabels = []`
```       
for (i = 0; i < date.length; i++) {
  this.lineChartLabels.push(date[i])
}
```

**Comment by tianjy15** [comment]
@wsjwong  
I also have the same issue?  
Is the data from server？ If the data from server , I can't update the Pie?   
Please help me to see !
such as 
  var url=" /api/product/"+this.productId+"/versionState";
        this._http.get(url).subscribe((res: Response) => {
            this.versionStateList = res.json();
            for(var i=0; i<this.versionStateList.length; i++){
                var versionState = this.versionStateList[i];
                this.pieChartLabels.push(versionState.versionName);
                this.pieChartData.push(versionState.buildNumber);
            }
        });

**Comment by wsjwong** [comment]
I think your code could work, though I am using `this.lineChartData = _lineChartData` for data instead of push.

Please format your code with markdown next time.

**Comment by tianjy15** [comment]
Thank you, I'v resolved ! that base-chart shows  after data fromat!  just add a *ngIf
