### ISSUE TITLE
Update documentation import instructions

### ISSUE THREAD

**Issue by AryanJ-NYC** [valor-software/ng2-charts#490]
The README.md instructions for import on the GitHub page does not match the import instructions [here](http://valor-software.com/ng2-charts/).

**Comment by sandikbarr** [comment]
I had to include `node_modules/chart.js/dist/Chart.js` rather than `<script src="node_modules/chart.js/src/chart.js"></script>` as shown in the documentation. I am using angular-cli, so in angular-cli.json, I have `"scripts": [
  "../node_modules/chart.js/dist/Chart.js"
]`

**Comment by AryanJ-NYC** [comment]
I can second the problem @sandikbarr ran into.

**Comment by sandikbarr** [comment]
Sorry if I'm missing something here, but `<script src="node_modules/chart.js/src/chart.js"></script>` is still in the README. I found that I needed to use the dist/Chart.js file.
