### ISSUE TITLE
How to use Chart.plugins with Ng2-chart?

### ISSUE THREAD

**Issue by jrvaroni** [valor-software/ng2-charts#496]
exemple:

Chart.pluginService.register({
  beforeDraw: function(chart) {
    var width = chart.chart.width,
        height = chart.chart.height,
        ctx = chart.chart.ctx;

    ctx.restore();
    var fontSize = (height / 114).toFixed(2);
    ctx.font = fontSize + "em sans-serif";
    ctx.textBaseline = "middle";

    var text = "75%",
        textX = Math.round((width - ctx.measureText(text).width) / 2),
        textY = height / 2;

    ctx.fillText(text, textX, textY);
    ctx.save();
  }
});

**Comment by jrvaroni** [comment]
up

**Comment by cnd5041** [comment]
I tried to answer this here FYI: http://stackoverflow.com/questions/41863305/how-do-i-use-plugins-in-ng2-charts/41987023#41987023

It allowed me to use Chart.pluginService.register which is what I needed.

**Comment by olivermuc** [comment]
Here is my workaround: #752
