### ISSUE TITLE
refresh data

### ISSUE THREAD

**Issue by mrJungle** [valor-software/ng2-charts#498]
hi to all, 
i hope is the right place to ask little help.

i follow the installatio/demo guide and now i have an amazing bar-chart on my angular2 testApp :-) !
But i don't understand how i can refresh the module to update the data.

I put a button to trigger the function "updateData()" but it update only the label in the graph.
The data value in valriable "this.data" is update, but in the graph still remain the old one. 
Only if i reload all the view using the side-menu or resizing it change.

**Comment by mrJungle** [comment]
i understand my error.

**Comment by Cacanny** [comment]
> i understand my error.

Please explain what you did, this is so annoying and similar to 'I found the solution' - and then not explaining how leaving people guessing.
