### ISSUE TITLE
Disable tooltip

### ISSUE THREAD

**Issue by victorcarvalhosp** [valor-software/ng2-charts#500]
I need to hide the tooltip, and found this solution for chart.js `Chart.defaults.global.tooltipenabled = false;`

http://stackoverflow.com/questions/36953558/hide-disable-tooltips-chart-js

how can I do that on ng2-charts?

**Comment by Herbis** [comment]
You can add to charts options: 
`this.options = {
      tooltips: {
        enabled: false
      }
}`

**Comment by SergeyKuryatnick** [comment]
@victorcarvalhosp 
is this issue still actual for you?

**Comment by whaberek** [comment]
@SergeyKuryatnick
Nope
