### ISSUE TITLE
Update your script file path, and an angular-cli way

### ISSUE THREAD

**Issue by AmitMY** [valor-software/ng2-charts#507]
I had a problem including charts, because I am using angular-cli, and tried to add the path you mention in your README to my "scripts".

You should mention that the correct path is:
"node_modules/chart.js/dist/Chart.bundle.min.js"

And that `angular-cli` users just need to add the path in their `scripts` section of `angular-cli.json`
(relative to the source, meaning "../node_modules/chart.js/dist/Chart.bundle.min.js")

Here is a relevant issue: https://github.com/angular/angular-cli/issues/3172

**Comment by valorkin** [comment]
@AmitMY nice reason for a small PR ;)

**Comment by dreweird** [comment]
thank you dude @AmitMY ... you saved my time searching for the solutions.

**Comment by MrFragStealer** [comment]
Thanks! Also solved my problem.
+1 To include this in the official README

**Comment by AmitMY** [comment]
Just need to merge this: https://github.com/valor-software/ng2-charts/pull/721/files

**Comment by valorkin** [comment]
@AmitMY would you love to maintain this project?

**Comment by AmitMY** [comment]
@valorkin Unfortunately, I do not have the time/expertise to do so..
But I hope I can make a final small request - Can you release v1.6.0, with latest changes?

**Comment by valorkin** [comment]
I will ask QA to test master branch
and will release afterwards
@SergeyKuryatnick could you please ?:)
