### ISSUE TITLE
Mixed Chart Types

### ISSUE THREAD

**Issue by dreweird** [valor-software/ng2-charts#508]
The line is not in the front view and i cannot hover the dot, how to solve this??

http://plnkr.co/edit/FQ2tGi?p=preview

**Comment by SergeyKuryatnick** [comment]
@dreweird 
If i correctly understand your issue - try to use RBGA colors for your chart.

**app.ts** in **plnkr**. Change color to
public color:Array<any> = [
    { // teal
      backgroundColor: 'rgba(115, 221, 137, 0.68)',
      borderColor: 'rgba(36, 148, 58, 0.45)',
      HoverBackgroundColor: 'rgba(36, 148, 58, 0.77)',
      HoverBorderColor: 'rgba(36, 148, 58, 0.77)'
    }];

**Comment by SergeyKuryatnick** [comment]
@dreweird Any news?

**Comment by dreweird** [comment]
@SergeyKuryatnick 

Thank you for your response but the two colors are overlapping and i want a chart like this in a google chart

![image](https://cloud.githubusercontent.com/assets/16024897/20590045/9b48cf6a-b25b-11e6-9ef4-10affcccd04b.png)

**Comment by SergeyKuryatnick** [comment]
Something like this? :)
http://plnkr.co/edit/NbMtGF?p=preview

**Comment by dreweird** [comment]
Yeah thank you... @SergeyKuryatnick !
