### ISSUE TITLE
ChartJS does not work properly in Angular 2 (Ionic 2)

### ISSUE THREAD

**Issue by leonschwanitz** [valor-software/ng2-charts#51]
Blocked by [https://github.com/nnnick/Chart.js/issues/2000](https://github.com/nnnick/Chart.js/issues/2000)

**Comment by valorkin** [comment]
I see you mentioned that with charts.js 2 it works?

**Comment by aicokleinovink** [comment]
I'm using `Ionic 2.0.0-beta.4` with `angular 2.0.0-beta.14` and `ng2-charts 1.0.2` and can confirm that it all works fine now.

**Comment by valorkin** [comment]
Awesome! Closing

**Comment by anandraj9497** [comment]
I am also getting error in Ionic2 application
`Uncaught Error: Can't resolve all parameters for Chart: (?, ?)`
