### ISSUE TITLE
How to set colors?

### ISSUE THREAD

**Issue by AmitMY** [valor-software/ng2-charts#510]
If my colors variable is:
```
[
    {backgroundColor: '#e84351'}, // red
    {backgroundColor: '#434a54'}, //grey
    {backgroundColor: '#3ebf9b'}, //green
    {backgroundColor: '#4d86dc'}, 
    {backgroundColor: '#f3af37'}
]
```

My graph looks like so:
![image](https://cloud.githubusercontent.com/assets/5757359/20456715/9f0df100-ae84-11e6-8362-94f682067ad6.png)

What is the way to set colors in the latest version?

**Comment by AmitMY** [comment]
Answer:
You need to do like:
```
[{backgroundColor: ["#e84351", "#434a54", "#3ebf9b", "#4d86dc", "#f3af37"]}]
```

Not documented, so I won't close yet

**Comment by brettatoms** [comment]
I'm not sure why ng2-charts doesn't just follow the Chart.js API and define the colors in the dataset.  At the very least if the colors attribute isn't specified when declaring the component then the Chart.js API should still work instead of ng2-charts selecting default colors of your.

**Comment by beck24** [comment]
Took me way too long to figure this out, thankfully I found this, I was just about to create an issue here stating that colors in the dataset are ignored.
I agree that it would be ideal if the chartjs API still worked as documented

**Comment by KsuGav** [comment]
@beck24 So, what solution did you find?

**Comment by beck24** [comment]
See the comment above by @AmitMY 
That's the solution

**Comment by AmitMY** [comment]
Full answer:
For a single data series, the coloring is:
`[{backgroundColor: ["#e84351", "#434a54", "#3ebf9b", "#4d86dc", "#f3af37"]}]`

For multiple data series, the coloring is:
```
[
    {backgroundColor: '#e84351'},
    {backgroundColor: '#434a54'}, 
    {backgroundColor: '#3ebf9b'},
    {backgroundColor: '#4d86dc'}, 
    {backgroundColor: '#f3af37'}
]
```
