### ISSUE TITLE
On iOS, showing a chart makes the whole page blank, except for the chart

### ISSUE THREAD

**Issue by AmitMY** [valor-software/ng2-charts#511]
Having a normal chart on a page in iOS makes the whole page look blank (background colors are white, and font color is white)

I cannot share more info, as I don't have a debug console for iOS.

**Comment by SergeyKuryatnick** [comment]
What type of iOS device did you use(iPhone/iPad)?
What model of device?
What browser?

**Comment by AmitMY** [comment]
@SergeyKuryatnick I am sorry for lack of details.
iPhone 5S, 6S, 6S Plus
iOS 10.1.1
Native safari browser.

**More info:**
So after more fiddeling, it does not change the background color, or the font color, but acctually removes HTML elements from the page, or at least somewhat hides them. (they are not there when I try to select them)
It happens once every 2-3 refreshes of the page.
**Weird part:**
I could not reproduce the issue on mac iOS simulator, at all

I normally produce a video of the bug, but this time my employer demanded I will not do such thing.

I will try to find time, probably next week, to create a reproduction code.

**Comment by SergeyKuryatnick** [comment]
@AmitMY Thanks for information, i will try to reproduce
