### ISSUE TITLE
How to change legend position ?

### ISSUE THREAD

**Issue by sridharan31** [valor-software/ng2-charts#519]
how to change the position of the legend its default appear on top of the chart, As per document tried public doughnutposition:string= 'left';   change the position but not working 

 ```
 <canvas baseChart
              [datasets]="datasets"
              [labels]="doughnutChartLabels"
              [chartType]="doughnutChartType"
              [colors]="colorsEmptyObject"
              [options]="barChartOptions"
              [position] ="doughnutposition"
              [legend]="barChartLegend"
              (chartHover)="chartHovered($event)"
              (chartClick)="chartClicked($event)">
</canvas>
```
```
public doughnutChartLabels:string[] = ['EMI', 'Food', 'Fuel', 'bike'];
data:number[] = [3350, 5450, 4100, 1000];
  public doughnutChartType:string = 'doughnut';
  private barChartLegend:boolean = true;
  public doughnutposition:string= 'left';
```

**Comment by SergeyKuryatnick** [comment]
@sridharan31 Hey, `ng2-charts` uses default position for legend, that calculated in `chart.js.`
so you cannot tune legend position in `ng2-charts` settings

Default settings for legend in chart.js(node_modules/chart.js/src/core/core.legend.js) is set for **top**: 
```
Chart.defaults.global.legend = {

		display: true,
		position: 'top',
		fullWidth: true, 
		reverse: false,
}
```

**Comment by m98** [comment]
@SergeyKuryatnick Thanks for the answer, is there any way to change charts legend font-size?

**Comment by JanPeeters** [comment]
@sridharan31 , @SergeyKuryatnick ,  actually, the position can be tuned in ng2-charts:

    public barChartOptions:any = {
    	legend: {position: 'bottom'}
    }

**Comment by kahboom** [comment]
Thanks @JanPeeters !

**Comment by gshashikant** [comment]
Hi  I'm able to bring the legend from the default top position to bottom using:
    public options: any = {
        legend: {position: 'bottom'},
    };

however, I need it at a bottom right corner..  how can i do that?

**Comment by singhrasster** [comment]
@gshashikant Did you find a solution? I want to keep it at the top left. Is it possible?

**Comment by lcustodio** [comment]
There is no clear solution, actually this is a chartjs limitation.
The legend is defined by the `generateLabels` function that only allows `top|bottom|left|right`

http://www.chartjs.org/docs/#chart-configuration-legend-configuration

**Comment by lakshyamathur1** [comment]
see I am using doughnut charts and I am getting values from backend so now the need is to filter those values in descending order .....so how to sort the values of labels?

**Comment by wordBoy** [comment]
To move the legend left or right, I applied [this example for legend spacing (CodePen)](https://codepen.io/jordanwillis/pen/ZeOYdL), then added this.left = (number) below the this.height expression to manipulate the left/right position.

**Comment by FlyingDance1995** [comment]
legend: {
        // orient: 'vertical',
        // top: 'middle',
        bottom: 10,
        left: 'right',
        data: ['西凉', '益州','兖州','荆州','幽州']
    },
bạn có thể dùng cái này nhé

**Comment by UserCalsoft** [comment]
> guys, I'm able to bring the legend from the default top position to bottom using:
> public options: any = {
> legend: {position: 'bottom'},
> };
> 
> however, I need it at a bottom right corner.. how can i do that? tried doing:
> legend: {position: 'bottom right'}
> but to no avail!

Try::
https://www.chartjs.org/docs/latest/configuration/legend.html#align
