### ISSUE TITLE
system.js config

### ISSUE THREAD

**Issue by tamirkr** [valor-software/ng2-charts#520]
is there any guide to work with system.js? nothing seems to be working..also iv'e got this error
Error: Error: Unexpected value 'undefined' imported by the module 'AppModule'(…)

**Comment by skmetic** [comment]
add chart.js to index.html:
  add this  
`<script src="node_modules/chart.js/dist/chart.js">`
before 
` <script> System.import('app').catch(function(err){ console.error(err); });</script>`
in system.config.js add the following lines:
     under //other libraries add 
    ` 'ng2-charts': 'npm:ng2-charts',`
     and in packages add this object
    ```
 'ng2-charts': {
          defaultExtension: 'js'    
      }
```

**Comment by erasad22** [comment]
**I am getting same error like this** 

Error: Error: Unexpected value 'undefined' imported by the module 'AppModule'  at eval 
	  
**Here is my systemJS Code, please help me solve it,** 

(function (global) {
  // map tells the System loader where to look for things
  var map = {
    'app': 'app', // 'dist',
    '@angular': 'node_modules/@angular',
    'angular2-in-memory-web-api': 'node_modules/angular2-in-memory-web-api',
    'ng2-ckeditor':               'node_modules/ng2-ckeditor/lib/CKEditor.js',
    'rxjs': 'node_modules/rxjs',
    'ng2-datetime-picker': 'node_modules/ng2-datetime-picker/dist',
    'ng2-charts':          'node_modules/ng2-charts/bundles/ng2-charts.js'
  };
  // packages tells the System loader how to load when no filename and/or no extension
  var packages = {
    'app': { main: 'main.js', defaultExtension: 'js' },
    'rxjs': { defaultExtension: 'js' },
    'angular2-in-memory-web-api': { main: 'index.js', defaultExtensionz: 'js' },
    'ng2-datetime-picker': { main: 'ng2-datetime-picker.umd.js', defaultExtensionz: 'js' },
    'ng2-charts':                 { main: 'ng2-charts.js', defaultExtension: 'js' }
  };
  var ngPackageNames = [
    'common',
    'compiler',
    'core',
    'forms',
    'http',
    'platform-browser',
    'platform-browser-dynamic',
    'router',
    'router-deprecated',
    'upgrade',
  ];

**Comment by sxmon** [comment]
I can't get it working with system.js

**Comment by joeyjreij** [comment]
getting 404

**Comment by Reintjuu** [comment]
When trying the things @skmetic suggested, I placed the
```
'ng2-charts': {
    defaultExtension: 'js'
}
```
in the `systemjs.config.extras.js` file. I got some 404's and figured that I forgot to include the file in the index.html after the `<script src="systemjs.config.js"></script>` line. So add `<script src="systemjs.config.extras.js"></script>` after that and the 404's should go away.

**Comment by wilbo** [comment]
Thanks @Reintjuu, worked like a charm!

**Comment by an2207** [comment]
I also have the 404 error. 
My app.module.ts:
```
import {ChartsModule} from 'ng2-charts';
[...]
@NgModule({
    imports: [
        BrowserModule,
        FormsModule,
        HttpModule,
        routing,
        AccountModule,
        ChartsModule
    ] [...]
```

My systemjs.config.js
```
(function (global) {
    System.config({
        paths: {
            // paths serve as alias
            'npm:': 'lib/'
        },
        // map tells the System loader where to look for things
        map: {
            // our app is within the app folder
            app: 'lib/spa',
            // angular bundles
            '@angular/core': 'npm:@angular/core/bundles/core.umd.js',
            '@angular/common': 'npm:@angular/common/bundles/common.umd.js',
            '@angular/compiler': 'npm:@angular/compiler/bundles/compiler.umd.js',
            '@angular/platform-browser': 'npm:@angular/platform-browser/bundles/platform-browser.umd.js',
            '@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
            '@angular/http': 'npm:@angular/http/bundles/http.umd.js',
            '@angular/router': 'npm:@angular/router/bundles/router.umd.js',
            '@angular/forms': 'npm:@angular/forms/bundles/forms.umd.js',
            // other libraries
            'rxjs': 'npm:rxjs',
            'angular-in-memory-web-api': 'npm:angular-in-memory-web-api/bundles/in-memory-web-api.umd.js',
            'ng2-charts': 'npm:ng2-charts',
        },
        // packages tells the System loader how to load when no filename and/or no extension
        packages: {
            app: {
                main: './main.js',
                defaultExtension: 'js'
            },
            rxjs: {
                defaultExtension: 'js'
            },
            'angular2-in-memory-web-api': {
                main: './index.js',
                defaultExtension: 'js'
            },
            'ng2-charts': {
                defaultExtension: 'js'
            }

        }
    });
})(this);

```
What might be the problem? What should I have in my lib to make it work?

**Comment by joeyjreij** [comment]
I keep getting the error, even in a new angular quickstart with Angular V4, "404 get "@angular/material", think it is in the main.ts, the struggle is real..

**Comment by jiggy1com** [comment]
@an2207 Try 
`'ng2-charts': 'node_modules/ng2-charts/bundles/ng2-charts.umd.js',` 

notice the ".umd" (figured this out by opening up node_modules/ng2-charts/bundles...)  

(and keep) 
`'ng2-charts': {
    defaultExtension: 'js'
 }`

The upper path fix prevented the errors that brought me here. I then copy/paste the first line chart example and it rendered. Whoo!

**Comment by jiggy1com** [comment]
@tamirkr Did you figure this out? I think this issue can be closed.

**Comment by JoeyJreijStudent** [comment]
Just use the CLI version, and all of these problems will be gone :)

**Comment by paviad** [comment]
This package is now updated for Angular 7, and `webpack` is your friend. If this issue persists, please provide a codepen/stackblitz/... example showing the issue.
