### ISSUE TITLE
this.chart is not defined

### ISSUE THREAD

**Issue by jaroslawziolkowski** [valor-software/ng2-charts#521]
Hi I use ng-charts in 1.4.1 version. I've been tried run it witj charts.js in versions 2.4, 1.0.2, 1.1.1 because I found information that it doesn't work with newest versions.

Unfortunately still I see same error `this.chart is not defined` 

I added in appModule
```
import { ChartsModule } from "ng2-charts";

@NgModule({
    imports: [
        BootstrapModalModule,ChartsModule]...
})
```
and in component

```
<div style="display: block; position: relative;">
        <canvas (chartHover)="chartEvent($event)" (chartClick)="chartEvent($event)" baseChart [chartType]="'pie'" [options]="options" [datasets]="chartData.data" [labels]="chartData.labels"></canvas>
        </div>
```

data is simplae numbers array and labels array of strings.

Which versions combination I should use to run it? I use angular 2.1.1 (typescript) and I added to head section in my html code import for charts.js

**Comment by valorkin** [comment]
`this.chart is not defined` means charts.js was not loaded properly

**Comment by jaroslawziolkowski** [comment]
How can I solve it? Because I did all like in tutorial and other issues o  github
--
Regards
Jarek Ziółkowski
PHP Developer

mobile: +48 531537 359
e-mail: jarek@jaroapp.com

Dnia 28 listopada 2016 13:41:21 CET, Dmitriy Shekhovtsov <notifications@github.com> napisał(a):

**Comment by aloisDeLaComble** [comment]
Same issue, I cannot change other properties than the ones bound in template element (datasets, options, colors, legend, chartType and events) dynamically. Still, everything else works well.

**Comment by Dazag** [comment]
Same issue here, but using multiple charts only

**Comment by Dhanush4444** [comment]
**This worked**


`<div *ngIf="dataAvailable ; else notAvailable">
<div class="row">
  <div class="col-md-6">
    <div style="display: block;">
      <canvas baseChart width="400" height="400"
              [datasets]="lineChartData"
              [labels]="lineChartLabels"
              [options]="lineChartOptions"
              [colors]="lineChartColors"
              [legend]="lineChartLegend"
              [chartType]="lineChartType"
              (chartHover)="chartHovered($event)"
              (chartClick)="chartClicked($event)"></canvas>
    </div>
  </div>
</div>
</div>
<ng-template #notAvailable>
  Waiting for sync
</ng-template>`

`
public dataAvailable = false;
ngOnInit(): void {
    this.itemRef.snapshotChanges().subscribe(action => {
      this.dataAvailable = true;
    });
  }`

**Comment by paviad** [comment]
This package has been updated for Angular 7, with many bugs fixed and features added. I believe this issue is now resolved. If not, please provide a stackblitz/codepen/... example showing it.

**Comment by almgwary** [comment]
any updates
