### ISSUE TITLE
Embedd Chart.js

### ISSUE THREAD

**Issue by bene-starzengruber** [valor-software/ng2-charts#526]
Hey guys!

I'm trying to use ng2-charts in my app, but I get following error

`EXCEPTION: Uncaught (in promise): Error: Error in ./Skillset class Skillset - inline template:5:10 caused by: ng2-charts configuration issue: Embedding Chart.js lib is mandatory
Error: ng2-charts configuration issue: Embedding Chart.js lib is mandatory
    at BaseChartDirective.getChartBuilder `

I already installed ng2-charts and chart.js via npm.
Where can I embedd Chart.js in an Angular2 app? (it's already in the vendor.browser.ts - file)

Thanks

**Comment by limjoonae** [comment]
me too
![image](https://cloud.githubusercontent.com/assets/3191903/20962811/73d6eec0-bc9d-11e6-83a5-f134ccfed795.png)

**Comment by schrej** [comment]
The easiest way is to just include the `Chart.min.js` from `node_modules/chart.js/dist/Chart.min.js`

**Comment by jkon** [comment]
I was having this problem too because my project is set up in a way that the node_modules weren't getting served in a way that I could reference them in my index.html to embed Chart.js from there. I just used the cdn instead. It means I need an internet connection for testing all the time, but it works just fine for me.
https://cdnjs.com/libraries/Chart.js

**Comment by MrFragStealer** [comment]
I'm having the same issue in an Angular CLI app, and I'm also not sure where to embed.
I added the line "../node_modules/chart.js/src/chart.js" to angular-cli.json but it didn't work. (also tried adding here schrej's suggestion).
I tried adding <script src="node_modules/chart.js/src/chart.js"></script> to my index.html file and also to the corresponding component template. But none of these solved the issue.

Please advise.

**Comment by HtetWaiYanLin** [comment]
hay guys 

please insert your index.html.

`<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.1.3/Chart.bundle.min.js"></script>`

**Comment by Cuica20** [comment]
Guys,
In your component.ts insert this:

import 'chart.js'

**Comment by EdgarSalazar** [comment]
After @MrFragStealer  's solution, stop and restart your application. Live reload won't do the trick.

**Comment by ahmadalibaloch** [comment]
Do this in your main.ts below your other imports:
```
import * as Chart from 'chart.js';
window['Chart'] = Chart;
```

you must have already done this:
```
npm install ng2-charts --save
npm install chart.js --save
```

**Comment by clintonjnelson** [comment]
@EdgarSalazar 's tip to restart the application reminded me that changes to the angular-cli config (.angular-cli.json), requires the `ng build --watch` be stopped/restarted to apply the updated configuration. Doh! Working great now.

**Comment by lukibsubekti** [comment]
You don't need to include the script in index.html, just do what @Cuica20 or @ahmadalibaloch suggest, both work for me. But, don't forget to update chart.js to latest version. I just spent an hour to find a way, I reliazed my chart.js was still v1.1.1 then I upgraded to latest (2.5.0) and it worked.

**Comment by rabee1981** [comment]
1- open https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.1.3/Chart.bundle.min.js in the browser and copy the content of the page
2- create new folder "chartjs" under assests
3- create file under the new folder and call it Chart.bundel.min.js
4- copy the content to the file
5- in index.html add `<script src="assets/chartjs/Chart.bundle.min.js"></script>`

**Comment by paviad** [comment]
This package is now updated for Angular 7. It is now no longer required to embed chart.js manually in your `index.html` or in `angular.json`. Please see the [demo app](https://valor-software.com/ng2-charts/) for reference (it is also updated). If this issue persists, please provide a codepen/stackblitz/... example showing the issue.
