### ISSUE TITLE
is there scaling/zooming?

### ISSUE THREAD

**Issue by Andranik-89** [valor-software/ng2-charts#527]
Hi everyone,

is it possible to have a mini chart for the main chart with the scaling/zooming capabilities, like here:
http://jsfiddle.net/gh/get/jquery/1.7.2/highcharts/highcharts/tree/master/samples/stock/navigator/multiple-series/

you can see it right underneath the main chart
Thank you very much in advance!

**Comment by paviad** [comment]
Please refer to #388
