### ISSUE TITLE
Canvas isn't shown

### ISSUE THREAD

**Issue by FreakyJ** [valor-software/ng2-charts#53]
Hi all,

I would like to use ng2-charts but unfortunately I can't get it to work.

There are no errors thrown or any kind of log entry, but the canvas stays empty.

This is the generated dom code:

`<base-chart class="chart">
  <canvas height="0" width="0" style="width: 0px; height: 0px;"></canvas>
  <ul class="bar-legend"><li><span style="background-color:rgba(151,187,205,0.2)"></span>Series A</li><li><span style="background-color:rgba(220,220,220,0.2)"></span>Series B</li></ul></base-chart>`

I can see the legend, but not the graph itself.
I followed exactly the tutorial, this is my template:

`<base-chart class="chart"
            [data]="barChartData"
            [labels]="barChartLabels"
            [options]="barChartOptions"
            [series]="barChartSeries"
            [legend]="barChartLegend"
            [chartType]="barChartType"
            (chartHover)="chartHovered($event)"
            (chartClick)="chartClicked($event)"></base-chart>`

And the whole component:

`import {Component, View, ViewEncapsulation, EventEmitter} from "angular2/core";
import {COMMON_DIRECTIVES, CORE_DIRECTIVES, NgClass} from "angular2/common";
import {HTTP_PROVIDERS, Http, Request, RequestMethod} from "angular2/http";

import { PROGRESSBAR_DIRECTIVES } from 'ng2-bootstrap/ng2-bootstrap';
import {CHART_DIRECTIVES} from 'ng2-charts/ng2-charts';

import {ConfigurationService} from "../../../common/lib/ConfigurationService/ConfigurationService";
import {ISystemInformation} from "./ISystemInformation";

@Component({
    templateUrl: "app/modules/systemStatus/systemStatus.html",
    directives: [COMMON_DIRECTIVES, CORE_DIRECTIVES, PROGRESSBAR_DIRECTIVES, CHART_DIRECTIVES, NgClass],
    encapsulation: ViewEncapsulation.None // don't use View Encapsulation because we wan't to overwrite some css
})
export class SystemStatusComponent {
    BASE_URL: string;

    systemInformation: ISystemInformation;

    constructor(private http: Http, private configurationService: ConfigurationService) {
        this.BASE_URL = configurationService.config.WebApiUrl;

        var url: string = this.BASE_URL + "/api/v1/Server/Information";

        this.http.request(new Request({
            method: RequestMethod.Get,
            url: url
        })).map(res => res.json()).subscribe(res => {
            this.systemInformation = res;
        });
    }

    getPercent(value: number, total: number, decimal: number = 0): number {
        var result: number = (value / total * 100);
        return isNaN(result) ? 0 : parseFloat(result.toFixed(decimal));
    }

    BytesToXBString(bytes: number): string {
        var extension: string = "bytes";
        var convertedBytes: number = bytes;

        // to TB
        if (bytes > 1e+12) {
            convertedBytes = bytes / 1e+12;
            extension = "TB";
        }
        // to GB
        else if (bytes >= 1e+9) {
            convertedBytes = bytes / 1e+9;
            extension = "GB";
        }
        // to MB
        else if (bytes >= 1000000) {
            convertedBytes = bytes / 1000000;
            extension = "MB";
        }

        return convertedBytes.toFixed(2) + " " + extension;
    }

    // lineChart
    private barChartOptions = {
        scaleShowVerticalLines: false,
        responsive: true,
        multiTooltipTemplate: '<%if (datasetLabel){%><%=datasetLabel %>: <%}%><%= value %>'
    };
    private barChartLabels = ['2006', '2007', '2008', '2009', '2010', '2011', '2012'];
    private barChartSeries = ['Series A', 'Series B'];
    public barChartType = 'Bar';
    private barChartLegend:boolean = true;

    private barChartData = [
        [65, 59, 80, 81, 56, 55, 40],
        [28, 48, 40, 19, 86, 27, 90]
    ];

    // events
    chartClicked(e:any) {
        console.log(e);
    }
    chartHovered(e:any) {
        console.log(e);
    }

}`

Chart.js is included in the head of index.html:
`<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/1.0.2/Chart.min.js"></script>`
And system.js is also configured fine:
`<script>
        System.config({
            defaultJSExtensions: true,
            packages: {
                app: {
                    format: 'register',
                    defaultExtension: 'js'
                },
                "/ng2-translate": {
                    defaultExtension: 'js'
                }
            },
            map: {
                'ng2-translate': 'node_modules/ng2-translate',
                'rxjs': 'node_modules/rxjs',
                'angular2': 'node_modules/angular2',
                'ng2-bootstrap': 'node_modules/ng2-bootstrap',
                'ng2-charts': 'node_modules/ng2-charts',
                'moment': 'node_modules/moment/moment.js'
            }
        });
        System.import('app/boot')
                .then(null, console.error.bind(console));
    </script>`

Hope somebody has an idea what's wrong.

**Comment by Vader699** [comment]
I believe I had the same issue.  I think it comes from the canvas needing some css that is not included with the ng2-charts component.

Try adding this somewhere on the html where <base-chart> is located.
`<style>
   .chart {display: block; width: 100%;}
</style>`

**Comment by ironmanwaring** [comment]
That took care of the issue for me as well, thanks for the tip

**Comment by rud0lf0** [comment]
`responsive: true` was the problem for me. When I changed it to `false` the canvas appeared.

**Comment by vincic** [comment]
Same issue here with a angular2 beta9 app, Chrome@OSX and IE11. 
Setting responsive: false solved the height calculation. 

Debugging the code I found out that this.parent.clientHeight is 0 all the time. 
https://github.com/valor-software/ng2-charts/blob/master/components/charts/charts.ts#L244

**Comment by valorkin** [comment]
should be fixed in #136 please check (release 1.0.2)

**Comment by vishwastyagi** [comment]
Keep chartjs script as first statement under headr in index.html

**Comment by kevinbeal** [comment]
In my case, I had the canvas as the first element inside of a component template and it only showed after I made the host element `display: block;`

**Comment by Mohammed-Shoaib** [comment]
I had to change the `ChartOptions`. Both of the below solutions worked for me.

* Solution 1: `responsive: false,`
* Solution 2: `responsive: true, maintainAspectRatio: false,`
