### ISSUE TITLE
How to format labels to number ? 

### ISSUE THREAD

**Issue by nhatdq1810** [valor-software/ng2-charts#533]
Hi, my labels is an array of number like : [2000000, 1500000, 1000000, 500000, 2500000, 3000000]
I want to display this label with format number, i.e: 2,000,000. How can I do that ?

Here is example:
http://plnkr.co/edit/ioy2Kdn7j0Dv05PWo2Se?p=preview

Thank you very much

**Comment by jkon** [comment]
can you update your example with the pipe? I'm curious how to do this

**Comment by nhatdq1810** [comment]
Hi @jkon , I used DecimalPipe:
let label = new DecimalPipe('en').transform(prop);
this.labelsTvDT.push(label);

with prop is '2000000' for example, the label will be 2,000,000

**Comment by jkon** [comment]
Ah, cool. Thanks!

**Comment by duard** [comment]
@nhatdq1810 how can I show my bar values as decimal ?

**Comment by NoumanMukhtar** [comment]
How can i show my values like 10GB, 20GB ? Anyone help please ?
