### ISSUE TITLE
How to set data and draw chart with async data?

### ISSUE THREAD

**Issue by h4mit** [valor-software/ng2-charts#534]
Hi, what's idea for set data and draw chart with async data?

```
 this.userService.getChart().subscribe(response => {
            this.lineChartData = response.data;
            this.lineChartLabels = response.label;
        });
```
not drawing chart 😢

**Comment by h4mit** [comment]
Is there a method to refresh chart ?!

**Comment by XidongHuang** [comment]
Hi, is this block of code in a method, the it can be invoked by the chart? Like: 
`public selected(value: any): void {
       this.userService.getChart().subscribe(response => {
            this.lineChartData = response.data;
            this.lineChartLabels = response.label;
        });
}`

Or this method is going to initialize the chart, then you can use component's **constructor** or component life hook **OnInit()**.
I did initialize my chart in component constructor, the code looks like:
`constructor(private userService: UserService) {
       this.userService.getChart().subscribe(response => {
            this.lineChartData = response.data;
            this.lineChartLabels = response.label;
        });
}`

Hope it help you

**Comment by h4mit** [comment]
Hi, this code implemented on component life in **OnInit()**. if set default value in data drawing pie chart but after when change data value drawing not again by new value chart.

**Comment by XidongHuang** [comment]
Hey man, the **OnInit()** method just run once right after constructor. 
So are you trying to like update the pie chart up-to-date automatically? How about try **OnChange()** method, just let one of your pie chart component receive the new data, and use **OnChange()** method monitor it, once any changings in those values of pie chart's component, then **OnChange()** method change  **this.lineChartDat**a and **this.lineChartLabels** in your main pie chart.

**Comment by h4mit** [comment]
I know, I want set data for once begin initialize component and show pie chart async mode.

**Comment by XidongHuang** [comment]
Yeah, so you mean after initializing, you also want the chart refresh if the database updates, right?? 
If like that, I think just use **socket.io** to monitor the database, and just keep changing your **lineChartData**, **lineChartLabels** array if there are any new data coming.

**Comment by aguarino77** [comment]
Having to pass data to the chart in the constructor is really a bad habit. Please read angular official docs:  [https://angular.io/docs/ts/latest/tutorial/toh-pt4.html](url)
> The ngOnInit Lifecycle Hook
AppComponent should fetch and display heroes without a fuss. Where do we call the getHeroes method? In a constructor? We do not!
Years of experience and bitter tears have taught us to keep complex logic out of the constructor, especially anything that might call a server as a data access method is sure to do.
The constructor is for simple initializations like wiring constructor parameters to properties. It's not for heavy lifting. We should be able to create a component in a test and not worry that it might do real work — like calling a server! — before we tell it to do so.

I would strongly suggest that ng2 charts supports this!

**Comment by bkartik2005** [comment]
Were you able to resolve this issue? I am running into the same problem

**Comment by aguarino77** [comment]
Have a look at #291: @zbagley comment is a perfect fix. You basically do not render the chart until you finish fetching data.

**Comment by johanwannheden** [comment]
Have a look at https://github.com/valor-software/ng2-charts/blob/master/demo/src/app/components/charts/bar-chart-demo.ts:
```
    let clone = JSON.parse(JSON.stringify(this.barChartData));
    clone[0].data = data;
    this.barChartData = clone;
    /**
     * (My guess), for Angular to recognize the change in the dataset
     * it has to change the dataset variable directly,
     * so one way around it, is to clone the data, change it and then
     * assign it;
     */
```
That worked for me.
