### ISSUE TITLE
Charts in Flex boxes

### ISSUE THREAD

**Issue by armarton** [valor-software/ng2-charts#555]
I have a flex based layout. I would like to insert the charts into flexboxes with dynamic size, and I can't figure out how can I do that. I would like to reach to fill the full flexbox with the chart. So if I have a flexbox with 33% of size, in that case the chart should be that size, but in case of 100% e.g. a line chart should be full sized, not just double sized in case of maintainAspectRatio: true.
This is really important, if I would like to implement a fully responsive flex layout contains charts.
Can you check if I mess with something please?
Thanks a lot and have a very great new year! 

HTML:
```html
<div class="row">
    <div class="col col-gt2" *ngFor="let chart of charts" [ngClass]="'col-' + chart.width">
        <div>
            <canvas baseChart [data]="chart.data" [datasets]="chart.datasets" [labels]="chart.labels" [chartType]="chart.type" [legend]="chart.legend" [options]="chart.options" [colors]="chart.colors"></canvas>
         </div>
      </div>
</div>
```

SCSS:
```scss
.col {
    display: flex;
    justify-content: center;
    align-content: center;
    height: 350px;
    padding: 10px;
    background: $background2;
    color: $background4;
    &-gt1 {
        flex: 1 1 33%;
    }
    &-gt2 {
        flex: 2 1 66%;
    }
    &-gt3 {
        flex: 3 1 100%;
    }
}
```

TS:
```typescript
public charts:any[] = [
        {
            title: "Projects",
            labels: ['New', 'Active', 'Closed'],
            data: [204, 104, 1514],
            datasets: null,
            type: 'doughnut',
            width: 'gt1',
            height: 240,
            cols: 2,
            rows: 4,
            isLegend: true,
            options: {
                responsive: true,
                maintainAspectRatio: false
            },
            colors: [
                {
                    backgroundColor: [
                        'rgba(29, 83, 150, 1)',
                        'rgba(204, 59, 59, 1)',
                        'rgba(136, 196, 37, 1)'
                    ]
                }
            ]
        },
        {
            title: "Members",
            labels: ['PM', 'DA', 'DO', 'ST1', 'ST2', 'ST3', 'ST4'],
            data: null,
            datasets: [
                {data: [65, 59, 80, 81, 56, 55, 40], label: 'All Members'},
                {data: [28, 48, 40, 19, 26, 27, 8], label: 'Recent Members'}
            ],
            type: 'bar',
            width: 'gt2',
            height: 260,
            cols: 4,
            rows: 4,
            isLegend: true,
            options: {
                scaleShowVerticalLines: false,
                responsive: true,
                maintainAspectRatio: false
            },
            colors: [
                {
                    backgroundColor: 'rgba(29, 83, 150, 0.6)',
                    hoverBackgroundColor: 'rgba(29, 83, 150, 1)'
                },
                {
                    backgroundColor: 'rgba(204, 59, 59, 0.6)',
                    hoverBackgroundColor: 'rgba(204, 59, 59, 1)'
                }
            ]
        }
```

**Comment by nicolassharp** [comment]
@armarton did you ever figure this out?

**Comment by armarton** [comment]
Honestly the problem is with the canvas. This is a fixed size pixel based image.
There are workarounds for that to catch every window size modification, and resize the canvas, but finally I've chosen a SVG based chart, which is vector based so easily re-sizable.
The issue can be closed.

**Comment by henninga** [comment]
@armarton Did you use a library or made something yourself?

**Comment by tommybananas** [comment]
I came across a solution I think. You need to make sure that the container element has it's height set **regardless** of whether or not it is actually respected by flexbox. Chart.js relies on the height being set to resize properly.

So, if you're using flexbox and even if the parent is a dynamic flexbox container, you can always use `flex-grow:1` to make sure the wrapper fits it's parent container. The trick is that [at least in chrome], you can set a height on the wrapper element which will ultimately be **ignored** because of the `flex-grow:1`. But this is still enough to get Chart.js to resize properly. 

This is incomplete code but this is basically how I got chart.js and ng2-charts to work inside flexbox:

```
<div style="display:flex; flex-direction:column">
  <div style="flex-grow:1; height:100px; position:relative">
    <charts-canvas></charts-canvas>
  </div>
</div>
```

**Comment by mikecabana** [comment]
> I came across a solution I think. You need to make sure that the container element has it's height set **regardless** of whether or not it is actually respected by flexbox. Chart.js relies on the height being set to resize properly.
> 
> So, if you're using flexbox and even if the parent is a dynamic flexbox container, you can always use `flex-grow:1` to make sure the wrapper fits it's parent container. The trick is that [at least in chrome], you can set a height on the wrapper element which will ultimately be **ignored** because of the `flex-grow:1`. But this is still enough to get Chart.js to resize properly.
> 
> This is incomplete code but this is basically how I got chart.js and ng2-charts to work inside flexbox:
> 
> ```
> <div style="display:flex; flex-direction:column">
>   <div style="flex-grow:1; height:100px; position:relative"> //100px or 1px, doesn't matter
>     <charts-canvas></charts-canvas>
>   </div>
> </div>
> ```
> **Note:** I was using a column layout so my `flex-grow:1` was only affecting the height of my div. I would assume that if you're using a row based layout, chart.js would need you to specify a _width_ instead. The important part, like I said, is that you set a width/height even if the flexbox engine ignores it.
> 
> ALSO, YOU NEED TO SET `maintainAspectRatio: false`
> 
> ```
> chartOptions = {
>    maintainAspectRatio: false
> };
> ```

Wow this was exactly what I was looking for. Don't know why pixel based canvas images are such a pita to deal with in flex. 😩
