### ISSUE TITLE
ng2-charts with angular 2.0.2

### ISSUE THREAD

**Issue by beckmx** [valor-software/ng2-charts#562]
Hello, I was wondering if the ng2-chart is compatible with the angular 2.0.2 version, I am getting a wierd error:

Unexpected module 'ChartsModule' declared by the module 'AppModule'
at /Users/andressantos/cemexuicomponents/ClientApp/dist/vendor.js:28041:34

**Comment by pturner1989** [comment]
ChartsModule should be included in the imports array not declarations. Can you check if you have that correct in your Module

example:
`
@NgModule({
  declarations: [
    AppComponent,
  ],
  imports: [
    BrowserModule,
    ChartsModule,
    FormsModule,
    HttpModule,
    routing
  ],
  providers: [appRoutingProviders, ...],
  bootstrap: [AppComponent],
})
`

**Comment by thigrand** [comment]
@beckmx We imports modules on "imports". "declarations" are for all types of directives.

**Comment by beckmx** [comment]
Hello, I did everything correctly, but it seems it doesn't work with my setup, I ended up putting the chart.js directly on the index, I am using the dotnet core single-page-application setup but it seems the webpack doesn't accept the dependency in the webpack.config
