### ISSUE TITLE
Tooltip always visible

### ISSUE THREAD

**Issue by thigrand** [valor-software/ng2-charts#564]
Is it a way to show always tooltip? Not only on hover?
It is posible on chart.js. But i can't find a way in ng2-charts.

**Comment by eddieedease** [comment]
I agree that this would be very useful

**Comment by WebDoin** [comment]
Hi, it is possible now?

Thanks!!

**Comment by AntoineGJ** [comment]
Is it possible now ? Please.
Thanks!

**Comment by Mumumurilo** [comment]
I'd be very happy if I could set it to always visible too. :)

**Comment by FatemeFazli** [comment]
any update on this issue?

**Comment by mariusl-a** [comment]
+1

Would be a nice feature to use in case of touch devices.

**Comment by paviad** [comment]
Please refer to this `chart.js` comment https://github.com/chartjs/Chart.js/issues/1861#issuecomment-219186703

**Comment by likefurnis** [comment]
> Please refer to this `chart.js` comment [chartjs/Chart.js#1861 (comment)](https://github.com/chartjs/Chart.js/issues/1861#issuecomment-219186703)

A bit late for me to join, but the solution on that comment cannot be applied since the Chart interface from chart.js does not have any implementation of a constructor for 'Tooltip' since 'Tooltip' is a static 'Chart.ChartTooltipsStaticConfiguration'.

**Comment by likefurnis** [comment]
Ended up using [chartjs-plugin-datalabels plugin](https://github.com/chartjs/chartjs-plugin-datalabels), works perfectly.
