### ISSUE TITLE
Add types for chart customisation

### ISSUE THREAD

**Issue by Mark-McCracken** [valor-software/ng2-charts#571]
There is a lot of type: any when customising.
Would be straightforward and a lot easier to develop in if there were some straightforward types you could import into a component using a chart.
E.g.
export type ChartType = 'bar' | 'line' | 'pie' | 'doughnut' ; etc..
Could also create this for Colors, ChartOptions, BarChartData,  quite easily.
Would making developing a good bit easier, and pretty easy to implement

**Reproduction of the problem**

ng2-charts is a port & modification of Chart.js component for Angular 2. Sometimes the issue is related with Chart.js instead of ng2-charts.
To confirm, if the issue shows in a pure Chart.js project, it is a issue of Chart.js.
Pure Chart.js starting template: https://jsfiddle.net/Hongbo_Miao/mvct2uwo/3/

If the issue does not show in a pure Chart.js project, and shows in a ng2-charts project, please try to provide a minimal demo of the problem.
ng2-charts starting template: http://plnkr.co/edit/Ka4NXG3pZ1mXnaN95HX5?p=preview

**Comment by paviad** [comment]
This is a good suggestions, the goal is that `any` only appears when referring to external libraries and where there's absolutely no other choice.

I will start working on it.
