### ISSUE TITLE
No Chart directives

### ISSUE THREAD

**Issue by mburger81** [valor-software/ng2-charts#58]
after install your latest ng2-chart there es no ng2-chart.ts for importing  CHART_DIRECTIVES into my typscript file ...

This doesn't work
import {CHART_DIRECTIVES} from 'ng2-charts/ng2-charts';

on inspecting the node_module folder there seemes to be no chart directive, only one ng2-charts/components/charts/charts.ts file which exports an BaseChart Directive which doesn't work.

Can you also bring the module to latests ng2-bootstrap and angular2 beta6

thx

**Comment by rud0lf0** [comment]
Try [THIS](http://stackoverflow.com/a/34704124). Worked for me ;)

**Comment by valorkin** [comment]
system.js bundles now part of npm module
from #136 please check (release 1.0.2)
