### ISSUE TITLE
Missing final bar in single dataset Bar Chart

### ISSUE THREAD

**Issue by gwsampso** [valor-software/ng2-charts#586]
Hello

Is this a known issue?

running "ng2-charts": "^1.5.0" "chart.js": "^2.4.0",,

I've set up my chart as per the example but reduced my dataset to just the 1 and i'm missing the final value eg. 40.. the axis lable shows however now data is populated.

really basic setup in component.ts

`  public barChartLabels:string[] = ['2006', '2007', '2008', '2009', '2010', '2011', '2012'];
  public barChartType:string = 'bar';
  public barChartLegend:boolean = true; 
  public barChartData: any[] = [
    {data: [65, 59, 80, 81, 56, 55, 40], label: 'Series A'}
  ];`

and then my html

`					<div style="display: block">
						<canvas baseChart
								class = "chart"
								[datasets]="barChartData"
								[labels]="barChartLabels"
								[options]="barChartOptions"
								[chartType]="barChartType"></canvas>
					</div>
`

**Comment by gwsampso** [comment]
![missing bar](https://cloud.githubusercontent.com/assets/19770122/22234259/d7780cd4-e24a-11e6-937b-64b7b37ea203.PNG)

**Comment by abmedury** [comment]
Had a similar issue, but noticed the y-axis scale....

Try the below as [options]
barChartOptions: any = {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero:true
                }
            }]
        }
    };

**Comment by derrickxiang** [comment]
I have the same issue, the last bar just not shown, any one has a solution?

**Comment by mnhmilu** [comment]
Make sure your dataset is in **number format**. I had a problem with type "any" and alway some bar was missing with lots of issues

**Comment by paviad** [comment]
@abmedury comment resolves this issue.
