### ISSUE TITLE
Labels over segments of pie chart and doughnut chart?

### ISSUE THREAD

**Issue by Natanael1234** [valor-software/ng2-charts#587]
How to show the labels of each segment of over segments of pie charts and doughnut charts over the respective segments this way:

http://www.bbc.co.uk/staticarchive/d00d6ca860bc06b66d5dd54f774144b2484623cc.gif

**Comment by alshdavid** [comment]
I'd also like an answer for this

**Comment by alshdavid** [comment]
Solved it, perhaps not ideally, but solved it.

Include a script file under where you imported chart.js in your index.html with the following code in it:

`
Chart.pluginService.register({
  beforeRender: function (chart) {
    if (chart.config.options.showAllTooltips) {
        // create an array of tooltips
        // we can't use the chart tooltip because there is only one tooltip per chart
        chart.pluginTooltips = [];
        chart.config.data.datasets.forEach(function (dataset, i) {
            chart.getDatasetMeta(i).data.forEach(function (sector, j) {
                chart.pluginTooltips.push(new Chart.Tooltip({
                    _chart: chart.chart,
                    _chartInstance: chart,
                    _data: chart.data,
                    _options: chart.options.tooltips,
                    _active: [sector]
                }, chart));
            });
        });

        // turn off normal tooltips
        chart.options.tooltips.enabled = false;
    }
},
  afterDraw: function (chart, easing) {
    if (chart.config.options.showAllTooltips) {
        // we don't want the permanent tooltips to animate, so don't do anything till the animation runs atleast once
        if (!chart.allTooltipsOnce) {
            if (easing !== 1)
                return;
            chart.allTooltipsOnce = true;
        }

        // turn on tooltips
        chart.options.tooltips.enabled = true;
        Chart.helpers.each(chart.pluginTooltips, function (tooltip) {
            tooltip.initialize();
            tooltip.update();
            // we don't actually need this since we are not animating tooltips
            tooltip.pivot();
            tooltip.transition(easing).draw();
        });
        chart.options.tooltips.enabled = false;
    }
  }
});
`

Then in the options of your chart, include:

`
options: {
    showAllTooltips: true
}
`

For extra points, you can include it in your app.component.ts, underneath the class howeer you need to declare Chart with `declare var Chart:any;`

**Comment by OArnarsson** [comment]
@alshdavid have you found any other solution to this problem?
I can't seem to get this script to work as expected, could you maybe include some more info?

**Comment by Natanael1234** [comment]
Nope. I'm using another library.

**Comment by paviad** [comment]
The `chartjs-plugin-datalabels` handles displaying any information on top of bars/pie slices etc. Please see the [demo app](https://valor-software.com/ng2-charts) for examples (under bar and pie charts).

**Note** The `datalabels` plugin registeres itself automatically upon load, so that it applies to all charts. In order to only apply it to selected charts, it needs to be unregistered globally, and then included in the inline plugins array for each chart. This is all demonstrated in the demo app.
