### ISSUE TITLE
Gradient Support

### ISSUE THREAD

**Issue by nikkwong** [valor-software/ng2-charts#599]
Gradients for like ```backgroundColor``` styles does not seem to be supported. Is there plan to add support for this?

**Comment by Charlie-Hua** [comment]
this works for me:

```typescript
// in template
<canvas #myCanvas ...

// in component
@ViewChild("myCanvas") canvas: ElementRef;

// in ngOnInit
let gradient = this.canvas.nativeElement.getContext('2d').createLinearGradient(0, 0, 0, 200);
gradient.addColorStop(0, 'green');
gradient.addColorStop(1, 'white');

// use it
...
backgroundColor: this.gradient,
...
```

**Comment by webcat12345** [comment]
@Charlie-Hua , how to use `backgroundColor: this.gradient,` ?
More information please.

**Comment by Charlie-Hua** [comment]
@webcat12345 I've updated my previous comment, hope it helps.

**Comment by webcat12345** [comment]
@Charlie-Hua , Thanks for your update.
But after changing chart color as gradient, it's hover color is grey. any solution?

**Comment by Charlie-Hua** [comment]
@webcat12345 I am not sure what you mean by hover color, are you using bar chart?
you can check the available options for certain chart type in chart.js doc: http://www.chartjs.org/docs/#bar-chart-dataset-structure

```typescript
this.barChartColors = [
  {
    backgroundColor: gradient,
    hoverBackgroundColor: anotherGradient,
    // borderColor: ...
    // hoverBorderColor: ...
  }
];
```

**Comment by vickieallen** [comment]
@Charlie-Hua  does this still work? I'm trying to do this but canvas is always undefined so I get 

 ERROR TypeError: Cannot read property 'nativeElement' of undefined

Any ideas?

**Comment by divyanshu-rawat** [comment]
@vickieallen can you please write your code, that is causing  Cannot read property 'nativeElement' of undefined.

**Comment by aishwaryardandi** [comment]
I am getting the same error when I have canvas inside a modal. Any ideas on how to fix this?

**Comment by polygonov** [comment]
Same problem - cannot read property 'nativeElement' of undefined.

**Comment by orl99** [comment]
Remember to use the AfterViewInit life-cycle of Angular, if you try to access to the DOM in the ngOnInit the reference will be undefined.

I also recommend to use the 'HTMLCanvasElement' interface.
```JavaScript
  ngAfterViewInit() {
    const domCanvasAccess = this.canvas.nativeElement as HTMLCanvasElement;
    const gradientColor = domCanvasAccess.getContext('2d').createLinearGradient(0, 0, 0, 200);
    gradientColor.addColorStop(0, 'green');
    gradientColor.addColorStop(1, 'white');
  }
```

**Comment by NBprojekt** [comment]
Im using the ng-chart inside of `ngSwitchCase`, so I can't access the context in `ngAfterViewInit`.

Therefore i'm using this code to get my canvas element:
```
@ViewChild('myCanvas', {static: false}) set content(elementRef: ElementRef<HTMLCanvasElement>) {
  if(elementRef) {
    const context: CanvasRenderingContext2D = elementRef.nativeElement.getContext('2d');
    this.gradient = context.createLinearGradient(0, 0, 0, 600);

    this.gradient.addColorStop(0, 'green');
    this.gradient.addColorStop(1, 'white');
  }
}
```

The weird thing is that my chart turn gray now.

**Comment by vickieallen** [comment]
Just to confirm. This worked when I put it in the AfterViewInit.

**Comment by orl99** [comment]
> Im using the ng-chart inside of `ngSwitchCase`, so I can't access the context in `ngAfterViewInit`.
> 
> Therefore i'm using this code to get my canvas element:
> 
> ```js
> @ViewChild('myCanvas', {static: false}) set content(elementRef: ElementRef<HTMLCanvasElement>) {
>   if(elementRef) {
>     const context: CanvasRenderingContext2D = elementRef.nativeElement.getContext('2d');
>     this.gradient = context.createLinearGradient(0, 0, 0, 600);
> 
>     this.gradient.addColorStop(0, 'green');
>     this.gradient.addColorStop(1, 'white');
>   }
> }
> ```
> 
> The weird thing is that my chart turn gray now.

Have you try to use setTimeOut function as a wrapper for your code, sometimes it works

**Comment by NBprojekt** [comment]
@orl99 Yes I did, I also set the setTimeOut to 3min (just for the sake of science) but it did the same as without the timeout.

> The weird thing is that my chart turn gray now.

**Comment by pufalone** [comment]
Works on _ngAfterViewInit_ but it just throws _`ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'colors: undefined'. Current value: 'colors: [object Object]'.`_

**Comment by vickieallen** [comment]
I got this too but was fixed once I wrapped it in 
`setTimeout(() => { everything in ngAfterViewInit });`

**Comment by kenshintdd** [comment]
I fixed it using AfterContentInit instead of ngAfterViewInit.

Cheers.
