### ISSUE TITLE
Dynamically change generated labels not worked

### ISSUE THREAD

**Issue by jerkly** [valor-software/ng2-charts#614]
Version: ng2-charts `v1.5.0`

Reproduction of the problem
http://plnkr.co/edit/Ggp7hasnGBsKTlq8hu1R?p=preview

Probably dynamically change generated labels feature was removed by this PR #563 .

related task to this feature #445

**Comment by jerkly** [comment]
@m0t0r

**Comment by m0t0r** [comment]
hey, @jerkly, I made a PR fixing your issue.

**Comment by stojankukrika** [comment]
When it will be in production version?

**Comment by cnd5041** [comment]
In the mean time, in case you need it, here's a plkr that updates the labels 'manually'.

**Comment by stojankukrika** [comment]
I move to https://www.npmjs.com/package/angular2-highcharts and thy make it to works perfect! Use it and enjoy ;)

**Comment by jerkly** [comment]
ref to #592

**Comment by jakeNesom** [comment]
@stsojankukrika - I edited your plunkr to match my issue which i believe is similar to the one described here (labels not changing)

Everyone else - is this issue similar to the original or should I create a new issue?

My issue happens when the labels array length or data array length changes from what was in the component on initialization

In my example, if you click the "change2" button, the labels[] and data[] are replaced with a new labels array and new data array.  However, somehow the chart visuals won't update to show the new information - it's like the labels and data array length are still set to their original values

http://plnkr.co/edit/gVprkAvV4cycpl9mUrtI?p=preview

**Comment by giumarzo** [comment]
I resolved the problem with this method https://github.com/Puigcerber/ng2-charts/commit/1ae41eeb53df6e6b2afad84ce95de172aa0951b9

**Comment by nikkwong** [comment]
Yeah, the library stinks. Docs stink, you have to fiddle around with everything to make it work. Extremely hard to get it to work with async/changing data. Overall terrible experience and leaves a bad taste in my mouth for valor-software.

**Comment by andrewkhan1** [comment]
@nikkwong Would have to agree with you here. Everything about this library is terrible.

**Comment by t-moritsugu** [comment]
If this chagen is allowed... 

ng2-charts/charts/charts.js

```javascript
BaseChartDirective.prototype.ngOnChanges = function (changes) {
    if (this.initFlag) {
        // Check if the changes are in the data or datasets
        if (changes.hasOwnProperty('data') || changes.hasOwnProperty('datasets')) {
            if (changes['data']) {
                this.updateChartData(changes['data'].currentValue);
            }
            else {
                this.updateChartData(changes['datasets'].currentValue);
            }
            // add label change detection every time
            if (changes['labels']) { 
                if (this.chart && this.chart.data && this.chart.data.labels) {
                    this.chart.data.labels = changes['labels'].currentValue;    
                }
            }
            this.chart.update();
        }
        else {
            // otherwise rebuild the chart
            this.refresh();
        }
    }
};

```

**Comment by MinsuLim** [comment]
@t-moritsugu 
It works perfectly for me also. 
Thank you very much.

**Comment by jjosef** [comment]
Why is this not merged? Is someone maintaining this project any longer?

**Comment by ratshidaho** [comment]
For those looking for a walk around, for now you can put your labels and data in an object and put that object in an array and just loop through the array in your html. This will redraw the element every time your array changes.

in your type script every time there's  a change.
`data = [...]
labels = [...]
chartArray = [{data , labels }]
`

in your html

`
<canvas *ngFor="let chartData of chartArray "  [data]="chartData.data"
          [labels]="chartData.labels" >
</canvas>
`

in your type script every time there's  a change.
`data = [...]
labels = [...]
chartArray = [{data , labels }]
`

in your html

`
<canvas *ngFor="let chartData of chartArray "  [data]="chartData.data"
          [labels]="chartData.labels" >
</canvas>
`

**Comment by paviad** [comment]
This package has been updated for Angular 7, with many bugs fixed and features added. I believe this issue is now resolved. If not, please provide a stackblitz/codepen/... example showing it.
