### ISSUE TITLE
Line Charts Option don't work

### ISSUE THREAD

**Issue by dantavo** [valor-software/ng2-charts#616]
Hi I am trying to do something very easy but with no success. 
I am using version 1.5.0 and I have a line charts where I don't want the fill under the line so I put fill option to false but nothing happen and the same anomaly happens with lineTension option, is it my mistake?

```
public lineChartOptions: any = {
        fill: false,        
        responsive: true,
        lineTension: 1
    };
```

**Comment by jerkly** [comment]
Try to use `lineChartColors` to do this

```typescript
  public lineChartColors: any = {
      backgroundColor: 'rgba(0, 0, 0, 0)'
      ...
    }
```

**Comment by dantavo** [comment]
Thanks to your reply, but this doesn't work form me because I have a multiline graph and I want to have single colored line, with the solution you proposed I get a gray scale results :(

**Comment by jerkly** [comment]
Could you provide plinker with your problem?

**Comment by MonkeyDo** [comment]
Based on the plunkr in the Readme:
http://plnkr.co/edit/ECC8hEGh8Edi7VSdnz3z?p=preview

In this case, adding either ```tension: 0``` or ```lineTension:0```has no effect on the curve interpolation.

**Comment by MonkeyDo** [comment]
Well, found the answer to that: the option is to be defined in the dataset, rather than the options object:

http://plnkr.co/edit/D9rMqkrCjDpb2S10Dq4P?p=preview

**Comment by akimirka** [comment]
Thanks, it resolved the problem!

**Comment by elpdrc** [comment]
This is the working sample:

```
<canvas baseChart 
    [datasets]="[{ data: [65, 59, 80, 81, 56, 55, 40], fill: false, lineTension: 0 }]"
      [labels]="['January', 'February', 'March', 'April', 'May', 'June', 'July']"
      [options]="{}"
      [chartType]="'line'"
    >
</canvas>
```
