### ISSUE TITLE
Running ng2-charts on iOS with cordova 

### ISSUE THREAD

**Issue by alexlu3211** [valor-software/ng2-charts#617]
I'm currently developing an iOS app with Angular 2. After I wrap the project with cordova, it runs pretty well in browsers and all the ng2 charts is able to be displayed. However, once I build it on iOS, all the charts doesn't work anymore.

I was wondering was it caused by the incompatibility of angular 2 and iOS or any other reason?

Thanks a lot. :)

**Comment by Pawan14051991** [comment]
i am facing same issue

**Comment by alexlu3211** [comment]
@Pawan14051991 I solved the problem by changing [hidden] to ngIf. Not sure if yours is caused by the same problem.
