### ISSUE TITLE
Error: Cannot read property 'data' of undefined - Data using @Input

### ISSUE THREAD

**Issue by vandanakogentix** [valor-software/ng2-charts#630]
Hi,

I want to dynamically populate the pie chart on load. I am using @Input to fetch the data from parent component. But something is wrong, I am getting following error - 

_Error: Cannot read property 'data' of undefined_

My sample code:

@Component({
  selector: 'chart',
  template: `
    <canvas baseChart height="100" width="100" [data]="pieChartData" [labels]="pieChartLabels" [options]="pieChartOptions" [chartType]="pieChartType"
        [colors]="pieColors" (chartClick)="chartClicked($event)"></canvas>
`
})
export class ChartComponent { 
  public pieChartLabels:string[] = ['abc', 'def'];
  @Input() public pieChartData:number[] = [];
  public pieColors: any[] = [{
    backgroundColor: ["#36A2EB", "#FF82B3"],
    hoverBackgroundColor: ["#36A2EB", "#FF82B3"]
  }];
  public pieChartOptions: any = {
    responsive: true,
    legend: {
      display: false
    }
  };
  public pieChartType:string = 'pie';
  constructor() {

  }
 }

Please advice, what am I doing wrong?

**Comment by fr4ngus** [comment]
Hi,
I don't know if I have correctly understood your problem.
I try to create a child component and pass to ChildComponent chartData and it works.
https://plnkr.co/edit/hEGmRF93JV2Mo5GdfejV?p=preview

**Comment by fr4ngus** [comment]
Please close issue

**Comment by vandanakogentix** [comment]
Thanks for your sample code. I was also doing like this but the issue is related to angular 2 promise and it is resolved. Thanks again.

**Comment by maksof-kashif** [comment]
<canvas baseChart
[datasets]="ChartData"
//...other stuff >

and in the component I have a function which update the chart with new data, and then I clone the datasets and re-assign it

drawChart(){
this.ChartData=[{data: this.dataX, label: 'X'}]; // this.dataX has new values from some place in my code
//nothing happened with my chart yet, until I add this lines:
let clone = JSON.parse(JSON.stringify(this.ChartData));
this.ChartData=clone;
//other stuff like labels etc.
}
