### ISSUE TITLE
steppedLine for lineChartType='line' does not work

### ISSUE THREAD

**Issue by jiolpi** [valor-software/ng2-charts#635]
Option steppedLine does not produce a stepped line. It has no effect.

**Comment by jiolpi** [comment]
This issue can be closed. steppedLine belongs to "datasets". Thank you.

**Comment by Antonyselt** [comment]
@jiolpi where do you put it?

**Comment by Antonyselt** [comment]
@jiolpi never mind. Thank you

**Comment by Antonyselt** [comment]
@jiolpi never mind. Thank you
