### ISSUE TITLE
chartHovered not invoked when hovering on a bar

### ISSUE THREAD

**Issue by singhrasster** [valor-software/ng2-charts#638]
I am creating a bar chart and my HTML code looks like:

```
<div style="display: block">
    <canvas baseChart
            [datasets]="barChartData"
            [labels]="barChartLabels"
            [options]="barChartOptions"
            [legend]="barChartLegend"
            [chartType]="barChartType"
            (chartHover)="chartHovered($event)"
            (chartClick)="chartClicked($event)"></canvas>
  </div>
```

Typescript has the two handlers:

  public chartClicked(e:any):void {
    console.log(e);
  }
 
  public chartHovered(e:any):void {
    console.log(e);
  }

When I click on a bar, the chartClicked method is invoked. However, when I just hover on the bar, the chartHovered method is not invoked. Is there a bug?

**Comment by jevit** [comment]
Hi,

Have you tried to add this in options:

```
hover:{
        onHover: function(e:any) {
           this.chartHovered(e)
        }
}
```

**Comment by arameau** [comment]
I have exactly the same problem, on the web of ng2-chart the event works but not in my example

**Comment by laurentperroteau** [comment]
+1

**Comment by alissarenz** [comment]
On line 55 of the included charts/chart.js, the function passes `active` -- I believe it should actually be passing `event` and `active`, like the onClick below it. Since the first argument passed (actually a MouseEvent) is not the presumed active array, and will never have a length, it will never emit.

To get around it in the meantime, manually define the hover method in options:

```
hover: {
     onHover: function(event, active) {
          // do stuff with active         
     }
}
```

**Comment by marcus-jan** [comment]
+1

**Comment by jevit** [comment]
how keep scope with 
hover: {
     onHover: function(event, active) {
          // do stuff with active         
     }
}

?

**Comment by vedk21** [comment]
you can use an arrow function if working in typescript. 
say 
`hover: {
onHover: (event, active) => {
// do stuff with active
this.your_property 
}
}`

**Comment by popsapple** [comment]
(mouseover)="chartHovered($event)"

Good Luck :)

**Comment by labeltran01** [comment]
Hi, i have the same problem, i´m working with Angular4, when I use chartHover, it doesn´t return any value. 

I have something like this: 
`in the HTML:
<div style="display: block">
  <canvas baseChart
              [data]="doughnutChartData"
              [labels]="doughnutChartLabels"
              [chartType]="doughnutChartType"
              (chartHover)="chartHovered($event)"
              (chartClick)="chartClicked($event)"></canvas>
</div>

in the component: 
export class PieChartComponent implements OnInit {
  // Doughnut
  public doughnutChartLabels: string[] = ['Download Sales', 'In-Store Sales', 'Mail-Order Sales'];
  public doughnutChartData: number[] = [350, 450, 100];
  public doughnutChartType: string = 'doughnut';

  ngOnInit() {

  }

  // events
  public chartClicked(e: any): void {
    console.log(e);
  }

  public chartHovered(e: any): void {
    console.log(e);
  }
}`

**Comment by labeltran01** [comment]
Hi, i have the same problem, i´m working with Angular4, when I use chartHover, it doesn´t return any value.

I have something like this:
`in the HTML:
<div style="display: block">
  <canvas baseChart
              [data]="doughnutChartData"
              [labels]="doughnutChartLabels"
              [chartType]="doughnutChartType"
              (chartHover)="chartHovered($event)"
              (chartClick)="chartClicked($event)"></canvas>
</div>
in the component:
export class PieChartComponent implements OnInit {
// Doughnut
public doughnutChartLabels: string[] = ['Download Sales', 'In-Store Sales', 'Mail-Order Sales'];
public doughnutChartData: number[] = [350, 450, 100];
public doughnutChartType: string = 'doughnut';

ngOnInit() {

}

// events
public chartClicked(e: any): void {
console.log(e);
}

public chartHovered(e: any): void {
console.log(e);
}
}`

**Comment by cemezgn** [comment]
Is there any solition for this ? I solved this problem with @alissarenz s solution but it has problem. When the resize screen without again hover chart doesn't display on screen.

**Comment by paviad** [comment]
Please refer to the updated [demo app](https://valor-software.com/ng2-charts), it shows that the hover even works over bars in the bar chart.

**Comment by sandeep-synswift** [comment]
@cemezgin Thanks ... hover event working
But can you suggest on change hover how to change event
