### ISSUE TITLE
Hover on line charts not working, at all?

### ISSUE THREAD

**Issue by dbogdantech101** [valor-software/ng2-charts#643]
http://valor-software.com/ng2-charts/

Hovering on the line chart doesn't perform the console.log. Having issues with my local implementation and when I came to check it looks like it doesn't work at all. Is this a bug or just not supported?

**Comment by atifsaddique211f** [comment]
I am also getting this.

**Comment by paviad** [comment]
Two things:

1. Hovering on points on the line does work, also clicking on the chart anywhere works as well.
2. This is an issue for chart.js not for this library. chart.js is responsible for issuing the hover events.
