### ISSUE TITLE
Changing Default Background Colors for Bar Chart

### ISSUE THREAD

**Issue by blubberbo** [valor-software/ng2-charts#645]
What is the best way to change the global default color for a bar chart using multiple datasets?

**Comment by dowrow** [comment]
Attribute [colors]="myColors" where
myColors = [{ backgroundColor: ['#firstBarColor', '#secondBarColor', '#thirdBarColor']}];

**Comment by kahboom** [comment]
Thanks @dowrow !

**Comment by blubberbo** [comment]
thank you @dowrow however, that just sets the colors for each bar, what if I have multiple datasets and I want all the bars of each dataset to have the same color. 

For instance if I have a bar chart with 1 dataset, I want all the bars on that chart to be the same color. If I have 2 data sets, I want the first bar in each group to be the same color, then the second bar in each set to be the same color and so on and so forth.

Does that make sense?

**Comment by dowrow** [comment]
Note that, in my example, myColors is an array where each object element applies to a different dataset. So, if you want to style different sets just use more objects:
myColorsForMultipleDatasets = [{ backgroundColor: [...] }, { backgroundColor: [...] }];

**Comment by blubberbo** [comment]
@dowrow Thanks for the clarification, I tried that and the result I get is the following: 

![image](https://cloud.githubusercontent.com/assets/17286750/24711216/2810a51e-19d4-11e7-91fd-c345871bc551.png)

[colors] = [{ backgroundColor: ['rgba(8, 123, 180, 1)'] }, { backgroundColor: ['rgba(113, 24, 255, 1)'] }, { backgroundColor: ['rgba(223, 0, 145, 1)'] }];`

The array works for the first set of bars (the colors are correct, even though it's hard to see there are any "Open" but it doesn't work for the rest. If make each array have n number of items in them, it will work for up to n number of items. Is there a way to just make `{ backgroundColor: ['rgba(8, 123, 180, 1)'] }` work for any number of bar sets?

I hope that makes sense. 

Thank you for your help!

**Comment by dowrow** [comment]
This issue could be closed now.

**Comment by elavanya** [comment]
need to add two color in each bar, one is #F8F8F8 from bottom to top full bar, and another one is actual data count #0084E7
Like this https://prnt.sc/ritp45
