### ISSUE TITLE
getting error after install ng2-charts

### ISSUE THREAD

**Issue by chan51** [valor-software/ng2-charts#647]
Hello,

After install getting error: Unhandled Promise rejection: ctorParameters.map is not a function ; Zone: angular ; Task: Promise.then ; Value: TypeError: ctorParameters.map is not a function
    at ReflectionCapabilities.parameters

Please help, I'm helpless since two days. I'm found no solutions on this errors.
Thanks

**Comment by AndrewKralovec** [comment]
@chan51  what was your solution ?
