### ISSUE TITLE
Option 'lineArc' for Radar chart doesn't work

### ISSUE THREAD

**Issue by ShakurOo** [valor-software/ng2-charts#653]
When I set the lineArc option in 'scale' configuration, the graph doesn't display. When I set the option to true, the graph is displaying.

Here is implementation with ng2-charts : http://plnkr.co/edit/jGDsd3?p=preview
Here is is with native charts.js : https://jsfiddle.net/hvenb74o/2/

It is a bug ?

**Comment by Artfloriani** [comment]
Did you find a fix for this? I'm having the same issue

**Comment by ShakurOo** [comment]
Hello,

I simply downgraded the version of chart.js to 2.1.6. I don't know what features has been changed since this version but It seems this has an negative impact with this option.

My **package.json** file looks like :
`{
    "chart.js": "2.1.6",
    "ng2-charts": "^1.5.0"
}`

And my property **radarChartOptions**  :
`{
    scale: {
        lineArc: true,
        angleLines: {
            display: true
        } 
    }
}`

The directive is using like this : 
`<canvas baseChart
    id="radar"
    class="chart"
    [options]="radarChartOptions">
</canvas>`

Hoping this will be helpful.

**Comment by Artfloriani** [comment]
Thank you for such a quick reply!

For me it has been working using `{ "chart.js": "2.4.0", "ng2-charts": "1.4.0" }`. I did not try updating ng2-charts without updating chart.js. 

I will open another issue as I do need the chart.js on the latest build 😞
