### ISSUE TITLE
Change labels font size (Bar chart type)

### ISSUE THREAD

**Issue by sarn3792** [valor-software/ng2-charts#659]
I was looking for a solution where I can modify labels font size but I haven't found it.
Does anyone have an example?

My source code is on: https://github.com/sarn3792/CRMCharts 
Thanks!

**Comment by m0t0r** [comment]
@sarn3792 you can change font size for legend labels like this: 

```js
public barChartOptions: any = {
...
  legend: {
      position: 'right',
      labels: {
        fontSize: 14
      }
  }
}
```

or if you want to change labels of axis you can do it like this:

```js
public barChartOptions: any = {
...
  scales: {
     yAxes: [
      {
          display: true,
          ticks: {
            fontSize: 14
          }
      }
    ]
  }
}
```

In general you can use any chart options defined in [official charts.js documentation](http://www.chartjs.org/docs/).

**Comment by sarn3792** [comment]
@m0t0r Thanks so much! It's working perfectly.

I have another doubt. Do you know how to show the value above bar chart? I would like to displat it as seen in the following image:
![image](https://cloud.githubusercontent.com/assets/9375416/23768627/47ea5e14-04d2-11e7-86e0-faf72c15d8dc.png)

I'll really appreciate your help :)

**Comment by MohammedImtiyaz** [comment]
I was having the same issue, searched all over the web. But i dint get solution. Then i made changes in dc.js file , it worked well. This is for bar chart. You can change fonts for other charts also by going to respective labels.

open your dc.js file.
goto line number 5631
ADD this line to d3 labels :         .style("font-size", "12px")      
This worked for me.

**Comment by paviad** [comment]
Use `chartjs-plugin-datalabels`. See this stackblitz: https://stackblitz.com/edit/ng2-charts-bar-labels

![image](https://user-images.githubusercontent.com/1235688/54044525-d80cc380-41d7-11e9-871f-b395994a5e0b.png)
