### ISSUE TITLE
How to display value above bar chart

### ISSUE THREAD

**Issue by sarn3792** [valor-software/ng2-charts#662]
Hi.

I would like to display the value above bar chart.
![image](https://cloud.githubusercontent.com/assets/9375416/23635773/47c21be4-0297-11e7-899d-39e7b7631f94.png)

**Component.ts**
```typescript
import { Component, OnInit } from '@angular/core';
import { ProspectService } from './prospect.service';
import {Observable} from 'rxjs/Rx';
import { Prospect } from './prospect';
import { ChartData } from "../chartData";

@Component({
  selector: 'app-prospects',
  templateUrl: './prospects.component.html',
  styleUrls: ['./prospects.component.css'],
  providers : [ProspectService]
})
export class ProspectsComponent implements OnInit {
  private prospects: Array<Prospect> = [];

  public barChartOptions:any = {
      scaleShowVerticalLines: false,
      responsive: true, 
      scaleShowValues: true, 
      scaleValuePaddingX: 10,
      scaleValuePaddingY: 10
  };

  public barChartLabels:string[] = ['Test'];
  public barChartType : string = 'bar';
  public barChartLegend: boolean = true;
  public barChartData: ChartData[] = [
    {data: [50], label: 'Series A'}
  ];


  public chartColors: Array<any> = [
    { // first color
      backgroundColor: '#67b346',
      //backgroundColor:["#FF7360", "#6FC8CE", "#FAFFF2", "#FFFCC4", "#B9E8E0"],
      borderColor: '#000000',
      pointBackgroundColor: 'rgba(225,10,24,0.2)',
      pointBorderColor: '#fff',
      pointHoverBackgroundColor: '#fff',
      pointHoverBorderColor: 'rgba(225,10,24,0.2)'
    }];
 
  // events
  public chartClicked(e:any):void {
    //console.log(e);
  }
 
  public chartHovered(e:any):void {
    //console.log(e);
  }
  constructor(private prospectService : ProspectService) { 
  	Observable.interval(10000).subscribe(x => { //every 10 seconds
		    this.getProspect();
	});
  }

  ngOnInit() {
  	this.getProspect();
  }

  public getProspect(): void{
  	this.prospectService.getProspects().then(response => {
  		this.prospects = response;
  		this.setValuesToChart();
  	});
  }

  public setValuesToChart(): void{
  	let i =0;
  	this.clearValues();
  	var newData = new ChartData();
    this.prospects.forEach((prospect) =>{
    	if(i != 0){
	    	this.barChartLabels.push(prospect.name);
	    	newData.data.push(prospect.value);
	    	newData.label = " Estimated Prospect Value by Account Manager";
	    }
	    i++;
    });
    this.barChartData.push(newData);
    this.barChartData = this.barChartData.slice();
  }

  public clearValues() : void{
    this.barChartData.forEach((info) =>{
      info.data.slice(0);
    });
    this.barChartData.splice(0);
    this.barChartLabels.splice(0);
  }

}
```

**Component.html**
```html
<div class="container-fluid">
	<div>
	  <div style="display: block">
	    <canvas baseChart height="140"
	            [datasets]="barChartData"
	            [labels]="barChartLabels"
	            [options]="barChartOptions"
	            [legend]="barChartLegend"
	            [colors]="chartColors"
	            [chartType]="barChartType"
	            (chartHover)="chartHovered($event)"
	            (chartClick)="chartClicked($event)">
	            
	    </canvas>
	  </div>
	</div>
</div>
```

Hope someone could help me

Thanks :)

**Comment by sanju31** [comment]
if you found any solution then please share.

**Comment by RamakrishnaE** [comment]
Hi @sarn3792 ,

I Hope you found a way to make it. Could you please let me know?

Thank you very much.

**Comment by philippegabert** [comment]
Hi, 

I don't know if it works for barchart, but here is what I used for line chart:

 ```
public lineChartOptions: any = {
        responsive: true,
        animation: {
            onComplete: function () {
                var chartInstance = this.chart,
                    ctx = chartInstance.ctx;

                ctx.textAlign = 'center';
                ctx.textBaseline = 'bottom';

                this.data.datasets.forEach(function (dataset, i) {
                    var meta = chartInstance.controller.getDatasetMeta(i);
                    meta.data.forEach(function (bar, index) {
                        var data = dataset.data[index];
                        ctx.fillText(data, bar._model.x, bar._model.y - 5);
                    });
                });
            }
        }
        
    };

```

Philippe

**Comment by sanjeevani-ftcash** [comment]
Thanks Philippe, but where we need to put this function?

**Comment by philippegabert** [comment]
In your file Component.ts

Actually you need to update your barChartOptions to add the animation part.

If your current options are:
`public barChartOptions:any = {
scaleShowVerticalLines: false,
responsive: true,
scaleShowValues: true,
scaleValuePaddingX: 10,
scaleValuePaddingY: 10
};`

You should replace them with:
`public barChartOptions:any = {
scaleShowVerticalLines: false,
responsive: true,
scaleShowValues: true,
scaleValuePaddingX: 10,
scaleValuePaddingY: 10,
 animation: {
           onComplete: function () {
               var chartInstance = this.chart,
               ctx = chartInstance.ctx;
               ctx.textAlign = 'center';
               ctx.textBaseline = 'bottom';
               this.data.datasets.forEach(function (dataset, i) {
                   var meta = chartInstance.controller.getDatasetMeta(i);
                   meta.data.forEach(function (bar, index) {
                       var data = dataset.data[index];
                       ctx.fillText(data, bar._model.x, bar._model.y - 5);
                   });
               });
           }
       }
};`

**Comment by sanjeevani-ftcash** [comment]
got it working, thanks a lot. 👍

**Comment by philippegabert** [comment]
Great. Do not forget to close the issue. :+1:

**Comment by sanjeevani-ftcash** [comment]
Fixes #662

**Comment by sanjeevani-ftcash** [comment]
Fixes #662

**Comment by sukumar89** [comment]
Team, I implemented this fix to my bar chart it worked well. But looking for some more improvisation on it, if particular does not appears on the chart as a result no data or length of dataset is 0, How to omit the value of 0 displaying. My chart is as below, can someone just a quick way for not displaying the 0's


![image](https://user-images.githubusercontent.com/26416719/32586436-770fbb1c-c4d0-11e7-918a-9dbf0e79acf9.png)

**Comment by ProElbs** [comment]
Any solution for a Pie chart? So we can display data into each part of the pie.

Thanks forward

**Comment by karthik67** [comment]
in the animation, you can do something like this:
 animation: {
           onComplete: function () {
               var chartInstance = this.chart,
               ctx = chartInstance.ctx;
               ctx.textAlign = 'center';
               ctx.textBaseline = 'bottom';
               this.data.datasets.forEach(function (dataset, i) {
                   var meta = chartInstance.controller.getDatasetMeta(i);
                   meta.data.forEach(function (bar, index) {
                       var data = dataset.data[index];
                       if (data > 0) {
                         ctx.fillText(data, bar._model.x, bar._model.y - 5);
                      }
                   });
               });
           }
       }

**Comment by karthik67** [comment]
that will get rid of the zeros in the bar

**Comment by king612** [comment]
thank you @philippegabert !!  That worked beautifully for me.

**Comment by king612** [comment]
@philippegabert  Actually, now that I play with it some, the data labels above the bars disappear as soon as you hover over one of the bars and the default tooltip / mouse over appears.  Any suggestions?  Thanks!

**Comment by guto-gomes** [comment]
@philippegabert Excellent solution, but it appears at once on the chart, exist a way with "transition"?

**Comment by imran-khan8** [comment]
Thank you @philippegabert. I see one problem with that, as soon as I move mouse over the chart, the values disappears.

**Comment by karthik67** [comment]
if you keep the mouse, it will be back.


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by manhar-developer** [comment]
Hi @karthik67 @imran-khan8  @guto-gomes 
Any solution so that data remains on the bar even if tooltip is displayed or on hover. Currently on mouse over it disappears

**Comment by guto-gomes** [comment]
@vinitkrb I inserted with the following code:

`animation: {
      onComplete: function () {
        const chartInstance = this.chart,
          ctx = chartInstance.ctx;

        const fontSize = 20;
        const fontStyle = '600';
        const fontFamily = 'Open Sans';
        ctx.font = Chart.helpers.fontString(fontSize, fontStyle, fontFamily);

        ctx.textAlign = 'center';
        ctx.textBaseline = 'bottom';
        ctx.fillStyle = '#676A6C';

        this.data.datasets.forEach(function (dataset, i) {
          const meta = chartInstance.controller.getDatasetMeta(i);
          meta.data.forEach(function (bar, index) {
            if(dataset.data[index] != 0){
              const data = dataset.data[index] + '%';
              ctx.fillText(data, bar._model.x, bar._model.y - 0);
            }
          });
        });
      }
    },`

**Comment by vinitkrb** [comment]
not working

**Comment by DiegoArredondo** [comment]
> Hi @karthik67 @imran-khan8 @guto-gomes
> Any solution so that data remains on the bar even if tooltip is displayed or on hover. Currently on mouse over it disappears

Did someone found a way? I really need something like this

**Comment by paviad** [comment]
Use `chartjs-plugin-datalabels` which is robust and full featured. Check this stackblitz: https://stackblitz.com/edit/ng2-charts-bar-labels

![image](https://user-images.githubusercontent.com/1235688/54043811-28832180-41d6-11e9-928f-9112d5f049a1.png)

**Comment by henkkruger** [comment]
You can duplicate the code for the onComplete event for the onProgress event, which will only cause a slight flicker but this is better than it disappearing and reappearing:

        animation: {
          onComplete: function () {
              var chartInstance = this.chart,
                  ctx = chartInstance.ctx;

              ctx.textAlign = 'center';
              ctx.textBaseline = 'bottom';

              this.data.datasets.forEach(function (dataset, i) {
                  var meta = chartInstance.controller.getDatasetMeta(i);
                  meta.data.forEach(function (bar, index) {
                      var data = dataset.data[index];
                      ctx.fillText(data, bar._model.x, bar._model.y - 5);
                  });
              });
          },
          onProgress: function () {
              var chartInstance = this.chart,
                  ctx = chartInstance.ctx;

              ctx.textAlign = 'center';
              ctx.textBaseline = 'bottom';

              this.data.datasets.forEach(function (dataset, i) {
                  var meta = chartInstance.controller.getDatasetMeta(i);
                  meta.data.forEach(function (bar, index) {
                      var data = dataset.data[index];
                      ctx.fillText(data, bar._model.x, bar._model.y - 5);
                  });
              });
          }
      }
