### ISSUE TITLE
Displaying bars in a merged fashion not possible?

### ISSUE THREAD

**Issue by giorgi-pro** [valor-software/ng2-charts#687]
Isn't it possible to show bars like this:

![bars_correct](https://cloud.githubusercontent.com/assets/8410406/24085934/6f84992c-0d05-11e7-8720-ccfdc45fa5a5.JPG)

instead of this:

![bars](https://cloud.githubusercontent.com/assets/8410406/24085925/06c66c30-0d05-11e7-9e63-75f6d0e5651c.JPG)

**Comment by steady-daddy** [comment]
Use `stacked: true` in chart options:

```
{
...
options: {
        scales: {
            xAxes: [{
                stacked: true
            }],
...
}
```
