### ISSUE TITLE
Accessing BaseChartDirective with @ViewChild

### ISSUE THREAD

**Issue by BerkerD** [valor-software/ng2-charts#691]
Basically, i am subscribed to mqtt host and recieving data each second. I need to print them on two different charts but i cannot acces to baseChart with @ViewChild it always returns undefined therefore my update method is not working. I managed to update one chart with following code:

**UPDATES ONLY ONE CHART**
`  
@ViewChild(BaseChartDirective) private _chart ;
this._chart.chart.update();
`
But its not enough for me ..

**TRIED TO DIVIDE BASECHART**

` @ViewChild('panelA') panelA : BaseChartDirective;
 @ViewChild('panelB) panelB : BaseChartDirective;
this.panelA.chart.update();
this.panelA.chart.update();
`

**Markup Code**

` <canvas baseChart #panelA
                [datasets]="panel1Dataset"
                [labels]="panel1Labels"
                [options]="lineChartOptions"
                [colors]="lineChartColors"
                [legend]="lineChartLegend"
                [chartType]="lineChartType"
        ></canvas>
        <canvas baseChart #panelB
                [datasets]="panel2Dataset"
                [labels]="panel1Labels"
                [options]="lineChartOptions"
                [colors]="lineChartColors"
                [legend]="lineChartLegend"
                [chartType]="lineChartType"
        ></canvas>`

**Error**

Cannot read property 'update' of undefined

**Comment by BerkerD** [comment]
I figured it out. I was trying to reach the <canvas></canvas> by using # and ViewChild, therefore my update function was trying to update the canvas not the directive inside. Thats why i changed the html part of the code as follows: 

 <canvas #panelA=base-chart baseChart  > ... </canvas>

Exporting this canvas as baseChart to my defined variable.

**Comment by balr404** [comment]
Could you please share the code change what you have done to resolve the issue. It helps us to understand the fix

Thanks

**Comment by micobarac** [comment]
The suggested HTML markup is invalid:

`#panelA=base-chart`

**Comment by ZaLiTHkA** [comment]
In the interest of not leading others astray:

> The suggested HTML markup is invalid:
> 
> `#panelA=base-chart`

..for everything before HTML5, sure.

But not only is it valid in current standards (which were already around in Nov 2019), it's also used to tell Angular to create a template reference variable, even in the [current Angular documentation](https://angular.io/api/core/ViewChild) (v10.0.1 at the time of writing this).

**Comment by Leab-JB** [comment]
> I figured it out. I was trying to reach the by using # and ViewChild, therefore my update function was trying to update the canvas not the directive inside. Thats why i changed the html part of the code as follows:
> 
> <canvas #panelA=base-chart baseChart > ...
> 
> Exporting this canvas as baseChart to my defined variable.

Thanks a lot. Took me 06 hours investigating what's going on 😅.
