### ISSUE TITLE
How to create horizontal bar chart ?

### ISSUE THREAD

**Issue by venkadesh02** [valor-software/ng2-charts#706]
Is it possible to create horizontal bar chart ? If not, is it planned for future release?

**Comment by zbagley** [comment]
Bar charts can be used by adjusting the "chartType" option within your baseChart canvas.
```
<canvas baseChart
            [datasets]="data"
            [labels]="label"
            chartType="horizontalBar">
</canvas>
```

**Comment by venkadesh02** [comment]
Its working. Thanks.

**Comment by vkumar2-aires** [comment]
It is not working for me
