### ISSUE TITLE
How to use a chartjs-plugin-annotation with ng2-charts

### ISSUE THREAD

**Issue by sarraRoza** [valor-software/ng2-charts#713]

**Comment by misham** [comment]
Been trying to make this work and it's not showing up.

I'm using the line example from https://codepen.io/anon/pen/LzOgRp

I installed the plugin as in the instructions and added it in the `.angular-cli.json`.

There are no errors in the console but nothing is showing up.  Any suggestions?

**Comment by vvaldersteins** [comment]
Same here!

**Comment by javiertrillo** [comment]
I have the same problem.

I'm trying to use the chartjs-plugin-annotation plugin to configure 3 box annotations bound to my Y axis, but it doesn't work.

I follow this example but its not working:

http://plnkr.co/edit/06pviURN80eto8lsGRjE?p=catalogue

**Comment by detchison** [comment]
Looking for this as well, have tried many things

**Comment by GeorgeBark** [comment]
Any news on this? Having the same issue here. Thanks!

**Comment by detchison** [comment]
I was able to get it to work by installing it via npm, and including it the the scrips of angular-cli.json. Definitely sure this isnt the correct way but it does work

**Comment by zperee** [comment]
@detchison I was trying the same but for me, it was not working. Could you provide more information on how you have done it?

Thanks

**Comment by somejavadev** [comment]
Is anyone looking into this? @GeorgeBark which file exactly did you modify to get this working, I don't see that snippet in my index.ts file in ng2-charts?

**Comment by GeorgeBark** [comment]
@somejavadev it was in **node_modules/ng2-charts-x/index.js**

This is my patch file:

```diff
patch-package
--- a/node_modules/ng2-charts-x/index.js
+++ b/node_modules/ng2-charts-x/index.js
@@ -1,5 +1,6 @@
 import { Directive, ElementRef, EventEmitter, Input, NgModule, Output } from '@angular/core';
-import Chart from 'chart.js';
+//import Chart from 'chart.js'; // <-- creation of new instance, breaks plugins
+const Chart = window.Chart; // <-- using exising instance
 import 'moment';
 
 var BaseChartDirective = (function () {
```

Hope it helps

**Comment by somejavadev** [comment]
Thanks @GeorgeBark for the quick response, not sure if I am missing something basic here, my node package is in the folder: /node_modules/ng2-charts/ and the content of my index.js looks as follows (no -x at the end of the folder name):
`"use strict";
function __export(m) {
    for (var p in m) if (!exports.hasOwnProperty(p)) exports[p] = m[p];
}
__export(require("./charts/charts"));` I am using "ng2-charts": "^1.6.0",

**Comment by GeorgeBark** [comment]
You are right @somejavadev, I am using [this fork](https://github.com/donothingloop/ng2-charts-x#readme). 

I guess that in your case, the line to change is line 12 of  **node_modules/ng2-charts/charts/charts.js**:

```javascript
//var chart_js_1 = require("chart.js");
var chart_js_1 = window.Chart
```
But I might be wrong, haven't tested that.

**Comment by somejavadev** [comment]
@GeorgeBark thanks, experimenting with a couple of changes, I already tried that change, otherwise I will try the fork you are using.

**Comment by somejavadev** [comment]
@GeorgeBark thanks I have managed to get it to work using the forked branch. I also see that the annotations doesn't work with scatter graphs which I was using, only changing to line graphs made the annotation appear. I will see if I can make a fix for it to work with scatter graphs as well.

**Comment by VivekShingala** [comment]
Hi @somejavadev 
Did you manage to work annotations with scatter graph as well? Please share it here as I am facing the same issue. Thanks.

**Comment by somejavadev** [comment]
@VivekShingala I managed to get it working using @GoergeBark's fork. The important thing was to specify the scales option of the chart via

```
options: {
        scales: {
            xAxes: [{
                type: 'linear',
                position: 'bottom'
            }]
        }
    }
```

**Comment by Antonyselt** [comment]
@somejavadev How you manage to get it work? I replace the ng2-charts for ng2-charts-x and I tried what @GeorgeBark said about the instance, but It breaks, because I don't use chart = new Chart. so there is no chart and it breaks my application

**Comment by paviad** [comment]
Please checkout the [demo](https://valor-software.com/ng2-charts/) app for an example of how to use `chartjs-plugin-annotation` - Look under **Line Chart**
