### ISSUE TITLE
How to set background color of plot area?

### ISSUE THREAD

**Issue by manjitsingh91** [valor-software/ng2-charts#729]
How can we set the background color of the plot area like this http://jsfiddle.net/rrcd60y0/

**Comment by ver0nikadataformers** [comment]
has there been a fix for this question? I need a solution too for exporting the images without a transparent background.

**Comment by ver0nikadataformers** [comment]
if this is a solved issues, could someone please be so kind as to point us the answer?

**Comment by ver0nikadataformers** [comment]
@manjitsingh91 : can you please add the label "help wanted"?

**Comment by paviad** [comment]
This package is now updated for Angular 7 and chart.js 2.7.45. Can you provide an updated stackblitz/jsfiddle?

**Comment by paviad** [comment]
I'm not an expert on plugins, but this works:

```typescript
  constructor() {
    BaseChartDirective.registerPlugin({
      beforeDraw(chart, easing) {
        const ctx = chart.ctx;
        const chartArea = chart.chartArea;

        ctx.save();
        ctx.fillStyle = '#555555';
        ctx.fillRect(chartArea.left, chartArea.top, chartArea.right - chartArea.left, chartArea.bottom - chartArea.top);
        ctx.restore();
      }
    });
  }
```
