### ISSUE TITLE
anuglar2 compatible ?

### ISSUE THREAD

**Issue by AndrewKralovec** [valor-software/ng2-charts#731]
**Reproduction of the problem**

Does anyone know a ng2-charts version that is comptatble with anuglar2: 2.0.0 ?
I tried adding this to my project and im getting errors, so im hoping there is an older version out there that will work with 2.0.0

Thanks 

package.json 

```
{
  "name": "Angular2Spa",
  "version": "0.0.0",
  "dependencies": {
    "@angular/common": "2.0.0",
    "@angular/compiler": "2.0.0",
    "@angular/core": "2.0.0",
    "@angular/forms": "2.0.0",
    "@angular/http": "2.0.0",
    "@angular/platform-browser": "2.0.0",
    "@angular/platform-browser-dynamic": "2.0.0",
    "@angular/platform-server": "2.0.0",
    "@angular/router": "3.0.0",
    "@types/node": "^6.0.38",
    "angular2-fullcalendar": "^1.1.1",
    "angular2-platform-node": "~2.0.10",
    "angular2-universal": "~2.0.10",
    "angular2-universal-polyfills": "~2.0.10",
    "aspnet-prerendering": "^1.0.6",
    "aspnet-webpack": "^1.0.11",
    "bootstrap": "^3.3.7",
    "chart.js": "^2.5.0",
    "css": "^2.2.1",
    "css-loader": "^0.25.0",
    "es6-shim": "^0.35.1",
    "expose-loader": "^0.7.1",
    "extract-text-webpack-plugin": "^1.0.1",
    "file-loader": "^0.9.0",
    "isomorphic-fetch": "^2.2.1",
    "jquery": "^2.2.1",
    "ng2-charts": "^1.5.0",
    "preboot": "^4.5.2",
    "raw-loader": "^0.5.1",
    "rxjs": "5.0.0-beta.12",
    "style-loader": "^0.13.0",
    "to-string-loader": "^1.1.5",
    "ts-loader": "^0.8.2",
    "typescript": "^2.0.0",
    "url-loader": "^0.5.7",
    "webpack": "^1.12.14",
    "webpack-externals-plugin": "^1.0.0",
    "webpack-hot-middleware": "^2.10.0",
    "webpack-merge": "^0.14.1",
    "zone.js": "^0.6.21"
  }
}



```

**Comment by zbagley** [comment]
Best bet would be to just keep downgrading ng2-charts until you find a suitable version! Of course you might run into problems with the possibly needing a downgraded version of chart.js.
Change "ng2-charts": "1.0.0" and go down from there if needed.

Is there a specific reason for not upgrading your angular components to 2.3 (I think that's what's required, and it is a non-breaking release)?

**Comment by hshinde** [comment]
I am facing an issue while running the demo app.
My package.json is as given below. I am using latest angular versions.

`{
  "name": "ng2-charts-base",
  "version": "1.5.0",
  "private": true,
  "description": "Reactive, responsive, beautiful charts for Angular2 based on Chart.js",
  "scripts": {
    "lite-server": "lite-server -c demo/bs-config.json",
    "demo.serve": "run-s build link demo.build lite-server",
    "demo.gh-pages": "run-s build demo.build demo.deploy",
    "demo.build": "ng build -prod --aot",
    "demo.deploy": "gh-pages -d demo/dist",
    "link": "ngm link -p src --here",
    "lint": "exit 0",
    "disable-lint": "tslint \"**/*.ts\" -c tslint.json --fix --type-check -t prose -e \"node_modules/**\" -e \"dist/**\" -e \"temp/**\" -e \"scripts/docs/**\"",
    "flow.changelog": "conventional-changelog -i CHANGELOG.md -s -p angular",
    "flow.github-release": "conventional-github-releaser -p angular",
    "build": "ngm build -p src --clean",
    "build.watch": "ngm build -p src --watch --skip-bundles",
    "start": "ng serve --aot",
    "pretest": "run-s lint build link",
    "test": "ng test -sr",
    "test-coverage": "ng test -sr -cc",
    "version": "npm run flow.changelog && git add -A"
  },
  "main": "bundles/ng2-charts.umd.js",
  "module": "index.js",
  "typings": "index.d.ts",
  "keywords": [
    "angular",
    "chart.js",
    "angular2",
    "angularjs",
    "charts"
  ],
  "author": "Dmitriy Shekhovtsov <valorkin@gmail.com>",
  "license": "MIT",
  "repository": {
    "type": "git",
    "url": "git+ssh://git@github.com/valor-software/ng2-charts.git"
  },
  "bugs": {
    "url": "https://github.com/valor-software/ng2-charts/issues"
  },
  "homepage": "https://github.com/valor-software/ng2-charts#readme",
  "dependencies": {
    "chart.js": "^2.5.0"
  },
  "peerDependencies": {
    "@angular/common": "^2.3.0",
    "@angular/core": "^2.3.0"
  },
  "devDependencies": {
    "@angular/cli": "^1.0.0",
    "@angular/common": "2.4.3",
    "@angular/compiler": "2.4.3",
    "@angular/compiler-cli": "2.4.3",
    "@angular/core": "2.4.3",
    "@angular/forms": "2.4.3",
    "@angular/http": "2.4.3",
    "@angular/language-service": "2.4.3",
    "@angular/platform-browser": "2.4.3",
    "@angular/platform-browser-dynamic": "2.4.3",
    "@angular/router": "3.4.3",
    "@angular/tsc-wrapped": "0.5.1",
    "@ngtools/webpack": "1.2.3",
    "@types/jasmine": "2.5.40",
    "@types/marked": "0.0.28",
    "@types/node": "7.0.0",
    "@types/webpack": "^2.2.1",
    "bootstrap": "3.3.7",
    "chokidar-cli": "1.2.0",
    "classlist-polyfill": "1.0.3",
    "codecov": "1.0.1",
    "codelyzer": "~2.0.0-beta.4",
    "conventional-changelog-cli": "1.2.0",
    "conventional-github-releaser": "1.1.3",
    "core-js": "^2.4.1",
    "cpy": "5.0.0",
    "cpy-cli": "1.0.1",
    "del-cli": "0.2.1",
    "gh-pages": "0.12.0",
    "gitignore-to-glob": "0.3.0",
    "google-code-prettify": "1.0.5",
    "html-loader": "0.4.4",
    "jasmine": "2.5.3",
    "jasmine-core": "2.5.2",
    "jasmine-data-provider": "2.2.0",
    "jasmine-spec-reporter": "3.2.0",
    "karma": "1.4.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "0.4.0",
    "karma-sauce-launcher": "1.1.0",
    "lite-server": "2.2.2",
    "lodash": "4.17.4",
    "markdown-loader": "^0.1.7",
    "marked": "0.3.6",
    "ng2-bootstrap": "1.2.2",
    "ng2-page-scroll": "4.0.0-beta.2",
    "ngm-cli": "0.4.0",
    "npm-run-all": "^4.0.1",
    "pre-commit": "1.2.2",
    "protractor": "5.0.0",
    "reflect-metadata": "0.1.9",
    "require-dir": "0.3.1",
    "rxjs": "5.0.3",
    "systemjs-builder": "0.15.34",
    "ts-helpers": "^1.1.1",
    "ts-node": "2.0.0",
    "tslint": "4.3.1",
    "tslint-config-valorsoft": "1.2.0",
    "typedoc": "0.5.5",
    "typescript": "2.1.5",
    "wallaby-webpack": "0.0.30",
    "webdriver-manager": "11.1.1",
    "zone.js": "0.7.5"
  },
  "contributors": [
    {
      "name": "Dmitriy Shekhovtsov",
      "email": "valorkin@gmail.com",
      "url": "https://github.com/valorkin"
    },
    {
      "name": "Soloviova Nataliya",
      "email": "nataliya.soloviova@valor-software.com",
      "url": "https://github.com/natali-abyss"
    }
  ]
}`

**Comment by zbagley** [comment]
@hshinde I'm happy to help, but will need a bit more information. If you could describe the issue a bit more and provide any error messages we can get it fixed up.

**Comment by hshinde** [comment]
I am getting following error on npm install command:

`ERROR in /Volumes/Projects/work/anand/pure-savannah-63184.bkp/node_modules/@types/lodash/index.d.ts (11587,21): ']' expected.
/Volumes/Projects/work/anand/pure-savannah-63184.bkp/node_modules/@types/lodash/index.d.ts (11587,22): ';' expected.
/Volumes/Projects/work/anand/pure-savannah-63184.bkp/node_modules/@types/lodash/index.d.ts (11587,23): Declaration or statement expected.
/Volumes/Projects/work/anand/pure-savannah-63184.bkp/node_modules/@types/lodash/index.d.ts (11587,33): ']' expected.
/Volumes/Projects/work/anand/pure-savannah-63184.bkp/node_modules/@types/lodash/index.d.ts (11587,34): ')' expected.
/Volumes/Projects/work/anand/pure-savannah-63184.bkp/node_modules/@types/lodash/index.d.ts (11587,35): Declaration or statement expected.
/Volumes/Projects/work/anand/pure-savannah-63184.bkp/node_modules/@types/lodash/index.d.ts (11587,37): Declaration or statement expected.
/Volumes/Projects/work/anand/pure-savannah-63184.bkp/node_modules/@types/lodash/index.d.ts (19580,1): Declaration or statement expected.
/Volumes/Projects/work/anand/pure-savannah-63184.bkp/node_modules/@types/lodash/index.d.ts (241,13): Duplicate identifier '_'.
/Volumes/Projects/work/anand/pure-savannah-63184.bkp/node_modules/@types/lodash/index.d.ts (245,19): Duplicate identifier '_'.
/Volumes/Projects/work/anand/pure-savannah-63184.bkp/node_modules/@types/lodash/index.d.ts (241,16): Cannot find namespace '_'.
/Volumes/Projects/work/anand/pure-savannah-63184.bkp/node_modules/@types/lodash/index.d.ts (243,25): Cannot find name 'Partial'.
/Volumes/Projects/work/anand/pure-savannah-63184.bkp/node_modules/@types/lodash/index.d.ts (362,39): Cannot find namespace '_'.`

**Comment by zbagley** [comment]
This appears to be an lodash module problem. First try npm uninstall lodash and then npm install. If that doesn't fix it I'd suggest deleting lodash folders manually (all lodash) and try rerunning npm install. If that doesn't work, delete the entire node_module folder to run a clean npm install. If those don't work you might want to try adding "@types/lodash": "0.0.28" to dev dependencies or lowering your version to "lodash": "^4.12.0" and repeating.

**Comment by paviad** [comment]
Project is now compatible with Angular 7.
