### ISSUE TITLE
Can't set autoSkipPadding

### ISSUE THREAD

**Issue by jans-y** [valor-software/ng2-charts#743]
Hi,

I was trying for several hours to find solution but couldn't do it.

Could you please help me where should I define autoSkipPadding?

Here is part of my code and it isn't working.

<pre>
public lineChartOptions:any = {
    responsive: true,
    elements: {
      point: {
        radius: 0
      }
    },
    scale: {
      ticks: {
        autoSkipPadding: 5 // <-- Doesn't work :-(
      }
    },
......
</pre>

Thank you very much for your responses.

**Comment by paviad** [comment]
You spelled `scales` wrong...

```typescript
    public chartOptions: ChartOptions = {
      scales: {
        ticks: {
          autoSkipPadding: 5
        }
      }
    };
```
