### ISSUE TITLE
Is there a way to customize the legend text on a doughnut chart?

### ISSUE THREAD

**Issue by bkartik2005** [valor-software/ng2-charts#744]
Hi,
   Is it possible to customize the default legend text.

For example - I need to show the legend text with the value - Lable + {value}
Red (6) , Blue (7) , Green (10)

I could change the label property of the dataset , but problem with that is that tooltip shows the value twice.

**Comment by Danielapariona** [comment]
help! :(

**Comment by sirius2013** [comment]
can you create issue on stackoverflow also?
and let me know link.

**Comment by paviad** [comment]
It's possible using the plugin interface. See this stackblitz https://stackblitz.com/edit/ng2-charts-legend-with-value

![image](https://user-images.githubusercontent.com/1235688/54071714-55d4db80-4279-11e9-83d4-f5e00728219b.png)
