### ISSUE TITLE
Ng2-charts cannot handle empty datasets

### ISSUE THREAD

**Issue by grahammutter** [valor-software/ng2-charts#751]
The library currently cannot handle empty datasets, even though this is supported by Chart.js itself. Possible solutions here include rendering an empty chart, or displaying a "No Data" warning instead of a chart (using a chart.js afterDraw plugin).

I'll begin work on this ~April 26th.

**Comment by alexnb11** [comment]
There is next error 
Cannot read property 'data' of undefined at BaseChartDirective.updateChartData
if you are trying set data empty array( data = [] )

**Comment by azarus** [comment]
Same issue here, looks like this lib is slighly untested.

**Comment by VlnRbn** [comment]
How to handle this, any suggetions?

**Comment by prashantpimpale93** [comment]
Any updates?

**Comment by prashantpimpale93** [comment]
@grahammutter Any updates?

**Comment by paviad** [comment]
Empty data set seems to work: https://stackblitz.com/edit/angular-uy819g

**Comment by mikegoodstadt** [comment]
@grahammutter @alexnb11 @azarus @VlnRbn I think that the difference between your observations above and the closing comment by @paviad lies in what each means by an empty dataset. A completely empty `datasets` array will not work:
`datasets: ChartDataSets[] = []; // <-- this is not enough`

However, as in the example given by @paviad, a `datasets` array will work if is contains a single "dummy" dataset object **with an empty array for the [data] value**:
1. This is the minimum required as shown in @paviad's example (Label is optional but avoids it appearing as undefined...):
`datasets: ChartDataSets[] = [ { data: [], label: '' } ];`

2. Or declare the variable and then assign in the constructor. This allows for dynamic assignment of the dummyData.
```
@Input() datasets: ChartDataSets[];
@Input() dummyData = { label: 'Dummy Dataset', data: [] }; 
...
  constructor() {
    this.datasets = [ dummyData ];
  }
```

p.s. I think that the name for ChartDataSets is misleading as it is the definition for only a single dataset, which needs to be part of an array to be valid input...

**Comment by benwinding** [comment]
Future readers, here's how I prevented the error:
``` jsx
      <canvas
        baseChart
        *ngIf="!!myDataSets?.length"
        [datasets]="myDataSets"
        [options]="options"
      >
      </canvas>
```
Only renders the canvas if there's at least a single dataset in the array

**Comment by JaapWeijland** [comment]
Why close this? I still have this issue when providing an empty array.

**Comment by azarus** [comment]
@JaapWeijland use `*ngIf` so the component won't be constructed unless data is available.
