### ISSUE TITLE
Ng2-Charts does not provide a mechanism to add plugins to underlying chart.js instance.

### ISSUE THREAD

**Issue by grahammutter** [valor-software/ng2-charts#752]
Some of the beauty of chart.js is how extensible it's behaviors are with feature plugins, which currently cannot be set via ng2-charts. An interface to set custom plugins would allow greater customization of the charts.

I will begin work on this ~April 26th.

**Comment by olivermuc** [comment]
Any updates on this or workarounds? @grahammutter 
It may be sufficient to amend the class with loading the plugin code after chart.js is imported.

Would an ìmport`statement suffice or do we need to add the plugin JS file in index.html after the main.js is loaded? The loading order appears to be critical.

**Comment by olivermuc** [comment]
Here is my workaround, based on the fact that I already have made a local copy with other fixes [see this thread](https://github.com/valor-software/ng2-charts/issues/806) #806: 
 
```
import * as ChartAnnotation from  'chartjs-plugin-annotation';
```
and
```
public constructor(element: ElementRef) {
	this.element = element;
	let loadPluginJS = ChartAnnotation;
}
```

**Comment by detchison** [comment]
Where are you putting these changes? I dont seem to be able to get this to work, the same plugin

**Comment by tucq88** [comment]
Me too, I can't get it work as well as @detchison comment.

**Comment by micobarac** [comment]
```typescript
import * as ChartJs from 'chart.js';
import * as ChartAnnotation from 'chartjs-plugin-annotation';

ngOnInit() {
    ChartJs.Chart.pluginService.register(ChartAnnotation);
}
```

Cheers :)

**Comment by tucq88** [comment]
@micobarac With this implementation, plugins will be applied globally - which is not recommend as performance effect and redundant usages :( 
I'm trying to find a way that could add plugin to specific charts, e.g you have 3 charts, but you just want to add plugins for one.

**Comment by AlexGamezo** [comment]
I'm trying to add an instance-specific plugin. Why not add support for passing in plugins to use as part of the chart creation? I see an open PR for adding global plugins, but nothing for just passing in a list of plugins as part of the new Chart(...) options param. Anything in the works for that?

**Comment by alexzaytsev-newsroomly** [comment]
Any updates?

**Comment by haimomesi** [comment]
What I did was register the custom plugin **globally**, with a specific id. then, in chart instance **options**, disable the plugin by id.

example:

`
// implement your own hooks here
let chartPlugin = {
      id: 'plugin1',
      beforeInit(chartInstance) {
         // implement your own
      },
      afterDatasetsDraw: (chartInstance) => {
         // implement your own
      },
      destroy: (chartInstance) => {
        // implement your own
      }
    };

    // to prevent multiple registration. can also move the register part to a service
    if (!Chart.pluginService.getAll().filter(p => p.id === 'plugin1')[0]) {
      Chart.pluginService.register(this.chartPlugin);
    }

    // if you want to exclude this plugin for a specific chart 

   let chartOptions = {
        plugins: {
              plugin1: false
        }
   };
`

**Comment by alexistoulotte** [comment]
To include `chartjs-plugin-annotation` in your angular project, you just have to import it at the end of `src/polyfills.ts` file:

```typescript
import 'chartjs-plugin-annotation';
```

If you do a `Chart.pluginService.register(ChartAnnotation);` registration in `ngOnInit` it will be performed each time component is rendered.

**Comment by abannsunny** [comment]
> What I did was register the custom plugin **globally**, with a specific id. then, in chart instance **options**, disable the plugin by id.
> 
> example:
> 
> `
> // implement your own hooks here
> let chartPlugin = {
> id: 'plugin1',
> beforeInit(chartInstance) {
> // implement your own
> },
> afterDatasetsDraw: (chartInstance) => {
> // implement your own
> },
> destroy: (chartInstance) => {
> // implement your own
> }
> };
> 
> ```
> // to prevent multiple registration. can also move the register part to a service
> if (!Chart.pluginService.getAll().filter(p => p.id === 'plugin1')[0]) {
>   Chart.pluginService.register(this.chartPlugin);
> }
> 
> // if you want to exclude this plugin for a specific chart 
> ```
> let chartOptions = {
> plugins: {
> plugin1: false
> }
> };
> `

This worked perfectly for me!! thank you

**Comment by paviad** [comment]
Please refer to https://github.com/valor-software/ng2-charts/issues/1058#issuecomment-469021112 for an example on how to register a plugin.

**Comment by sridhark158** [comment]
@alexistoulotte 
ngOnInit() {
    Chart.pluginService.register(ChartAnnotation);
    Chart.pluginService.register(ChartZoom);
} is not working for me in angular 7.2 version 

But it was working fine when i was use with angular 6

**Comment by mikegoodstadt** [comment]
Has anyone had any luck integrating [chartsjs-plugin-gantt](https://github.com/anton-shchyrov/chartjs-plugin-gantt/issues/new)?
