### ISSUE TITLE
Global chart dataoptions cannot be set

### ISSUE THREAD

**Issue by grahammutter** [valor-software/ng2-charts#753]
The global/default chart dataoption configuration feature of chart.js cannot be set currently.

http://www.chartjs.org/docs/#chart-configuration-global-configuration

I will begin work on this ~April 26th.

**Comment by chinaowl** [comment]
Is there any workaround for this right now? I would like to set some global font settings.

**Comment by the-catalin** [comment]
yes, i'd love to see a workaround for this

**Comment by evandrogrm** [comment]
```
for (let i = 0; i < this.chart.data.datasets.length; i++) {
     this.chart.data.datasets[i].borderWidth = 2;
}
```

**Comment by s-patompong** [comment]
Came across this issue and it made me look at .ts source code. Here is how you can set default for the charts.

```typescript
// Import
import Chart from "chart.js";

// ngOnInit() method
ngOnInit() {
	// Set default font size to 10 pixel
	Chart.defaults.global.defaultFontSize = 10;
}
```

I use ng2-charts version ^2.3.0.

Hope this helps :)

**Comment by santam85** [comment]
Fixed in v3+
