### ISSUE TITLE
Pie chart onClick Event not returning any selected label data

### ISSUE THREAD

**Issue by harishkumarreddy12** [valor-software/ng2-charts#765]
Pie chart onClick Event not returning any selected label data. 
![issue](https://cloud.githubusercontent.com/assets/16139974/25422283/0404c2bc-2a7e-11e7-9938-e0d945fd9bce.PNG)

**Comment by MorlaRamakrishna** [comment]
For me also the same issue, we are in need to strictly present data.

**Comment by paviad** [comment]
This package was updated for Angular 7, please see the demo app under *Pie Chart* and hover and click on the chart to see events in the javascript console.
