### ISSUE TITLE
How can i get multi charts(bar and line) with ng2-charts?

### ISSUE THREAD

**Issue by neelshah23** [valor-software/ng2-charts#767]

**Comment by JessyRiordan** [comment]
Have you figured this out yet? I am also looking to be able to do this (bar and line) in one chart.

**Comment by olavoshibata** [comment]
I am also looking for it.

**Comment by sofialunkes** [comment]
nothing related?

**Comment by lblower** [comment]
If you need something link in this link [https://codepen.io/Karl53/pen/MbYrPN](https://codepen.io/Karl53/pen/MbYrPN)

i guess one need to add "type" attribute in your data
like below is the data variable (code)  i passed to barchart and get bar chart for currency and line chart for days

> barChartData = [
>       {data: [1,3,5,6], label: 'Days',**type:'line'**,  yAxisID: 'yAxis1'},
>       {data: [11,4,11,32], label: "currency" , yAxisID: 'yAxis2'}
>     ];

**Comment by paviad** [comment]
@lblower has the right answer, see this stackblitz https://stackblitz.com/edit/ng2-charts-bar-and-line

![image](https://user-images.githubusercontent.com/1235688/54071700-28882d80-4279-11e9-9c0c-77830ff56781.png)

**Comment by imvikaskohli** [comment]
@paviad You saved our life Thanks genius
