### ISSUE TITLE
installing components

### ISSUE THREAD

**Issue by 20centcroak** [valor-software/ng2-charts#783]
Hi,
I'm new to angular and then my questions could be very naive. 
First here are pieces of information about my angular versions:
@angular/cli: 1.0.1
node: 7.9.0
os: win32 x64
@angular/common: 4.1.0
@angular/compiler: 4.1.0
@angular/core: 4.1.0
@angular/forms: 4.1.0
@angular/http: 4.1.0
@angular/platform-browser: 4.1.0
@angular/platform-browser-dynamic: 4.1.0
@angular/router: 4.1.0
@angular/cli: 1.0.1
@angular/compiler-cli: 4.1.0

I followed the instructions to install via npm ng2-charts, chart.js and I have imported the component in my modules. 
But chart.js installed in node_modules which is as the same level than my src directory. Using "<script src="../node_modules/chart.js/src/chart.js"></script>" in the index.html file, I always have an error (can't get the file). Then I moved manually chart.js in the assets diretcory for a try. Then  using "<script src="./assets/chart.js/src/chart.js"></script>" there is no getting error while observing the console.
However I always have the following error: ERROR Error: ng2-charts configuration issue: Embedding Chart.js lib is mandatory

Can you help?

**Comment by mark-win** [comment]
If you used @angular/cli to create the project, you can let webpack handle the js assets for you.
Instead of including the .js files yourself in index.html, you need to add the path to your .angular-cli.json like this:
```
...
    "apps": [
        ...
        "scripts": [
            ...
            "../node_modules/chart.js/src/chart.js",
            ...
        ],
        ...
    ]
...
```
Notice that changes to .angular-cli.json will not affect right away, if you use `ng serve`. You will need to  re run the command.

Also notice that there also is a `styles` member next to `scripts` where you can do the same to .css or .scss files

**Comment by 20centcroak** [comment]
Thanks for your help. It is very useful. Now I don't have to put chart.js in the asset directory and there is no "getting" error.

However I still have the same error with ng2-charts : 

```
ERROR Error: ng2-charts configuration issue: Embedding Chart.js lib is mandatory
Trace de la pile :
BaseChartDirective.prototype.getChartBuilder@http://localhost:4200/vendor.bundle.js:66143:19 [angular]
BaseChartDirective.prototype.refresh@http://localhost:4200/vendor.bundle.js:66199:22 [angular]
BaseChartDirective.prototype.ngOnInit@http://localhost:4200/vendor.bundle.js:66085:13 [angular]
```
Any idea ?

**Comment by mark-win** [comment]
Make sure you rebuild the entire app (i.e. re-run `ng serve`), so changes to .angular-cli.json take effect.

Try reloading the page without caches isn't a bad idea as well.

Finally, if nothing works, I can only suggest, to look for chart.js specific code in the stuff that is being sent to your browser. I.e. I just found `Chart.Bar = function(context, config) {` in the file 0.chunk.js. Could be any other leading number in your case or vendor.bundle.js, if you don't use any lazy loading.
Then you should know, weather the lib is loaded by your client or not, which is the closest I can get you to the problem. Sadly I'd have no clue how to fix it either way, as the first two steps should have done already.

**Comment by 20centcroak** [comment]
Thanks. rebuild and empty the cache does not fix the pb sadly. The message "Embedding Chart.js lib is mandatory" let me think that chart.js is not accessible but I don't know why and I may be wrong...

**Comment by mark-win** [comment]
Try including the built version of chart.js:
```
"scripts": [
        "../node_modules/chart.js/dist/Chart.bundle.min.js"
      ],
```

**Comment by 20centcroak** [comment]
And it works ! 
Tanks so much for your help, I really appreciate.
