### ISSUE TITLE
Passing colors to a pie chart results in gray segments

### ISSUE THREAD

**Issue by cbruce11** [valor-software/ng2-charts#784]
` <canvas baseChart
                        [data]="pieChartData"
                        [labels]="pieChartLabels"
                        chartType="doughnut"
                        [colors]="pieChartColors"
                        legend="false"
                        (chartHover)="chartHovered($event)"
                        (chartClick)="chartClicked($event)"></canvas>
`
This is the html element and the labels and data work fine, but the colors are not rendering. Below is the array that is being passed in. When I inspect the array of colors show up on the element but they are all rendering as gray

`
    public pieChartColors:string[] = ['#2CCC32', '#FFE22B', '#FF6384'];
`

**Comment by hirenalken** [comment]
How did you solve this?

**Comment by ayyash** [comment]
@cbruce11 you closed the issue, did you get around it?

**Comment by AChandel01071994** [comment]
pass colors like this- 

colors = {
    backgroundColor: [
      "#E42000",
      "#56D8E9"
    ]
  };

**Comment by madmacc** [comment]
Has anyone got an idea of why this happens?
Colors work fine if I hardcode the data.
If I load the data then it is gray.  Even if I assign the colors again after loading the data.
