### ISSUE TITLE
Can't adjust barThickness in a horizontal bar chart

### ISSUE THREAD

**Issue by laurenskvh** [valor-software/ng2-charts#786]
```
  public barChartOptions: any = {
    scales: {
      yAxes: [{
        barThickness: 50,
        display: false,
        stacked: true,
      }]
    }
  };
```

Does not seem to respond to the barThickness option

**Comment by warriotox** [comment]
Facing the same issue. Did you figure it out by any chance?

**Comment by paviad** [comment]
This now works. See this stackblitz https://stackblitz.com/edit/ng2-charts-horizontalbar-stack-barwidth
