### ISSUE TITLE
Change dataset length causes ERROR

### ISSUE THREAD

**Issue by nicolassharp** [valor-software/ng2-charts#791]
Say you start with dataset `(7) [Object, Object, Object, Object, Object, Object, Object]` and later change it to dataset `(3) [Object, Object, Object]` you get the error `ERROR TypeError: Cannot read property 'data' of undefined`.

This seems to be a new problem, works when going back to 1.4.4

**Comment by Wihan** [comment]
I'm having the same problem, the dataset does not seem to be rebinding when the input changes to the chart component

**Comment by nicolassharp** [comment]
@Wihan Until this is fixed going back to 1.4.4 is the easiest solution...

**Comment by lastnod** [comment]
same problem update data properly but not background color in bubble chart
if you update 2 times colors dont changes
` public randomize():void {
    let chart = []

    for(let j = 0; j<10 ;j++){
        chart.push(
        {
            label: ''+j,
            data: [],
            backgroundColor:this.randomColor(),
            hoverBackgroundColor: this.randomColor(),
        })
      let data = []
      for(let i = 0; i<10 ;i++){
        data.push({x: Math.random()*100,y: Math.random()*100,r: 8})
      }
      chart[j].data = data;
      
    }
    this.ChartData = chart;
    console.log(this.ChartData)
  }
   randomColor() {
    var letters = '0123456789ABCDEF';
    var color = '#';
    for (var i = 0; i < 6; i++ ) {
        color += letters[Math.floor(Math.random() * 16)];
    }
    return color;
  }`

**Comment by kbakozoda** [comment]
Just make the size of chart dataset equal to the size of your new dataset, something like:
```
....fill in this.lineChartData array with some data, then:

 this._chart.chart.data.datasets.length = this.lineChartData.length; 
 this._chart.chart.update();

assuming that your chart is defined in layout like this:

<canvas baseChart class="chart"
            [datasets]="lineChartData"
            [labels]="lineChartLabels"
            [options]="lineChartOptions"
            [colors]="lineChartColours"
            [legend]="lineChartLegend"
            [chartType]="lineChartType"
            (chartHover)="chartHovered($event)"
            (chartClick)="chartClicked($event)"></canvas>
```

**Comment by skotturi** [comment]
I went with @kbakozoda's workaround because v1.4.4 was giving me import errors with an Ionic3/NG4 project that v1.6 was not. It's working but seems bizarre that I can't remove a dataset from a radar chart but I can remove labels w/o a problem.

**Comment by paviad** [comment]
This should be fixed now.
