### ISSUE TITLE
How to display value on Chart (ionic 2)?

### ISSUE THREAD

**Issue by venkadesh02** [valor-software/ng2-charts#802]
I want to display plotted values on Chart always. Currently its showing when user hover / click on the chart. How to show values always on the chart? i attached the sample image that i want to display the values (i attached bar chart but i want to display values on all type of charts).
![screen shot 2017-05-17 at 12 14 42 pm](https://cloud.githubusercontent.com/assets/3060733/26141662/9b7742aa-3afa-11e7-914c-c5c3f05384e1.png)

**Comment by seksitha** [comment]
Replace this options in my component is working. 
Credit [https://stackoverflow.com/questions/37028046/bar-values-in-chart-js-2-x-dataset-metadata-undefined](stackoverfolw)
```
public lineChartOptions: any = {
    responsive: true,
    tooltips: {
      enabled: false
    },
    animation: {
      onComplete: function () {
        var ctx = this.chart.ctx;
        ctx.textAlign = "center";
        ctx.textBaseline = "middle";
        var chart = this;
        var datasets = this.config.data.datasets;

        datasets.forEach(function (dataset: Array<any>, i: number) {
          ctx.font = "10px Arial";


          ctx.fillStyle = "Black";
          chart.getDatasetMeta(i).data.forEach(function (p: any, j: any) {
            ctx.fillText(datasets[i].data[j], p._model.x, p._model.y - 20);
          });

        });
      }
    },
    legend: {
      display: true,
      labels: {
        fontColor: 'rgb(255, 99, 132)'
      }
    }
  }
```

**Comment by venkadesh02** [comment]
Great!! Working fine. Thanks.

**Comment by venkadesh02** [comment]
Can you please tell me how display values on donut chart ?

**Comment by seksitha** [comment]
OK, after searching for a while I only have solution of showing all tooltips.
[stackOverflow](https://stackoverflow.com/questions/40592920/showing-tooltips-all-the-time-in-chartjs-2-4-not-working)
First you need to create a chartjs plugin and import it to your app.

here is the code.
`Chart.pluginService.register({
  beforeRender: function(chart) {
    if (chart.config.options.showAllTooltips) {
      // create an array of tooltips
      // we can't use the chart tooltip because there is only one tooltip per chart
      chart.pluginTooltips = [];
      chart.config.data.datasets.forEach(function(dataset, i) {
        chart.getDatasetMeta(i).data.forEach(function(sector, j) {
          chart.pluginTooltips.push(new Chart.Tooltip({
            _chart: chart.chart,
            _chartInstance: chart,
            _data: chart.data,
            _options: chart.options.tooltips,
            _active: [sector]
          }, chart));
        });
      });

      // turn off normal tooltips
      chart.options.tooltips.enabled = false;
    }
  },
  afterDraw: function(chart, easing) {
    if (chart.config.options.showAllTooltips) {
      // we don't want the permanent tooltips to animate, so don't do anything till the animation runs atleast once
      if (!chart.allTooltipsOnce) {
        if (easing !== 1)
          return;
        chart.allTooltipsOnce = true;
      }

      // turn on tooltips
      chart.options.tooltips.enabled = true;
      Chart.helpers.each(chart.pluginTooltips, function(tooltip) {
        tooltip.initialize();
        tooltip.update();
        // we don't actually need this since we are not animating tooltips
        tooltip.pivot();
        tooltip.transition(easing).draw();
      });
      chart.options.tooltips.enabled = false;
    }
  }
});`

in the chart component 

`  public options: any = {
    responsive: true,
    showAllTooltips:true,
    legend: {
      display: true,
      labels: {
        fontColor: 'rgb(255, 99, 132)'
      }
    }
  };`
In view
`  <canvas baseChart
              [data]="doughnutChartData"
              [labels]="doughnutChartLabels"
              [chartType]="doughnutChartType"
              [options]="options">

  </canvas>`

**Comment by venkadesh02** [comment]
Is it not possible to display the value inside the donut chart like what is shown in image?

**Comment by shashank00000007** [comment]
can u tell me how to do it for pie chart?

**Comment by seksitha** [comment]
I believe it is the same in Pie chart. If you get the donut chart to work it will work the same.

**Comment by lakshyamathur1** [comment]
I want to display values of legends in descending order so how to do this?

**Comment by seksitha** [comment]
@lakshyamathur1 I'm not clear about your question. what kind of chart do you refer to?
Anyway, I guess you want to display chart from high value down to lowest one? 
then just short your model before pass to chat `[data] = chartDataAfterShort`

**Comment by lakshyamathur1** [comment]
@seksitha 
Thanks for your response 
See I am using ng2-doughnut chart.
I am getting values from backend(API) to build my chart ..
Now the requirement is to show the values of legend in the descending order. 
So please help

**Comment by seksitha** [comment]
Your info is not enough for me to help you. 
Can you show your API data you get from Backend? 
Can you show the image or draw by what you mean?

**Comment by seksitha** [comment]
<img width="575" alt="screen shot 2018-05-22 at 9 19 39 pm" src="https://user-images.githubusercontent.com/13382133/40368572-55415f3e-5e06-11e8-84f0-192d4cb9f73d.png">
Is this something you are looking for?

**Comment by seksitha** [comment]
This is data require to use in chart
`doughnutChartLabels: string[] = ['A', 'B', 'C', 'D', 'E']`
`doughnutChartData: number[] = [100, 70, 60, 40, 20]`
This is is normally data I get from API
`data = [{'B':70}',{'A':100},{'D':40},{'E':20},{'C':60}] ` (It is not in order descending)
So you need to write pipe function to short your data and separate as your requirement.

**Comment by lakshyamathur1** [comment]
@seksitha I am somewhat getting you but my case is little complicated so, now let me share the code with you

**Comment by lakshyamathur1** [comment]
@seksitha I am building my code in Angular 4( Typescript )

**Comment by seksitha** [comment]
Where is your code? I will help if I can.

**Comment by lakshyamathur1** [comment]
@seksitha can you suggest me how to wrap the value of labels...
means now for e.g. I am getting values ABCDE-20%
but as per my screen  I want to display values like :- ABC...-20%...
Please help immediately

**Comment by lakshyamathur1** [comment]
@seksitha :- my HTML is:- 
 <canvas baseChart
                            [chartType]="doughnutChartType"
                            [data]="pieData2"
                            [labels]="labels2"
                            [options]="options"
                            [legend]="true"
                            [colors]="pieChartColor"></canvas>

**Comment by lakshyamathur1** [comment]
@seksitha :- my TS( Typescript ) file looks like:-

                    this.labels.push();
                    this.pieData.push(result.Share);
                    this.labels2.push(result.OwnerShipName + '-' + result.Share + '%');
                    this.pieData2.push(null);

**Comment by seksitha** [comment]
[Let chat](https://join.slack.com/t/probsworkspace/shared_invite/enQtMzY5MTYyNjg0NTAwLTQyNzQzNjczZjZkYjJjOTEyODQwNzYxN2Y2N2RlY2QwY2VhZDIyMjUxMDVkNWM4OTgyOGFmZmRlZDk3Y2FlMzA) it is better

**Comment by vinitkrb** [comment]
@seksitha

Hii seksitha,
I have stacked bar chart in which 3bar chart is there I am able to so the value separate separate on each three bar can u help me to show addition of all three bar at top of stacked bar chart....I will be greatful for your help...

**Comment by seksitha** [comment]
@vinitkrb I don't understand what you mean. do you mean you can display 3 bar but not other 3 bars? can you show the screenshot?

**Comment by vinitkrb** [comment]
![screenshot 90](https://user-images.githubusercontent.com/35526059/44784440-55150b80-abab-11e8-818f-888ab16786fd.png)
![screenshot 91](https://user-images.githubusercontent.com/35526059/44784446-59d9bf80-abab-11e8-86ce-c71b33a5d2ac.png)

**Comment by seksitha** [comment]
Sorry, I still don't understand what you want to archive. your screenshot did not explain me.

**Comment by vinitkrb** [comment]
Can u see the value on bar chart 3 color is there on 1 staced chart and 3
value is coming I don't want that 3 value I want addition of all 3 value at
top of chart

**Comment by paviad** [comment]
Use `chartjs-plugin-datalabels` - see this stackblitz: https://stackblitz.com/edit/ng2-charts-bar-labels
