### ISSUE TITLE
How to get the value of the data after clicked

### ISSUE THREAD

**Issue by tssobe** [valor-software/ng2-charts#803]
Hi
I would like to get the data value of a bar(for example) after clicked.
I have managed to get the active elements, but I see data such as label/ datasetLabel ..
but not the the actual value of the data.
Any idea?

Thanks

**Comment by artemkosenko** [comment]
Hi,

Try this way.
Add chartClicked event to canvas element. (chartClick)="chartClicked($event)"

Get data from $event
private chartClicked(e:any):void {
    if(e.active.length > 0) {
      let selectedLabed = e.active[0]._chart.config.data.labels[e.active[0]._index];
}
}

**Comment by artemkosenko** [comment]
Hi,
That's how you can get a value and a label of selected element in line chart.
private chartClicked(e:any):void {
    if(e.active.length > 0) {
      console.log("Index", e.active[0]._index);
      console.log("Data" , e.active[0]._chart.config.data.datasets[0].data[e.active[0]._index]);
      console.log("Label" , e.active[0]._chart.config.data.labels[e.active[0]._index]);
}
}

**Comment by sharpevo** [comment]
@artemkosenko There will be multiple `acitve` in an array, if more than one point  at the same x coordinate. How to get the value of the specific point?

![active](https://cloud.githubusercontent.com/assets/7692030/26228928/4916e0a2-3c70-11e7-9c98-fc0daae1d448.png)
![point](https://cloud.githubusercontent.com/assets/7692030/26228979/b602f89a-3c70-11e7-812c-d8b79ed252bd.png)

**Comment by sharpevo** [comment]
Got it.
```
  options = {
    hover: {
      mode: "nearest",
      intersec: true,
    },
    interaction: {
      mode: "nearest",
    },
  }
```

**Comment by LereveLabs** [comment]
@sharpevo - This solution worked correctly.  Thanks!
