### ISSUE TITLE
Add vertical line to line chart

### ISSUE THREAD

**Issue by jspencersharpe** [valor-software/ng2-charts#805]
Hi, I am trying to add an arbitrary vertical line to a line chart. Like this:

<img width="285" alt="screen shot 2017-05-18 at 5 01 15 pm" src="https://cloud.githubusercontent.com/assets/9039237/26225208/a83e26f6-3beb-11e7-8afd-1c93fb2f7bad.png">

Chart.js has/had `lineAtIndex`, but I couldn't find any way to do this in the library. Any suggestions?

**Comment by paqogomez** [comment]
Sad no one answered this.  Its probably because it is more of a stackoverflow question.  I'm looking for a similar answer.  I found this:

http://jsfiddle.net/dbyze2ga/14/

**Comment by paviad** [comment]
See this issue for solution https://github.com/valor-software/ng2-charts/issues/1036#issuecomment-470051965
