### ISSUE TITLE
Angular 4 Support?

### ISSUE THREAD

**Issue by RyanDawkins** [valor-software/ng2-charts#813]
**Reproduction of the problem**
If you try to install angular 4 while ng2-charts is installed it will say it has a dependency on @angular/common^2.3.0

**Comment by charliebrink** [comment]
+1

**Comment by dgpuranik** [comment]
+1

**Comment by peschee** [comment]
From what I see it works with Angular 4, but the peer dependency is still wrong.

**Comment by Killian-Herveau** [comment]
I am working on a project with angular 4 and ng2-charts is working just fine.

**Comment by paviad** [comment]
This package is now updated for Angular 7. If this issue persists, please provide a codepen/stackblitz/... example showing the issue.
