### ISSUE TITLE
Documentation incorrectly states you cannot provide an array of arrays for the dataset for a doughnut chart.

### ISSUE THREAD

**Issue by jasonburrows** [valor-software/ng2-charts#831]
The documentation states this:

> data (Array<number[]> | number[]) - set of points of the chart, it should be Array<number[]> only for line, bar and radar, otherwise number[];

...but this is not correct.  You can provide Array<number[]> for doughnut charts and it will render as a set of embedded rings.

**Comment by pedro412** [comment]
i want to show multiple doughnuts graphs with differents values data[]=[] , within the same page how can i do this?

**Comment by paviad** [comment]
You're right, closed by 92437bc
