### ISSUE TITLE
Multi Axis/ stacked bar chart how to get specific data after clicked

### ISSUE THREAD

**Issue by tssobe** [valor-software/ng2-charts#835]
Hi

1.
I have a multi Axis chart and one I click on some point I get all active points per this value.
For example:  I have 4 lines. For year 2000 I click on the point of the first line.
But I get an array of active points that contains 4 active points.
I want to know on which of the active points I have clicked, and not get all the 4.
Or to get just the specific active point I have clicked on instead of array of all four.
How it can be done?

2. 
If I hover on one point all the other three are highlighted.
Can I only highlight the specific point I have hovered on and not all the rest?

Thanks

**Comment by classic9** [comment]
Hi did you get any solution for this?

**Comment by LereveLabs** [comment]
I'm having the same problem.  The click event passes all active points in all datasets and not the specific element that was clicked.  How do you get the specific chart element that was clicked?

**Comment by anshulnegitc** [comment]
hey anyone know the solution?
