### ISSUE TITLE
Is there a way to have the labels within the chart to display without hover

### ISSUE THREAD

**Issue by DarylSmith** [valor-software/ng2-charts#836]
Currently the labels display on the chart within the hover event -- What I would like to do is have those labels display permanently for all items (without the need to have to hover over the element to display), however, I don't see anything with the ng chart api documentation that would allow this.  Is this at all possible?

**Comment by fawee** [comment]
I'm using **Chart.PieceLabel.js** for this problem, check out the [demo](https://emn178.github.io/Chart.PieceLabel.js/samples/demo/).

**Comment by yokidane** [comment]
@fawee Can you please post a sample on using Chart.PieceLable.js? I also need to display chart label on the pie chart I'm working on.

**Comment by paviad** [comment]
Use `chartjs-plugin-datalabels`, see this stackblitz: https://stackblitz.com/edit/ng2-charts-bar-labels-center

**Comment by lenichols** [comment]
Im still unable to get this to work with Angular 7 cli i have no idea why. I keep getting error 'Can't bind to 'plugins' since it isn't a known property of 'canvas''...

**Comment by learnuser521** [comment]
@lenichols - try updating your package npm install ng2-charts@2.2.3 --save

**Comment by VamanPatel** [comment]
how to display label through legend option bottom of the graph. pls tell
