### ISSUE TITLE
Can ng2-charts work with Chart.js zoom plugin?

### ISSUE THREAD

**Issue by mac10046** [valor-software/ng2-charts#837]
I am trying to add zoom functionality to my chart using the chartjs-plugin-zoom project but I haven't been able to get it working yet.

I added the chartjs-plugin-zoom to my project. I have the zoom property added to my chart config as well.

**Comment by rbaumi** [comment]
@mac10046: in addition install hammerjs 

`npm install hammerjs --save`

and add to your module:

```ts
import 'hammerjs';
import 'chartjs-plugin-zoom';
```

**Comment by hambecker** [comment]
Is zoom now just a part of chart options after doing what rbaumi just did?  Like how do you actually tell your graph to turn its zoomable property on?  Because I have inserted that code and there is still no zoom functionality.

**Comment by rbaumi** [comment]
@hambecker did you enalbed zoom / pan in graph settings? Take a look at the graph settings from one of the available samples: [https://github.com/chartjs/chartjs-plugin-zoom/blob/master/samples/zoom.html](https://github.com/chartjs/chartjs-plugin-zoom/blob/master/samples/zoom.html)

**Comment by hambecker** [comment]
@rbaumi I don't quite understand, so are you using ng2-charts at all in this example? or are you using strictly chartjs and hammerjs?

**Comment by rbaumi** [comment]
@hambecker I'm using ng2-charts. Check out working graph in one of my my projects: [math-diet](https://github.com/rbaumi/math-diet)

**Comment by mac10046** [comment]
Thanx rbaumi - it worked like a charm.

**Comment by nicscap** [comment]
Hello, 
sorry if I comment here, but I have the same problem. I think that I import the right things but I'm not able to pan or zoom in to the charts. I upload all my [code here](https://stackblitz.com/edit/ng2-charts-select-interval-multitouch). Can you help me? I will leave the code on link, so who will need in the future, will have an example.
thanks

**Comment by surenzxx** [comment]
@nicscap did you figure it out?

**Comment by bertoldomarcia** [comment]
Hello,
In this sample 
[https://stackblitz.com/edit/ng2-charts-select-interval-multitouch]
posted by nicscap.
If you change file path app.module.ts 
import { ChartsModule } from 'ng2-charts';
to 
**import { ChartsModule } from 'ng2-charts/ng2-charts';**
it´s works very well.
thanks!!!

**Comment by fabiocionini** [comment]
Hello, I have some issues building an Ionic 3 app with AOT compiling (--prod flag) and this plugin.
The build fails with errors "Cannot write file [...] because it would overwrite input file" on many .js files.
Can someone give me a hint?

**Comment by sakshi-c** [comment]
Hi, I have done all the imports and configurations mentioned. In my case, there is no error in the code but the pan and zoom feature is not working so I added console statements in zoom configuration, the console is working but the features are still not working.
I am using angular2_chartjs.
