### ISSUE TITLE
Does this working with the breaking Changes of chart.js 2.6

### ISSUE THREAD

**Issue by mburger81** [valor-software/ng2-charts#838]
A few weeks ago there was a new release of chart.js in version 2.6

https://github.com/chartjs/Chart.js/releases

Does your ng2-charts 1.6.0 working well with the breaking changes of chart.js 2.6?

**Comment by mburger81** [comment]
I saw in your #822 you upgrade chart.js from 2.5 to 2.6

**Comment by paviad** [comment]
This package is now updated for Angular 7 (and chart.js 2.7.45). If this issue persists, please provide a codepen/stackblitz/... example showing the issue.
