### ISSUE TITLE
[Feat] Allow delay of rendering for charts

### ISSUE THREAD

**Issue by luchillo17** [valor-software/ng2-charts#84]
Here's the sceneario, i have a doughnut chart that shows a percentage, as it is defined the chart starts empty thus rendering with animation 100%, but 250 ms later i change the data to be say 80%, now it re-render the chart so you can see it jumping and playing the animation again, it looks like a bug.

As some data comes from servers outside of an application, it would be great if we could delay or cancel the first refresh in:
[charts.ts#L129](https://github.com/valor-software/ng2-charts/blob/master/components/charts/charts.ts#L129)

**Comment by jcquinlan** [comment]
Couldn't you just use an Observer and .debounce() the response so as to only render once? That might be simpler than adding a delay option onto the charts.

**Comment by Luchillo** [comment]
The issue is that i would have to hide the chart, thus layout would be messed up until the data is received.

**Comment by paviad** [comment]
This is beyond the scope of this package, you may use an observable as jcquinlan suggested.
