### ISSUE TITLE
Request: Make the default colors configurable

### ISSUE THREAD

**Issue by soumak77** [valor-software/ng2-charts#840]
I would like to request making it possible to globally override the default colors used for the charts.  I understand that the `colors` attribute can be used to override the colors for a specific chart, however, the attribute requires the user to know the exact properties to set for each chart type.  Instead I would like for there to be a way to configure the module by providing a colors array similar to `ChartsModule.defaultColors`.

I'm thinking this can be implemented by providing a `forRoot` method on the ChartsModule.  This method would accept a default colors array `Array<number[]>` which can be used to override the internal `defaultColors` value.

**Comment by paviad** [comment]
This sounds like a good idea, someone should pick this up.
