### ISSUE TITLE
chartHover event is not working

### ISSUE THREAD

**Issue by anjumkhalid** [valor-software/ng2-charts#842]
using ng2-chart 
chartClick is working but chartHover  event is not working

**Template:**             

 <canvas baseChart
                [datasets]="_donutPriceChartData"
                [labels]="_donutPriceChartLabels"
                [colors]="_donutChartColors"
                [options]="donutChartOptions"
                [chartType]="'doughnut'"
                (chartHover)="chartHovered($event)"
                (chartClick)="chartClicked($event)"></canvas>

**component.ts:**

 private _donutPriceChartData: any[] = [{ label: 'Price Range', data: [], }];
  private _donutPriceData:DonutPrice[];
  private _donutPriceChartLabels: string[];
  private _donutChartBGColor: string[] =['#1BBC9B','#3699DD','#DC532F'];
  private _donutChartColors:{}[] = [ { backgroundColor: this._donutChartBGColor } ];

  public donutChartOptions: any = {
    global: {
        defaultFont: "rawline, sans-serif",
        defaultFontSize: 14
    },
    tooltips: {
        callbacks: {
            label: function(tooltipItem, data) {
                //console.log(tooltipItem, data);
                let index  = tooltipItem.index;
                let quantity = parseInt(data.datasets[0].data[index]);
                let text  = data.labels[index] + "  " + quantity.toLocaleString();
                //console.log("text",text);
                return text;
            }
        }
    },         
    responsive: true,
    maintainAspectRatio: false,
  }  
  **public chartHovered(e:any):void {
    console.log("hover",e);
  }  
  public chartClicked(e:any):void {
    console.log("click",e);
  }**

**Comment by anjumkhalid** [comment]
no one here to answer?

**Comment by jimmykane** [comment]
Confirmed

**Comment by vedk21** [comment]
I have resolved this issue:  

you should add this in your options 
`hover: {
     onHover: function(event, active) {
          //do your stuff      
     }
}`

basically, I believe it should actually be passing event and active to the onHover function instead of passing active only.

**Comment by manufao** [comment]
@vedk21 thx for your fix. Do you know how retrieved information contained in chart segment (like label for example) through your function ?

**Comment by vedk21** [comment]
@manufao yes you can retrieve the information regarding the segment you hover on.
see the following snippet:
hover: {
     onHover: (event, active) => {
       if(active && active.length){
         let index = active[0]._index; //with this you get the index of the segment you hovered on

         console.log(active[0]._chart.config.data.labels);  //with this you can get all the labels of your chart -- this is an array of labels
         console.log(active[0]._chart.config.data.datasets[0].backgroundColor);   //with this you can get all the bg color of your chart -- this is an array of background colors
         console.log(active[0]._chart.config.data.datasets[0].data);   //with this you can get all the dataset values of your chart -- this is an array of data values given
       }
     }
}

to get more information you can check this `active` object which also consists of various different attributes of a chart, such as borderWidth, startAngle, endAngle etc.
