### ISSUE TITLE
Cannot read property 'parentNode' of null

### ISSUE THREAD

**Issue by BenjaminDaRos** [valor-software/ng2-charts#847]
Hello,

I have a page with one line chart and two doughnuts chart ([Picture 1](http://hpics.li/6c27245)).
And some times I get this error ([Picture 2](http://hpics.li/31d2046)).
It does nothing, like breaking or preventing the page from working.
But I would like to know where it comes from, if someone has an idea ?

Thanks in advance.

**Comment by paviad** [comment]
This package has been updated to Angular 7, check out the demo app. If this issue is still relevant, feel free to reopen this with a stacklitz/codepen/... example showing the issue.
