### ISSUE TITLE
"chart_js_1.Chart is not a constructor"

### ISSUE THREAD

**Issue by meghsmayur** [valor-software/ng2-charts#848]
Getting above error when I am trying to implement chart .

**Comment by mrtipster49** [comment]
Did you fix this issue, facing same error while implementing ng2-charts

**Comment by meghsmayur** [comment]
Update "chart.js": "1.1.1" to "chart.js": "^2.6.0" in package.json.
Install latest chart.js and ng2 charts
npm install ng2-charts --save
npm install chart.js --save

**Comment by mrtipster49** [comment]
@meghsmayur thanks mate issue fixed.

**Comment by kndenney** [comment]
I am trying to use Chart.js (2.7.1 from Cloudflare CDN) as well as the latest version of ng2-charts and am receiving this error in my project. It worked before upgrading to Angular 5 if that helps.

**Comment by thianlopezz** [comment]
Hello I had the same issue, but I am not using ng2-charts, Im using pure Charts.js, I solved this attaching, the Chart.js libray into "scripts"{
"../node_modules/chart.js/dist/Chart.min.js"
} 
on angular-cli.json, then in my controller I just wrote **declare var Chart: any;,**  right after my imports.

**Comment by adimittal** [comment]
thianlopezz's comment helped me resolve this though it's not angular-cli.json now, but in angular.json in the scripts add:

"scripts": [
              "../node_modules/chart.js/dist/Chart.min.js"
            ]

Then in the component:
`
declare var Chart: any;
/**
   * Draws the chart on the context given the options
   * @param ctx
   * @param options
   */
  getChart(ctx, options){
    return new Chart(ctx, options);
  } 
`

**Comment by DennisTsiang** [comment]
I am having the same issue. I have chart.js version 2.7.3 and ng2-charts version 1.6.0. I have already tried adding `declare var Charts: any` to the component and including the script in my `.angular-cli.json` file but nothing has worked.

**Comment by paviad** [comment]
This package is now updated for Angular 7 (and chart.js 2.7.45). If this issue persists, please provide a codepen/stackblitz/... example showing the issue.

**Comment by Slion** [comment]
I have that same issue with 3.7.1. npm builds but at runtime it gives me that error.

**Comment by Slion** [comment]
Using:
```JS
import { Chart, registerables } from 'chart.js';
Chart.register(...registerables);
```
Instead of:
```JS
import { Chart } from "chart.js/auto";
```
Fixed it for me.
