### ISSUE TITLE
Chart.HeatMap Support ?

### ISSUE THREAD

**Issue by kyawzintun** [valor-software/ng2-charts#849]
Is there plan to add support for Heat Map ? I Googled lots unfortunately couldn't find Chart.HeatMap for angular 2 and 4.

**Comment by ninadvadujkar** [comment]
Is Heatmap supported in ng2-charts?

**Comment by paviad** [comment]
This is out of scope for this package, and in `chart.js` there is currently there is no support for heat map. But there are clever workarounds, see this: https://github.com/chartjs/Chart.js/issues/4627#issuecomment-400911590
