### ISSUE TITLE
It doesn't work.

### ISSUE THREAD

**Issue by GTamara** [valor-software/ng2-charts#85]
Hi,
I go through the following steps: 
1. git clone https://github.com/valor-software/ng2-charts.git  (everything is ok)
2. npm install  (everything is ok)
3. gulp
then I get the error message:
Error: Could not find the following rules specified in the configuration:
no-trailing-comma
sort-object-literal-keys
    at Object.loadRules (/home/testCharts/ng2-charts/node_modules/tslint/lib/ruleLoader.js:29:15)

What is wrong with my actions?

**Comment by ThomasBuron** [comment]
Find tslint.json and remove :
 no-trailing-comma
sort-object-literal-keys

**Comment by GTamara** [comment]
Thank you for your help :)

**Comment by GTamara** [comment]
it works!
