### ISSUE TITLE
Click event behavior

### ISSUE THREAD

**Issue by RKornu** [valor-software/ng2-charts#851]
Using ng2-charts, I have created a bar chart. Using **chartClick** event, I am not able to differentiate on which bar the click event is happening.  Could you please let me know if there is any way to differentiate it?

**Comment by RKornu** [comment]
Below is one way to solve this issue:
 public chartClicked(e: any): void {
        if (e.active.length > 0) {
            var chartElement = e.active[0]._chart.getElementAtEvent(event);
            console.log(chartElement[0]._model.datasetLabel)
        }
    }

**Comment by kairos2489** [comment]
Hi,
I am new in Angular so please don't mind me asking basic questions.
My query- I have a bar graph and my project requirement is to display all the  bar details with some additional info in a TABLE when clicked on bars of graph.
Please help as to how i can implement this or share me some useful links.
Thanks in advance.

**Comment by RA344710** [comment]
chartElement[0]._model.datasetLabel it's for lable. what I need use to print bar chart clicked value. Could you please let me know.
