### ISSUE TITLE
Set custom values for y-axis.

### ISSUE THREAD

**Issue by venkadesh02** [valor-software/ng2-charts#853]
Currently y axis values are determined form the chat datasource. Is it possible to set max values or custom intervals for y-axis.

For example:
   This chart plots percentage values. Since its a percentage, it has to be plotted against the maximum value of 100%. Is it possible to display 100% as the maximum value on y-axis regardless of the chart data.

![chart](https://user-images.githubusercontent.com/3060733/27779634-eeb03fc4-5fe1-11e7-8f59-2179baf49945.png)

**Comment by srinidhi-rao** [comment]
I have this issue too. Can anyone help?

**Comment by bjines** [comment]
Check the Chart.JS docs for this one. It is set in options.

You didn't post your code, so I am unsure what your variables are, but:

```
optionsVariable : {
  scales : {
    yAxes: [{
       ticks: {
          steps : 10,
          stepValue : 10,
          max : 100,
        }
    }] 
  }
}
```

That should do it for you

**Comment by srinidhi-rao** [comment]
Thanks. This works. This how my chart looks after applying the change that
you suggested.

**Comment by sasrinidhi** [comment]
![img_20170710_113635](https://user-images.githubusercontent.com/3539177/28004785-80df9714-6564-11e7-9878-535bdb500535.jpg)

**Comment by preservance717** [comment]
`
optionsVariable : {
  scales : {
    yAxes: [{
       ticks: {
          steps : 10,
          stepValue : 10,
          max : 100,
        }
    }] 
  }
}` 
it don't work for me.

`
optionsVariable : {
  scales : {
    yAxes: [{
       ticks: {
          min: 0,
          stepValue : 10,
          max : 100,
        }
    }] 
  }
}`
but  this config work for me

**Comment by ArneKnockaert** [comment]
its not 'min', use beginAtZero: true

**Comment by AmalMtibaa** [comment]
@bjines 
Do you know how I can set dynamically the max value optionsVariable  ? 
In other words I only want to set max in different events. 

this.optionsVariable.scales.yAxes.ticks.max =maxValue didn't work for me, and I got this error : "Cannot set property 'max' of undefined" .

**Comment by katedoctor** [comment]
@bjines 
if u add in ngOnInit 
 this.chartOptions.scales.yAxes[0].ticks.max = this.maxYaxis;
must work

**Comment by Ashok-Kumar-Venaktesh** [comment]
But it is always plotting data with respect primary/first axis scaling values.  How to plot based on mulitple scaling values?

**Comment by thotasatyasri** [comment]
s

**Comment by thotasatyasri** [comment]
yAxes: [{
            stacked: true,            // this also..
            scaleLabel: {
              display: true,
              labelString: 'Flowdata'
            },
            ticks: {
              min: 0, max : 60,steps:5,stepValue:12,
              // Include a dollar sign in the ticks
              callback: function(value, index, values) {
                  return  value + 'ml/s';
              }
            }
          }]
I have added all those things in my code ,still its not working

**Comment by Saitejas1997** [comment]
steps under ticks section is not working for me

**Comment by kedar2594** [comment]
y-axis tickes section works for me, Thank you for the code.
Here is my code : 
```
 scales: {
          yAxes: [{
            barPercentage: 6.0,
            categoryPercentage: 6.0,
            ticks: {
             beginAtZero: true,
              callback: function (value, index, values) {
                return '$' + value + 'k';
              },
            }
          }]
        }
```

**Comment by mateushff** [comment]
> ` optionsVariable : { scales : { yAxes: [{ ticks: { steps : 10, stepValue : 10, max : 100, } }] } }`
> it don't work for me.
> 
> ` optionsVariable : { scales : { yAxes: [{ ticks: { min: 0, stepValue : 10, max : 100, } }] } }`
> but this config work for me

If nothing works, use:

`yAxes: [{
                ticks: {
                  stepSize: 20,
                }
           }]`

**Comment by sirakx** [comment]
> > ` optionsVariable : { scales : { yAxes: [{ ticks: { steps : 10, stepValue : 10, max : 100, } }] } }`
> > it don't work for me.
> > ` optionsVariable : { scales : { yAxes: [{ ticks: { min: 0, stepValue : 10, max : 100, } }] } }`
> > but this config work for me
> 
> If nothing works, use:
> 
> `yAxes: [{ ticks: { stepSize: 20, } }]`

Work for me, im using ng2-chart v2.2.3
