### ISSUE TITLE
Update the demo website to latest version

### ISSUE THREAD

**Issue by MerlinDuChaos** [valor-software/ng2-charts#854]
It is said in the Readme "Sample in below website uses ng2-charts@1.1.0"

I used version 1.4.4 in my website (with good results).  When updating to 1.6.0, nothing works anymore with the same code.  So my guess is that some things have changed between those versions.  An up-to-date demo website would allow me to check if I need to change the way I use the lib.

Thanks !

**Comment by amarnathm** [comment]
+1

I have it working from ng2-charts 1.5.0, but when updating to 1.6.0, it fails. Essentially, things are not being found (404).  

My configuration is:

package.json:
 "chart.js": "^2.6.0",
"ng2-charts": "^1.6.0"

system.config.js:
'ng2-charts': 'npm:ng2-charts'

app.module.ts:
import { ChartsModule } from 'ng2-charts/ng2-charts';

index.html:
<script src="node_modules/chart.js/dist/Chart.bundle.js"></script>

I'm trying out permutations of these, such as have only one "ng2-charts" in app.module.ts, or a different file in index.html, but so far, it's not working.

The configuration above gives
GET http://localhost:3000/chart.js 404 (Not Found)

An updated example would be helpful!

**Comment by paviad** [comment]
Demo site updated.
