### ISSUE TITLE
Datasets from where?

### ISSUE THREAD

**Issue by azarus** [valor-software/ng2-charts#855]
**Reproduction of the problem**
Give empty datasets.

```
 Error: ng-charts configuration error,
      data or datasets field are required to render char line
```

How am i supposed to give data to the chart without having the dataset ready? I am getting the information from a third party service and so what am i supposed to give to the component if theres nothing to give yet? I am not sure what causes the error but if this is the case that i have to give some random data upfront, then it is slightly stupid angular implementation, and the whole thing is useless for me.

**Comment by bjines** [comment]
Just put a ngIf on the canvas element that returns false until the data is ready

**Comment by surajsakhareprojects** [comment]
Yehhh, Thanks bjines.

 <div style="display: block" *ngIf="barChartData.length > 0">
                            
                              <canvas baseChart
                                      [datasets]="barChartData"
                                      [labels]="barChartLabels"
                                      [options]="barChartOptions"
                                      [legend]="barChartLegend"
                                      [chartType]="barChartType"
                                      (chartHover)="chartHovered($event)"
                                      (chartClick)="chartClicked($event)"></canvas>
                            </div>


It's working for me..
