### ISSUE TITLE
Hidden property on datasets

### ISSUE THREAD

**Issue by azarus** [valor-software/ng2-charts#858]
Add Hidden property as defined in chart.js

`dataset.hidden = true;`

Allows toggling visibility on datasets.

**Comment by bjines** [comment]
This is available already.

If you have a legend, clicking on the dataset in the legend will hide it.
Going to [here](http://valor-software.com/ng2-charts/) and clicking on the legend on the first chart will demonstrate this.

If you want to do this using custom code it is a little silly how it needs to be done - but lets say you have an array of 3 datasets and you want to toggle hidden on the third, your code would look like this.

```
    if (this.chart && this.chart.chart) {
      this.chart.chart.config.data.datasets[2].hidden = !this.chart.chart.config.data.datasets[2].hidden;
      this.chart.chart.update();
    }
```

Where 2 is the index of your dataset. This will toggle the hidden state, so if it is hidden it will show it, if not it will hide it.

**Comment by azarus** [comment]
@bjines I've already forked the ng2-charts library and made the changes, and i am aware that clicking on the legends hides the code, but i disabled the legends. And i want third party controlls to hide / show my datasets and controll my chart.
It's very nice of posting some code, hovever your code is hacky: **this.chart.chart.config.data.datasets?** Wtf?
Heres the code man that will add this support its not too hard:
```
dataset.hidden = newDataValues[i].hidden;
dataset.type = newDataValues[i].type;
```
