### ISSUE TITLE
Graphs not showing up with Promises

### ISSUE THREAD

**Issue by azhuang3** [valor-software/ng2-charts#860]
Hello,

The end goal for me is to dynamically update the data in the charts using data pulled from a database. Right now I'm simply pulling hard-coded data from a .ts file. When I try to use Promises, the graph just would not show up. I confirmed that the data is properly being retrieved with Promises by creating a separate table to display the data. I'm just having the issue with the graphs. 

Here is what works:
**component.ts**
`  getWorkOrders(): void {
    this.lineChartData = this.workOrdersService.getWorkOrders();
  }`
**service.ts**
`
  getWorkOrders(): WorkOrder[] {
    return (BARCHARTDATA);
  }
`
**component.html**
`      <canvas baseChart
                  [datasets]="lineChartData"
                  [labels]="lineChartLabels"
                  [options]="lineChartOptions"
                  [colors]="lineChartColors"
                  [legend]="lineChartLegend"
                  [chartType]="lineChartType"
                  (chartHover)="chartHovered($event)"
                  (chartClick)="chartClicked($event)" style="max-width: 800px;"></canvas>`

Here are the changes I made with Promises that kept the graph from showing up:

**component.ts**
`   getWorkOrders(): void {
    this.workOrdersService.getWorkOrders().then(results => setTimeout(this.lineChartData = results) );
  }`

**service.ts**
`     getWorkOrders(): Promise<WorkOrder[]> {
    return Promise.resolve(BARCHARTDATA);
  }
`

Any insight on this issue is greatly appreciated.

**Comment by whyboris** [comment]
Unsure if this can solve your problem, but I had a similar issue (waiting for data to be inserted into my pre-made empty array from an API call) which was solved with an `*ngIf`
I got the idea from @bjines https://github.com/valor-software/ng2-charts/issues/855#issuecomment-313705242

**Comment by paviad** [comment]
This package has been updated to Angular 7, check out the [demo app](https://valor-software.com/ng2-charts). If this issue is still relevant, feel free to reopen this with a stacklitz/codepen/... example showing the issue.
