### ISSUE TITLE
labels doesnt work properly on linechart with Point(x, y) data

### ISSUE THREAD

**Issue by doncatas** [valor-software/ng2-charts#862]
When you add few lines in data, and set them by Point(x,y).
For examples x axis data => 1,2,3,4
data: 
test: [{x:1,y:10},{x:2,y:10}],
test2: [{x:1,y:10},{x:3,y:10}]

And when trying to hover on test2 line's second point, it shows label on the second x value.
I think there is bug, because it counts hovered dot on line position in array, but not trying get x value position on x axis data. So if you have more lines, and they have some skipped x values, on hover all points gets in random places.

**Comment by paviad** [comment]
You should be using the `scatter` chart type for this, which is now supported. See this stackblitz https://stackblitz.com/edit/ng2-charts-scatter
