### ISSUE TITLE
How can I set some texts in the center of Doughnut chart

### ISSUE THREAD

**Issue by suresh2018** [valor-software/ng2-charts#864]
**Reproduction of the problem**

ng2-charts is a port & modification of Chart.js component for Angular 2. Sometimes the issue is related with Chart.js instead of ng2-charts.
To confirm, if the issue shows in a pure Chart.js project, it is a issue of Chart.js.
Pure Chart.js starting template: https://jsfiddle.net/Hongbo_Miao/mvct2uwo/3/

If the issue does not show in a pure Chart.js project, and shows in a ng2-charts project, please try to provide a minimal demo of the problem.
ng2-charts starting template: http://plnkr.co/edit/Ka4NXG3pZ1mXnaN95HX5?p=preview

**Comment by usamaiqbal83** [comment]
I would also like an answer for this

**Comment by FergusZhou** [comment]
+1

**Comment by pallen0304** [comment]
+1

**Comment by JacoRoos** [comment]
+1

**Comment by lesiaosypenko** [comment]
any updates here?

**Comment by HoracioEspinosa** [comment]
+1

**Comment by paviad** [comment]
Check this stackblitz: https://stackblitz.com/edit/ng2-charts-doughnut-centertext

It's based on this SO answer: https://stackoverflow.com/a/43026361/235648

**Comment by LeonardoRick** [comment]
`type 'Chart' does not have property 'innerRadius'`

**Comment by richardgunawan26** [comment]
I want to reproduce this behavior with 
```
"chart.js": "~3.8.0",
"ng2-charts": "^3.1.2",
```
Is there any guide to reproduce the same thing?
