### ISSUE TITLE
BarChart colors only change legend color

### ISSUE THREAD

**Issue by Robouste** [valor-software/ng2-charts#867]
I tried to change the color of the bar chart like this : 
  ```JS
  public barColors: any[] = [
		{
			backgroundColor: [
				"#f04723"
			],
			borderColor: [
				"#f04723"
			],
			hoverBackgroundColor: [
				"#f04723"
			],
			hoverBorderColor: [
				"#f04723"
			]
		}
	];
```

Then in template : 
`[colors]="barColors"`

But then, all bars are grey and only the legend is red. See screenshot : 
![image](https://user-images.githubusercontent.com/5463032/28919630-9e4d24c2-784e-11e7-8edb-b92dfee28141.png)

What am I doing wrong ?

**Comment by Robouste** [comment]
any help ? I can't find a solution

**Comment by Robouste** [comment]
Finally found the solution : 

[Angular 2 charts with good documentation](https://www.primefaces.org/primeng/#/chart/bar)

**Comment by BaymaxGroot** [comment]
@Robouste 
![image](https://user-images.githubusercontent.com/30405676/31607498-246bd44c-b29f-11e7-9837-7709fdba3eaa.png)
how do you do this style ?

can you tell me?

 thank you !

**Comment by paviad** [comment]
Drop the array over the `backgroundColor` field. See this stackblitz https://stackblitz.com/edit/ng2-charts-bar-colors

Code:
```typescript
public barChartColors: Color[] = [
  { backgroundColor: 'red' },
  { backgroundColor: 'green' },
]
```
