### ISSUE TITLE
Use TypeScript definitions for Chart.js from Definitely Typed

### ISSUE THREAD

**Issue by mklein994** [valor-software/ng2-charts#872]
This project is lacking in typescript type definitions. The type definitions on [Definitely Typed](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/chart.js/index.d.ts) are very thorough. It would be great if this project leaned on those definitions instead of defaulting to `any` (that kind of defeats the point of TypeScript). For example, datasets are defined in this library as an `any[]`, where as in the [TypeScript definition](https://github.com/valor-software/ng2-charts/blob/602742b71d61d19bb56b23f71094ff189315355b/src/charts/charts.ts#L35), it defines it as `ChartDataSets[]`.

**Comment by miao17game** [comment]
anyway, the chart.js is huge and the declare work still has long way to go :(

**Comment by paviad** [comment]
This package is now updated for Angular 7. It includes strong typing for all members of `BaseChartDirective`. If this issue persists, please provide a codepen/stackblitz/... example showing the issue.
