### ISSUE TITLE
How to set border width for pie charts?

### ISSUE THREAD

**Issue by georgeedwards** [valor-software/ng2-charts#873]
I have a very small graph in my application, where the white gap between the segements isn't appropriate, see below:
[![enter image description here][1]][1]

I tried adding the `[boarderWidth]='[0]'` property that the [chart.js](http://www.chartjs.org/docs/latest/charts/doughnut.html#dataset-properties) seem to suggest, but that throws an error as it isn;t a recognised property of canvas...

How can I change that spacing with ng2-charts.

  [1]: https://i.stack.imgur.com/04e0d.png

**Comment by nebrs** [comment]
Your post has a typo, it should be "borderWidth", maybe it's as easy as that?

**Comment by Juchar** [comment]
I am also not able to set the border width for a doughnut chart.

What I tried:

### Using it at the directive level:
```
<canvas baseChart width="200" height="200"
                [options]="chartOptions"
                [datasets]="chartDatasets"
                [labels]="chartLabels"
                [colors]="chartColors"
                [borderWidth]="[10]"
                chartType="doughnut">
```

### Using it at the dataset level:
  ```
public chartDatasets: Array<any> = [
    {data: [10, 20, 30, 40], borderColor: ['#000000'], borderWidth: [10]}
  ];
```

Strangely `borderColor` works in this case.

Any suggestions? Or maybe a bug?

**Comment by paviad** [comment]
Border width should be specified as part of the chart options, it is not a directive property.

**Comment by JacoRoos** [comment]
@paviad Which chart options property should this be specified on?

**Comment by REPTILEHAUS** [comment]
This still doesnt work for me, any current fix ?
