### ISSUE TITLE
Dynamic number of datasets not being parsed

### ISSUE THREAD

**Issue by nebrs** [valor-software/ng2-charts#875]
I have a dataservice that provides 1->n datasets which I would like to show in a ng2-charts. The number of dataset can change on-the-fly. When I initialize a component, I do not yet know how many datasets will have to be shown. (The data is provided by a dataservice with an interval).

My problem is that when the number of Datasets changes, the chart doesn't respond to this. So when the new number of dataset is smaller than the orignal set, I get errors. When the new number is higher, it won't show the new sets. I've made a simplified example in Plunker which simulates te problem.

http://plnkr.co/edit/PRhTiFWB4kkGVXir2sq6?p=preview

How do I notifify the chart to update completely when the number of datasets have changed?

**Comment by BaymaxGroot** [comment]
Hello I also meet the problem . Now How do you fix them?

**Comment by nebrs** [comment]
I haven't yet found a proper way to fix this unfortunately. I think this might be a bug and am hoping that the Devs will fix/respond.

**Comment by antonvasyliev** [comment]
There is more or less acceptable way to solve the issue. Have a look:
https://github.com/valor-software/ng2-charts/issues/859#issuecomment-340596768

**Comment by paviad** [comment]
This package has been updated for Angular 7 with many bug fixes and enhancements. If this issue persists feel free to reopen with a stackblitz example.
