### ISSUE TITLE
Custom chart type with Angular CLI

### ISSUE THREAD

**Issue by bitflower** [valor-software/ng2-charts#876]
I have a custom chart type in a separate JS file called 'Chartjs.stripe.js' in the src/assets/js folder.
I have added it to the globals scripts in the angular-cli.json file like this:

```typescript
{
...
  "apps": [
    {
      ...
      "scripts": [
        "../node_modules/chart.js/dist/Chart.bundle.min.js", 
        "./assets/js/Chartjs.stripe.js"
      ],
```
It gets included in the scripts.bundle.js. I see this because I have added console.logs to the file and they get executed.

I can also see that the Chart.defaults are being extended with the new chart type (from console):
```typescript
{global: {…}, scale: {…}, 
bar: {…}, 
horizontalBar: {…}, 
bubble: {…}, 
doughnut: {…},
global: {…}, 
horizontalBar: {…}, 
line: {…}, 
polarArea: {…}, 
scatter: {…}
stripe: {…}
```

However when changing the chart type from 'line' to the new 'sprite' type
```html
<canvas 	
	baseChart
  	class="chart"
  	width="100%"
	[datasets]="datasets"
	[labels]="labels"
	[options]="options"
	[colors]="lineChartColors"
	[chartType]="chartType"
	(chartHover)="chartHovered($event)"
	(chartClick)="chartClicked($event)">
</canvas>
```

 i get this error:
`ERROR Error: "stripe" is not a chart type.`

And it's true: When I now check via console of the Chart.defaults.sprite exists, it doesn't:
```typescript
{global: {…}, scale: {…}, 
bar: {…}, 
horizontalBar: {…}, 
bubble: {…}, 
doughnut: {…},
global: {…}, 
horizontalBar: {…}, 
line: {…}, 
polarArea: {…}, 
scatter: {…}
<-- stripe is MISSING
```

I have the feeling that this has to do with the Angular "Each component gets its own instance of plugins" thing.

Any ideas would be appreciated!

**Comment by paviad** [comment]
`ng2-charts` currently does not support custom chart types, however this is something we definitely want. Someone should definitely pick this up.

**Comment by paviad** [comment]
Custom chart types are supported. Please see the [financial tab at the demo app](https://valor-software.com/ng2-charts/#FinancialChart)

**Comment by xNeophyte** [comment]
> Custom chart types are supported. Please see the [financial tab at the demo app](https://valor-software.com/ng2-charts/#FinancialChart)

Is there anything special that needs to be done in order to use a custom chart type?

I've been trying to get a custom chart  called [chartjs-chart-matrix](https://github.com/kurkle/chartjs-chart-matrix) working for a while but always get this error:

```
ERROR Error: getColors - Unsupported chart type matrix
    at getColors (ng2-charts.js:56)
```

I assumed I'd just need to import the package in my component and then set the chart type string. Maybe I'm missing something.

**Comment by Peshou** [comment]
@xNeophyte 
If you look at the financial demo, they have an input called `colors`, and it's defined in the code as:

```
 public financialChartColors: Color[] = [
    {
      borderColor: 'black',
      backgroundColor: 'rgba(255,0,0,0.3)',
    },
  ];
```

So if you implement your own list of colors for your chart, you can use the custom charts, as long as you add the Input to the baseChart directive in the HTML code:
```
[colors]="financialChartColors"
```

**Comment by serhiisol** [comment]
Current it doesn't support custom Chart controllers, `getColors` method will throw unsupported error. The best scenario just to revert that `throw error` line to something that library has in v.1.6.0. https://github.com/valor-software/ng2-charts/blob/602742b71d61d19bb56b23f71094ff189315355b/src/charts/charts.ts#L317
