### ISSUE TITLE
Issue occurs at __decorate([core_1.Input() ... as core_1 is undefined at time of initial script load

### ISSUE THREAD

**Issue by LotusShiv** [valor-software/ng2-charts#882]
**Reproduction of the problem**

ng2-charts is a port & modification of Chart.js component for Angular 2. Sometimes the issue is related with Chart.js instead of ng2-charts.
To confirm, if the issue shows in a pure Chart.js project, it is a issue of Chart.js.
Pure Chart.js starting template: https://jsfiddle.net/Hongbo_Miao/mvct2uwo/3/

If the issue does not show in a pure Chart.js project, and shows in a ng2-charts project, please try to provide a minimal demo of the problem.
ng2-charts starting template: http://plnkr.co/edit/Ka4NXG3pZ1mXnaN95HX5?p=preview

I cannot show the plnkr demo as we are restricted at work to do so. In any case I am providing the details of what I have done

I did follow the steps to install ng2-charts
When I run my Angular 4 in a ASP.Net web application, I get error at the generated charts.ts on line 
16281 - basically the core_1 object is undefined, hence it is not able to resolve the Input() method of the object...

Issue at the generated 'charts.ts' file for the code block
```typescript
BaseChartDirective.defaultColors = [ [255, 99, 132], [54, 162, 235], [255, 206, 86], [231, 233, 237], [75, 192, 192], [151, 187, 205], [220, 220, 220], [247, 70, 74], [70, 191, 189], [253, 180, 92], [148, 159, 177], [77, 83, 96] ]; __decorate([ core_1.Input(), __metadata("design:type", Array)
```
Here Array not defined error occurs as "Unhandled exception at line 16281, column 1 in http://localhost:25867/Scripts/ng2-charts/bundles/ng2-charts.umd.js
```
0x800a138f - JavaScript runtime error: Unable to get property 'Input' of undefined or null reference"
```
Please let me know what I need to do. I am doing the following:

I copied the node_modules - ng2-charts folder to Scripts folder

in my SystemJS.config.js I have in the map section
as
```
'ng2-charts': 'Scripts/ng2-charts/bundles/ng2-charts.umd.js'
```
and in the packages section as
```
'ng2-charts': {
defaultExtension: 'js'
}
```
in app.module.ts as
```typescript
import { ChartsModule, Color } from 'ng2-charts';
```
in @NgModule section as
```typescript
imports: [
BrowserModule,
FormsModule,
HttpModule,
RouterModule,
routing,
ChartsModule
],
```
Any help is greatly appreciated as I am on a time crunch sooner will be better.

**Comment by paviad** [comment]
This package has been updated for Angular 7 and has had many bugs fixed and features added. If you still encounter a problem feel free to reopen this.
