### ISSUE TITLE
drop shadow

### ISSUE THREAD

**Issue by nitinht1988** [valor-software/ng2-charts#883]
I want to perform something similar to below link:
https://jsfiddle.net/7kbz1L4t/
I have no idea how i can do it with ng2-charts.
Please help.

**Comment by nitinht1988** [comment]
can anyone please help?

**Comment by paviad** [comment]
This is a good feature request, someone should pick this up.

**Comment by narkhedetushar** [comment]
any update/workaround for this feature?

**Comment by chiranshu14** [comment]
Is this feature available in 2021?

**Comment by abdelsalamshahlol** [comment]
You'd have to create your own custom chart class and use then use it.

https://www.chartjs.org/docs/master/developers/charts.html#extending-existing-chart-types
