### ISSUE TITLE
ng2-charts update the graphic at the label

### ISSUE THREAD

**Issue by manolait** [valor-software/ng2-charts#886]
I'm trying to update the graphic at the label level, I've got it with the data.

My problem is that my graph has the dates as a label. I have designed two fields of start date and end date so that the user can customize the graph and generate it automatically.

My problem is that I have the field barChartLabels which is a string and it retrieves the range of dates selected, but when the range is extended or decrement this stays with the same value as the first time.

I do not know what the solution can be if every time I query a data range put the label to null and re-generate it. Or if there is any way to generate just as many label as values ​​recovers.

for example I have 4 date label and I only show 3 data, the correct thing would be to display 3 label as well.

my component:

```
mostrarnombre(){
  this._invService.getinvfecha(this.fecha1,this.fecha2).subscribe(
      response => {
      if (!response) {
        console.log('error al cargar datos');
      } else {

        this.resultData = response;
        this.barChartLabels = this.resultData.map(item => item.fecha);

        var d0=this.resultData.map(item => item.sensorluz1);
        var d1=this.resultData.map(item => item.sensorluz2);
        var d2=this.resultData.map(item => item.sensorluz3);
        this.barChartData.push({data: d0, label: 'sensorluz1'});
        this.barChartData.push({data: d1, label: 'sensorluz2'});
        this.barChartData.push({data: d2, label: 'sensorluz3'});
        let clone = JSON.parse(JSON.stringify(this.barChartData));
        clone[0].data = d0;
        clone[1].data = d1;
        clone[2].data = d2;
        this.barChartData = clone;
        this.loaded = true;
      }
    },
    error =>{
      console.log(<any>error);
    }
  );
```
when updating it would only have to show 3 columns and it shows 4 since it does not update the label. As shown in the picture.

How could I solve this problem I do not know how to update the field

this.barChartLabels = this.resultData.map (item => item.day);
this contains my item.day: `["2017-09-05T11: 15: 06.000Z", "2017-09-05T17: 22: 14.000Z", "2017-09-05T17: 22: 14.000Z", "2017- 09-12T12: 22: 00ZZ "]`

**Comment by gabor182** [comment]
I've encountered this bug too. I solved it by using ViewChild query:

`@ViewChild(BaseChartDirective) private _chart: BaseChartDirective;`

And in the method you want to update your labels:
`this._chart.chart.data.labels = newLabels;`
