### ISSUE TITLE
Ng 2 Line Chart legend's Icon Position

### ISSUE THREAD

**Issue by ZubairIrfan** [valor-software/ng2-charts#889]
want to place Icons above the legend's label? Plz help..
![image](https://user-images.githubusercontent.com/32097417/30591361-de74daf4-9d5b-11e7-91e0-f44da40fd504.png)

**Comment by paviad** [comment]
This is out of scope of this package, see this `chart.js` issue https://github.com/chartjs/Chart.js/issues/4158
