### ISSUE TITLE
Ng2 Charts linechart not all x-axis labels displayed

### ISSUE THREAD

**Issue by LotusShiv** [valor-software/ng2-charts#891]
I followed all the steps 
 1. I have the Canvas markup as 
`<div *ngIf="showChart">
  <canvas baseChart height="200"
   [datasets]="lineChartData"
   [labels]="lineChartLabels"
   [options]="lineChartOptions"
  ....
</canvas>
</div>

2. and in my component I have
...
export class LineChartComponent{
  public lineChartOptions: any = {
   responsive: true,
   maintainAspectRatio: false
  }

  ....

  @Input() lineChartData: Array<any> = [{data: [], label: 'Test Set'}];
   @Input() lineChartLabels: Array<any> = [];
}

`

And the lineChartLabels get set from a call to my service, which decides for a specific set of chart data values what are the chart labels. 

3. I even have a setTimeout... to display the line chart with a delay, still I see on the x-axis only alternate ticks with labels for e.g. label1, label3, label5 etc., 
When I debug I do see all the labels in the TypeScript code.

4. I even put a callback for the ticks inside the lineChartOptions
as
`public lineChartOptions: any = {
   responsive: true,
   maintainAspectRatio: false,  
   scales: {
     xAxes: [{
      ticks: {
         callback: function (value, index, values){
           return 't-'+ value;
         }
       }
     }]
   }
  }`
And on debugging I do see the callback being called for the number of labels say if I had 7 labels, it cycles through all 7, but on display I see only alternate labels.

This continues to happen each time I refresh the data for the lineChart as well. The line chart displays with all the ticks and labels showing on the Y-axis. Only thing I can think of is the y-axis consists of numbers and x-axis consists of string labels such as Overdue, Today+7, Today+14 etc.,

Also, I notice that when the values for specific x-axis ticks are same (for e.g. if I have (Overdue, 1), (Today,1), (Today+7, 5) ... so on - then only x-axis labels Overdue, Today+7 ... shows up in the **ng-reflect-labels** when I see in the DOM explorer on F12 (in IE for e.g.).
Any help is greatly appreciated. I am on a time crunch....

**Comment by ElectricMaxxx** [comment]
I do have an equal issue.
Thema Major Problem i, that the Labels (values of x-Axis) are Not updated, when Datasets (Count per Set) and Labels Changes. Looking Into ngOnChange() seems to verify it.

**Comment by paviad** [comment]
This package has been updated for Angular 7 and has had many bugs fixed and features added. Please see the [demo app](https://valor-software/ng2-charts) under the *Pie Chart* section, there is a button there which changes the labels dynamically.

**Comment by ElectricMaxxx** [comment]
@paviad thanks a alot. I am really happy to see it running in newest anglar Version.

**Comment by iryanjan18** [comment]
I'm also having this issue on Angular 9. I used `horizontalBar`. Not all xAxes labels are displaying
```ts
public chartOptions: ChartOptions = {
    responsive: true,
    scales: {
      yAxes: [{ stacked: true }],
      xAxes: [{ ticks: { autoSkip: false } }]
    }
};
```
