### ISSUE TITLE
ng2 line chart with angular4 

### ISSUE THREAD

**Issue by sajeetharan** [valor-software/ng2-charts#894]
I am using ng2 charts with my angular4 application.

I am generating a line chart , when i bind the static data it works well.

But when i get the data from server and bind it , it generates only the first series, but if i bind the same data hardcoded it works well.

is it an issue with the library? or is there any alternative to fix this?

**Comment by ferares** [comment]
Have you tried something like this?

```  randomizeBarChart(): void {
    // Only Change 3 values
    const data = [
      Math.round(Math.random() * 100),
      59,
      80,
      (Math.random() * 100),
      56,
      (Math.random() * 100),
      40];
    const clone = JSON.parse(JSON.stringify(this.barChartData));
    clone[0].data = data;
    this.barChartData = clone;
    /**
     * (My guess), for Angular to recognize the change in the dataset
     * it has to change the dataset variable directly,
     * so one way around it, is to clone the data, change it and then
     * assign it;
     */
  }
```

They suggest to clone the current data change it and then assigning it back.

It's in the demo/examples

**Comment by sajeetharan** [comment]
I managed to fix with a timeout

  @ViewChild(BaseChartDirective) private _chart;

after setting the data, 

 setTimeout(() => {
      this._chart.refresh();
    }, 10);
