### ISSUE TITLE
Set whole chartarea a background color - [FEATURE]

### ISSUE THREAD

**Issue by miwha1990** [valor-software/ng2-charts#898]
It would be nice to have a possibility to fill the canvas background, because by default its white, and when I want to export it to PNG or to PDF - it fills with transparent or black color.
Pls take a look of plugin implementation for chart.js - http://jsfiddle.net/rrcd60y0/
It would be nice to do something like that just to enter as attribute to your directive

**Comment by rodschulz** [comment]
Does putting the canvas in a div with color-background set to something works for you? I've been doing that in my charts.

**Comment by paviad** [comment]
You can do this using the plugin interface, see this stackblitz: https://stackblitz.com/edit/ng2-charts-background-color

It is based on this [SO answer](https://stackoverflow.com/a/38493678/235648).

![image](https://user-images.githubusercontent.com/1235688/54071605-83208a00-4277-11e9-9f30-ce75d637eae6.png)
