### ISSUE TITLE
x label 

### ISSUE THREAD

**Issue by BaymaxGroot** [valor-software/ng2-charts#900]
![image](https://user-images.githubusercontent.com/30405676/31608009-3fd9a78e-b2a1-11e7-89d5-1f4870f5b605.png)
How can I do this x style? 
How to config bar-chart?
Thanks

**Comment by vinitkrb** [comment]
layout: {
      padding: {
        left: 50,
        right: 0,
        top: 0,
        bottom: 0
      }
    },

**Comment by paviad** [comment]
Bind to the `colors` property of the canvas. See this stackblitz: https://stackblitz.com/edit/angular-abcjsd
