### ISSUE TITLE
tooltip shaking 

### ISSUE THREAD

**Issue by amineparis** [valor-software/ng2-charts#905]
display bug : continious shaking tooltip when hover stacked horizontal bar chat. any solutions ?

**Comment by teja22060** [comment]
i am also facing the same issue, please tell e any solutions. It seems other project angular2 charts js has some solution, for similar problem

**Comment by neutron92** [comment]
me too

**Comment by CodeMeNow** [comment]
The tooltip was shaking for me anytime I was trying to pass in a function to any of the canvas[baseChart] attributes. To fix the issue for me, I just assigned the function to a variable in the component and passed that variable into the canvas[baseChart] component.

**Comment by paviad** [comment]
I believe this issue is no longer relevant, see this stackblitz: https://stackblitz.com/edit/ng2-charts-horizontalbar-stack
