### ISSUE TITLE
Using with Angular CLI produces a heavy bundle size

### ISSUE THREAD

**Issue by kalimotxo666** [valor-software/ng2-charts#906]
Hi guys!

I'm using:
- angular: 4.4.6
- angluar CLI: 1.4.8
- chart.js: 2.7.0
- ng2-charts: 1.6.0

I build my app by "ng build --prod". That produces a vendor bundle of 1,05MB, without compression.

If I analyse that bundle with source-map-explorer I can see that chart.js itself is 42% of that bundle!

Take a look:
![screenshot-2017-10-31 dist vendor 5094f2a43a269e066419 bundle js - source map explorer](https://user-images.githubusercontent.com/16034532/32212981-a0d315a6-be19-11e7-8f05-a1d4ced5a698.png)

A closer look:
![screenshot-2017-10-31 dist vendor 5094f2a43a269e066419 bundle js - source map explorer 1](https://user-images.githubusercontent.com/16034532/32213038-db7653b2-be19-11e7-9a8a-e8bddb58e00b.png)

While Angular compiler includes chart.js inside vendor bundle I don't need to do this
`<script src="node_modules/chart.js/src/chart.js"></script>`
but, for me, 440 KB is not acceptable.

I'm not able excluede chart.js from bendor, so... any ideas?

Thanks!

**Comment by ryanbonial** [comment]
It looks like it was changed to import chart.js instead of using the global Chart which bundles all of chart.js (and moment)
https://github.com/valor-software/ng2-charts/commit/6ed93e6c7ecd1b37388dacaff3000a39cbc1a96a#diff-cbaa749063f7b0c324b98815be16b470

**Comment by paviad** [comment]
This package has been updated for Angular 7. If this issue persists, feel free to reopen.

**Comment by vlaco** [comment]
I still have this issue.... 
angular: 8.1
angluar CLI: 8.1
chart.js: 2.8.0
ng2-charts: 2.3.0

I have recently swiched from moment to luxon, but I still have moment in my bundle after prod build.  I guess this is because of the chart.js dependency... 
![image](https://user-images.githubusercontent.com/10897547/63160809-fac0c500-c01e-11e9-96d1-afcc937fd145.png)

Not sure if I am doing something wrong or is it still a persistent problem with this library. Would be grateful for any help :)

**Comment by rscherer** [comment]
A bit late, but still may be useful for somebody. 

I archieved this by using a custom webpack config (something like this: https://medium.com/angular-in-depth/customizing-angular-cli-build-an-alternative-to-ng-eject-v2-c655768b48cc). I'm currently using **_Angular 9.1.9_**.

Then, my **extra-webpack.config.js**:

```
const webpack = require('webpack');
module.exports = {
  resolve: {
    alias: {
      "chart.js": "chart.js/dist/Chart.min.js"
    }
  },
  plugins: [
    new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/)
  ]
}
```

As a result, chart.min.js will be used, and all moment locales will be ignored.

**Comment by hardmaster92** [comment]
> A bit late, but still may be useful for somebody.
> 
> I archieved this by using a custom webpack config (something like this: https://medium.com/angular-in-depth/customizing-angular-cli-build-an-alternative-to-ng-eject-v2-c655768b48cc). I'm currently using **_Angular 9.1.9_**.
> 
> Then, my **extra-webpack.config.js**:
> 
> ```
> const webpack = require('webpack');
> module.exports = {
>   resolve: {
>     alias: {
>       "chart.js": "chart.js/dist/Chart.min.js"
>     }
>   },
>   plugins: [
>     new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/)
>   ]
> }
> ```
> 
> As a result, chart.min.js will be used, and all moment locales will be ignored.

After all these years this problem still exists in this library. Thanks for the suggestion, I'll try it. Could you please also help me to change the config so I can include files from the locale folder but just a few that I desire?

**Comment by pubkey** [comment]
@hardmaster92 Yes you can ignore some language files from the include.
See here https://stackoverflow.com/a/25426019/3443137

```ts
var webpack = require("webpack");
module.exports = {
  // ...
  plugins: [
    new webpack.ContextReplacementPlugin(/moment[\/\\]locale$/, /de|fr|hu/)
    // new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/)
  ]
};
```
