### ISSUE TITLE
How can i add some animation image inside the doughnut chart center ?

### ISSUE THREAD

**Issue by MohamedSahir** [valor-software/ng2-charts#911]
I have an requirement to show the gif animation behind doughnut chart which will occupy the center as well as doughnut chart not beyond the doughnut chart? is it possible to use by chart js as well as Chart.PieceLabel.js in angular4 component.

And one more thing is if i set it as 

```
public doughnutChartLabels:string[] = ['Growth Team'];
public doughnutChartData:number[] = [35,75];
public doughnutChartType:string = 'doughnut';
private doughnutChartColors: any[] = [
  { 
    backgroundColor: ["rgb(242, 163, 106)", "white"],
      },

```

if i choose color orange means 
 value will be reach as 25 means slight orange,50 means little dark orange , if value reaches 75 means much more darker orange , how to achieve is it possible? like circular prograssbar

**Comment by paviad** [comment]
See this comment for a possible direction: https://github.com/valor-software/ng2-charts/issues/864#issuecomment-470999858
