### ISSUE TITLE
dataset hidden field.

### ISSUE THREAD

**Issue by sfinnman** [valor-software/ng2-charts#915]
**Reproduction of the problem**
I will override the options.legend.onClick function, in order to have some custom functionality for the legend. This results in a situation where I need to ensure that the dataset becomes hidden manually. This is done using dataset.hidden field. This however, does not achieve the desired hidden state. Rather it does nothing at all.

**Reason and Solution**
The reason behind this is that ng2-charts does not support the hidden field in datasets upon change. The fix was simple, editing the src/charts/charts.ts at line 126: 

`{

    if (Array.isArray(newDataValues[0].data)) {
      this.chart.data.datasets.forEach((dataset: any, i: number) => {
        dataset.data = newDataValues[i].data;

        if (newDataValues[i].label) {
          dataset.label = newDataValues[i].label;
        }
      });
    } else {
      this.chart.data.datasets[0].data = newDataValues;
    }
  }`

to instead be 

` {

    if (Array.isArray(newDataValues[0].data)) {
      this.chart.data.datasets.forEach((dataset: any, i: number) => {
        dataset.data = newDataValues[i].data;
        dataset.hidden = newDataValues[i].hidden;
        if (newDataValues[i].label) {
          dataset.label = newDataValues[i].label;
        }
      });
    } else {
      this.chart.data.datasets[0].data = newDataValues;
    }
  }`

This can be temporarily fixed directly in the npm module by editing the chart.js at line 86 as described above

**Comment by Octarines** [comment]
Needed to say thanks for this post. I had the same issue with adding a custom onClick and this method was exactly what i was missing.
