### ISSUE TITLE
NG2 Bar chart: line through(Strikethrough) lables

### ISSUE THREAD

**Issue by orenger** [valor-software/ng2-charts#916]
using bar chart, everything is working fine,
i am using a feature when u click on any label, it takes out its data of the chart and put a line through the label, like its making it invisible or not part of the chart. ( no plunker as u can see it in https://valor-software.com/ng2-charts/)
my question is: is there any way i can start the chart with Strikethrough label? where in the code i can find the "onLabelClick" function or so?
help is appreciated Thank you

**Comment by paviad** [comment]
Yes, there is a property called `hidden` for a dataset, which will do this. Example:

```typescript
public barChartData: ChartDataSets[] = [
  { data: [65, 59, 80, 81, 56, 55, 40], label: 'Series A', hidden: true },
  { data: [28, 48, 40, 19, 86, 27, 90], label: 'Series B' }
];
```
