### ISSUE TITLE
BUILD error

### ISSUE THREAD

**Issue by blaforet** [valor-software/ng2-charts#917]
Hi 
ng serve work just fine, but Not able to ng build --prod, give me this error. 
![image](https://user-images.githubusercontent.com/27684619/32923290-c6221990-cb04-11e7-8718-a4971927c852.png)

"Module build failed: ModuleBuildError: Module build failed: TypeError: c.hslaString is not a function
    at exports.default (C:\Angular\B-ClubI\node_modules\colormin\dist\index.js:59:26)"

Not sure but i think the hslaString from the ng2-charts-umd.js  is causing the issue.   Because i have another project that does not use ng2-charts and build fine. 

Can someone point me in the right direction?
Thank you

**Comment by paviad** [comment]
This package is now updated for Angular 7. It no longer depends on `colormin`. If this issue persists, please provide a codepen/stackblitz/... example showing the issue.
