### ISSUE TITLE
change boxwidth of doughnut pie chart

### ISSUE THREAD

**Issue by vugar005** [valor-software/ng2-charts#918]
Hi 
I am trying to change box width of doughnut but it does not work and no errors shown on console. 
Please check my code:

```
  public pieChartOptions: any = {
    responsive: true,
    boxWidth: 2,
    legend: {
      position: 'left',
      boxWidth:  2,
      labels: {
        boxWidth:  2,
        usePointStyle: true,
      }
    }
  };
```
Hope someone give advice.Thanks

**Comment by paviad** [comment]
It works now, see this stackblitz https://stackblitz.com/edit/ng2-charts-legend-boxwidth
