### ISSUE TITLE
How can I solve this?

### ISSUE THREAD

**Issue by nicolascamilo** [valor-software/ng2-charts#919]
Hey guys! 
I'm trying to show the result of query/JSON that I receive on ngOnInit:

```
// This is where I set chart variables

private modelsChartData = this.listModelNumber;

// The rest of the chart variables

constructor(private _info: InfoService) {}

ngOnInit() {

this._info.getCameras(CAMERA).subscribe((data) => {

      this.listCameras= data;

      for (let i of this.listCameras) {

        let a = Number(i.MODEL);

        this.listModelNumber.push(a);

      }
});

}
```

If I print this, I'll receive a number array with different numbers.
And I cannot get this to work. The error I'm getting is that dataset is undefined and I believe it's because I'm fetching camera models on ngOnInit, but I must do that. 
Any way to solve this?

Thanks!

**Comment by m--c** [comment]
do not show the chart (use *ngIf or something like that) until you have the data

**Comment by nkmishra1997** [comment]
@nicolascamilo were you able to resolve this?

**Comment by nicolascamilo** [comment]
@nkmishra1997 Yes sir
