### ISSUE TITLE
is it possible to do an  numeric animation according to the chart rotation in ng2doughnut

### ISSUE THREAD

**Issue by MohamedSahir** [valor-software/ng2-charts#920]
while chart is rotating as per the dynamic value and according to chart rotation, number also gets auto increment in the center position of doughnut chart. is it possible with chart js.

Expected the same behaviour in chart js 
https://codepen.io/anon/pen/eeLmWz

**Comment by paviad** [comment]
See this comment for a possible solution: https://github.com/valor-software/ng2-charts/issues/864#issuecomment-470999858
