### ISSUE TITLE
donut-chart inside position:fixed div is flickering inside Internet explorer V11 while scrolling the webpage

### ISSUE THREAD

**Issue by swapsword** [valor-software/ng2-charts#925]
Hello Developers,

I am using donut-chart ( from ng2-charts).
what I am trying to achieve?
- I wanted to fix position the donut chart on webpage.
I have implement it and working totally fine on browser( chrome, Microsoft edge, firefox). However, it is flickering(shaking) inside Internet Explorer V11, while scrolling the webpage.

Note: I have created a demo : http://plnkr.co/edit/PShMdPrrgpCnDigavCLj?p=preview . However, this demo is not working in Internet Explorer.

**Comment by paviad** [comment]
This package has been updated to Angular 7, check out the demo app. If this issue is still relevant, feel free to reopen this with a stacklitz/codepen/... example showing the issue.
