### ISSUE TITLE
Use different colors per data points on the same Line Charts

### ISSUE THREAD

**Issue by NicoGit** [valor-software/ng2-charts#926]
Hi,

I want to have different colors per data points on the same line chart. I found how to do it with the charts.js original plugin but I can't reproduce it with the ng2-charts plugin. It seems that colors need to be handle with the color attribute but I can only give on color per line, and not ont color per point in a line chart.

Is it possible with the ng2-charts plugin?

Nicolas

**Comment by paviad** [comment]
The plugin should be usable in `ng2-charts` as well.
