### ISSUE TITLE
ng2-charts double Y axis is not working

### ISSUE THREAD

**Issue by ketwang** [valor-software/ng2-charts#929]
```typescript
chartjs:
"_args": [
    [
      {
        "name": "chart.js",
        "raw": "chart.js@2.7.1",
        "rawSpec": "2.7.1",
        "scope": null,
        "spec": "2.7.1",
        "type": "version"
      },
      "/myprojects/angular/html/ng2-admin"
    ]
  ],

ngx-charts:
"_args": [
    [
      {
        "name": "ng2-charts",
        "raw": "ng2-charts",
        "rawSpec": "",
        "scope": null,
        "spec": "latest",
        "type": "tag"
      },
      "/myprojects/angular/html/ng2-admin"
    ]
  ],

lineOptions:
public lineChartOptionsxx: any = {
    tooltips: {
      mode: 'index'
    },
    scales: {
      yAxes: [
        {
          type:"linear",
          id: "yAxis1",
          position: "left",
          display: true
        },
        {
          type:"linear",
          id: "yAxis2",
          position: "right",
          display: true,
          gridLines: {
            drawOnChartArea: false
          },
        }
      ],
    }
  };

lineData:
this.lineChartData_2 = [
          {data: this.chartsData['EDF'], label: 'EDF', fill: false, yAxisID: 'yAxis1'},
          {data: this.chartsData['A_VOLATILITY'], label: 'EDF_XX', fill: false, yAxisID: 'yAxis2'}
];
```
the charts show double y axis correctly,but two line datasets only use one side y axis.

**Comment by BellusTechnologies** [comment]
+1 

  public barChartOptions: any = {
    scaleShowVerticalLines: false,
    responsive: true,
    scales: {
      yAxes: [{
        id: "y-axis-1",
        position: 'left',
        // type: 'linear',
        ticks: {min: 0}
        // scaleLabel: {
        //   display: true,
        //   labelString: 'Claims Count'
        // }
      },
        {
          id: "y-axis-2",
          position: 'right',
          // type: 'linear',
          ticks: {min: 0, max: 20}
          // ticks: {
          //   beginAtZero:true,
          //   labelString: 'Sums Charges'
          // }
        }]
    }
  };


  public barChartData: any[] = [{
    label: 'Claims Count',
    type: 'bar',
    yAxisID: "yaxis2",
    data: [],
  },
{
  label: 'Sums Charges',
    type: 'line',
  yAxisID: "yaxis1",
  data: []
}];

No matter what y-axis I tell it to use it always uses the left axis. (Always ignores right y-axis)

**Comment by paviad** [comment]
Multiple axes work fine, stackblitz example https://stackblitz.com/edit/angular-csayt9
