### ISSUE TITLE
Chart.js 2.7.x stalls angular 4 application

### ISSUE THREAD

**Issue by nullpointer77** [valor-software/ng2-charts#934]
Please forgive the pseudo code here.

```
export class ChartWidget {
   private chartModel: MyChartModel = new MyChartModel();

  constructor(){ 
    this.loadChartData()
  }

  private loadChartData(){
    let chartData = this.AjaxService.getChartData();
    let chartBuilder = new ChartBuilder();
    chartBuilder.PopulateChart(this.chartModel, this.chartData);    
  }
}


html file example


<canvas baseChart 
	[datasets]="chartModel.lineChartData"
	[labels]="chartModel.lineChartLabels"
	[options]="chartModel.lineChartOptions"
	[colors]="chartModel.lineChartColors"                        
	[chartType]="chartModel.lineChartType"></canvas>

```

What ends up happening is that angular 2 will attempt to render the chart with basically blank data for each of it's attributes that is supposed to be populated after the data is loaded from the backend.  I think that angular/ng2-charts directive is looping trying to redraw it over and over again until data exists.  This causes the browser to display long running script warnings and ajax calls to be stalled in a 'pending' status.

My work around for this is to use *ngIf around the chart to have angular not load it until the data is finished loading from the backend.

**Comment by paviad** [comment]
This package is now updated for Angular 7, if this issue persists, please reopen this with comment and example on codepen/stackblitz showing the problem.
