### ISSUE TITLE
Angular5 update

### ISSUE THREAD

**Issue by gczuczy** [valor-software/ng2-charts#935]
Could you please check whether this requires an update for angular5?

When I tried to update a project to angular5, I've got a warning for ng-charts:

```
npm WARN ng2-charts@1.6.0 requires a peer of @angular/common@^2.3.0 || >=4.0.0 but none was installed.
npm WARN ng2-charts@1.6.0 requires a peer of @angular/core@^2.3.0 || >=4.0.0 but none was installed.
```

Thanks

**Comment by MitchWilkins** [comment]
I installed it on a fresh project earlier today and I did not run into this.

**Comment by nukec** [comment]
same here no issues on clean project

**Comment by paviad** [comment]
This package is now updated for Angular 7. If this issue persists please provide a stackblitz/codepen/... example which reproduces it.
