### ISSUE TITLE
Need to change graph UI

### ISSUE THREAD

**Issue by kapilkarda** [valor-software/ng2-charts#936]
current ui like this 
![image](https://user-images.githubusercontent.com/4336836/34610797-b6cf3f5c-f248-11e7-9838-7a35c12da5c0.png)
 and we want like this

![image](https://user-images.githubusercontent.com/4336836/34610816-d14ecfdc-f248-11e7-9935-50526aac1ed6.png)

**Comment by paviad** [comment]
This sounds like a question in the scope of `chart.js` not of this package.

**Comment by santam85** [comment]
ng2-charts delegates chart rendering to Chart.js Check [their docs](https://www.chartjs.org/docs/latest/) for instructions on how to achieve this
