### ISSUE TITLE
Creating Multiple bar chart  with service call, getting data undefined issue 

### ISSUE THREAD

**Issue by gauravshri12** [valor-software/ng2-charts#946]
![image](https://user-images.githubusercontent.com/31828662/35111983-b07a7860-fca2-11e7-9f82-62a8b8019148.png)
```typescript
getOntimeData(){
    this.ontimeService.getOntimeData().subscribe(data => {
      this.resultData2 = data;
      this.labels = this.resultData2.map(item => item.label);
      var f=this.resultData2.map(item => item.data)
      this.barChartData2 = this.resultData2.map(item => <any>{"data":Array.of(item.data), "label":item.label});
      console.log(this.barChartData2)
      // add new data set
      //this.barChartData.push({data:[200], label:"new data set"})
      this.loaded = true;
    }
  }

labels: string[] =[];
    barChartType2: string = 'bar';
    barChartLegend2: boolean = false;
    barChartData2: any[] =[];
    resultData2: IDataChart3[] =[];

loaded = false;
```

```html
<canvas *ngIf="loaded" height="180"
      baseChart 
      class="chart" [datasets]="barChartData2" 
      [colors]="chartColors"
      [labels]="labels"
      [options]="barChartOptions2" 
      [legend]="barChartLegend2" 
      [chartType]="barChartType" 
      (chartHover)="chartHovered($event)"
      (chartClick)="chartClicked($event)">
      </canvas>
```

**Comment by monish-u** [comment]
I just started learning angular 2 weeks back and i faced a similar issue while loading charts. See if this helps

You have to first initialize the barChartData2 with empty dataset like this 
barChartData2: any[] =[
{data: [], label: ''},
];

and then use it to assign. Also take a look at the bar chart example in [https://valor-software.com/ng2-charts/]  they have cloned the barchartdata and added the dataset in the clone and then assigned the clone back to our barchartData

  let clone = JSON.parse(JSON.stringify(this.barChartData));
    clone[0].data = data;
    this.barChartData = clone;
    /**
     * (My guess), for Angular to recognize the change in the dataset
     * it has to change the dataset variable directly,
     * so one way around it, is to clone the data, change it and then
     * assign it;
     */

**Comment by monish-u** [comment]
@gauravshri12 were you able to solve the issue ?
