### ISSUE TITLE
How to real time change the yAxis 

### ISSUE THREAD

**Issue by luisellenar** [valor-software/ng2-charts#948]
How can i real-time change the yAxis?

i've tryed many things without success, can someone help?

**Comment by nicholaslombardi1970** [comment]
Found the solution elsewhere in case anyone else has fun into this issue.  Add this to the options property:

     scales: {
       yAxes: [
         {
           ticks: {
             beginAtZero: true,
             userCallback: function(label, index, labels) {
               if (Math.floor(label) === label) {
                 return label;
               }
             }
           }
         }
       ]
     }
