### ISSUE TITLE
[Bug] Axis (ZeroIndexLine) is not colorable 

### ISSUE THREAD

**Issue by haribalajip** [valor-software/ng2-charts#949]
The X and Y axis colors are bound to gridlines and I was unable to color the zeroIndexLine specifically .
 My code: 
 `scales: {
    xAxes: [{
        gridLines: {
            zeroLineColor:'blue',
            drawTicks: false
        }        
    }]
}`

![image](https://user-images.githubusercontent.com/18653930/35373818-4437ead8-01c6-11e8-9092-39878b09d83e.png)

**Comment by haribalajip** [comment]
Any one has updates on this ?

**Comment by paviad** [comment]
It works now, see this stackblitz https://stackblitz.com/edit/ng2-charts-hbar-zeroline

**Comment by haribalajip** [comment]
Thanks a lot @paviad
