### ISSUE TITLE
I can't use my own colors

### ISSUE THREAD

**Issue by hayanisaid** [valor-software/ng2-charts#950]
there is no options to customize colors in ng-chart

**Comment by DevidCIC** [comment]
I am not sure what you mean but:

`public myColors = [
        {
            backgroundColor: 'rgba(103, 58, 183, .1)',
            borderColor: 'rgb(103, 58, 183)',
            pointBackgroundColor: 'rgb(103, 58, 183)',
            pointBorderColor: '#fff',
            pointHoverBackgroundColor: '#fff',
            pointHoverBorderColor: 'rgba(103, 58, 183, .8)'
        },
        // ...colors for additional data sets
    ];`

And then binding it works for me

**Comment by odecharette** [comment]
Hello

Working example for Bar Charts colors with 2 dimensions 

In TS
`public barChartAgesColors:any[] = [{ backgroundColor: '#C99AA8', borderColor: '#C6758D'}, { backgroundColor: '#81C8DF', borderColor: '#3EB8DD'}];`

and in HTML 
```
<canvas baseChart
		            [datasets]="barChartAgesData"
		            [labels]="barChartAgesLabels"
		            [options]="barChartAgesOptions"
		            [legend]="barChartAgesLegend"
		            [chartType]="barChartAgesType"
		            [colors]="barChartAgesColors">
		        </canvas>
```
