### ISSUE TITLE
Can't update labels on a Pie chart

### ISSUE THREAD

**Issue by king612** [valor-software/ng2-charts#951]
I have a Angular 5 page that is trying to use your package to draw a simple Pie chart.  The data is all set after rendering, and the data seems to update just fine, but when I try to generate and set the labels array, every label shows up as undefined.  I have debugged to check the array is getting loaded correctly, but it seems like with labels on Pie / Donut charts, only a statically set array of labels at declaration works.  Changing the label array (even creating a new array and resetting the class member) fails to render any labels on the standard mouseover / hover tooltip.

Any suggestions appreciated.

**Comment by david-j-lee** [comment]
I noticed this is an issue on #774. When can we expect a fix?

**Comment by itabo** [comment]
Any news?. I have the same problem.

**Comment by king612** [comment]
The post below on that page worked for me.  It's a work around, but it
worked.

John K.

* mertyildiran <https://github.com/mertyildiran> * commented on Apr 30, 2017
<https://github.com/valor-software/ng2-charts/issues/774#issuecomment-298263293>

**Comment by paviad** [comment]
Closed by ef5d2f4

**Comment by maksof-kashif** [comment]
try this i have try it with bar chat but process is same just customize according to your code.

<canvas baseChart
[datasets]="ChartData"
//...other stuff >

and in the component I have a function which update the chart with new data, and then I clone the datasets and re-assign it

drawChart(){
this.ChartData=[{data: this.dataX, label: 'X'}];  // this.dataX has new values from some place in my code
//nothing happened with my chart yet, until I add this lines:
let clone = JSON.parse(JSON.stringify(this.ChartData));
this.ChartData=clone;
//other stuff like labels etc.
}
