### ISSUE TITLE
[Feature] Modifying axes line color (excluding gridlines) - Bar chart

### ISSUE THREAD

**Issue by haribalajip** [valor-software/ng2-charts#952]
Unable to change the axis line color . I would like to have a different color for axis lines and gridlines .
Axis lines should be prominent .
Existing chart :
![image](https://user-images.githubusercontent.com/18653930/35610616-fe9bcbe0-0687-11e8-80ca-6119b980e618.png)

Expected result:
![image](https://user-images.githubusercontent.com/18653930/35610964-66ceb3a2-0689-11e8-8419-dc2ccbeb892d.png)

**Comment by paviad** [comment]
This is a chart.js issue, please follow this PR https://github.com/chartjs/Chart.js/pull/5480

**Comment by paviad** [comment]
Answered in https://github.com/valor-software/ng2-charts/issues/949
