### ISSUE TITLE
Can I pass multiple bar percentage in single Bar chart ? 

### ISSUE THREAD

**Issue by praveencbomminani** [valor-software/ng2-charts#954]
Hi,

can any one got this kind of requirement like to pass different bars have different sizes..
http://plnkr.co/edit/DMuYKdlpDy87yRX5Rl8B?p=preview
I can give  barPercentage: 0.05 like this bar size reducing . but i want to show different  barPercentage for different labels.. is there any work around for it ? 
Thank you !

**Comment by paviad** [comment]
This sounds like a new chart type requirement (which is out of scope of this package). See this [SO answer](https://stackoverflow.com/a/47130660/235648).
