### ISSUE TITLE
Unable to change label width and change style

### ISSUE THREAD

**Issue by amit509** [valor-software/ng2-charts#956]
Hi,

I am unable to change width of "labels" for bar chart. I am trying to keep "text-overflow:ellipsis" also but my labels are still getting full width and few labels are hidden.

Below is the screen shot

![image](https://user-images.githubusercontent.com/25607741/35806840-e8844756-0aa6-11e8-884d-b07cc2d7b707.png)

Can you guys help me.

Thanks in advance.

ng2-charts is a port & modification of Chart.js component for Angular 2. Sometimes the issue is related with Chart.js instead of ng2-charts.
To confirm, if the issue shows in a pure Chart.js project, it is a issue of Chart.js.
Pure Chart.js starting template: https://jsfiddle.net/Hongbo_Miao/mvct2uwo/3/

If the issue does not show in a pure Chart.js project, and shows in a ng2-charts project, please try to provide a minimal demo of the problem.
ng2-charts starting template: http://plnkr.co/edit/Ka4NXG3pZ1mXnaN95HX5?p=preview

**Comment by lenichols** [comment]
+1

**Comment by paviad** [comment]
You can provide a callback which will modify the tick labels in any way you like, for example:

(using `lodash`'s [truncate](https://lodash.com/docs/4.17.11#truncate) function)

```typescript
chartOptions: ChartOptions = {
  scales: {
    xAxes: [{
      ticks: {
        callback: value => _.truncate(value, { length: 5 })
      }
    }]
  },
};
```
