### ISSUE TITLE
Line chart tooltips don't show the color for the data

### ISSUE THREAD

**Issue by arrow-dev** [valor-software/ng2-charts#958]
Setting tooltips.displayColors to true should show a colored box in the tooltip next to the data, this seems to work with default colors but when using the colors attribute to set custom colors for the chart these box's just become transparent.

**Comment by LautaroLorenz** [comment]
idem

setting doughnutChartColors
the tooltip on hover always is black for all colors

**Comment by paviad** [comment]
This package has been updated, it looks like the tooltip color is displayed properly. See the [demo app](https://valor-software/ng2-charts) under *Doughnut Chart*.

![image](https://user-images.githubusercontent.com/1235688/54044849-a1837880-41d8-11e9-9f3c-4c830267687d.png)
