### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by shyamal890** [valor-software/ng2-charts#959]
There have been so many issues without any response from the maintainer. Moreover, the most demanded feature is auto updating of chart for dynamic `datasets`.

@valorkin @greenkeeperio-bot can you please share your thoughts.

**Comment by DevidCIC** [comment]
This would also interest me as well.

**Comment by Jehoel** [comment]
> Moreover, the most demanded feature is auto updating of chart for dynamic datasets.

Auto-updating charts works for me, the trick is to re-assign to the exposed dataset property into your component so it triggers change detection:

Template:

    <canvas baseChart [datasets]="chartDatasets" [options]="chartOptions" [chartType]="'line'"></canvas>

Component:

    chartDatasets: Partial<ChartDataSet>[];
    chartOptions: ChartOptions = ...
    
    updateChart( newValue: number ) {
        
        this.chartDatasets[0].data.push( { x: new Date(), y: newValue } );
        this.chartDatasets = Object.assign( [], this.chartDatasets );
    }

**Comment by paviad** [comment]
The answer to the issue topic is yes, and apart from that, I believe the update issue is now resolved.
