### ISSUE TITLE
draw error bar

### ISSUE THREAD

**Issue by abedzaben28** [valor-software/ng2-charts#961]
is there way to draw error bar, i found the highchart allow me to do that, see the attached snapshot to get the idea. 

thanks in advnace
![error bar](https://user-images.githubusercontent.com/26892251/36394669-05695934-15be-11e8-8dad-982a258f6bb3.JPG)

**Comment by paviad** [comment]
Please check out this package: https://www.npmjs.com/package/chartjs-plugin-error-bars
