### ISSUE TITLE
Unexpected value 'ChartsModule' from electron app

### ISSUE THREAD

**Issue by utd1878** [valor-software/ng2-charts#962]
**Reproduction of the problem**
clone this repo. https://github.com/colinskow/angular-electron-dream-starter
install ng2-charts
add the import statement in the app.module file
error shows

I have successfully added chartjs and have been using it, but would like to utilize ng2-charts if I can, but I get this error.

![image](https://user-images.githubusercontent.com/5215011/36504148-c1e9e6ba-170c-11e8-97d9-a46f440d5c01.png)

**Comment by paviad** [comment]
Please check out the README on the home page of this repo for instructions.
