### ISSUE TITLE
dynamic data with canvas not updating

### ISSUE THREAD

**Issue by tokishorbankar** [valor-software/ng2-charts#964]
we have implemented two charts both have dynamic data from api but charts canvas not updating.

1. with static data charts are display
2. with one static and one dynamic chart display when we have "@ViewChild(BaseChartDirective) _chart;" to _chart.refresh(); 
3. with dynamic data two chart are not display (or canvas not updating data)

**Comment by lenichols** [comment]
+1

**Comment by andreyhideki** [comment]
See solution in issue #806 by @Shadowlauch

**Comment by paviad** [comment]
This package has been updated for Angular 7 and has had many bugs fixed and features added. If you still encounter a problem feel free to reopen this.
