### ISSUE TITLE
how to highlight selected datapoint for a Line chart

### ISSUE THREAD

**Issue by Dashing-Daniel-Li** [valor-software/ng2-charts#966]
I am looking for a way to select the datapoint I click. 

I couldn't find a drag feature so I made a slider below which I want to programatically click and hightlight that datapoint using its index (x axis point)

**Comment by santam85** [comment]
ng2-charts delegates chart rendering to Chart.js Check [their docs](https://www.chartjs.org/docs/latest/) for instructions on how to achieve this
