### ISSUE TITLE
Confusing document

### ISSUE THREAD

**Issue by trungk18** [valor-software/ng2-charts#969]
I am using ng2-charts in our Angular application. It is working well so far. But run through the document, there is one line that you guys mention that Important

> Embedding Chart.js in application is mandatory!

![confusing-statement](https://user-images.githubusercontent.com/6767322/37637743-5db8283a-2c44-11e8-9282-0baaa557e05d.png)

I checked the source of the file "node_modules/chart.js/src/chart.js". So basically it will contain all the CommonJS module, and it doesn't work on browser for sure. 

`/**
 * @namespace Chart
 */
var Chart = require('./core/core')();

Chart.helpers = require('./helpers/index');

// @todo dispatch these helpers into appropriated helpers/helpers.* file and write unit tests!
require('./core/core.helpers')(Chart);

Chart.defaults = require('./core/core.defaults');
........`

So my question is: Is this step required? If not, please remove it from the documentation. Otherwise people will be confused.

**Comment by arrow-dev** [comment]
I'm also confused about this, my app seems to work just fine if I only include ng2-charts and don't install chart.js at all?  "Embedding Chart.js in application is mandatory!" - is this no longer the case?
