### ISSUE TITLE
How can I have a bar background color alternate depending on data value?

### ISSUE THREAD

**Issue by alex-nicholas** [valor-software/ng2-charts#972]
I have a single series of data currently plotted on a horizontal bar chart. 

I would like any bar whose value >= 100 to be green, and < 100 to be red. 

I am able to change the background color per series, but not per value within a series. 

Is the best solution to explode my data into one 'series' per value to attain the result I desire?

**Comment by paviad** [comment]
You might achieve that using stacks, you will need to explode your data not into a separate series per point, but just into 2 series, one for the red, and one for the green. Please see this stackblitz for example: https://stackblitz.com/edit/angular-px7mut
