### ISSUE TITLE
How to put value next to a legend label

### ISSUE THREAD

**Issue by aztekinetix** [valor-software/ng2-charts#974]
Hi guys,

First, I want to congratulate you for the great job here.  I was googling it but I didn't find how I could put the value next to a legend label, like the picture below:
![spend](https://user-images.githubusercontent.com/6136448/38696411-a6827cd8-3e54-11e8-83d9-2bad94affcaa.PNG)

Is this possible? Thanks!

**Comment by Joklogh** [comment]
Hi @aztekinetix 
Did you found solution? I can probably help you if not.
Let me know.

**Comment by paviad** [comment]
This can be done using the plugin interface, see this stackblitz https://stackblitz.com/edit/ng2-charts-legend-with-value

It is base on this [SO answer](https://stackoverflow.com/a/52446895/235648).
