### ISSUE TITLE
Display TABLE when clicked on Bar Graphs's bars.

### ISSUE THREAD

**Issue by kairos2489** [valor-software/ng2-charts#976]
Hi,
I am new in Angular so please don't mind me asking basic questions.
My query- I have a bar graph and my project requirement is to display all the bar details with some additional info in a TABLE when clicked on bars of graph.

Please help as to how i can implement this or share me some useful links.
Thanks in advance.

**Comment by paviad** [comment]
This sounds like a general programming question, please ask in https://stackoverflow.com
