### ISSUE TITLE
Fix yAxes to div

### ISSUE THREAD

**Issue by lenichols** [valor-software/ng2-charts#978]
what is the best method to fix the yaxes?

My chart displays values for inventory but i have a horizontal scroll bar that displays in the event there are more results than normal. When you scroll left to right, I want to be able to display the yaxis without it being scrolled out of view. I want to make it fixed while keeping the chart itself scrollable. Any ideas on how to achieve this?

**Comment by Asim1996** [comment]
https://stackoverflow.com/questions/35854244/how-can-i-create-a-horizontal-scrolling-chart-js-line-chart-with-a-locked-y-axis 
This might help

**Comment by paviad** [comment]
There is a comment on that which referes to a brilliant jsfiddle which solves the issue: http://jsfiddle.net/jmpxgufu/
