### ISSUE TITLE
how to synchronize multiple ng2 charts on click

### ISSUE THREAD

**Issue by manhar-developer** [valor-software/ng2-charts#979]
**Reproduction of the problem**

how to synchronize multiple ng2 charts on click
Is it possible to achieve feature like drill down in other charting libraries. 
I have one pie chart and one bar chart with same set of data and want to apply cross filtering on these charts so that if I click on pie chart, bar chart also changes

ng2-charts is a port & modification of Chart.js component for Angular 2. Sometimes the issue is related with Chart.js instead of ng2-charts.
To confirm, if the issue shows in a pure Chart.js project, it is a issue of Chart.js.
Pure Chart.js starting template: https://jsfiddle.net/Hongbo_Miao/mvct2uwo/3/

If the issue does not show in a pure Chart.js project, and shows in a ng2-charts project, please try to provide a minimal demo of the problem.
ng2-charts starting template: http://plnkr.co/edit/Ka4NXG3pZ1mXnaN95HX5?p=preview

**Comment by paviad** [comment]
Use the `chartClick` events to synchronize.
