### ISSUE TITLE
How to Wrap Text on Bar Chart Labels

### ISSUE THREAD

**Issue by lenichols** [valor-software/ng2-charts#982]
What is the appropriate way to wrap text on labels? My labels are long and it seems all the answers in there are hacks that do not work in this version of Ng2. Any help would be appreciated.

**Comment by Joklogh** [comment]
Hi @lenichols 
Here is example of shortening labels. 
https://stackblitz.com/edit/ng2-chart-example-kqqezx
You can customize how the label will look like in the `callback` of `tick` in the options.
Let me know if this is the behaviour you want or have other questions to my example

**Comment by paviad** [comment]
Labels may be strings or they may be arrays of strings. If a label is an array of string, it represents a multi-line label where each element is on a line of its own.
