### ISSUE TITLE
Issue with moment.locale() when using 1.6.0

### ISSUE THREAD

**Issue by guillaumegarcia13** [valor-software/ng2-charts#984]
**Description of the problem**
When using the latest release (1.6.0 at the time of writing), Chart.js is actually embedded as a dependency in ng2-charts@1.6.0
To localize the moment that Chart.js is using is... kind of a daunting task! (haven't found how actually)

**Why localizing?**
To be able to display time axis (rendered by Chart.js using moment.js) in the user's locale.

**One approach to solve this**
Just wanted to share my solution to be able to localize the charts produced by ng2-charts:
1. Downgrade to ng2-charts@1.5.0 (I know, this sucks...)
`npm i ng-charts@1.5.0 --save`
2. Install Chart.js as a dependency of your project
`npm i chart.js --save`
3. Modify your .angular-cli.json (or whatever you are using to load your js files)
```
"../node_modules/moment/min/moment-with-locales.min.js",
"../src/moment-locale.js",
"../node_modules/chart.js/dist/Chart.min.js", 
```
Notice here, the moment-locale.js file - placed in-between moment.js and Chart.js - which only consists in:
`moment.locale('fr');`
Yet, this part is needed for Chart.js to take this version of moment instead of default (en) one.
see: https://github.com/chartjs/Chart.js/issues/3108#issuecomment-238104810

That's it, you should be able to have your time axis rendered with localized labels.
![image](https://user-images.githubusercontent.com/2786038/39729511-8f7fc9c0-525c-11e8-9b7a-f6b5cef52ecd.png)

**Comment by paviad** [comment]
Two things:

1. The package was recently updated to Angular 7, with many bug fixes and improvements. `chart.js` is no longer an embedded dependency.
2. The dependency on `moment` is a `chart.js` issue.
