### ISSUE TITLE
Horizontal Bar Chart displaying tooltip Data Inside the Bar

### ISSUE THREAD

**Issue by lenichols** [valor-software/ng2-charts#988]
How to add data from dataset inside bar rotated... for example, my tooltip displays amount and a city along with my label name. I want to display the city inside...

![citiespng](https://user-images.githubusercontent.com/5247113/40017503-6e8cbcca-576e-11e8-9e95-4b0b0fbc2b04.PNG)

**Comment by paviad** [comment]
One option is to use `chartjs-plugin-datalabels` along with its `formatter` option. See this stackblitz https://stackblitz.com/edit/ng2-charts-bar-labels-rotated
