### ISSUE TITLE
How to change the color of the line that divides two segments.

### ISSUE THREAD

**Issue by NeerajNegi** [valor-software/ng2-charts#995]
how to remove white line between green area and grey area?
![screenshot from 2018-06-01 14-01-42](https://user-images.githubusercontent.com/17411633/40830685-b4204d58-65a4-11e8-9a0d-379c8da04ac0.png)

**Comment by paviad** [comment]
Use this:

```typescript
  public pieChartOptions: ChartOptions = {
    elements: {
      arc: {
        borderWidth: 0,
      },
    },
  };
```
